<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: the part of a NN which has the data we want to analyze
### Hidden Layer: part of the NN which does the analysis of the data we fed it (input layer)
### Output Layer: part of the NN which tells us the result of the analysis from the hidden layers (usually a classifcation of the input data)
### Neuron: in NN they recieve inputs and pass results to the next layer
### Weight: a transformation value between layers of a NN
### Activation Function: part of every node that determines how much information passes to the next NN layer. Nodes in a given layer usually have the same activation/transder function.
### Node Map: flowchart of a NN's layers
### Perceptron: NN with no hidden layers and generates a single output


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### NN basic overview
- Input Layer
    - populated with the data we want to analyze

- Hidden Layer (if present)
    - weights and bias affect what the activation function passes on to the next layer

- Output Layer
    - an output vector whose size/shape depend on the type of problem we're trying to solve

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [151]:
inputs = df.iloc[:,:3].values
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [152]:
correct_outputs = df.iloc[:,2:].values
correct_outputs

array([[1],
       [1],
       [1],
       [0]])

In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [154]:
%%time
weights = 2 * np.random.random((3,1)) - 1
for _ in range(10000):
    weighted_sum = np.dot(inputs, weights)
    activated_output = sigmoid(weighted_sum)
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivative(activated_output)
    weights += np.dot(inputs.T, adjustments)

print(f"Final weights are \n{weights}")
print(f"Final predictions are\n {activated_output}")

Final weights are 
[[-3.80408962]
 [-3.8095261 ]
 [11.69654958]]
Final predictions are
 [[9.99991676e-01]
 [9.99626553e-01]
 [9.99624518e-01]
 [4.93489067e-04]]
CPU times: user 148 ms, sys: 0 ns, total: 148 ms
Wall time: 147 ms


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [3]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [4]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

In [5]:
y=diabetes.iloc[:,-1].values

In [6]:
X=diabetes.iloc[:,0:8].values

In [7]:
scaler = MinMaxScaler()
print(scaler.fit(diabetes))

MinMaxScaler(copy=True, feature_range=(0, 1))


In [8]:
scaler.fit(X)
scale_X = scaler.transform(X)
# scale_y = scaler.transform(y)

In [9]:
scale_X.shape

(768, 8)

In [10]:
scale_X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [11]:
scale_X.shape[1]

8

In [12]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
        
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)
        

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = np.zeros(X.shape[1])

        for _ in range(self.niter):
            # Weighted sum of inputs / weights
            self.weighted_sum = np.dot(X, self.weights)
            # Activate!
            self.activated_output = self.__sigmoid(self.weighted_sum)
            # Calc error
            self.error = y - self.activated_output
            # Update the Weights
            self.adjustments = self.error * self.__sigmoid_derivative(self.activated_output)
            self.weights += np.dot(X.T, self.adjustments)
        
    def predict(self, X):
        """Return class label after unit step"""
#         return np.where((np.dot(X, self.weights[1:]) + self.weights[0])>= 0.0, 1, -1)
        return np.where((np.dot(X, self.weights))>= 0.0, 1, 0)

In [13]:
dia_per = Perceptron(10000)

In [14]:
dia_per.fit(scale_X,y)

In [15]:
predictions = dia_per.predict(scale_X)

In [16]:
from sklearn.metrics import accuracy_score

In [17]:
accuracy_score(y,predictions)

0.5052083333333334

In [23]:
class Perceptron_JC(object):
  def __init__(self, rate = 0.01, niter = 10):
    self.rate = rate
    self.niter = niter

  def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # weights
    self.weight = np.zeros(1 + X.shape[1])

    # Number of misclassifications
    self.errors = []  # Number of misclassifications

    for i in range(self.niter):
      err = 0
      for xi, target in zip(X, y):
        delta_w = self.rate * (target - self.predict(xi))
        self.weight[1:] += delta_w * xi
        self.weight[0] += delta_w
        err += int(delta_w != 0.0)
      self.errors.append(err)
    return self

  def net_input(self, X):
    """Calculate net input"""
    return np.dot(X, self.weight[1:]) + self.weight[0]

  def predict(self, X):
    """Return class label after unit step"""
    return np.where(self.net_input(X) >= 0.0, 1, 0)

In [24]:
dia_per2 = Perceptron_JC(.01, 1000)

In [25]:
%%time
dia_per2.fit(scale_X,y)

CPU times: user 6.65 s, sys: 15.8 ms, total: 6.67 s
Wall time: 6.65 s


In [26]:
predictions2 = dia_per2.predict(scale_X)

In [27]:
accuracy_score(y,predictions2)

0.7369791666666666

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?