<a href="https://colab.research.google.com/github/AuFeld/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/CG_DS_421_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: "raw" data that one imputers into the neural network. there is one node per variable that you want to input

### Hidden Layer: layers that do the actual transforming of the input data, using weights and biases (each different per layer), based on how the neural network has been trained. Depending on the complexity of the neural network/data, one may have more hidden layers. they are called hidden layers because we don't "see" how they work because they occur "under the hood"

### Output Layer: the resulting output from the neural network, which will be a value from 0 to 1. depending on the neural network you're using and the problem you're tring to answer, there can be one or more nodes in the ouput layer. 

### Neuron: aka nuerons or nodes of a neural network. they recieve data (one number) as input, and transform it based on the given weights and biases, and pass the new value on to the next neuron/node. 

### Weight: a number in a given layer that multiplied by the incoming value, in order to transform it to pass on to the next layer of neurons. Weights are tuned as part of the training process for the neural network. 

### Activation Function: is what is housed within each node that determines what or how much to pass along to the next layer of nodes. it is called an activation functions because it's based on activatino of biological neurons, which only activated after a certain threshold is met. With artificial neural networks, the node uses the activation function to transform its data (commonly using a Sigmoid function or Relu function) to determing which value to pass on to the next layer. 

### Node Map: a visual representation of a neural network, to help understand the relationship between the node layers and which types of nodes they are, and how it all flows together. 

### Perceptron: the most basic type of neural network. it consists of any number of inputs, and creates a single output, with no hidden layers. The perceptron is best at categorizing linearly seperable data. 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

a neural network first receives data input, from at least two variables, and usually more. this is the data you pass into your code. each variable goes into a node, and from there is put though a series of layers (depending on the network). each node within a given layer receives input from the previous later (beginning with the input layer), and then multiplies that value by the wieght, adds the bias, then puts the value through the activation function in order to determine what value to pass to the next layer, which then repeats the process until an output (or many outputs) of 0 to 1 is provided, which can be used to apply back to your data. 


## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
# import the goods! 

import pandas as pd
import numpy as np 

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
# create sigmoid activation function

def sigmoid(x): 
  return 1 / (1 + np.exp(-x))

# create sigmoid derivative function

def sigmoid_derivative(x): 
  sx = sigmoid(x)
  return sx * (1-sx)

In [14]:
# initialize random weights

weights = np.array([0.0, 0.0, 0.0])

# def inputs including an extra column of noise to help Perceptron 
# sort through data

inputs = np.array([
                   [0, 0, 1],
                   [1, 0, 1],
                   [0, 1, 1], 
                   [1, 1, 1] 
])

# def correct outputs

correct_outputs = np.array(df.y)
correct_outputs

array([1, 1, 1, 0])

In [15]:
type(weights[0])

numpy.float64

In [16]:
# create perceptron in a for loop

for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate the Error
    error = correct_outputs - activated_output
    
    # Adjust Error
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)



Weights after training
[-11.83940805 -11.83940805  17.80797679]
Output after training
[0.99999998 0.99744837 0.99744837 0.00281285]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [17]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [18]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[feats]

normalized = Normalizer().fit_transform(X)

normalized

array([[0.03355237, 0.82762513, 0.40262844, ..., 0.18789327, 0.00350622,
        0.27960308],
       [0.008424  , 0.71604034, 0.55598426, ..., 0.22407851, 0.00295683,
        0.26114412],
       [0.04039768, 0.92409698, 0.32318146, ..., 0.11765825, 0.00339341,
        0.16159073],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.14103664, 0.00131885,
        0.16149234],
       [0.00665306, 0.83828547, 0.39918356, ..., 0.20025708, 0.00232192,
        0.31269379],
       [0.00791454, 0.73605211, 0.55401772, ..., 0.24060198, 0.00249308,
        0.18203439]])

In [19]:
mmscaler = MinMaxScaler()

X2 = mmscaler.fit_transform(diabetes[feats])

X2

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [20]:
feats

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [21]:
np.zeros(1+ diabetes[feats].shape[1])

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
##### Update this Class to First Class! #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X_, y):
        """
        Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """    
        # Add in Bias Term
        X = np.append(X_, X_.shape[0]*[[1]], axis=1)   
    
        # Initialize Weights as Zeros
        self.weights = np.zeros((X.shape[1]))
        
        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)

            # Activate!
            activated_output = self.__sigmoid(weighted_sum)
            
            # Cac error
            error = y - activated_output

            # Update the Weights
            adjustments = error * self.__sigmoid_derivative(activated_output)
            self.weights += np.dot(X.T, adjustments)
        
        return self.weights

    def predict(self, X):
        """Return class label after unit step"""
        X_ = np.append(X, X.shape[0]*[[1]], axis=1)
        calculations = np.dot(X_, self.weights)
        activated_output = self.__sigmoid(calculations)
        return np.where(activated_output >= .5, 1, 0)

In [0]:
# add sigmoid to final prediction?

In [38]:
np.zeros((1 + X.shape[1])).shape

(9,)

In [0]:
# def X training vectors and y target values

X = Normalizer().fit_transform(diabetes[feats])
y = diabetes['Outcome']

In [40]:
X.shape

(768, 8)

In [41]:
perceptron = Perceptron(400)

weights = perceptron.fit(X2, y)

weights

array([ 8.02952642e+01,  2.71851743e+02, -4.57122183e+01,  2.22743185e-02,
       -1.89905175e+01,  1.92843565e+02,  7.43795417e+01,  4.41262931e+01,
       -2.42169785e+02])

In [42]:
predictions = perceptron.predict(X2)

sum(predictions - y)

220

In [43]:
sum(predictions == y)

508

In [0]:
def accuracy (target, predictions):
  return (sum(predictions == target)/len(target))

In [45]:
accuracy(y, predictions)

0.6614583333333334

In [46]:
len(y)

768

In [47]:
sum(predictions - y)

220

In [0]:
# visualize training process

import matplotlib.pyplot as plt
pn = Perceptron()
fit = pn.fit(normalized, y)
plt.plot(range(1, len(pn.errors) + 1), pn.errors, marker='o')
plt.xlabel('Epochs')
plt.ylabel('Number of Errors')
plt.show()

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?

In [0]:
!pip install tensorflow>=2.0

In [0]:
# tensorflow
import tensorflow as tf


In [5]:
tf.__version__

'1.15.0'