<a href="https://colab.research.google.com/github/ChanceDurr/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/Chance_Dare_LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input 
Layer: Receives  input from data set
### Hidden 
Layer: Only accesesd through input layers, comes after input
### Output Layer: 
Outputs a vector of values that is in a format for the problem
### Neuron: 
The flow of the data from input to output
### Weight: 
input weights get adjusted based off off error
### Activation Function: 
The function that gives you your output
### Node Map: 
A map to show the flow of the neuron
### Perceptron: 
In machine learning, the perceptron is an algorithm for supervised learning of binary classifiers. A binary classifier is a function which can decide whether or not an input, represented by a vector of numbers, belongs to some specific class.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?
You give inputs, that are adjusted by the weights and bias, the put through an activation function to give you an output.

#### Your Answer Here

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'x1': [0, 1, 0, 1], 'x2': [0, 0, 1, 1], 'y': [1, 1, 1, 0]})

In [272]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [0]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return sigmoid(x) * (1 - sigmoid(x))

In [0]:
inputs = np.array(df[['x1', 'x2']]).astype('float')

correct_output = np.array(df['y']).reshape(-1, 1).astype('float')

weights = 2 * np.random.random((2, 1)) - 1

bias = np.zeros(inputs.shape[0])

In [275]:
print(inputs)
print(correct_output)
print(weights)
print(bias)

[[0. 0.]
 [1. 0.]
 [0. 1.]
 [1. 1.]]
[[1.]
 [1.]
 [1.]
 [0.]]
[[-0.21598202]
 [ 0.57209728]]
[0. 0. 0. 0.]


In [276]:
for iteration in range(10000):
  
#   print(weights)

  weighted_sum = np.dot(inputs, weights) + bias.reshape(-1, 1)
#   print(weighted_sum)
  
  activated_output = sigmoid(weighted_sum)
#   print(activated_output)
  
  error = correct_output - activated_output
#   print(error)
  
  adjustments = error * sigmoid_derivative(activated_output)
#   print(adjustments)
  
  weights = weights + np.dot(inputs.T, adjustments) 
  
  bias += np.sum(adjustments, axis=1)
  
  
print('Weights: \n', weights)
print('\nActivated Outputs: \n', activated_output)

Weights: 
 [[-0.21252058]
 [ 0.18151929]]

Activated Outputs: 
 [[9.99490924e-01]
 [9.99490759e-01]
 [9.99490760e-01]
 [4.00602253e-04]]


In [277]:
print(error)

[[ 0.00050908]
 [ 0.00050924]
 [ 0.00050924]
 [-0.0004006 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')

In [279]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
inputs = np.array(df[['Pregnancies', 'Glucose', 'BloodPressure',
                      'SkinThickness', 'Insulin', 'BMI',
                      'DiabetesPedigreeFunction', 'Age']])

correct_output = np.array(df['Outcome']).reshape(-1, 1)

weights = 2 * np.random.random((8, 1)) - 1

bias = np.zeros(inputs.shape[0])

In [281]:
for iteration in range(10000):
  
  weighted_sum = np.dot(inputs, weights) + bias.reshape(-1, 1)

  activated_output = sigmoid(weighted_sum)

  error = correct_output - activated_output

  adjustments = error * sigmoid_derivative(activated_output)
  
  weights += np.dot(inputs.T, adjustments)
  
  bias += np.sum(adjustments, axis=1)
  
print('Weights: \n', weights)
print('\nActivated Outputs: \n', activated_output)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


Weights: 
 [[130636.0044486 ]
 [  6377.72632049]
 [-22919.19429606]
 [ -1765.31826517]
 [   592.86309669]
 [-10142.74423954]
 [ 12320.99721638]
 [-12758.24160132]]

Activated Outputs: 
 [[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?