<a href="https://colab.research.google.com/github/KristineYW/DS-Unit-4-Sprint-2-Neural-Networks/blob/main/Kristine_Wang_LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
- The initial data for the neural network. This is usually how many columns/features there are.  
### Hidden Layer: 
-The intermediate layer/layers between the inputs and the outputs. This is where all the computation happens, and where we are trying to determine the weights. The number of hidden layers is a hyperparameter and can be changed according to the complexity of the model. 
### Output Layer:
-Our expected results (targets) from the inputs. The shape is a vector of values. The model is trained based on reducing errors to reach the output layer. 
### Neuron:
- The biological basis for neural networks. 
### Weight:
- The number(s) attempted to be calculated with the activation functions to reach the output layers with the given inputs. There are as many weights as there are inputs. 
### Activation Function:
- The activation function determines if a given node should be “activated” or not based on the weighted sum. The specific function to use is based on the requirements of the model (i.e. linear, binary, or multiclass). 
### Node Map: 
- Node maps are the diagrams of how to get from inputs to outputs. With a node map, we can visualize the relationship between the input layer, the hidden layer(s), and the output layer. 
### Perceptron:
- Perceptrons are the simplest kind of neural networks, with just a single node created from any number of inputs to get to a single output. 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
import numpy as np

np.random.seed(812)

inputs = np.array([[0,0, 1],
                   [1,0, 1],
                   [0,1, 1],
                   [1,1, 1]
                  ])

correct_outputs = [[1], [1], [1], [0]]

In [3]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx * (1 - sx)

In [4]:
weights = np.random.random((3,1))

In [5]:
weights

array([[0.5049808 ],
       [0.60592761],
       [0.45748719]])

In [6]:
print(inputs.shape)
print(weights.shape)

(4, 3)
(3, 1)


In [7]:
weighted_sum = np.dot(inputs, weights)

weighted_sum

array([[0.45748719],
       [0.96246799],
       [1.06341479],
       [1.5683956 ]])

In [8]:
activated_output = sigmoid(weighted_sum)

activated_output

array([[0.6124179 ],
       [0.72361567],
       [0.74334258],
       [0.82755477]])

In [9]:
error = correct_outputs - activated_output

error

array([[ 0.3875821 ],
       [ 0.27638433],
       [ 0.25665742],
       [-0.82755477]])

In [10]:
adjustments = error * sigmoid_derivative(weighted_sum)

adjustments

array([[ 0.09199735],
       [ 0.05527577],
       [ 0.04896623],
       [-0.11809858]])

In [11]:
inputs.T

array([[0, 1, 0, 1],
       [0, 0, 1, 1],
       [1, 1, 1, 1]])

In [13]:
weights += np.dot(inputs.T, adjustments)

weights

array([[0.44215799],
       [0.53679525],
       [0.53562795]])

In [12]:
print(adjustments.shape)
print(inputs.T.shape)

(4, 1)
(3, 4)


In [14]:
inputs.T

array([[0, 1, 0, 1],
       [0, 0, 1, 1],
       [1, 1, 1, 1]])

In [15]:
for iteration in range(100000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)


Weights after training
[[-10.39526168]
 [-10.39526168]
 [ 15.67772134]]
Output after training
[[0.99999984]
 [0.99494573]
 [0.99494573]
 [0.00598321]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [25]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [26]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes.drop(['Outcome'], axis=1)

y = diabetes['Outcome']

X.head()

Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0            6      148             72  ...  33.6                     0.627   50
1            1       85             66  ...  26.6                     0.351   31
2            8      183             64  ...  23.3                     0.672   32
3            1       89             66  ...  28.1                     0.167   21
4            0      137             40  ...  43.1                     2.288   33

[5 rows x 8 columns]

In [27]:
X.shape

(768, 8)

In [28]:
min_max_scaler = MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(X)
X = pd.DataFrame(x_scaled, columns=[feats])

In [29]:
X.head()

Pregnancies   Glucose  ... DiabetesPedigreeFunction       Age
0    0.352941  0.743719  ...                 0.234415  0.483333
1    0.058824  0.427136  ...                 0.116567  0.166667
2    0.470588  0.919598  ...                 0.253629  0.183333
3    0.058824  0.447236  ...                 0.038002  0.000000
4    0.000000  0.688442  ...                 0.943638  0.200000

[5 rows x 8 columns]

In [30]:
# Introduce learning rate somewhere of 0.1 or 0.01

class Perceptron(object):
    
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter
    
    def sigmoid(self, x):
        return 1/(1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)

    weights = 2 * np.random.random((8,1)) - 1

    def fit(self, X, y):

        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        weights = 2 * np.random.random((8,1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights)

            # Activate!
            activated_output = self.sigmoid(weighted_sum)

            # Cac error
            error = y - activated_output

            # Can add in learning rate for better performance.
            adjustments = error * self.sigmoid_derivative(weighted_sum)

            # Update the Weights
            weights += np.dot(X.T, adjustments)

        return activated_output

    def predict(self, X):
        return activated_output

In [31]:
X = np.array(X)
y = [[i] for i in y]

In [43]:
model = Perceptron(rate = 0.01, niter=10)

model.fit(X, y)

array([[1.61829738e-14],
       [1.43597322e-10],
       [3.02399304e-13],
       [2.10288669e-10],
       [3.90313700e-13],
       [1.78191955e-11],
       [7.07190417e-10],
       [5.66680883e-08],
       [1.53550458e-15],
       [5.69845914e-12],
       [2.99354008e-13],
       [9.75971642e-15],
       [1.73979965e-14],
       [1.70126903e-14],
       [4.65504642e-14],
       [4.16338948e-07],
       [9.22379817e-15],
       [8.68770233e-12],
       [2.64653812e-10],
       [1.58942369e-12],
       [6.18552937e-15],
       [3.34723502e-13],
       [1.85391420e-16],
       [1.67159002e-13],
       [2.34854692e-16],
       [2.26605089e-13],
       [4.72756598e-14],
       [2.55080645e-10],
       [1.67897803e-14],
       [1.53730398e-13],
       [1.36439578e-13],
       [1.67503024e-14],
       [1.38518822e-09],
       [1.51854321e-11],
       [7.72511383e-14],
       [1.70088030e-11],
       [1.10219812e-13],
       [1.04766459e-13],
       [3.58114353e-12],
       [1.42677903e-14],


In [35]:
predictions = model.predict(X)

predictions

array([[0.99999984],
       [0.99494573],
       [0.99494573],
       [0.00598321]])

In [34]:
model.predict(X)

array([[0.99999984],
       [0.99494573],
       [0.99494573],
       [0.00598321]])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?