<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The data we feed into the neural network
### Hidden Layer: The hidden layer contains the sum of the weights of the input layer.
### Output Layer: The prediction or solution to the question we were asking with the data.
### Neuron: The biological unit that neural network nodes are based on. It receives input from the brain and passes it on to complete other physical functions.
### Weight: The metric used to forward propegate the Input Layer to a Hidden Layer in order to obtain the output of a given neural network
### Activation Function: An activation function determines the output of a deep learning model. These include sigmoid, tanh and ReLU, which are non-linear activation functions. (What are linear activation functions?)
### Node Map: A node map is used to show the structure of a neural network.
### Perceptron: The simplest of neural networks, it includes only inputs and an output


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

We give the neural network input in the form of data, the inputs are then multiplied by the weights, a bias is added to the sum of the weights, an activation function is used to determine the output. The mathematics for weights, bias and activation functions are completed in the hidden layers and feed the answer to the output node.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [4]:
import pandas as pd

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [14]:
import numpy as np

# Turn data into an array
inputs = np.array([
    [0, 0, 1],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 0]
])

# Set the correct outputs for y
correct_outputs = [[1], [1], [1], [0]]

# show input data
print('Inputs', inputs)
# show output data
print('Correct Outputs', correct_outputs)

Inputs [[0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 0]]
Correct Outputs [[1], [1], [1], [0]]


In [8]:
# sigmoid activation function.
def sigmoid(x):
    return 1/ (1 + np.exp(-x))
# sigmoid derivative function to update weights.
def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [19]:
# Randomly intitialized weights
weights = 2 * np.random.random((3,1)) - 1

# weights = np.array([[1], [1], [-1.5]]) = Initializing non-random weights
weights

array([[ 0.66875514],
       [ 0.25988261],
       [-0.8878342 ]])

In [21]:
# Calculate the weighted sum of inputs and weights

weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.8878342 ],
       [-0.21907906],
       [-0.6279516 ],
       [ 0.92863775]])

In [24]:
# Use the sigmoid function on the weighted sum
activated_outputs = sigmoid(weighted_sum)

# Show the activated output
activated_outputs

array([[0.29155697],
       [0.44544825],
       [0.34797515],
       [0.71679883]])

In [26]:
# Find the error
error = correct_outputs - activated_outputs

# Show the error
error

array([[ 0.70844303],
       [ 0.55455175],
       [ 0.65202485],
       [-0.71679883]])

In [28]:
# Use the derivative function on the activated outputs (Gradient Descent)
adjustments = error * sigmoid_derivative(weighted_sum)

# Show the adjustments
adjustments

array([[ 0.14632997],
       [ 0.13698765],
       [ 0.1479369 ],
       [-0.14550892]])

In [29]:
# Create updated weights
weights += np.dot(inputs.T, adjustments)

# Show the updated weights
weights

array([[ 0.66023387],
       [ 0.26231059],
       [-0.45657968]])

In [30]:
# Steps we've already done: 
# 1. Randomly Initialized Weights already. Those are in memory as `weights`
# 2. We've already got input data & correct_outputs


# Update our weights 10,000 times to reduce error
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-2.40950532]
 [-2.41083635]
 [ 7.49004961]]
Output after training
[[0.99944165]
 [0.99382157]
 [0.99381339]
 [0.00799993]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [32]:
# Read in the data frame
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')

# Show the first five rows of the dataset
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [35]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

# Set the features as an array without the last column
features = list(diabetes)[:-1]

# Set the minmaxscalar
scaler = MinMaxScaler()

# Fit transform on the data with the set features
X = scaler.fit_transform(diabetes[features])

# Show the data
X

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [37]:
# Set the target with the last column (correct_outcome/y)
y = diabetes.iloc[:, 8].values

# Show the array
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [54]:
##### Update this Class #####


# perceptron class.
class Perceptron(object):
    
    def __init__(self, niter = 10000):
        self.niter = niter
    # sigmoid activation function.
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    # sigmoid derivative function to update weights.
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)
    # predict function.
    def predict(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # randomly initialize weights
        self.weight = np.zeros(X.shape[1])

        for i in range(self.niter):
            # sum up the weights.
            weighted_sum = np.dot(X, self.weight)  
            # use the sigmoid function on the weighted sum.
            activated_output = sigmoid(weighted_sum)   
            # find the calculation error.
            error = y - activated_output   
            # use the derivative function on the avivated outputs.
            adjustments = error * sigmoid_derivative(activated_output)   
            # update the weights with adjustments.
            self.weight += np.dot(X.T, adjustments)

        return activated_output


In [56]:
# imports.
from sklearn.metrics import accuracy_score
# set the perceptron.
pn = Perceptron()
# set the ypred with predict.
y_pred = pn.predict(X, y)
# create the test with ypred.
test = y_pred.astype(int)
print(test)
print('accuracy score:', accuracy_score(y, test))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?