<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

The input layer are the inital values being put into the model, your x variables. They can be tabular data, but also images and text.

### Hidden Layer:

If you imagine that a neural network is layers of different models, then the hidden layer is a model in the middle, one that takes outputs from another hidden layer or the input layer, and then creates an output given to the output layer. It is called a 'hidden' layer because we do not generally check the outputs of these layers when using/training a neural network. 

### Output Layer:

This is the result that you expect from your neural network. It is the final layer of the model that outputs a final result. 

### Neuron:

Receives input and produces an output, a single piece of the neural network that doesn't include the activation function. 

### Weight:

Each input in each layer of a neural network has a weight associated with it. When a neural network is created, these values are often picked at random and tuned during training. The weight can be thought of as similar to a coefficient in your equation. 

### Activation Function:

This is what decides whether, or how much, a neuron will 'fire', as they do in the biological sense. If the neuron does fire, based on how much it does, the output will be transferred to the next layer in the network. 

### Node Map:

These are basic, high level overviews to help us understand and differenciate between complex types of neural networks. 

### Perceptron:

A perception is the most simple form of a neural network, with only one layer.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

You begin with putting an input in, the first thing that happens is each input is multiplied by a weight. During training, this weight is created by iterating over many times to find the ideal weight. You then add all of the inputs multiplied by the sums together, and add on the bias. The bias helps to avoid over-fitting, and generally you want a bias that helps get the sum of multiplied inputs and weights get to the activation threshold. This is the last step before this cycle is repeated again, or we reach the final process. This decides whether the next layer is activated by the outputs, and if it is 'lit up' or a weaker output is passed on, or not being activated at all. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [2]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [10]:
np.random.seed(812)

inputs = np.array([
    [0, 0, 1],
    [1, 0, 1],
    [0, 1, 1],
    [1, 1, 0]
])

correct_outputs = [[1], [1], [1], [0] ]

In [4]:
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [2]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [6]:
import numpy as np

#we have our first column as inputs,
#two layers,
#and our output

#we have to begin by creating a sigmoid function and using it on our input values
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivitive(x):
    sx = sigmoid(x)
    return sx * (1- sx)

#we also need to create our initial weight values
weights = 2 * np.random.random((3,1)) -1

In [7]:
weights

array([[ 0.0099616 ],
       [ 0.21185521],
       [-0.08502562]])

In [8]:
data

{'x1': [0, 1, 0, 1], 'x2': [0, 0, 1, 1], 'y': [1, 1, 1, 0]}

In [8]:
# it is time to find the weighted sum of our inputs

weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.08502562],
       [-0.07506402],
       [ 0.12682959],
       [ 0.22181681]])

In [9]:
#lets find our first output value, given one training epoch

activated_output = sigmoid(weighted_sum)
activated_output

array([[0.47875639],
       [0.4812428 ],
       [0.53166496],
       [0.55522794]])

In [11]:
#now we find the amount of error, so we can adjust the weights to be more accurate

error = correct_outputs - activated_output
error

array([[ 0.52124361],
       [ 0.5187572 ],
       [ 0.46833504],
       [-0.55522794]])

In [13]:
#use the error to create adjustments for our weights

adjusted = error = sigmoid_derivitive(activated_output)
adjusted

array([[0.23620452],
       [0.23606625],
       [0.23313343],
       [0.23168101]])

In [14]:
#our improved weights

weights += np.dot(inputs.T, adjusted)
weights

array([[0.47770887],
       [0.67666965],
       [0.62037858]])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [15]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [16]:
diabetes.shape

(768, 9)

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [23]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes.iloc[0:768, [0, 1, 2, 3, 4, 5, 6, 7]]

y = diabetes.iloc[0:768, [8]]

In [24]:
y

Outcome
0          1
1          0
2          1
3          0
4          1
..       ...
763        0
764        0
765        0
766        1
767        0

[768 rows x 1 columns]

In [22]:
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [48]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        self.x = x
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        self.x = x
        sx = sigmoid(x)
        return sx * (1- sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        weights =  2 * np.random.random((8,1)) -1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weights)
            # Activate!
            activated_output = sigmoid(weighted_sum)
            # Cac error
            error = y - activated_output
            # Update the Weights
            adjusted = error = sigmoid_derivitive(activated_output)
            weights += np.dot(X.T, adjusted)

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

In [49]:
p = Perceptron(10)

In [50]:
p.fit(X, y)
p.predict(X)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':


AttributeError: 'Perceptron' object has no attribute 'net_input'

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?