<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

The input layer of a neural network takes the input signals, it doesn't apply any operations or have weights and biases. The input layer for image recognition might be all the pixels in the image.

For a dataset in a dataframe, the input layer might be all the feature columns.

### Hidden Layer:

The hidden layer, or layers, of a neural network, will take inputs from the previous layer (either input or another hidden layer) and apply weights to all the inputs as well as a bias term and apply an activation function (some sort of sigmoid or other activation function). If the inputs trigger the activation function, then the hidden layer nueron will send a signal to the next layer.


### Output Layer:

The output layer is the last layer of the network and recieves signals from the last hidden layer. Depending on the signals it recieves it will modify the output signal that we see.

### Neuron:

A single node, the basic unit of neural network. It recieves inputs, applies a weight to them and a bias. It then applies an activation function, which if it activates, sends a signal to the next next layer of the network.

### Weight:

Weight represents the strength of the connection between two neurons/nodes. They can be positive, negative or near zero.

### Activation Function:

This is the function, usually sigmoid, tanh, or relu that introduce the non-linearity of neural networks. They squash the inputs into a smaller range like a sigmoid and so the function either activates and sends a signal to the next layer, or it doesn't activate and sends no signal.

### Node Map:

A visual representation of the neural net, there are several different NN structures that are suited for different tasks: LSTM for natural language, or Deep Convoluted NN for image recognition.

### Perceptron:

A single node neural network, it takes several inputs, weighs them, applies an activation function and a bias and then send out an output.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [97]:
##### Your Code Here #####
import numpy as np

np.random.seed(2001)

inputs = np.array([
    [0,1,0, 1],
    [0,0,1,1]
])

correct_outputs = [[1,1,1,0]]

def tanh(x):
    nom = 2
    denom = (1 + np.exp(-2 * x))
    return (nom / denom) - 1

def tanh_deriv(x):
    return 1 - (tanh(x) ** 2)

In [98]:
np.dot(inputs, weights)

array([[ 0.71298746, -0.27716047],
       [-0.27310629, -0.95130961]])

In [99]:
activated_output

array([[ 0.61254677, -0.270275  ],
       [-0.26651287, -0.74037537]])

In [100]:
weighted_input

array([[ 0.71298746, -0.27716047],
       [-0.27310629, -0.95130961]])

In [106]:
weights = 2 * np.random.random((1,4)) - 1

for epoch in range(10000):
    #weigh the input variables
    weighted_input = np.dot(inputs, weights)
    weighted_input

    #activate the function on the weighted input
    activated_output = tanh(weighted_input)
    activated_output

    #calculate the error term as the difference between correct and activated output
    error = correct_outputs - activated_output
    error

    #gradient adjust back propogate the error
    adjustments = error * tanh_deriv(activated_output)
    adjustments

    weights += np.dot(inputs.T, adjustments)
    weights

print('Weights after training ', weights)

print('Activated output after training ', activated_output)

    
    

ValueError: shapes (2,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [104]:
np.random.random((4,2))

array([[0.64351347, 0.65772245],
       [0.06606537, 0.64535942],
       [0.12120544, 0.50294212],
       [0.39197015, 0.126939  ]])

In [66]:
# interesting that this function did not work with tanh, I'll try sigmoid

def perceptron(activation, deriv, inputs, correct_outputs, weights, epochs):
    
    for epoch in range(epochs):
        #weigh the input variables
        weighted_input = np.dot(inputs, weights)

        #activate the function on the weighted input
        activated_output = activation(weighted_input)

        #calculate the error term as the difference between correct and activated output
        error = correct_outputs - activated_output
        

        #gradient adjust back propogate the error
        adjustments = error * deriv(activated_output)
        weights += np.dot(inputs.T, adjustments)
        

    print('Weights after training ', weights)

    print('Activated output after training ', activated_output)
    

In [67]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [70]:
inputs = np.array([
    [0,0],
    [1,0],
    [0,1],
    [1,1]
])

correct_outputs = [[1], [1], [1], [0]]

weights = 2 * np.random.random((2,1)) - 1

perceptron(sigmoid, sigmoid_derivative, inputs, correct_outputs, weights, 100000)

Weights after training  [[ 1.66533454e-16]
 [-3.05311332e-16]]
Activated output after training  [[0.5]
 [0.5]
 [0.5]
 [0.5]]


In [181]:
# neither of the above implementations works so I'll try the dummy columns
import numpy as np
np.random.seed(812)

# adding a row of dummy ones

inputs = np.array([
    [0,0, 1],
    [1,0, 1],
    [0,1, 1],
    [1,1, 1]
])

correct_outputs = [[1], [1], [1], [0]]

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

weights = 2 * np.random.random((3,1)) - 1  #this creates the potential for negative random numbers, so we get range(-1,1)
weights

bias = -0.8

for iteration in range(100000):
    # Weighted sum of inputs/weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum + bias) 
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-16.45541379]
 [-16.45541379]
 [ 25.53131611]]
Output after training
[[1.00000000e+00]
 [9.99745484e-01]
 [9.99745484e-01]
 [2.80263095e-04]]


In [121]:
# that worked, so I needed bias in order to `activate` the sigmoid function? maybe?

## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [74]:
##### Your Code Here #####
import pandas as pd

url = 'https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv'
pima_df = pd.read_csv(url)

pima_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [158]:
# I want activations that correspond to negative weights to be lower
# and activations that correspond to positive weights to be higher
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of neural network
        self.input = 8
        self.hiddenNodes = 9
        self.outputNodes = 1
        
        # Initial Weights
        # 8x9 matrix for first layer
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        #9x1 matrix for hidden to output layer
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forawrd

        """

        #weighted sum of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)

        #Activations of weighted sums
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        #Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        # Final Activation of output
        self.activated_output = self.sigmoid(self.output_sum)

        return (self.activated_output)
    
    def get_attributes(self):
        
        attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']

        [print(i + '\n', getattr(nn,i), '\n' + '---'*3) for i in dir(nn) if i in attributes]

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [169]:
target = 'Outcome'

X = pima_df.drop(columns=target).values
y = np.array(pima_df[target]).reshape(pima_df.shape[0], 1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state=2001)

In [174]:
y_train.shape

(691, 1)

In [171]:
nn = NeuralNetwork()
print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 weights: \n", nn.weights2)

Layer 1 weights: 
 [[-0.95536998 -0.26147293 -0.5255482  -1.27932348 -1.15666451 -0.82438149
   0.85881406 -0.17868153  0.55579413]
 [-1.2205535  -1.10577648  0.24260815  0.63241576  1.11306683 -0.99875325
   0.13751903 -0.02939866  0.4040244 ]
 [-1.43998803  0.3988736  -0.16112681  1.08606078  1.10026901  0.70566204
   0.24548742 -2.01646116 -0.6149177 ]
 [-0.73106283 -0.58544964  0.01084408 -0.4755477   0.33709497  1.5317098
   3.32809322  0.40969134  0.14847584]
 [-1.41704162 -0.77984809 -0.91179833 -1.51700024 -0.78250644  0.05435741
  -0.1479062  -0.69677054 -0.79682132]
 [ 0.0144473   0.51020183  0.42874783  0.46821144  0.75036515 -1.20297078
   0.28298656 -0.4748899  -0.02505139]
 [-0.36871357 -2.59725252  0.98548421  0.89970768  1.16001943 -2.13608208
  -0.67313108 -0.07811872 -0.81917962]
 [-0.36132764 -1.1560178   0.33528418 -0.05034614 -0.01697218 -1.91639276
   2.23954675  0.01640627 -0.27541553]]
Layer 2 weights: 
 [[ 0.52777853]
 [ 1.55659807]
 [-0.50422319]
 [ 1.20872874

In [175]:
nn = NeuralNetwork()

for i in range(1000):
    nn.train(X_train,y_train)

In [180]:
print('Loss: ', str(np.mean(np.square(y_test - nn.feed_forward(X_test)))))

Loss:  0.35064935064935066


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?