<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
The layer of nodes which receives input from your data
### Hidden Layer:
A layer of nodes, since there can be multiple, that take data from the input layer or other hidden layers and apply their rules or transformations
### Output Layer:
The nodes which handle displaying the result of the various rules and transformations generated by the network
### Neuron:
A type of cell found within the human brain, which is what a node in a neural network is based off of in terms of functionality, hence the name "neural network"
### Weight:
The weight of a connection; this affects how strongly a node might consider the results of a node in the previous layer, as well as how strongly its own results will be treated.
### Activation Function:
The function inside the node which applies transformations to the data passing through it.
### Node Map:
A visual representation of the various nodes in a network and their connections. [Some examples](https://www.asimovinstitute.org/wp-content/uploads/2019/04/NeuralNetworkZo19High.png)
### Perceptron:
The simplest type of neural network, comprised of two Input nodes leading into an output node.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

The data is fed into the input layer, through the hidden layers, and eventually to the output. At each layer, it will apply the transformations it thinks will give the most accurate result, and eventually come to a conclusion. Each one of these cycles is called an "epoch", and after each one, it updates its transformations and connection weights to try and come closer to the correct answer.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [35]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

inputs = np.array(df[['x1','x2']])
correct_outputs = []
for y in df['y']:
    correct_outputs.append([y])
correct_outputs = np.array(correct_outputs)

##### Your Code Here #####
import numpy as  np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

print("Inputs:",inputs)
print("Correct Outputs",correct_outputs)

class Perceptron:
    def __init__(self):
        """
        Class constructor for Perceptron.
        
        make sure you use Perceptron.fit() before trying to get predictions
        """
        self.inputs = None
        self.correct_outputs = None
    
    def resolve(self, inputs, correct_outputs, iterations=10000):
        """
        Fit this model to some data
        
        Parameters
        ----------
        inputs: 2d numpy array, in a [[row], [row], [row]] format
        
        correct_outputs: 2d numpy array, in a [[row], [row], [row]] format
        
        Returns
        -------
        2d numpy array
            resulting weights for the data.
            
        2d numpy array
            resulting output for the data.
        """
        
        # generate some initial weights for the perceptron
        weights = np.random.random((len(inputs[0]),1))
        print("Weights",weights)

        for i in range(iterations):
            # get the dot product of the weighted sum of the inputs and weights
            weighted_sum = np.dot(inputs, weights)
            #print("Weighted Sum",weighted_sum)

            # get the sigmoid of the weighted sum
            activated_output = sigmoid(weighted_sum)
            #print("Activated Output",activated_output)

            # subtract the correct values by the activated outputs
            error = correct_outputs - activated_output
            #print("Error",error)

            # and from the errors, get the adjustments that need to be made
            adjustments = error * sigmoid_derivative(weighted_sum)
            #print("Adjustments",adjustments)

            # and update the weights
            weights += np.dot(inputs.T, adjustments)
        
        return weights, adjustments

p = Perceptron()
print(p.resolve(inputs, correct_outputs, iterations=100))

Inputs: [[0 0]
 [1 0]
 [0 1]
 [1 1]]
Correct Outputs [[1]
 [1]
 [1]
 [0]]
Weights [[0.26410126]
 [0.35829928]]
(array([[-6.69315558e-05],
       [ 6.69281331e-05]]), array([[ 0.125     ],
       [ 0.12500446],
       [ 0.12499554],
       [-0.125     ]]))


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [36]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [37]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

n = Normalizer()

feats = list(diabetes)[:-1]

X = diabetes[feats]
Xn = n.fit_transform(X)
y = np.array([[r] for r in diabetes['Outcome']])
print(Xn[:5])
y[:5]

[[0.03355237 0.82762513 0.40262844 0.19572216 0.         0.18789327
  0.00350622 0.27960308]
 [0.008424   0.71604034 0.55598426 0.24429612 0.         0.22407851
  0.00295683 0.26114412]
 [0.04039768 0.92409698 0.32318146 0.         0.         0.11765825
  0.00339341 0.16159073]
 [0.00661199 0.58846737 0.43639153 0.15207584 0.62152733 0.185797
  0.0011042  0.13885185]
 [0.         0.5963863  0.17412739 0.15236146 0.73133502 0.18762226
  0.00996009 0.14365509]]


array([[1],
       [0],
       [1],
       [0],
       [1]])

In [52]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
        self.weights = None
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Initialize Weights and errors
        self.weights = np.zeros(1 + X.shape[1])
        self.errors = []
        for i in range(self.niter):
            err = 0
            # iterate through records
            for xi, target in zip(X, y):
                # update delta
                delta_w = 0.01 * (target - self.predict(xi))
                # update non-bias weights
                self.weights[1:] += delta_w * xi
                # update bias
                self.weights[0] += delta_w
                # update error
                err += int(delta_w != 0.0)
            # append errors onto errorlist
            self.errors.append(err)

    def predict(self, X):
        """Return class label after unit step"""
        return np.where((np.dot(X, self.weights[1:]) + self.weights[0]) >= 0.0, 1, 0)
        
p = Perceptron()
p.fit(Xn, y)
print(p.predict(Xn)[:10])
print(y[:10])

[0 0 1 0 1 0 0 1 1 0]
[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]]


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?