<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The layer to a network where external values are fed.
### Hidden Layer: A layer between the input and output layers where hidden stuff happens
### Output Layer: The final layer of a network which results are read from.
### Neuron: A node in a neural network with associated activation and connecting weights
### Weight: A connection between two neurons dictating the degree to which a signal is scaled
### Activation Function: A function used to calculate the output value of a neuron, often used for the purposes of scaling neuron 
### Node Map: A diagramatic presentation of a neural network depicing neurons as small circles and weights as connecting lines
### Perceptron: A kind of neural network with a simple input fed to an outpu


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Training data starts at the input layer. the input layer then activates using connecting weights to other layers. The hidden layers receive these signals, then relay them, modify them using appropriate weights, applying their activation functions, then sending them to the next layer. At each layer, a bias term is applied, perterbing the whole signal in some direction. The final layer is the output layer, from which the results from the network can be read.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [4]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [7]:
##### Your Code Here #####
per = Perceptron(niter = 10000)

X = (np.array([data['x1'], data['x2']]).T)
y = (np.array([data['y']]).T)

per.fit(X, y)

np.round(per.predict(X))

array([[1.],
       [1.],
       [1.],
       [0.]])

In [12]:
per.weights

array([[-12.55254133],
       [-12.55254133]])

In [312]:
y

array([[1],
       [1],
       [1],
       [0]])

diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [15]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = np.array(diabetes[feats])
y = np.array(diabetes[['Outcome']])

mms = MinMaxScaler()
X = mms.fit_transform(X)

In [22]:
per = Perceptron(niter = 100000)

per.fit(X, y)

In [23]:
pred = np.round(per.predict(X))

In [24]:
from sklearn.metrics import accuracy_score

accuracy_score(pred, y)

0.75

Descent.

In [6]:
##### Update this Class #####
import numpy as np

class Perceptron(object):
    
    def __relu(x):
        if x >= 0:
            return x
        else:
            return 0
    
    def __relu_array(x):
        return np.vectorize(Perceptron.__relu)(x)

    def __relu_derivative(x):
        if x >= 0:
            return 1
        else:
            return 0
    
    def __relu_derivative_array(x):
        return np.vectorize(Perceptron.__relu_derivative)(x)
    
    def __sigmoid(x):
        return 1 / (1 + np.exp(-x))

    def __sigmoid_derivative(x):
        sx = Perceptron.__sigmoid(x)
        return sx * (1-sx)
    
    def __init__(self, niter = 10):
        self.niter = niter

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # X : n x m
        # y : n x 1
        
        # Randomly Initialize Weights
        # weights : m x 1
        self.weights = 2 * np.random.random((len(X.T), 1)) - 1
        
        # Randomly initialized bias
        # bias : n x 1
        self.bias = 2 * np.random.random() - 1

        for i in range(self.niter):
            #print("\nweights\n", self.weights)
            
            # Weighted sum of inputs / weights
            # weighted_sum : (n x m) ; (m x 1) = n x 1
            weighted_sum = np.dot(X, self.weights) + self.bias
            #print("\nweighted_sum\n", weighted_sum)
            
            # activated : n x 1
            activated = Perceptron.__sigmoid(weighted_sum)
            #print("\nactivated\n", activated)

            # Cac error
            # error : n x 1
            error = y - activated
            #print("\nerror\n", error)

            # Update the Weights
            # adjusted : n x 1
            adjusted = error * Perceptron.__sigmoid_derivative(activated)
            #print("\nadjusted\n", adjusted)
            
            # weights : (m x n) ; (n x 1) = m x 1
            self.weights += np.dot(X.T, adjusted)
            self.bias += np.mean(error)


    def predict(self, X):
        """Return class label after unit step"""
        weighted_sum = np.dot(X, self.weights) + self.bias
        
        return Perceptron.__sigmoid(weighted_sum)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?