<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np

np.random.seed(734)

In [2]:
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [3]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [16]:
inputs = np.array(df)
print(inputs.shape)
inputs

(4, 3)


array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [17]:
target_outputs = []
for i in df['y']:
    target_outputs.append([i])
print('target out:', target_outputs)

target out: [[1], [1], [1], [0]]


In [18]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [19]:
weights = 2 * np.random.random((len(inputs[0]),1)) - 1
weights

array([[-0.26251945],
       [-0.23963685],
       [ 0.59215452]])

In [20]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[ 0.59215452],
       [ 0.32963506],
       [ 0.35251767],
       [-0.50215631]])

In [21]:
activated_output = sigmoid(weighted_sum)
print(f'target output:{target_outputs}\n')
print(f'activated output:{activated_output}')

target output:[[1], [1], [1], [0]]

activated output:[[0.64385934]
 [0.58167058]
 [0.58722797]
 [0.37703406]]


In [22]:
error = target_outputs - activated_output
error

array([[ 0.35614066],
       [ 0.41832942],
       [ 0.41277203],
       [-0.37703406]])

In [23]:
adjusted = error * sigmoid_derivative(activated_output)
adjusted

array([[ 0.08040971],
       [ 0.09621217],
       [ 0.09478421],
       [-0.09098649]])

In [24]:
weights += np.dot(inputs.T, adjusted)
weights

array([[-0.25729377],
       [-0.23583913],
       [ 0.86356061]])

In [25]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calc error
    error = target_outputs - activated_output
    
    adjusted = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjusted)
    
print("\nWeights after training")
print(weights)

print("\nOutput after training")
print(activated_output)

print("\nOutput after training (rounded)")
print(activated_output.round())


Weights after training
[[-3.80709658]
 [-3.80690885]
 [11.6971269 ]]

Output after training
[[9.99991681e-01]
 [9.99625645e-01]
 [9.99625715e-01]
 [4.93296859e-04]]

Output after training (rounded)
[[1.]
 [1.]
 [1.]
 [0.]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [26]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [27]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [ ]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
    self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights

        # Activate!

        # Calc error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?