<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

The first stage of a nural network, the input layer is the initial data that is fed to the machine. There should be exactly one input node for each feature. 

### Hidden Layer:

The intermediate step between input and output, the hidden layer carries out computations before feeding data to the output layer. A perceptron has no hidden layer, while some neural networks can have one or multiple hidden layers.

### Output Layer:

The final step, the output layer gives the expected result of the neural network. Like the input layer, the output layer has one node for each feature the neural network is designed to spit out. 

### Neuron:

A neuron or a 'node' is a component of neural network that takes some input and produces an output. These inputs and outputs can either be the inputs or outputs of the neural network as a whole, or come from/go to other neurons in the network. 

### Weight:

The weight is the value by which the input value(s) are modified in a node before being outputted. For example, a node might work on a function similar to y = 100 * x, in which case the weight would be 100. Weights are often changed over time as a neural network is improved, with weights being adjusted mathematically in ways that are assumed to make the output of a network closer to the 'true' value.

### Activation Function:

The activation function is the mathematical function that happens inside of a node. There are many types of activation functions, although every node in a particular layer all have the same type of activaction function. This function determines whether or not a node 'fires', and what signal to send to other nodes. 

### Node Map:

A node map is a visual representation of the layout of a neural network. It can give a rough idea of how a neural network works by showing what path the data takes from the input and output. It is useful or illistrating the differences between different types of neural networks.

### Perceptron:

A perceptron is the most simple kind of neural network that has only one input layer, an output layer, and no hidden layers. 

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
##### Your Code Here #####

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [3]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [4]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [5]:
df['bias'] = 1
inputs = df[['x1', 'x2', 'bias']].to_numpy()
print("inputs:\n", inputs, '\n')
correct_outputs = df['y'].to_numpy()
correct_outputs = correct_outputs[np.newaxis].T
print("correct outputs:\n", correct_outputs, '\n')

weights = 2 * np.random.random((3,1)) - 1
print("weights:\n", weights, '\n')
weighted_sum = np.dot(inputs, weights)
print("weighted sum:\n", weighted_sum,'\n')
activated_output = sigmoid(weighted_sum)
print("activated output:\n", activated_output, '\n')
error = correct_outputs - activated_output
print("error:\n", error, '\n')
adjustments = error * sigmoid_derivative(weighted_sum)
print('adjustments:\n', adjustments, '\n')
weights += np.dot(inputs.T, adjustments)

inputs:
 [[0 0 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]] 

correct outputs:
 [[1]
 [1]
 [1]
 [0]] 

weights:
 [[ 0.77814201]
 [ 0.97663108]
 [-0.93800792]] 

weighted sum:
 [[-0.93800792]
 [-0.15986591]
 [ 0.03862316]
 [ 0.81676517]] 

activated output:
 [[0.28130291]
 [0.46011842]
 [0.50965459]
 [0.69354924]] 

error:
 [[ 0.71869709]
 [ 0.53988158]
 [ 0.49034541]
 [-0.69354924]] 

adjustments:
 [[ 0.14530013]
 [ 0.13411169]
 [ 0.12254065]
 [-0.14740605]] 



In [6]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-8.01780976]
 [-8.01780976]
 [12.11318185]]
Output after training
[[0.99999451]
 [0.98362227]
 [0.98362227]
 [0.01940964]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [20]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
print(diabetes.shape)
diabetes.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [50]:
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.metrics import accuracy_score

feats = list(diabetes)[:-1]

X = diabetes[feats].to_numpy()
Y = diabetes['Outcome'].to_numpy()

# n = 150
# X = diabetes[feats].head(n).to_numpy()
# Y = diabetes['Outcome'].head(n).to_numpy()

Y = Y[np.newaxis].T

In [51]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = self.__sigmoid(x)
        return sx * (1-sx)

    def fit(self, x, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        
        # Transform data
        self.transformer = MinMaxScaler()
        x = self.transformer.fit_transform(x)
        x = np.append(x, np.ones((len(y), 1)), axis=1)
        
        # Randomly Initialize Weights
        self.weights = 2 * np.random.random((np.size(x, 1), 1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(x, self.weights)

            # Activate!
            activated_output = self.__sigmoid(weighted_sum)

            # Cac error
            error = y - activated_output
            rate = 0.01
            adjustments = rate * error * self.__sigmoid_derivative(weighted_sum)

            # Update the Weights
            self.weights += np.dot(x.T, adjustments)
            
#         print(activated_output)            
        return self


    def predict(self, x):
        """Return class label after unit step"""
        
        # Transform data
        x = self.transformer.transform(x)
        x = np.append(x,
                      np.ones((np.size(x,0), 1)),
                      axis=1)
        
        weighted_sum = np.dot(x, self.weights)
        return self.__sigmoid(weighted_sum)

In [52]:
pn = Perceptron(10000)
pn.fit(X, Y)
Y_pred = np.round(pn.predict(X))
print(accuracy_score(Y, Y_pred))

0.78125


In [53]:
Y_pred = np.round(pn.predict(diabetes[feats].to_numpy()))
print(accuracy_score(diabetes['Outcome'].to_numpy(), Y_pred))

0.78125


In [54]:
print(Y_pred.T)

[[1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 0. 0.
  0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1.
  0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0.
  1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0.
  1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1.
  0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0.
  0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.
  0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 0.
  0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 

Not great, but we'll call this good.

In [55]:
from statistics import mode

baseline = list(Y.T[0])

baseline_pred = mode(list(Y.T[0]))
n = np.size(Y,0)
baseline_pred = np.full((n, 1), baseline_pred)

baseline = (accuracy_score(Y , baseline_pred))
print(baseline)

0.6510416666666666


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?