# Intro to Neural Networks Assignment

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: Receives input from the dataset. 
### Hidden Layer: Layers after the input layer. Deep learning is using multiple hidden layers.
### Output Layer: The final layer of a neural network
### Neuron: A node in a network
### Weight: The amount of influence an input has.
### Activation Function: decide how much signal to pass onto the next layer. Common activation functions: sigmoid, tanh, step, relu
### Node Map: Visual diagram of the architecture of our neural network.
### Perceptron: A single node or nueron of a neural network and nothing else.
### Bias: as means, how far off our predictions are from real values.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Data flows to the inputs where activation functions commence before passing on a value with weight(multiplied) and bias(added). The value undergoes another activation function and passes another value to the output multiplied by weight and added by bias.

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [15]:
##### Your Code Here #####
import numpy as np

inputs = np.array([[1,0,0],
                   [1,1,0],
                   [1,0,1],
                   [1,1,1]])

correct_outputs = [[1],
                   [1],
                   [1],
                   [0]]

In [16]:
## Sigmoid activation funcation and its derivative for updating weights

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [19]:
# Initialize random weights for 2 inputs
weights = 2 * np.random.random((3,1)) - 1
weights

array([[-0.01704184],
       [ 0.44589882],
       [ 0.14704545]])

In [20]:
# Calculate weighted sum of inputs and weights

weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.01704184],
       [ 0.42885698],
       [ 0.13000361],
       [ 0.57590243]])

In [21]:
#Output the activated value for the end of 1 training epoch

activated_output = sigmoid(weighted_sum)
activated_output

array([[0.49573964],
       [0.60560069],
       [0.5324552 ],
       [0.64012401]])

In [22]:
# Take difference of output and true values to calculate error

error = correct_outputs - activated_output
error

array([[ 0.50426036],
       [ 0.39439931],
       [ 0.4675448 ],
       [-0.64012401]])

In [23]:
adjustments = error * sigmoid_derivative(activated_output)
adjustments

array([[ 0.11862626],
       [ 0.0900846 ],
       [ 0.10897794],
       [-0.14469535]])

In [24]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.15595161],
       [0.39128807],
       [0.11132803]])

In [25]:
for iteration in range(10000):
  
  # Weighted sum of inputs and weights
    weighted_sum = np.dot(inputs, weights)
  
  # Activate with sigmoid function
    activated_output = sigmoid(weighted_sum)
  
  # Calculate Error
    error = correct_outputs - activated_output
  
  # Calculate weight adjustments with sigmoid_derivative
    adjustments = error * sigmoid_derivative(activated_output)
  
  # Update weights
    weights += np.dot(inputs.T, adjustments)

print('optimized weights after training: ')
print(weights)

print("Output After Training:")
print(activated_output)

optimized weights after training: 
[[ 17.8076071 ]
 [-11.83916152]
 [-11.83916152]]
Output After Training:
[[0.99999998]
 [0.99744806]
 [0.99744806]
 [0.0028132 ]]


## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [14]:
##### Your Code Here #####
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')

df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
class Perceptron()





## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?