<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.
<br>
### Input Layer: <br>
* The input layer is what brings the initial data into the neural network for further processing. It is the very beginning of the neural network pipeline. <br>
### Hidden Layer: <br>
* The hidden layer (or layers) is used to transform the inputs into values that are useful for the output layer. <br>
### Output Layer: <br>
* The output layer is the last layer in a neural network and produces the desired output for the model. <br>
### Neuron: <br>
* Neurons are what constitute the input, hidden, and output layers of a neural network. Neurons consist of a set of inputs, a set of weights, and an activation function. <br>
### Weight: <br>
* A weight represent the strength of the connection between units. If the weight from node 1 to node 2 has greater magnitude, it means that neuron 1 has greater influence over neuron 2. A weight brings down the importance of the input value. <br>
### Activation Function: <br>
* The activation function determines whether a neuron is "fired" (activated) or not. <br>
### Node Map: <br>
* The node map shows the interactions between the layers and nurons of the neural network. <br>
![Neural Network](https://cdn-images-1.medium.com/max/1200/1*DW0Ccmj1hZ0OvSXi7Kz5MQ.jpeg) <br>
### Perceptron: <br>
* Simply, a perceptron is a single layer neural network.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [514]:
import numpy as np
import pandas as pd

np.random.seed(812)

inputs = np.array([
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [1,1,1]
])

ground_truth = [[0], [1], [1], [1]]

In [515]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

def sigmoid_derivate(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [503]:
sigmoid(0.1)

0.52497918747894

In [516]:
weights = 2 *np.random.random((3,1)) -1
weights

array([[ 0.0099616 ],
       [ 0.21185521],
       [-0.08502562]])

In [517]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.08502562],
       [ 0.12682959],
       [-0.07506402],
       [ 0.13679119]])

In [518]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.47875639],
       [0.53166496],
       [0.4812428 ],
       [0.53414457]])

In [519]:
error = ground_truth - activated_output
error

array([[-0.47875639],
       [ 0.46833504],
       [ 0.5187572 ],
       [ 0.46585543]])

In [520]:
adjustments = error * sigmoid_derivate(activated_output)
adjustments

array([[-0.11308442],
       [ 0.10918455],
       [ 0.12246107],
       [ 0.10853639]])

In [521]:
sigmoid_derivate(.5)

0.2350037122015945

In [522]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.24095906],
       [0.42957616],
       [0.14207197]])

In [523]:
for iteration in range(1000):
    
    # Weighted sum of inputs/weights
    weighted_sum = np.dot(inputs, weights)
    print(weighted_sum)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    print(activated_output)
    
    # Calculate the error
    error = ground_truth - activated_output
    
    # Adjustments
    adjustments = error * sigmoid_derivate(activated_output)
    
    weights += np.dot(inputs.T, adjustments)
    #print(weights)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

[[0.14207197]
 [0.57164813]
 [0.38303103]
 [0.81260719]]
[[0.53545837]
 [0.63914338]
 [0.59460394]
 [0.6926648 ]]
[[0.26015704]
 [0.83963463]
 [0.66231731]
 [1.2417949 ]]
[[0.56467489]
 [0.69838826]
 [0.65978075]
 [0.77587629]]
[[0.32138535]
 [1.01614802]
 [0.84835414]
 [1.5431168 ]]
[[0.57966184]
 [0.7342216 ]
 [0.70022177]
 [0.82391736]]
[[0.35000967]
 [1.14032984]
 [0.98075869]
 [1.77107885]]
[[0.58661992]
 [0.75774019]
 [0.72725873]
 [0.85459179]]
[[0.35827687]
 [1.23168375]
 [1.0793808 ]
 [1.95278768]]
[[0.58862325]
 [0.77411313]
 [0.74637679]
 [0.87575029]]
[[0.35308374]
 [1.30107339]
 [1.15531533]
 [2.10330498]]
[[0.58736518]
 [0.78601558]
 [0.76048044]
 [0.89122399]]
[[0.33865782]
 [1.35509881]
 [1.2153187 ]
 [2.23175969]]
[[0.58386445]
 [0.79496197]
 [0.77123868]
 [0.90306551]]
[[0.31775833]
 [1.39803703]
 [1.26377666]
 [2.34405535]]
[[0.57877784]
 [0.80187221]
 [0.77967555]
 [0.91246055]]
[[0.29227213]
 [1.43279661]
 [1.30367563]
 [2.4442001 ]]
[[0.5725523 ]
 [0.80733669]
 [0

[[-2.79680795]
 [ 3.5238955 ]
 [ 3.52268006]
 [ 9.84338351]]
[[0.05749691]
 [0.97136007]
 [0.97132624]
 [0.99994691]]
[[-2.79974294]
 [ 3.52667599]
 [ 3.52546738]
 [ 9.85188631]]
[[0.05733807]
 [0.97143733]
 [0.97140377]
 [0.99994735]]
[[-2.80266964]
 [ 3.5294491 ]
 [ 3.52824727]
 [ 9.86036601]]
[[0.05718008]
 [0.97151417]
 [0.97148089]
 [0.9999478 ]]
[[-2.80558809]
 [ 3.53221488]
 [ 3.53101975]
 [ 9.86882272]]
[[0.05702295]
 [0.97159061]
 [0.97155761]
 [0.99994824]]
[[-2.80849833]
 [ 3.53497334]
 [ 3.53378488]
 [ 9.87725656]]
[[0.05686667]
 [0.97166665]
 [0.97163392]
 [0.99994867]]
[[-2.81140042]
 [ 3.53772454]
 [ 3.53654269]
 [ 9.88566765]]
[[0.05671122]
 [0.9717423 ]
 [0.97170983]
 [0.9999491 ]]
[[-2.8142944 ]
 [ 3.54046852]
 [ 3.53929321]
 [ 9.89405612]]
[[0.0565566 ]
 [0.97181755]
 [0.97178534]
 [0.99994953]]
[[-2.8171803 ]
 [ 3.54320529]
 [ 3.54203648]
 [ 9.90242208]]
[[0.05640281]
 [0.97189241]
 [0.97186046]
 [0.99994995]]
[[-2.82005819]
 [ 3.54593492]
 [ 3.54477255]
 [ 9.910765

[[-3.37349613]
 [ 4.07779451]
 [ 4.07739724]
 [11.52868788]]
[[0.03313412]
 [0.98333755]
 [0.98333104]
 [0.99999016]]
[[-3.37517179]
 [ 4.07942196]
 [ 4.07902599]
 [11.53361974]]
[[0.03308048]
 [0.98336419]
 [0.98335771]
 [0.9999902 ]]
[[-3.37684471]
 [ 4.08104683]
 [ 4.08065215]
 [11.53854369]]
[[0.03302701]
 [0.98339075]
 [0.9833843 ]
 [0.99999025]]
[[-3.37851489]
 [ 4.08266912]
 [ 4.08227573]
 [11.54345975]]
[[0.03297372]
 [0.98341723]
 [0.98341081]
 [0.9999903 ]]
[[-3.38018235]
 [ 4.08428885]
 [ 4.08389674]
 [11.54836794]]
[[0.03292059]
 [0.98344362]
 [0.98343724]
 [0.99999035]]
[[-3.38184708]
 [ 4.08590602]
 [ 4.08551518]
 [11.55326828]]
[[0.03286763]
 [0.98346993]
 [0.98346358]
 [0.9999904 ]]
[[-3.38350911]
 [ 4.08752063]
 [ 4.08713107]
 [11.55816081]]
[[0.03281484]
 [0.98349616]
 [0.98348984]
 [0.99999044]]
[[-3.38516843]
 [ 4.08913271]
 [ 4.08874441]
 [11.56304555]]
[[0.03276222]
 [0.98352231]
 [0.98351601]
 [0.99999049]]
[[-3.38682506]
 [ 4.09074225]
 [ 4.0903552 ]
 [11.567922

[[-3.6634541 ]
 [ 4.36053888]
 [ 4.36031393]
 [12.3843069 ]]
[[0.02500262]
 [0.98738955]
 [0.98738675]
 [0.99999582]]
[[-3.66471484]
 [ 4.36177273]
 [ 4.36154834]
 [12.38803592]]
[[0.02497191]
 [0.9874049 ]
 [0.98740211]
 [0.99999583]]
[[-3.66597402]
 [ 4.36300509]
 [ 4.36278126]
 [12.39176038]]
[[0.02494127]
 [0.98742022]
 [0.98741744]
 [0.99999585]]
[[-3.66723165]
 [ 4.36423596]
 [ 4.36401268]
 [12.39548029]]
[[0.0249107 ]
 [0.9874355 ]
 [0.98743273]
 [0.99999586]]
[[-3.66848772]
 [ 4.36546535]
 [ 4.36524262]
 [12.39919568]]
[[0.02488021]
 [0.98745075]
 [0.98744799]
 [0.99999588]]
[[-3.66974223]
 [ 4.36669325]
 [ 4.36647107]
 [12.40290654]]
[[0.02484979]
 [0.98746595]
 [0.9874632 ]
 [0.99999589]]
[[-3.6709952 ]
 [ 4.36791967]
 [ 4.36769803]
 [12.4066129 ]]
[[0.02481945]
 [0.98748112]
 [0.98747838]
 [0.99999591]]
[[-3.67224663]
 [ 4.36914461]
 [ 4.36892352]
 [12.41031476]]
[[0.02478917]
 [0.98749626]
 [0.98749353]
 [0.99999592]]
[[-3.67349652]
 [ 4.37036808]
 [ 4.37014753]
 [12.414012

## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [486]:
url = 'https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv'

df = pd.read_csv(url)
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [487]:
df['Ones'] = np.ones(df.shape[0])
df['Ones'] = df["Ones"] + 9

In [488]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  Ones  
0                     0.627   50        1  10.0  
1                     0.351   31        0  10.0  
2                     0.672   32        1  10.0  
3                     0.167   21        0  10.0  
4                     2.288   33        1  10.0

In [489]:
features = ['Pregnancies', 'Glucose', 'BloodPressure',
             'SkinThickness', 'Insulin', 'BMI',
             'DiabetesPedigreeFunction', 'Age', 'Ones']
target = 'Outcome'

inputs = df[features]
ground_truth = pd.DataFrame(df[target])

print(inputs.shape, ground_truth.shape)

(768, 9) (768, 1)


In [490]:
weights = 2 *np.random.random((9,1)) -1
weights

array([[ 0.86391197],
       [ 0.08396928],
       [-0.20370562],
       [-0.47844378],
       [ 0.82697071],
       [-0.04634884],
       [ 0.89065764],
       [-0.94820024],
       [ 0.6627738 ]])

In [491]:
for iteration in range(10000):
    
    # Weighted sum of inputs/weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    #print(activated_output)
    
    # Calculate the error
    error = ground_truth - activated_output
    
    # Adjustments
    adjustments = error * sigmoid_derivate(activated_output)
    
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 6.71592724e+04]
 [ 2.18063605e+04]
 [-4.50854787e+03]
 [ 1.13546595e+02]
 [ 3.84468048e+03]
 [ 4.33797802e+04]
 [ 1.80432886e+05]
 [ 1.23158296e+04]
 [-4.21045558e+05]]
Output after training
[[1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0

In [492]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  Ones  
0                     0.627   50        1  10.0  
1                     0.351   31        0  10.0  
2                     0.672   32        1  10.0  
3                     0.167   21        0  10.0  
4                     2.288   33        1  10.0

In [493]:
test_df = pd.DataFrame(df['Outcome'])

In [494]:
test_df['y_pred'] = activated_output 

In [495]:
test_df.head()

Outcome  y_pred
0        1     1.0
1        0     0.0
2        1     1.0
3        0     0.0
4        1     0.0

In [496]:
test_df['diff'] = test_df['Outcome'] - test_df['y_pred']

In [497]:
test_df['diff'].value_counts(normalize=True)

 0.0    0.725260
 1.0    0.253906
-1.0    0.020833
Name: diff, dtype: float64

In [498]:
df['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [499]:
Accuracy = test_df['diff'].value_counts(normalize=True)[0]

In [500]:
Accuracy

0.7252604166666666

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?