<a href="https://colab.research.google.com/github/JonNData/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/LS_DS_421_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
    The X features matrix you input into the model
### Hidden Layer:
    The layer(s) of nodes that the model learns on and transmits output. Can vary,best kept to the same neuron length
### Output Layer:
    Prediction for each category they can do.
### Neuron:
    Also known as a node, shows the activation which is the sigmoidal(or other function) sum of weighted inputs
### Weight:
    When initialized it can be random. Assign importance to neuron from input to output
### Activation Function:
    relu, sigmoid, tan. When not activated, the node is 0 so no output coming from that will have value. Relu most common for hidden layers, then use the appropriate one for the output
### Node Map:
    Visualize the data flow from inputs to outputs across hidden layers. Shows how many neurons in each layer ( and the activation?)
### Perceptron:
    Simplest NN architecture. 
### Loss function
    MSE
    Measure of error, trying to minimize. Early stopping will compare the change in this over epochs
### Epoch
    one pass over your inputs, used to backpropagate

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Input the X feature matrix, going through any hidden layers. Each node in a dense network is the weighted sum of all the nodes in the previous layer. The weights, initially instantiated at random, can be updated via minimizing the loss and back propagation. The bias is the inherent tendency of a node in terms of activation. Activation functions, for now sigmoid, is what determines the output of the node. Input -> hidden layers -> output layer

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0],
         'b': [1,1,1,1]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [26]:
# Initialize random weights

weights = 2 * np.random.random((4,1)) - 1
weights.shape

(4, 1)

In [0]:
# sum of dot product of inputs and weights
inputs = df
outputs = ([1],[1],[1],[0])
weighted_sum = np.dot(inputs, weights)

In [0]:
# first output
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.72921778, 0.72921778, 0.72921778, 0.59199123],
       [0.77095857, 0.77095857, 0.77095857, 0.64936089],
       [0.63918347, 0.63918347, 0.63918347, 0.44057845]])

In [0]:
# Find the error
error = data['y'] - activated_output
error

array([[ 0.27078222,  0.27078222,  0.27078222, -0.59199123],
       [ 0.22904143,  0.22904143,  0.22904143, -0.64936089],
       [ 0.36081653,  0.36081653,  0.36081653, -0.44057845]])

In [0]:
# Gradient descent, finding the steepest slope to lower error

adjustments = error * sigmoid_derivative(weighted_sum)
adjustments.shape

(3, 4)

In [0]:
# Update the weights 
weights = weights + np.dot(inputs.T, adjustments)
weights

array([[-0.87030351, -0.87030351, -0.87030351, -1.06210686],
       [ 0.44829091,  0.44829091,  0.44829091, -0.1531051 ],
       [ 0.65834111,  0.65834111,  0.65834111,  0.08605717],
       [ 0.85617676,  0.85617676,  0.85617676, -0.12569983]])

In [31]:
# Forward Propagation time

for i in range(10000):
  # dot product the inputs and weights to get weighted sum
  weighted_sum = np.dot(inputs, weights)
  
  # activation function, could add bias here if you wanted
  activated_output = sigmoid(weighted_sum)

  # actual - predicted = error
  error = outputs - activated_output

  # Back Prop time
  adjustments = error * sigmoid_derivative(weighted_sum)

  # Update wthe weights with the dot product of inputs.T and adjustments
  weights = weights + np.dot(inputs.T, adjustments)
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-3.20952071]
 [-3.20892131]
 [ 6.69542204]
 [ 1.61492481]]
Output after training
[[0.99975408]
 [0.99394487]
 [0.99394847]
 [0.00813456]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [35]:
import pandas as pd
import numpy as np

diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head(10)

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1
5            5      116             74  ...                     0.201   30        0
6            3       78             50  ...                     0.248   26        1
7           10      115              0  ...                     0.134   29        0
8            2      197             70  ...                     0.158   53        1
9            8      125             96  ...                     0.232   54        1

[10 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

features = list(diabetes)[:-1]
target = list(diabetes)[-1:]

# Instantiate normalizer
normalizer = Normalizer()

# Normalize the feature data
X = normalizer.fit_transform(diabetes[features])
# Set target vector
y = diabetes[target]

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [0]:
class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # Randomly Initialize Weights
        self.weight = 2 * np.random.random((8,1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weight) + 1
            # Activate!
            activated_output = self.__sigmoid(weighted_sum)
            # Cac error
            error = y - activated_output
            adjustments = error * self.__sigmoid_derivative(weighted_sum)
            # Update the Weights
            self.weight = self.weight + np.dot(X.T, adjustments)

        return self
    
    
    def predict(self, X):
        """Return class label after unit step"""
        weighted_sum = np.dot(X, self.weight) + 1
        activated_output = self.__sigmoid(weighted_sum)
        return np.round(activated_output)

In [34]:
model = Perceptron()
model.fit(X, y)
model.predict(X)
#I just for the life of me can't understand shapes and dimensions here...

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?