<a href="https://colab.research.google.com/github/coopwilliams/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/LS_DS_421_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
A layer of neurons that process the input to a neural network. These neurons compute an activation function on the inputs and pass on the result.
### Hidden Layer:
A layer of neurons that applies a non-linear function to their inputs.
### Output Layer:
A layer of neurons that linearly scales its input to produce the "answer" returned by the neural network.
### Neuron:
A node in a neural network, inspired by real-life neural function in the brain. Each node has weights, biases, and usually an activation function. These weights can be modified through backpropagation.
### Weight:
A scalar that is multiplied by the input to a neuron.
### Activation Function:
A function that normalizes the input to a neuron.
### Node Map:
A diagram of a neural network architecture.
### Perceptron:
A simple neural network for binary classication.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here
Scalars are inputted to a neural network through the input cells. The activation functions in the input cells compute a linear transformation on those scalars. The result is passed on to many (if not all of) the cells in the first hidden layer. Each hidden layer in its turn computes a non-linear transformation on its inputs and passes on the result. Often this transformation is as simple as multiplying each input by a weight and summing all the products. The last hidden layer passes its results to the output layer, which scales its inputs to produce the final output of the neural network.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('float')

In [0]:
##### Your Code Here #####
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)


In [0]:
df.dtypes

x1    float64
x2    float64
y     float64
dtype: object

In [0]:
X = df.loc[:,'x1':'x2'].to_numpy()
y = df.loc[:, 'y'].to_numpy().reshape(4, 1)
# input, targets
X, y

(array([[0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 1.]]), array([[1.],
        [1.],
        [1.],
        [0.]]))

In [0]:
weights = 2 * np.random.random((2,1)) - 1
weights

array([[ 0.49221345],
       [-0.41017347]])

In [0]:
bias = 0

In [0]:
for i in range(10):
    
    weighted_sum = np.dot(X, weights) + bias
    print("-------\n",weighted_sum)
    activated_output = sigmoid(weighted_sum)
    print(activated_output)
    error = y - activated_output
    print("err", error)
    adjustments = error * sigmoid_derivative(activated_output)
    print(X.T, adjustments)
    weights += np.dot(X.T, adjustments)
    bias += error

print("Weights")
print(weights)
print("output")
print(activated_output)

-------
 [[ 0.        ]
 [ 0.49221345]
 [-0.41017347]
 [ 0.08203998]]
[[0.5       ]
 [0.62062773]
 [0.39887053]
 [0.5204985 ]]
err [[ 0.5       ]
 [ 0.37937227]
 [ 0.60112947]
 [-0.5204985 ]]
[[0. 1. 0. 1.]
 [0. 0. 1. 1.]] [[ 0.11750186]
 [ 0.08626602]
 [ 0.14445997]
 [-0.12169452]]
-------
 [[ 0.5       ]
 [ 0.83615723]
 [ 0.21372145]
 [-0.45112157]]
[[0.62245933]
 [0.69765527]
 [0.55322791]
 [0.38909414]]
err [[ 0.37754067]
 [ 0.30234473]
 [ 0.44677209]
 [-0.38909414]]
[[0. 1. 0. 1.]
 [0. 0. 1. 1.]] [[ 0.08580219]
 [ 0.06708653]
 [ 0.10356457]
 [-0.09368281]]
-------
 [[ 0.87754067]
 [ 1.11190568]
 [ 0.6703753 ]
 [-0.85693023]]
[[0.70631233]
 [0.75248422]
 [0.66158719]
 [0.29798111]]
err [[ 0.29368767]
 [ 0.24751578]
 [ 0.33841281]
 [-0.29798111]]
[[0. 1. 0. 1.]
 [0. 0. 1. 1.]] [[ 0.06497565]
 [ 0.05388439]
 [ 0.07598128]
 [-0.07286578]]
-------
 [[ 1.17122834]
 [ 1.34044006]
 [ 1.0119036 ]
 [-1.17077725]]
[[0.76336697]
 [0.7925623 ]
 [0.73339252]
 [0.23671452]]
err [[ 0.23663303]
 [

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [0]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

minmax = Normalizer()

X = minmax.fit_transform(diabetes[feats])
y = diabetes['Outcome'].to_numpy()
train = pd.DataFrame(data=X, columns=feats)
train.head()

Pregnancies   Glucose  ...  DiabetesPedigreeFunction       Age
0     0.033552  0.827625  ...                  0.003506  0.279603
1     0.008424  0.716040  ...                  0.002957  0.261144
2     0.040398  0.924097  ...                  0.003393  0.161591
3     0.006612  0.588467  ...                  0.001104  0.138852
4     0.000000  0.596386  ...                  0.009960  0.143655

[5 rows x 8 columns]

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)

In [0]:
X_train.shape

(384, 8)

In [0]:
y_train.shape

(384,)

In [0]:
y_train = y_train.reshape(384, 1)

In [0]:
# class Perceptron():
#     def __init__(self, rate=0.5, n_iter=10):
#         self.rate = rate
#         self.n_iter = n_iter
#     def fit(self, X, y):
#         self.weights = np.zeros(1 + X.shape[1])
#         self.errors = []
#         for i in range(self.n_iter):
#             err = 0
#             for xi, target in zip(X, y):
#                 print("-------xt", xi, target)
#                 print("delta is", (target - self.predict(xi)))
#                 delta = self.rate * (target - self.predict(xi))
#                 self.weights[1:] += delta * xi
#                 self.weights[0] += delta
#                 err += int(delta != 0.0)
#                 if delta != 0.0:
#                     print(delta, self.weights)
#             self.errors.append(err)
#             print("errs", self.errors)
#             print("-----------")
#         return self
#     def net_input(self, X):
#         return np.dot(X, self.weights[1:]) + self.weights[0]
#     def predict(self, X):
#         return np.where(self.net_input(X) >= 0.0, 1, -1)

In [0]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
      self.niter = niter
      self.weights = 2 * np.random.random((8, 1)) - 1
      self.bias = 0
    def __sigmoid(x):
      return 1 / (1 + np.exp(-x))

    def __sigmoid_derivative(x):
      sx = sigmoid(x)
      return sx * (1-sx)

    def fit(self, X, y):
      """Fit training data
      X : Training vectors, X.shape : [#samples, #features]
      y : Target values, y.shape : [#samples]
      """

      # Randomly Initialize Weights
      
      for i in range(self.niter):
        weighted_sum = np.dot(X, self.weights) + self.bias
        # print("-------\nWeighted",weighted_sum.shape)
        activated_output = sigmoid(weighted_sum)
        # print("activated", activated_output.shape)
        error = y - activated_output
        # print("err", y.shape, error.shape)
        adjustments = error * sigmoid_derivative(activated_output)
        # print("err", error.shape)
        # print("adjustments", X.shape, adjustments.shape)
        # print(error.sum())
        self.weights += np.dot(X.T, adjustments)
        self.bias += error

    def predict(self, X):
      """Return class label after unit step"""
      # print(X.shape, self.weights.shape, self.bias.shape)
      netted = sigmoid(np.dot(X, self.weights) + self.bias)
      # print(netted)
      # return np.where(netted >= 0.5, 1, 0)
      return netted

In [0]:
percy = Perceptron(niter=20000)
percy.fit(X_train, y_train)

In [0]:
y_test = y_test.reshape(384, 1)

In [0]:
y_train.shape

(384, 1)

In [0]:
X_test.shape

(384, 8)

In [0]:
percy.weights

array([[  2.6098826 ],
       [  3.86426758],
       [-12.1227976 ],
       [  0.78962576],
       [ -0.50126405],
       [ -1.20380815],
       [ -0.05986509],
       [ -0.37123798]])

In [0]:
y_pred = percy.predict(X_test)
# sum(np.where(y_pred != y_test, 1, 0))
sum(y_pred - y_test)


array([24.23566798])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?