<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: 
The input layer of a neural network is composed of artificial input neurons, and brings the initial data into the system for further processing by subsequent layers of artificial neurons. The input layer is the very beginning of the workflow for the artificial neural network. Input layer sends the data to subsequent layers, in which the neurons do have weighted inputs.

### Hidden Layer:
Hidden layer in artificial neural networks a layer of neurons, whose output is connected to the inputs of other neurons and therefore is not visible as a network output.

Hidden layers capture more and more complexity with every layer by discovering relationships between features in the input. This is why adding more and more layers will eventually lead to either overfit, or a decrease in accuracy as the computer starts to ‘create’ relationships that don’t exist.

### Output Layer:
The output layer in an artificial neural network is the last layer of neurons that produces given outputs for the program. Though they are made much like other artificial neurons in the neural network, output layer neurons may be built or observed in a different way, given that they are the last “actor” nodes on the network.

### Neuron:
Each neuron is a mathematical operation that takes it's input, multiplies it by it's weights and then passes the sum through the activation function to the other neurons.

### Weight:
Weight is the parameter within a neural network that transforms input data within the network's hidden layers. A neural network is a series of nodes, or neurons. Within each node is a set of inputs, weight, and a bias value. As an input enters the node, it gets multiplied by a weight value and the resulting output is either observed, or passed to the next layer in the neural network. Often the weights of a neural network are contained within the hidden layers of the network.

### Activation Function:
Activation functions determine the output of a deep learning model, its accuracy, and also the computational efficiency of training a model—which can make or break a large scale neural network. Activation functions also have a major effect on the neural network’s ability to converge and the convergence speed, or in some cases, activation functions might prevent neural networks from converging in the first place.

### Node Map:
Chart of neaural network paths from input to output.

### Perceptron:
A Perceptron is an algorithm for supervised learning of binary classifiers. This algorithm enables neurons to learn and processes elements in the training set one at a time. There are two types of Perceptrons: Single layer and Multilayer. Single layer Perceptrons can learn only linearly separable patterns.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [16]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [17]:
##### Your Code Here #####

In [18]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [19]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivate(x):
    sx = sigmoid(x)
    return (sx * (1-sx))

In [20]:
import numpy as np
weights = 2 * np.random.random((2,1)) - 1
weights

array([[ 0.87331732],
       [-0.62095888]])

In [22]:
inputs = df[['x1', 'x2']].values
inputs

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [23]:
correct_outputs = df['y'].values.reshape(-1,1).tolist()
correct_outputs

[[1], [1], [1], [0]]

In [24]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[ 0.        ],
       [ 0.87331732],
       [-0.62095888],
       [ 0.25235844]])

In [25]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.70543549],
       [0.3495634 ],
       [0.56275691]])

In [26]:
error = correct_outputs - activated_output
error

array([[ 0.5       ],
       [ 0.29456451],
       [ 0.6504366 ],
       [-0.56275691]])

In [27]:
adjusted = error * sigmoid_derivate(activated_output)
adjusted

array([[ 0.11750186],
       [ 0.06518902],
       [ 0.1577411 ],
       [-0.13011293]])

In [28]:
weights += np.dot(inputs.T, adjusted)
weights

array([[ 0.80839341],
       [-0.5933307 ]])

In [46]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    adjustments = error * sigmoid_derivate(activated_output)
    
    # Update the weights
    weights += np.dpt(inputs.T, adjustments)
    
print('Weights after training')
print(weights)

print('Output after training')
print(activated_output)

AttributeError: module 'numpy' has no attribute 'dpt'

In [47]:
class Perceptron(object):
    def __init__(self, niter = 1000):
        self.niter = niter
    
    def sigmoid(self, x):
        return 1 / (1+ np.exp(-x))
    
    def sigmoid_derivative(self,x):
        sx = sigmoid(x)
        return (sx*(1-sx))
    
    def fit(self, X, y):
        """Fit training data
        X: Training vectors, X.shape : [#samples, #features]
        y: Tarfet values, y.shape : [#samples]"""
        
        inputs = X
        correct_outputs = y.reshape(-1,1)
        # Randomly initialize weights
        weights = 2 * np.random.random((X.shape[1],1)) -1
        bias = 2 * np.random.random((len(X),1)) -1
        
        for i in range(self.niter):
            
            #Update the Weights
            weighted_sum = np.dot(inputs, weights) + bias
            
            #Activate!
            activated_output = sigmoid(weighted_sum)
            
            #Cac error
            error = correct_outputs - activated_output
            adjustments = error * sigmoid_derivate(activated_output)
            
            #Update the weights
            bias += error
            weights += np.dot(inputs.T, adjustments)
        self.activated_output = activated_output
        self.weights = weights
        self.bias = bias
        
    def predict(self, X):
        """Return class label after unit step"""
        weighted_sum = np.dot(X, self.weights) + self.bias
        
        return sigmoid(weighted_sum)
        

In [48]:
nl = Perceptron()
nl.fit(df[['x1','x2']].values, df['y'].values)
nl.predict(df[['x1','x2']].values)

array([[9.98997515e-01],
       [9.98966177e-01],
       [9.98966549e-01],
       [9.39295902e-04]])

In [49]:
nl.activated_output

array([[9.98996509e-01],
       [9.98965140e-01],
       [9.98965513e-01],
       [9.40237887e-04]])

In [50]:
bias = 2 * np.random.random((4,1)) -1
bias

array([[-0.31549029],
       [-0.50677931],
       [-0.83024231],
       [-0.49960104]])

In [51]:
nl.predict(df[['x1','x2']].values)

array([[9.98997515e-01],
       [9.98966177e-01],
       [9.98966549e-01],
       [9.39295902e-04]])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [52]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [53]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[feats].values
y = diabetes['Outcome'].values

scaler = MinMaxScaler()
X_scaled =scaler.fit_transform(X)

In [55]:
class Perceptron(object):
    def __init__(self, niter = 1000):
        self.niter = niter
    
    def sigmoid(self, x):
        return 1 / (1+ np.exp(-x))
    
    def sigmoid_derivative(self,x):
        sx = sigmoid(x)
        return (sx*(1-sx))
    
    def fit(self, X, y):
        """Fit training data
        X: Training vectors, X.shape : [#samples, #features]
        y: Tarfet values, y.shape : [#samples]"""
        
        inputs = X
        correct_outputs = y.reshape(-1,1)
        # Randomly initialize weights
        weights = 2 * np.random.random((X.shape[1],1)) -1
        bias = 2 * np.random.random((len(X),1)) -1
        
        for i in range(self.niter):
            
            #Update the Weights
            weighted_sum = np.dot(inputs, weights) + bias
            
            #Activate!
            activated_output = sigmoid(weighted_sum)
            
            #Cac error
            error = correct_outputs - activated_output
            adjustments = error * sigmoid_derivate(activated_output)
            
            #Update the weights
            bias += error
            weights += np.dot(inputs.T, adjustments)
        self.activated_output = activated_output
        self.weights = weights
        self.bias = bias
        
    def predict(self, X):
        """Return class label after unit step"""
        weighted_sum = np.dot(X, self.weights) + self.bias
        
        return sigmoid(weighted_sum)

In [56]:
per = Perceptron()
per.fit(X_scaled, y)

pred = per.predict(X_scaled)
pred_in = [1 if x >= 0.5 else 0 for x in pred]

res = pd.DataFrame(diabetes['Outcome'])
res['res'] = pred_in
res.head()

Outcome  res
0        1    1
1        0    0
2        1    1
3        0    0
4        1    1

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?