<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import numpy as np
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
class Perceptron():
  """
  """

  def __init__(self,
               activation='sigmoid',
               learning_rate=1,
               max_epochs=1000):
    self.activation = activation
    self.learning_rate = learning_rate
    self.max_epochs = max_epochs

  def sigmoid(self, x):
    return 1 / (1 + np.exp(-x))

  def d_sigmoid(self, x):
    return self.sigmoid(x) * (1 - self.sigmoid(x))

  def predict(self, input):
    input = np.c_[np.ones(len(input)), input]
    return self.sigmoid(np.dot(input, self.weights))

  def predict_bias(self, input):
    return self.sigmoid(np.dot(input, self.weights))

  def train(self, input, target):
    # Add bias term.
    input = np.c_[np.ones(len(input)), input]

    # Adjust dimensionality for single-column target - we don't want to type a
    # bunch of nested brackets.
    target = np.expand_dims(target, axis=1)

    # Initialize random weights in the range (-1, 1).
    self.weights = 2 * np.random.random((len(input[0]), 1)) - 1

    for epoch in range(self.max_epochs):
      prediction = self.predict_bias(input)
      error = prediction - target
      adjustments = self.learning_rate * error * self.d_sigmoid(np.dot(input, self.weights))
      self.weights = self.weights - np.dot(input.T, adjustments)


In [0]:
p = Perceptron(max_epochs=10000)

In [0]:
p.train(df[['x1', 'x2']], df['y'])

In [5]:
p.weights

array([[12.11617882],
       [-8.01980932],
       [-8.01980932]])

In [6]:
p.predict([[0, 0], [0, 1], [1, 0], [1, 1]])

array([[0.99999453],
       [0.98363918],
       [0.98363918],
       [0.01938957]])

In [0]:
np.random.seed(812)

inputs = np.array((
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
))

# Correct outputs (in this case) match first column of inputs.
correct_outputs = [0, 1, 1, 0]

In [0]:
p.train(inputs, correct_outputs)

In [9]:
p.predict([[0, 0, 1],
           [1, 1, 1],
           [1, 0, 1],
           [0, 1, 1]])

array([[0.00847261],
       [0.99242647],
       [0.99323951],
       [0.00756378]])

In [0]:
inputs = np.array((
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
))

# Or function
correct_outputs = [0, 1, 1, 1]

In [11]:
p.train(inputs, correct_outputs)
np.rint(p.predict(inputs))

array([[0.],
       [1.],
       [1.],
       [1.]])

In [0]:
# And function
correct_outputs = [0, 0, 0, 1]

In [13]:
p.train(inputs, correct_outputs)
np.rint(p.predict(inputs))

array([[0.],
       [0.],
       [0.],
       [1.]])

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for others' implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [14]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [15]:
diabetes['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[feats]

In [17]:
X.describe()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction         Age
count   768.000000  768.000000  ...                768.000000  768.000000
mean      3.845052  120.894531  ...                  0.471876   33.240885
std       3.369578   31.972618  ...                  0.331329   11.760232
min       0.000000    0.000000  ...                  0.078000   21.000000
25%       1.000000   99.000000  ...                  0.243750   24.000000
50%       3.000000  117.000000  ...                  0.372500   29.000000
75%       6.000000  140.250000  ...                  0.626250   41.000000
max      17.000000  199.000000  ...                  2.420000   81.000000

[8 rows x 8 columns]

In [18]:
scaler = MinMaxScaler()
scaled_df = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
scaled_df.describe()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction         Age
count   768.000000  768.000000  ...                768.000000  768.000000
mean      0.226180    0.607510  ...                  0.168179    0.204015
std       0.198210    0.160666  ...                  0.141473    0.196004
min       0.000000    0.000000  ...                  0.000000    0.000000
25%       0.058824    0.497487  ...                  0.070773    0.050000
50%       0.176471    0.587940  ...                  0.125747    0.133333
75%       0.352941    0.704774  ...                  0.234095    0.333333
max       1.000000    1.000000  ...                  1.000000    1.000000

[8 rows x 8 columns]

In [19]:
normalizer = Normalizer()
normalized_df = pd.DataFrame(normalizer.fit_transform(X), columns=X.columns)
normalized_df.describe()

Pregnancies     Glucose  ...  DiabetesPedigreeFunction         Age
count   768.000000  768.000000  ...                768.000000  768.000000
mean      0.022645    0.682903  ...                  0.002710    0.195434
std       0.020956    0.161166  ...                  0.001902    0.080940
min       0.000000    0.000000  ...                  0.000250    0.032460
25%       0.006476    0.587637  ...                  0.001379    0.139930
50%       0.016716    0.704501  ...                  0.002159    0.181108
75%       0.033330    0.801606  ...                  0.003507    0.239313
max       0.117208    0.973682  ...                  0.013417    0.616539

[8 rows x 8 columns]

In [20]:
diabetes['Outcome'].head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [21]:
p = Perceptron(max_epochs=10000)
p.train(normalized_df[:5], diabetes['Outcome'][:5])
np.rint(p.predict(normalized_df)[:5])

array([[1.],
       [0.],
       [1.],
       [0.],
       [1.]])

In [22]:
p = Perceptron(learning_rate=0.4, max_epochs=10000)
p.train(normalized_df[:100], diabetes['Outcome'][:100])
np.rint(p.predict(normalized_df)[:5])

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.]])

In [0]:
p = Perceptron(learning_rate=0.07, max_epochs=10000)
p.train(normalized_df, diabetes['Outcome'])
predictions = np.rint(p.predict(normalized_df))

In [0]:
from sklearn.metrics import accuracy_score, roc_auc_score

In [25]:
accuracy_score(diabetes['Outcome'], [0]*768)

0.6510416666666666

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
lr = LogisticRegression()

In [28]:
lr.fit(normalized_df, diabetes['Outcome'])

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
lr_predictions = lr.predict(normalized_df)

In [30]:
accuracy_score(diabetes['Outcome'], lr_predictions)

0.6484375

In [31]:
accuracy_score(diabetes['Outcome'], predictions)

0.65625

In [0]:
# ##### Update this Class #####

# class Perceptron(object):
    
#     def __init__(self, niter = 10):
#       self.niter = niter
    
#     def __sigmoid(self, x):
#         return 1 / (1 + np.exp(-x))
    
#     def __sigmoid_derivative(self, x):
#         return self.sigmoid(x) * (1 - self.sigmoid(x))

#     def fit(self, X, y):
#     """Fit training data
#     X : Training vectors, X.shape : [#samples, #features]
#     y : Target values, y.shape : [#samples]
#     """

#     # Randomly Initialize Weights
#     self.weights = 2 * np.random.random((len(input[0]), 1)) - 1

#     for i in range(self.niter):
#         # Weighted sum of inputs / weights

#         # Activate!

#         # Cac error

#         # Update the Weights


#     def predict(self, X):
#     """Return class label after unit step"""
#         return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?