# Intro to Neural Networks Assignment

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

## Python

In [1]:
import numpy as np

In [2]:
x = np.array(([0,0],[1,0],[0,1],[1,1]))
y = np.array([1,1,1,0])

In [3]:
x.shape, np.zeros((x.shape[0],1)).shape

((4, 2), (4, 1))

In [4]:
b = np.zeros((x.shape[0],1))

In [5]:
x = np.concatenate( (x,b  ), axis=1)

In [6]:
x

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.]])

In [7]:
##### Your Code Here #####
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1- sigmoid(x))


def generate_perceptron_weights(x,y,weights):
    lr= 0.01
    b = np.ones((x.shape[0],1))
    x = np.concatenate( (x,b  ), axis=1)
    dot = np.matmul(x, weights)
    activated_output = sigmoid(dot)
    error = (y - activated_output.ravel((-1,1)))*lr
    adjustment = error * sigmoid_derivative(activated_output).ravel((-1,1))
    weight_change = np.dot(x.T, adjustment)
    weights = weights.ravel((-1,1)) + weight_change
    return weights 
def perceptimus_prime(x,y, num_iterations=1000):
    weights = np.random.random( ([x.shape[1]+1,1]) )
    for i in range(2000):
        weights = generate_perceptron_weights(x,y,weights)
    bias = weights[-1:]
    weights = weights[:-1]
    return weights, bias

def predictor(weights,bias, x_features):
    result = np.dot(weights,x_features)+ bias[0]
    return np.where(result <0,1,0)

    

In [8]:
new_weights, bias = perceptimus_prime(x,y,1000)

/home/cwcollins/.local/share/virtualenvs/DS-Unit-4-Sprint-3-Neural-Networks-mCFuj6dK/lib/python3.6/site-packages/ipykernel_launcher.py:17: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
/home/cwcollins/.local/share/virtualenvs/DS-Unit-4-Sprint-3-Neural-Networks-mCFuj6dK/lib/python3.6/site-packages/ipykernel_launcher.py:18: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
/home/cwcollins/.local/share/virtualenvs/DS-Unit-4-Sprint-3-Neural-Networks-mCFuj6dK/lib/python3.6/site-packages/ipykernel_launcher.py:20: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead


In [9]:
new_weights , bias

(array([-0.84014672, -0.83312648,  0.90370074]), array([1.63533297]))

In [10]:
x_test = np.array([1,1])
print(predictor(new_weights,bias,x_test))
x_test = np.array([0,0])
print(predictor(new_weights,bias,x_test))
x_test = np.array([1,0])
print(predictor(new_weights,bias,x_test))
x_test = np.array([0,1])
print(predictor(new_weights,bias,x_test))


ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

In [11]:
class Perceptron(object):
    def __init__(self):
        
        
    def generate_perceptron(self,X,y):
        self.weights = np.random.random( ([x.shape[1],1]) )
        
        
    def perceptron(x,y,weights):
        dot = np.matmul(x, weights)
        activated_output = sigmoid(dot)
        error = y - activated_output.ravel((-1,1))
        adjustment = error * sigmoid_derivative(activated_output).ravel((-1,1))
        weight_change = np.dot(x.T, adjustment)
        weights = weights.ravel((-1,1)) + weight_change
        return weights
        
        

IndentationError: expected an indented block (<ipython-input-11-a4a0ee136375>, line 5)

## Julia

In [51]:
using Random

In [163]:
x = [ 0 0 ; 0 1 ; 1 0 ; 1 1]
y = [ 1 ; 1; 1; 0]
b = ones(4,1)

4×1 Array{Float64,2}:
 1.0
 1.0
 1.0
 1.0

In [164]:
function relu(r)
    return max(0,r)
end

relu (generic function with 1 method)

In [165]:
function relu_prime(r)
    if r>0
        return 1
    else
        return 0
    end
end

relu_prime (generic function with 1 method)

In [166]:
bias = ones(4)
learning_rate = 0.01
weights = ones(2).*0.5

2-element Array{Float64,1}:
 0.5
 0.5

In [167]:
 Σ = x * weights

4-element Array{Float64,1}:
 0.0
 0.5
 0.5
 1.0

In [168]:
output = Σ += bias

4-element Array{Float64,1}:
 1.0
 1.5
 1.5
 2.0

In [169]:
activated_output=(relu).(output)

4-element Array{Float64,1}:
 1.0
 1.5
 1.5
 2.0

In [170]:
error = (y - activated_output)

4-element Array{Float64,1}:
  0.0
 -0.5
 -0.5
 -2.0

In [172]:
(relu_prime).(activated_output)

4-element Array{Int64,1}:
 1
 1
 1
 1

In [173]:
adjustment = error .* ( (sigmoid_derivative).(activated_output) )

4-element Array{Float64,1}:
  0.0                
 -0.07457322603516643
 -0.07457322603516643
 -0.20998717080701323

In [174]:
weight_change= transpose(x)*adjustment*learning_rate

2-element Array{Float64,1}:
 -0.0028456039684217967
 -0.0028456039684217967

In [175]:
weights

2-element Array{Float64,1}:
 0.5
 0.5

In [176]:
weights += weight_change 

2-element Array{Float64,1}:
 0.4971543960315782
 0.4971543960315782

In [237]:
#stationary bias
weights = ones(2).*0.5
bias = ones(4)
learning_rate=0.01
function perceptron(data, target,learning_rate, weights,bias)
    Σ = data * weights + bias
    activated_output=(relu).(Σ)
    cost = (y - activated_output)
    adjustment = cost .* ( (relu_prime).(activated_output) )
    weight_change= transpose(data)*adjustment
    weights += (weight_change *learning_rate)
    return weights
end

perceptron (generic function with 1 method)

In [238]:
weights = ones(2).*0.5
bias = ones(4)
for i= 1:1000
   weights = perceptron(x,y,learning_rate,weights,bias)
end

In [239]:
weights

2-element Array{Float64,1}:
 -0.3333333333333325
 -0.3333333333333325

In [240]:
Σ =( x * weights) + bias

4-element Array{Float64,1}:
 1.0                
 0.6666666666666675 
 0.6666666666666675 
 0.33333333333333504

In [246]:
(relu).(Σ)

4-element Array{Float64,1}:
 1.0                
 0.6666666666666675 
 0.6666666666666675 
 0.33333333333333504

In [232]:
#weighted bias
weights = ones(3).*0.5
bias = ones(4)
learning_rate=0.01
function perceptron(data, target,learning_rate, weights,bias)
    xb = hcat(data,bias) 
    Σ =  xb* weights
    activated_output=(relu).(Σ)
    cost = (y - activated_output)
    adjustment = cost .* ( (relu_prime).(activated_output) )
    weight_change= transpose(xb)*adjustment
    weights += (weight_change *learning_rate)
    return weights
end

perceptron (generic function with 1 method)

In [233]:
for i= 1:1000
   weights = perceptron(x,y,learning_rate,weights,bias)
end

In [234]:
weights

3-element Array{Float64,1}:
 -0.4984378038358628
 -0.4984378038358628
  1.2481470156082675

In [235]:
Σ =(hcat(x,bias) * weights)

4-element Array{Float64,1}:
 1.2481470156082675
 0.7497092117724047
 0.7497092117724047
 0.2512714079365419

## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [12]:
##### Your Code Here #####
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv")
df = df[~((df["Species"] == "Iris-veriscolor" ) | (df["Species"] == "Iris-setosa") )]
x = df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
y = df["Species"]
y.value_counts()

Iris-virginica     50
Iris-versicolor    50
Name: Species, dtype: int64

In [13]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [14]:
y = y.replace("Iris-versicolor",1)
y = y.replace("Iris-virginica",0)

In [15]:
##### Your Code Here #####
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1- sigmoid(x))


def generate_perceptron_weights(x,y,weights):
    lr= 0.01
    b = np.ones((x.shape[0],1))
    x = np.concatenate( (x,b  ), axis=1)
    dot = np.matmul(x, weights)
    activated_output = sigmoid(dot)
    error = (y - activated_output.ravel((-1,1)))*lr
    adjustment = error * sigmoid_derivative(activated_output).ravel((-1,1))
    weight_change = np.dot(x.T, adjustment)
    weights = weights.ravel((-1,1)) + weight_change
    return weights 
def perceptimus_prime(x,y, num_iterations=1000):
    weights = np.random.random( ([x.shape[1]+1,1]) )
    for i in range(2000):
        weights = generate_perceptron_weights(x,y,weights)
    bias = weights[-1:]
    weights = weights[:-1]
    return weights, bias

def predictor(weights,bias, x_features):
    result = np.dot(weights,x_features)+ bias[0]
    return np.where(result >0,1,0)


In [16]:
new_weights, bias = perceptimus_prime(x,y,1000)
    
print(new_weights)

x_test = np.array([6.7,3.0,5.4,2.3])
    
predictor(new_weights,bias, x_test)


/home/cwcollins/.local/share/virtualenvs/DS-Unit-4-Sprint-3-Neural-Networks-mCFuj6dK/lib/python3.6/site-packages/ipykernel_launcher.py:17: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
/home/cwcollins/.local/share/virtualenvs/DS-Unit-4-Sprint-3-Neural-Networks-mCFuj6dK/lib/python3.6/site-packages/ipykernel_launcher.py:18: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
/home/cwcollins/.local/share/virtualenvs/DS-Unit-4-Sprint-3-Neural-Networks-mCFuj6dK/lib/python3.6/site-packages/ipykernel_launcher.py:20: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead


[ 3.58697798  3.64470448 -5.37085733 -6.23967977]


array(0)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?