<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:

The input layer is the layer of the neutral network in which your data interacts with. 
The features you want to feed into the network are each put into an input node in the input layer.

### Hidden Layer:

A hidden layer is one of the layers between the input and output layers in which the values that pass through 
them come from other nodes and not directly from user input or data

### Output Layer:

The output layer is where the final value output and visable.

### Neuron:

A neuron takes input values from other nodes, multiplies them by thier weight, sums the results, and passes it through an activation function.

### Weight:

Weight is a value that is used to determine the importance of a particular feature. 
More importance values have a higher weight and corelation is determined by the sign.

### Activation Function:

The activation function is a function used to normalize the output of a neuron, it also determines how much of the signal to send to the next layer.

### Node Map:

A node map shows all of the individual nodes, their type, and which other nodes they are connected to. 

### Perceptron:

A perceptron is the most simple neutral network in that it is just one neuron with a given number of input nodes that gives one output after applying weights/activation function.

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

Each feature being used in the neutral network is input through the input nodes. The value for each node is multiplied by its weight and summed.
Then bias is then added to the sum of the row, passed through an activation function and returned as output.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [85]:
# sigmoid function and derivative function from lecture
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [101]:
# setting initial weights
weights = 2 * np.random.random((2,1)) - 1
print(weights)

# setting bias
bias = 1

# setting lerning rate
lr = .1

# set iterations
niter = 10000

[[-0.10015907]
 [-0.74362578]]


In [102]:
for _ in range(niter):
    
    # creates weighted sum for each row
    df['w_sum'] = (df['x1'] * weights[0] + df['x2'] * weights[1]) + bias

    # creates activated value for each row
    df['a_value'] = df['w_sum'].apply(sigmoid)

    # gives error for eacg riw
    df['error'] = df['y'] - df['a_value']

    # gets adjustment value
    df['adjustment'] = lr * (df['error']*df['a_value'].apply(sigmoid_derivative))

    # adjusting weights
    weights[0] += np.dot(df['adjustment'], df['x1'])
    weights[1] += np.dot(df['adjustment'], df['x2'])

df.head()

x1  x2  y     w_sum   a_value     error  adjustment
0   0   0  1  1.000000  0.731059  0.268941    0.005900
1   1   0  1  0.309920  0.576866  0.423134    0.009745
2   0   1  1  0.309920  0.576866  0.423134    0.009745
3   1   1  0 -0.380159  0.406088 -0.406088   -0.009745

In [40]:
# # used for testing a different activation function

# def activate(x):
#     '''
#     activation function for classification
#     '''
#     if x < 0:
#         return 1
#     elif x >= 0:
#         return 0

# def train_network(df, *, bias=-1, lr=.01, iters=100):
    
#     weights = 2 * np.random.random((2,1)) - 1
    
#     for i in range(iters):
    
#         df['w_sum'] = (df['x1'] * weights[0] + df['x2'] * weights[1]) + bias

#         df['pred_value'] = df['w_sum'].apply(activate)

#         df['error'] = df['y'] - df['pred_value']

#         df['adjustment'] = lr*(df['error'] * df['pred_value'])
        
#         weights[0] += np.dot(df['adjustment'], df['x1'])
#         weights[1] += np.dot(df['adjustment'], df['x2'])
        
#     return(df, weights)

In [83]:
# trained_df, weights = train_network(df.drop(columns=['a_value']), bias=-1, iters=1000)

# print(f'weights =  \n {weights}')

# trained_df.head()

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [9]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [20]:
from sklearn.preprocessing import MinMaxScaler, Normalizer
scaler = MinMaxScaler()

feats = list(diabetes)[:-1]

for col in feats:
    diabetes[col] = diabetes[col].apply(float)

X = diabetes[feats]    
    
df1 = pd.DataFrame(scaler.fit_transform(X=X, y=diabetes['Outcome']), columns=feats)

In [144]:
df_original = pd.concat([df1, diabetes['Outcome']], axis=1).copy()
df_original.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   

   DiabetesPedigreeFunction       Age  Outcome  
0                  0.234415  0.483333        1  
1                  0.116567  0.166667        0  
2                  0.253629  0.183333        1  
3                  0.038002  0.000000        0  
4                  0.943638  0.200000        1

In [151]:
# nobody has a skin thickness, age, or BMI of 0
# removes 0 from these and similar columns to see if it improves the model
to_clean = ['BloodPressure', 'SkinThickness', 'Bmi', 'DiabetesPedigreeFunction', 'Age', 'Insulin', 'Glucose']

df_clean = df_original.copy()

df_clean = df_clean.replace({to_clean[0]: {0: np.nan}, 
                        to_clean[1]: {0: np.nan}, 
                        to_clean[2]: {0: np.nan}, 
                        to_clean[3]: {0: np.nan}, 
                        to_clean[4]: {0: np.nan},
                        to_clean[5]: {0: np.nan},
                        to_clean[6]: {0: np.nan}})

df_clean.dropna(inplace=True)
df_clean.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
4      0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   
6      0.176471  0.391960       0.409836       0.323232  0.104019  0.461997   
8      0.117647  0.989950       0.573770       0.454545  0.641844  0.454545   
13     0.058824  0.949749       0.491803       0.232323  1.000000  0.448584   
14     0.294118  0.834171       0.590164       0.191919  0.206856  0.384501   

    DiabetesPedigreeFunction       Age  Outcome  
4                   0.943638  0.200000        1  
6                   0.072588  0.083333        1  
8                   0.034159  0.533333        1  
13                  0.136635  0.633333        1  
14                  0.217336  0.500000        1

In [199]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, df, label, niter=10000, lr=0.1):
        self.df = df
        self.labels = df[label]
        self.features = self.df[self.df.columns[:8]]
        self.niter = niter
        self.weights = np.random.random((8, 1))
        self.lr = lr
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)
    
    def update_df(self):
        
        for _ in range(self.niter):
        
            self.df['weight_sum'] = np.dot(self.features, self.weights)

            self.df['actv_val'] = self.df['weight_sum'].apply(self.sigmoid)

            self.df['error'] = self.df['Outcome'] - self.df['actv_val']

            self.df['adjustments'] = self.lr * (self.df['actv_val'].apply(self.sigmoid_derivative) * self.df['error'])

            updates = np.dot(self.df['adjustments'], self.features)

            self.weights = (self.weights.T + updates).T

In [200]:
ptron = Perceptron(df=df_original.copy(), label='Outcome')

In [201]:
ptron.update_df()
ptron.df.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0     0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1     0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2     0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3     0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4     0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   

   DiabetesPedigreeFunction       Age  Outcome  weight_sum  actv_val  \
0                  0.234415  0.483333        1   -2.464078  0.078415   
1                  0.116567  0.166667        0   -5.491533  0.004105   
2                  0.253629  0.183333        1   -1.872873  0.133210   
3                  0.038002  0.000000        0   -6.336631  0.001767   
4                  0.943638  0.200000        1    0.563699  0.637308   

      error  adjustments  
0  0.921585     0.023004  
1 -0.004105    -0.000103  
2  0.866790     0.021574  
3 -0.001767    -0.000044  
4  0.362692     0.008206

In [202]:
ptron.weights

array([[  3.97515828],
       [  7.64965706],
       [-10.15090502],
       [  1.89073271],
       [  3.46115538],
       [ -0.44164248],
       [  3.8680975 ],
       [  6.81803313]])

In [212]:
ptron.df['error'].mean()

0.26917565959360695

In [204]:
ptron_clean = Perceptron(df=df_clean.copy(), label='Outcome')

In [205]:
ptron_clean.update_df()
ptron_clean.df.head()

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
4      0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   
6      0.176471  0.391960       0.409836       0.323232  0.104019  0.461997   
8      0.117647  0.989950       0.573770       0.454545  0.641844  0.454545   
13     0.058824  0.949749       0.491803       0.232323  1.000000  0.448584   
14     0.294118  0.834171       0.590164       0.191919  0.206856  0.384501   

    DiabetesPedigreeFunction       Age  Outcome  weight_sum  actv_val  \
4                   0.943638  0.200000        1    1.636708  0.837087   
6                   0.072588  0.083333        1   -1.119290  0.246143   
8                   0.034159  0.533333        1    2.259651  0.905480   
13                  0.136635  0.633333        1    3.159977  0.959300   
14                  0.217336  0.500000        1    0.758540  0.681037   

       error  adjustments  
4   0.162913     0.003435  
6   0.753857     0.018564  
8   0.094520     0.001938  
13  0.040700     0.000815  
14  0.318963     0.007117

In [206]:
ptron_clean.weights

array([[ 0.22179129],
       [ 3.73776161],
       [-6.00957431],
       [ 2.31322707],
       [ 1.53715763],
       [-1.667505  ],
       [ 1.36086325],
       [ 3.48730901]])

In [211]:
ptron_clean.df['error'].mean()

0.05929358903689473

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?