<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [2]:
df['bias'] = [1, 1, 1, 1]
print(df.shape)
df.head()

(4, 4)


x1  x2  y  bias
0   0   0  1     1
1   1   0  1     1
2   0   1  1     1
3   1   1  0     1

In [3]:
# okay I think the intent is to do this piece meal and then below I will
# create a reusable class

#sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

#derivative function
def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

#we are going to randomly initialize some weights.  This is starting as random
# because I have no prior input.  The more we iterate over this perceptron, 
# these we will adjust these weights
weights = 2 * np.random.random((3, 1)) - 1

# weights = pd.DataFrame(weights)

In [4]:
#okay this shape should be fine for workint withour dataframe.
weights

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [5]:
verbose = False

inputs = df[['x1', 'x2', 'bias']].values
correct_outputs = df['y'].values.reshape((4, 1))
if verbose: print(inputs, correct_outputs)


for iteration in range(100000):
    
    # multiplying our inputs (the x columns) by our weights
    weighted_sum = np.dot(inputs, weights)
    if verbose: print(weighted_sum)
    
    # I'm using a sigmoid function because my end output should be a 0 or a 1
    # (true or false)
    activated_output = sigmoid(weighted_sum)
    if verbose: print(activated_output)
    
    # Next we need to calculate error.  Basically the difference between our
    # prediction and our truth
    error = correct_outputs - activated_output
    if verbose: print(error)
    
    # good, now we know how much of a mistake we made in predicting, but it is
    # in terms of outputs.  I need to understand what to input to our next
    # epoch. The derivative will give me the instantaneous rate of change. 
    # so multiply our error by the rate of change, and I now have my error
    # "scaled" in a way that is meaningful as an input.
    adjustments = error * sigmoid_derivative(weighted_sum)
    if verbose: print(adjustments)
    
    # Now lets adjust our weights by what we learned this epoch.  Effectively 
    # we learned how far off our prediction is from our truth (error) so we
    # need to adjust our weights to minimize that error
    weights += np.dot(inputs.T, adjustments)
    if verbose: print(weights)
    
print('Weights after training:')
print(weights)

print('Output after training')
print(activated_output)

Weights after training:
[[-10.3952784]
 [-10.3952784]
 [ 15.6777464]]
Output after training
[[0.99999984]
 [0.99494577]
 [0.99494577]
 [0.00598316]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [27]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [28]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

# Min Max Scaler is better for scaling on a column, Normalizer is better for 
# normalizing a row. For my purposes minmax will do

scaler = MinMaxScaler()
normal = Normalizer()

feats = list(diabetes)[:-1]

y = diabetes['Outcome']

scaler.fit(diabetes.drop(columns = ['Outcome']))
X = scaler.transform(diabetes.drop(columns = ['Outcome']))

normal.fit(X)
X = normal.transform(X)

X = pd.DataFrame(X, columns = [feats])

print(X.shape, y.shape)
X.head()

(768, 8) (768,)


Pregnancies   Glucose BloodPressure SkinThickness   Insulin       BMI  \
0    0.271471  0.572045      0.453936      0.271928  0.000000  0.385158   
1    0.067347  0.489028      0.619373      0.335375  0.000000  0.453866   
2    0.376673  0.736073      0.419897      0.000000  0.000000  0.277943   
3    0.068414  0.520154      0.629186      0.270201  0.129227  0.487056   
4    0.000000  0.476330      0.226851      0.244610  0.137398  0.444422   

  DiabetesPedigreeFunction       Age  
0                 0.180305  0.371765  
1                 0.133458  0.190817  
2                 0.203012  0.146745  
3                 0.044198  0.000000  
4                 0.652899  0.138379

In [29]:
from random import uniform

class Perceptron(object):
    
    def __init__(self, niter = 10, verbose = False):
        '''
        Warning, verbose is very verbose.  Only use with small iterations, small
        dataframes or debugging
        '''
        self.niter = niter
        self.verbose = verbose
    
    def __sigmoid(self, x):
        return 1.0 / (1.0 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = self.__sigmoid(x)
        return sx * (1.0 - sx)

    def fit(self, X, y):
        """Fit training data
        Assumes X and Y are dataframes and series respectively, there is 
        no bias added to the inputs X, and that X has been
        scaled or normalized to some degree
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
        # making a copy, adding a bias column, storing the width after bias and
        # transforming to a numpy array
        inputs = X.copy()
        bias = [0.0] * X.shape[0]
        inputs['bias'] = bias
        #print(inputs.head())
        width = inputs.shape[1]
        inputs = inputs.values
        
        # transforming to a numpy array
        y_width = y.shape[0]
        correct_outputs = y.values.reshape((y_width, 1))

        # Randomly Initialize Weights
        weights = 2.0 * np.random.random((width, 1)) - 1.0

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(inputs, weights)
            if self.verbose: print(weighted_sum)
                
            # Activate!
            activated_output = self.__sigmoid(weighted_sum)
            if self.verbose: print(activated_output)
            
            # Cac error
            error = correct_outputs - activated_output
            if self.verbose: print(error)
            
            # Update the Weights
            adjustments = error * self.__sigmoid_derivative(weighted_sum)
            if self.verbose: print(adjustments)
                
            weights += np.dot(inputs.T, adjustments)
            if self.verbose: print(weights)
                
        self.weights = weights
        #print(activated_output)
        return self
    
    def net_input(self, X):
        # My bias is the last entry of my weights
        return np.dot(X, self.weights[:-1]) + self.weights[-1]
    
    def predict(self, X):
        return np.where(self.net_input(X) >= 0.5, 1, 0)

#     def predict(self, X):
#         """Return class label after unit step"""
#         # candidate for a helper function
#         try:
#             inputs = X.copy()
#             inputs['bias'] = self.bias
#             width = inputs.shape[1]
#             inputs = inputs.values

#             weighted_sum = np.dot(inputs, self.weights)
#             if self.verbose: print(weighted_sum)

#             activated_output = self.__sigmoid(weighted_sum)
#             if verbose: print(activated_output)
                
#             return activated_output
#         except:
#             print("Perceptron hasn't been fit yet")
#             return None

In [30]:
from sklearn.metrics import accuracy_score

ptrons = []

for i, col in enumerate(feats):

    ptron = Perceptron(niter = 100000)

    ptrons.append(ptron.fit(X[[col]], y))

    y_pred = pd.DataFrame(ptrons[i].predict(X[[col]]), columns = ['Predictions'])

    print('Accuracy is: ', accuracy_score(y, y_pred))
    y_pred['Predictions'].value_counts()

Accuracy is:  0.6510416666666666
Accuracy is:  0.6497395833333334
Accuracy is:  0.6510416666666666
Accuracy is:  0.58203125
Accuracy is:  0.6510416666666666
Accuracy is:  0.6510416666666666
Accuracy is:  0.6510416666666666
Accuracy is:  0.3489583333333333


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?