<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
- An input layer is the initial layer of neurons within a neural network that takes in un-weighted data

### Hidden Layer:
- A hidden layer is the layer(s) within a neural network, between the input and output layers where the neurons take in a set up weighted inputs, and produce a set of outputs through an activation function

### Output Layer:
- It is the last layer in a nueral network; it brings together the results of the prior layers into an ouput

### Neuron:
- A neuron is a singular unit of a layer within a nueral network, that takes in a set of weighted inputs along with a transformation function and an activation function; the neuron translates the weighted inputs, into a singular output

### Weight:
- Weights in a sense can be thought of as quite literal with respect to numerical values.  A great example can be foud in the this [link](https://www.quora.com/What-does-weight-mean-in-terms-of-neural-networks?share=1).  In essense, a weight contributes to the output of the nueron it is being taken in by.

### Activation Function:
- An activation function provides the neuron the 'knowledge' necessary to activate (fire) or not after the input data has been processed.

### Node Map:
- Node maps are visualizations of neural networks, in the form of paths that incorporate input, hidden, and ouput layers

### Perceptron:
- Perceptrons are composed of single layer neural networks; the combiination of multilayered perceptrons are called neural networks

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Flow of information in a nueral network can be broken down into a multilayered series of parts (pun intended)

- Notes:
    - Some set of data are fed into a layer of neurons; these set of data come from a given value between 0 - 1, called the activator; the way to obtain the output from the nueron in the second layer of the network, is to take the sum of the weight/activator product in a way that produces a vlue between 0 - 1 (this 'way' includes the use of weights, bias, and activator function), then run the process all over again, and condtinue to feed the the neurons in the layers following, until we result in the final, output layer of neurons, which produce a probabilistic result.
    - we do not want the neuron to be activated whenever the weighted sum (the sum of the products of the weights and activator vlues) is greater than zero, given the activator function, instead, we provide the activator function with a 'bias' value; this value is in corporated into the activator function, and provides the neuron with a threshold, of sorts, for activation (for example, if the bias is a given positive value, the neuron will not become activated unless the sum of the weighted/activator product is more positive than that given positive vlue)
    - Each neuron in the hidden layer has it's own weighted value, along with it's own bias for each input

    - Flow of Information in a neural network:
        - The flow of information in a neural network begins with the information.  That information (data) is taken in through was is called the input layer
            - Input Layer is the first layer in a series of three classes of layers.  The input layer is composed of activated neurons (by the data inputs); this layer, like all others is composed of neuron cells.
                - Neurons are individual data processing units.  Data is taken in by the neuron of the input layer, depending on other factors, after processing the data can then activate the neuron, and the resulting value is then transfered to the second layer, or following layer.  These processing 'factors' are weights, bias, and activation function, they lie at the root of the processing in a neural network.
                    - Activation function is the main component of the data processing.  The activation function takes the weights, which come alongside the data when transfered between layers; these weights then influence the behavior of the activation function.  Another compnent that influnces the bahavior of the activation function is the bias.  A bias value is a value that is incorporated into the function, to provide a sort of threshold for the activation function, if that threshold is not met, the activation function will not provide the neuron an activation signal, and thus resulting in an inactivation of said neuron.
                - This proces results in an activation value, between 0 - 1, which is then fed into the next layer of the neural network, the hidden layer.
            - The hidden layer is composed of a collection of neurons, and each neuron takes in the resulting activation value from each of the individual neurons from the previous, input, layer along with a weight and bias, and perfomes the same process.  This process is repeated, with each subsequent collection of leyers of neurons, until the data finds itself in the last layer of the neural network, the output layer
        - The output layer of neurons is the final layer the information (data) finds iteslf in.  This layer should have reasonable amount of information to provide one with a confident probability of what ever was being analyzed.  The example we saw was turning written numerical text recognizable digital information.
            
    - Neural networks are composed of three classes of layers
        - Hidden Layer: The hidden layers in a neural network are the layered collections of neurons that 
        - Output layer
        
        - Each class is composed of a collection of nuerons
            - Neurons take in inputs, and produce outputs through a series of steps
            
            - The steps
                 - Input (information) > input layer (individual neurons > activation function) > activation value * Weights + bias > hidden layer (neurons and activation function) > activation value > output layer > output

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [5]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [11]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [12]:
outputs = [[1], [1], [1], [0]]
outputs

[[1], [1], [1], [0]]

In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [8]:
weights = 2 * np.random.random((3, 1)) -1
weights

array([[ 0.68776061],
       [-0.27825845],
       [ 0.30155104]])

In [13]:
weighted_sum = np.dot(df , weights)
weighted_sum

array([[0.30155104],
       [0.98931165],
       [0.02329258],
       [0.40950216]])

In [14]:
activated_outputs = sigmoid(weighted_sum)
activated_outputs

array([[0.57482164],
       [0.72895194],
       [0.50582288],
       [0.6009685 ]])

In [16]:
error = outputs - activated_outputs
error

array([[ 0.42517836],
       [ 0.27104806],
       [ 0.49417712],
       [-0.6009685 ]])

In [17]:
adjusted = error * sigmoid_derivative(activated_outputs)
adjusted

array([[ 0.09797597],
       [ 0.05950142],
       [ 0.11596703],
       [-0.13745331]])

In [19]:
weights += np.dot(df.T, adjusted)

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [20]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [21]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
feats
# X = []

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age']

In [ ]:

class Perceptron(object):
    
    def __init__(self, niter = 10):
    self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights
        weighted_sum = np.dot(df , weights)

        # Activate!
        activated_outputs = sigmoid(weighted_sum)

        # Cac error
        error = outputs - activated_outputs

        # Update the Weights
        weights += np.dot(df.T, adjusted)


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?