<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
# Import statements
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import random

# Functions
def binary_classifier(result):
    if result >= 0.5:
        return 1
    else:
        return 0
    
# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [2]:
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

correct_outputs = [[1], [1], [1], [0]]
# correct_outputs = [[value] for value in data['y']]

df = pd.DataFrame.from_dict(data).astype('int')

df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [3]:
X = df[['x1', 'x2']]
X['bias'] = [1,1,1,1] # Simulated bias
y = df['y']

X.head()

x1  x2  bias
0   0   0     1
1   1   0     1
2   0   1     1
3   1   1     1

In [4]:
inputs = X[['x1', 'x2', 'bias']].values

inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]], dtype=int64)

### Initialize random weights

In [5]:
weights = 2 * np.random.random((3,1)) - 1

weights

array([[-0.80019471],
       [ 0.3089445 ],
       [ 0.22499004]])

### Calculate weighted sum of inputs and weights

In [6]:
weighted_sum = np.dot(inputs, weights)

weighted_sum

array([[ 0.22499004],
       [-0.57520467],
       [ 0.53393454],
       [-0.26626017]])

### Training first epoch

In [7]:
activated_output = sigmoid(weighted_sum) # Prediction first epoch

activated_output

array([[0.55601143],
       [0.36003674],
       [0.63040031],
       [0.43382545]])

### Calculate error

In [8]:
error = correct_outputs - activated_output # Absolute error

error

array([[ 0.44398857],
       [ 0.63996326],
       [ 0.36959969],
       [-0.43382545]])

### Gradient descent (weights correction)

In [9]:
adjustments = error * sigmoid_derivative(weighted_sum)

adjustments

array([[ 0.10960423],
       [ 0.14745412],
       [ 0.08611516],
       [-0.10655661]])

In [10]:
# weights = 0 # Clear

weights += np.dot(inputs.T, adjustments)

weights

array([[-0.7592972 ],
       [ 0.28850305],
       [ 0.46160693]])

### Update weights 'n' times (PART 0.5.1)

In [5]:
################
# Import block #
################

from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import random

##################
# Function block #
##################

def binary_classifier(result):
    if result >= 0.5:
        return 1
    else:
        return 0
    
# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

##########################
# Data declaration block #
##########################

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

correct_outputs = [[1], [1], [1], [0]]
# correct_outputs = [[value] for value in data['y']]

df = pd.DataFrame.from_dict(data).astype('int')

X = df[['x1', 'x2']]
X['bias'] = [1,1,1,1] # Simulated bias
y = df['y']

X.head()

inputs = X[['x1', 'x2', 'bias']].values

#####################
# Layman Perceptron #
#####################

weights = 2 * np.random.random((3,1)) - 1

for iteration in range(100):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate absolute error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
################    
# Result block #
################

binary_activated_output = pd.DataFrame(activated_output)[0].apply(binary_classifier)

print('Accuracy Score:', accuracy_score(df['y'], binary_activated_output))

print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Accuracy Score: 1.0
Weights after training
[[-2.63964767]
 [-2.64005004]
 [ 4.08491426]]
Output after training
[[0.98316073]
 [0.80838249]
 [0.8083174 ]
 [0.23354327]]


### Accuracy Score

In [497]:
binary_activated_output = pd.DataFrame(activated_output)[0].apply(binary_classifier)

binary_activated_output

0    1
1    1
2    1
3    0
Name: 0, dtype: int64

In [498]:
print('Accuracy Score:', accuracy_score(df['y'], binary_activated_output))

Accuracy Score: 1.0


---

### NAND Gate Prediction (Function)

In [14]:
#
# VAR PURGE
# run cell before subsequent attempts
#

%reset -f

In [1]:
# Import statements
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import random

# Functions
def binary_classifier(result):
    if result >= 0.5:
        return 1
    else:
        return 0
    
# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [2]:
# Danke for the snippet Brian!
np.random.seed(42)

obs = 1000
choices = [1, 0]

def nand(val1, val2):
     return 0 if (val1 == 1) & (val2 == 1) else 1
    
x1 = [random.choice(choices) for i in range(0,obs)]
x2 = [random.choice(choices) for i in range(0,obs)]
y = [nand(x1[i], x2[i]) for i in range(obs)]

# for i in range(0, obs): 
#     y_true = nand(x1[i], x2[i])
#     y.append(y_true)

df = pd.DataFrame({'x1': x1, 'x2': x2, 'y':y})

df['bias'] = 1 
# df['bias'] = np.ones((obs,), dtype=int)

df

x1  x2  y  bias
0     1   0  1     1
1     0   0  1     1
2     1   1  0     1
3     1   1  0     1
4     1   0  1     1
..   ..  .. ..   ...
995   1   1  0     1
996   1   1  0     1
997   0   1  1     1
998   0   1  1     1
999   1   1  0     1

[1000 rows x 4 columns]

---

### Isolating for troubleshooting

In [112]:
#
# DECLARATION
# single iteration testing
# CELL 02

"""
weighted_sum = np.dot(inputs, weights)
activated_output = sigmoid(weighted_sum)
error = correct_outputs - activated_output
adjustments = error * sigmoid_derivative(weighted_sum)
weights += np.dot(inputs.T, adjustments)

weights
"""

'\nweighted_sum = np.dot(inputs, weights)\nactivated_output = sigmoid(weighted_sum)\nerror = correct_outputs - activated_output\nadjustments = error * sigmoid_derivative(weighted_sum)\nweights += np.dot(inputs.T, adjustments)\n\nweights\n'

In [212]:
#> WORKING 
# DECLARATION
# main declaration
# CELL 01

# weights = 0 # Clear 
# weights = 2 * np.random.random((3,1)) - 1 # Included in-function
 
inputs = df[['x1', 'x2', 'bias']].values

correct_outputs = [[value] for value in df['y']]

# weights

In [213]:
#
# FRESH DECLARATION
# iterative function
# CELL 03

weights = 0 # Clear
weights = 10 * np.random.random((3,1)) - 1

for iteration in range(2000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate absolute error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 4.05884779]
 [ 3.15775038]
 [11.78473941]]
Output after training
[[0.99999987]
 [0.99999238]
 [0.99999999]
 [0.99999999]
 [0.99999987]
 [0.99999968]
 [0.99999987]
 [0.99999238]
 [0.99999968]
 [0.99999968]
 [0.99999968]
 [0.99999987]
 [0.99999968]
 [0.99999999]
 [0.99999968]
 [0.99999238]
 [0.99999238]
 [0.99999999]
 [0.99999238]
 [0.99999968]
 [0.99999238]
 [0.99999987]
 [0.99999968]
 [0.99999987]
 [0.99999968]
 [0.99999987]
 [0.99999968]
 [0.99999987]
 [0.99999238]
 [0.99999968]
 [0.99999999]
 [0.99999238]
 [0.99999987]
 [0.99999987]
 [0.99999238]
 [0.99999999]
 [0.99999999]
 [0.99999999]
 [0.99999968]
 [0.99999987]
 [0.99999968]
 [0.99999238]
 [0.99999987]
 [0.99999999]
 [0.99999238]
 [0.99999987]
 [0.99999999]
 [0.99999999]
 [0.99999987]
 [0.99999999]
 [0.99999999]
 [0.99999238]
 [0.99999968]
 [0.99999968]
 [0.99999238]
 [0.99999968]
 [0.99999238]
 [0.99999968]
 [0.99999999]
 [0.99999999]
 [0.99999999]
 [0.99999968]
 [0.99999987]
 [0.99999238]
 [0.99999968]

---

### Final NAND Gate Laymen Perceptron (PART 0.5.2)

In [13]:
################
# Import block #
################

from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import random

##################
# Function block #
##################

def binary_classifier(result):
    if result >= 0.5:
        return 1
    else:
        return 0
    
# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

##########################
# Data declaration block #
##########################

# Danke for the snippet Brian!
np.random.seed(42)

obs = 1000
choices = [1, 0]

def nand(val1, val2):
     return 0 if (val1 == 1) & (val2 == 1) else 1
    
x1 = [random.choice(choices) for i in range(0,obs)]
x2 = [random.choice(choices) for i in range(0,obs)]
y = [nand(x1[i], x2[i]) for i in range(obs)]

df = pd.DataFrame({'x1': x1, 'x2': x2, 'y':y})

df['bias'] = 1 
 
inputs = df[['x1', 'x2', 'bias']].values
correct_outputs = [[value] for value in df['y']]

#####################
# Layman Perceptron #
#####################

weights = 0 # Clear
weights = 2 * np.random.random((3,1)) - 1

for iteration in range(1000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate absolute error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
binary_activated_output = pd.DataFrame(activated_output)[0].apply(binary_classifier)

################    
# Result block #
################

print('Accuracy Score:', accuracy_score(df['y'], binary_activated_output))    
    
print("Weights after training")
print(weights)

print("Output after training")
# print(activated_output)

Accuracy Score: 1.0
Weights after training
[[-15.35586133]
 [-21.72688398]
 [ 28.61475222]]
Output after training


In [121]:
inputs = df[['x1', 'x2', 'bias']].values

inputs

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       ...,
       [0, 0, 1],
       [1, 1, 1],
       [0, 1, 1]], dtype=int64)

In [122]:
correct_outputs = [[value] for value in df['y']]

# correct_outputs_nand

In [123]:
weights = 2 * np.random.random((3,1)) - 1

weights

array([[ 0.19731697],
       [-0.68796272],
       [-0.68801096]])

In [85]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate absolute error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_outputd)

Weights after training
[[1.97238130e-01]
 [1.17069391e+05]
 [1.17069391e+05]]
Output after training
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]


---

### Testing result accuracy

In [53]:
binary_activated_output = pd.DataFrame(activated_output)[0].apply(binary_classifier)

print('Accuracy Score:', accuracy_score(df['y'], binary_activated_output))

Accuracy Score: 1.0


In [329]:
df_comparison = pd.DataFrame({'control': df['y'], 'result': binary_activated_output})

print(df_comparison['result'].value_counts()) # Binary result sanity test
print(df['y'].value_counts()) # Binary expected result sanity test

df_comparison_nand

1    728
0    272
Name: result, dtype: int64
1    728
0    272
Name: y, dtype: int64


control  result
0          1       1
1          1       1
2          1       1
3          1       1
4          1       1
..       ...     ...
995        1       1
996        0       0
997        1       1
998        1       1
999        1       1

[1000 rows x 2 columns]

### NAND Gate Prediction (Perceptron Class)

In [202]:
class Perceptron(object):
    
    def __init__(self, rate = 0.01, niter = 1000):
        self.rate = rate
        self.niter = niter

    # Sigmoid activation function and its derivative
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return self.sigmoid(x) * (1 - self.sigmoid(x))

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        weight = 2 * np.random.random((X.shape[1], 1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, weight)

            # Activate!
            activated_output = self.sigmoid(weighted_sum)

            # Calculate absolute error
            error = y - activated_output

            adjustments = error * sigmoid_derivative(weighted_sum)

            # Update the Weights
            weight += np.dot(X.T, adjustments)

#     def net_input(self, X):
#         return np.dot(self.weight, X)

    def predict(self, X):
        return self.sigmoid(self.net_input(X.T))

In [114]:
# class Perceptron(object):
    
#     def __init__(self, rate = 0.01, niter = 10):
#         self.rate = rate
#         self.niter = niter
    
    
#     # Sigmoid activation function and its derivative
#     def sigmoid(self, x):
#         return 1 / (1 + np.exp(-x))

#     def sigmoid_derivative(self, x):
#         return self.sigmoid(x) * (1 - self.sigmoid(x))

#     def fit(self, X, y):

#         self.weight = 2 * np.random.random((1, X.shape[1])) - 1
#         self.errors = [] 

#         for i in range(self.niter):
#             err = 0
#             for xi, target in zip(X, y):
#                 pred = self.predict(xi)
#                 delta_w = self.rate * (target - pred) * self.sigmoid_derivative(xi)
#                 self.weight += delta_w * xi
#                 err += int(np.linalg.norm(delta_w) != 0.0)
#             self.errors.append(err)
#         return self

#     def net_input(self, X):
#         return np.dot(self.weight, X)

#     def predict(self, X):
#         return self.sigmoid(self.net_input(X.T))

In [205]:
pn = Perceptron()

In [206]:
Perceptron(inputs, correct_outputs)

In [211]:
print(Perceptron.predict(self, inputs))

NameError: name 'self' is not defined

In [193]:
pn.fit(inputs, correct_outputs)

In [194]:
pn_activated_output = pn.predict(inputs)

AttributeError: 'Perceptron' object has no attribute 'weight'

In [183]:
predictions = np.round(pn_activated_output)

In [184]:
predictions.astype(int)

array([[1],
       [1],
       [0]])

In [120]:
print('Accuracy Score:', accuracy_score(correct_outputs, predictions[0]))

Accuracy Score: 1.0


---

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [65]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [66]:
diabetes['Bias'] = 1

diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  Bias  
0                       0.627   50        1     1  
1                       0.351   31        0     1  
2                       0.672   32        1     1  
3                       0.167   21        0     1  
4                       2.288   33        1     1  
..                        ...  ...      ...   ...  
763                     0.171   63        0     1  
764                     0.340   27        0     1  
765                     0.245   30        0     1  
766                     0.349   47        1     1  
767                     0.315   23        0     1  

[768 rows x 10 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [67]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

# feats = list(diabetes)[:-1]
feats = list(diabetes.drop(columns='Outcome'))

feats

['Pregnancies',
 'Glucose',
 'BloodPressure',
 'SkinThickness',
 'Insulin',
 'BMI',
 'DiabetesPedigreeFunction',
 'Age',
 'Bias']

In [68]:
X_normal = Normalizer().fit_transform(diabetes[feats])
X_scaler = MinMaxScaler().fit_transform(diabetes[feats])

In [88]:
M = X_normal

M

array([[0.03355185, 0.82761219, 0.40262215, ..., 0.00350617, 0.27959871,
        0.00559197],
       [0.00842371, 0.71601493, 0.55596454, ..., 0.00295672, 0.26113486,
        0.00842371],
       [0.04039717, 0.9240852 , 0.32317734, ..., 0.00339336, 0.16158867,
        0.00504965],
       ...,
       [0.026915  , 0.65134299, 0.38757599, ..., 0.00131883, 0.16149   ,
        0.005383  ],
       [0.00665291, 0.83826692, 0.39917472, ..., 0.00232187, 0.31268687,
        0.00665291],
       [0.00791429, 0.73602906, 0.55400037, ..., 0.002493  , 0.18202869,
        0.00791429]])

In [89]:
N = X_scaler

N

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.23441503, 0.48333333,
        0.        ],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.11656704, 0.16666667,
        0.        ],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.25362938, 0.18333333,
        0.        ],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.07130658, 0.15      ,
        0.        ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.11571307, 0.43333333,
        0.        ],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.10119556, 0.03333333,
        0.        ]])

In [72]:
y = diabetes['Outcome'].values

y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [81]:

"""
class Perceptron(object):
    
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        self.weights = ...

        for i in range(self.niter):
            return None
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None
"""

SyntaxError: invalid syntax (<ipython-input-81-dd206a7911d8>, line 15)

In [104]:
per = Perceptron()
per.fit(M, y)

In [105]:
predictions = per.predict(M)
predictions = np.round(predictions)
predictions = predictions.tolist()[0]

In [106]:
diabetus_y_labels = y.tolist()

In [107]:
accuracy_score(diabetus_y_labels, predictions) * 100

64.97395833333334

In [110]:
(diabetes["Outcome"].value_counts(dropna=False, normalize=True))[0]

0.6510416666666666

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?