<a href="https://colab.research.google.com/github/Jaydenzk/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module1-Intro-to-Neural-Networks/LS_DS_421_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: A layer that receives input from dataset to be passed to network
### Hidden Layer: The layer in between input and output. Hyperparameter, functions
### Output Layer:Output vector of values
### Neuron:  A function that receives an input and pass it to the next layer of nodes if a certain threshold is reached
### Weight: Modifies input to report output
### Activation Function: Transform output value into format that fits the context
### Node Map: Flow chart that shows the path from inputs to outputs
### Perceptron: First and simplest kind of neural network, a single node of neural network


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

inputs = df.values
corr_out = [[1],[1],[1],[0]]

In [0]:
##### Your Code Here #####

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [32]:
# weights for our three inputs
weights = 2 * np.random.random((3,1)) - 1
weights

array([[ 0.68917078],
       [ 0.69172963],
       [-0.81524649]])

In [33]:
# Create biases for node map
b = np.zeros(inputs.shape[0])
b

array([0., 0., 0., 0.])

In [34]:
# Calculate weighted sum of inputs and weights
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.81524649],
       [-0.12607571],
       [-0.12351685],
       [ 1.38090041]])

In [35]:
# Output the activated value for the end of 1 training epoch
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.30677363],
       [0.46852276],
       [0.46915999],
       [0.79913557]])

In [37]:
# take difference of output and true values to calculate error
error = corr_out - activated_output
error

array([[ 0.69322637],
       [ 0.53147724],
       [ 0.53084001],
       [-0.79913557]])

In [38]:
# Gradient descent/backprop - magic!
adjustments = error * sigmoid_derivative(activated_output)
adjustments

array([[ 0.16929223],
       [ 0.12583636],
       [ 0.12566705],
       [-0.17099897]])

In [39]:
# adjust weights base on inputs
weights += np.dot(inputs.T, adjustments)
weights

array([[ 0.64400817],
       [ 0.64639771],
       [-0.39445085]])

In [41]:
# steps we've already done:
# 1. randomly initialized weights already. Those are in memory as `weights`
# 2. we've already got input data & correct_outputs

# update our weights 100 times
for iteration in range(100):
    
    # weighted sum of inputs/weights
    weighted_sum = np.dot(inputs, weights) + b.reshape(-1,1)
    
    # activate!
    activated_output = sigmoid(weighted_sum)
    
    # calc error
    error = corr_out - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # update the weights
    weights += np.dot(inputs.T, adjustments)
    
    # update bias
    b += np.sum(adjustments, axis=1)
    
print('Weights after training:\n', weights)
print('Output after training\n', activated_output)

Weights after training:
 [[-0.60906376]
 [-0.60775482]
 [ 3.37079792]]
Output after training
 [[0.98958884]
 [0.98266554]
 [0.98266946]
 [0.02308274]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [47]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
scaley = MinMaxScaler()

X = scaley.fit_transform(diabetes[feats])

dia = pd.DataFrame(X)

In [0]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
    self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights

        # Activate!

        # Cac error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?