<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [108]:
# Import statements
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np
import random

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

correct_outputs = [[1], [1], [1], [0]]
# correct_outputs = [[value] for value in data['y']]

df = pd.DataFrame.from_dict(data).astype('int')

df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [26]:
X = df[['x1', 'x2']]
X['bias'] = [1,1,1,1] # Simulated bias
y = df['y']

X.head()

x1  x2  bias
0   0   0     1
1   1   0     1
2   0   1     1
3   1   1     1

In [27]:
inputs = X[['x1', 'x2', 'bias']].values

inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]], dtype=int64)

In [279]:
# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

### Initialize random weights

In [6]:
weights = 2 * np.random.random((3,1)) - 1

weights

array([[-0.71715162],
       [-0.90430724],
       [ 0.97195082]])

### Calculate weighted sum of inputs and weights

In [7]:
weighted_sum = np.dot(inputs, weights)

weighted_sum

array([[ 0.97195082],
       [ 0.25479919],
       [ 0.06764357],
       [-0.64950805]])

### Training first epoch

In [9]:
activated_output = sigmoid(weighted_sum) # Prediction first epoch

activated_output

array([[0.72550817],
       [0.56335739],
       [0.51690445],
       [0.34310041]])

### Calculate error

In [10]:
error = correct_outputs - activated_output # Absolute error

error

array([[ 0.27449183],
       [ 0.43664261],
       [ 0.48309555],
       [-0.34310041]])

### Gradient descent (weights correction)

In [30]:
adjustments = error * sigmoid_derivative(weighted_sum)

In [56]:
weights = 0 # Clear

weights += np.dot(inputs.T, adjustments)

weights

array([[0.03007907],
       [0.04330701],
       [0.20537887]])

### Update weights 'n' times

In [57]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calculate absolute error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(weighted_sum)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[-8.01895955]
 [-8.01895955]
 [12.11490517]]
Output after training
[[0.99999452]
 [0.98363151]
 [0.98363151]
 [0.01939868]]


### NAND Gate

In [428]:
# Danke Brian!
np.random.seed(42)

obs = 1000
choices = [1, 0]

def nand(val1, val2):
     return 1 if (val1 == 1) & (val2 == 1) else 0
    
x1 = [random.choice(choices) for i in range(0,obs)]
x2 = [random.choice(choices) for i in range(0,obs)]
y = []

for i in range(0, obs): 
    y_true = nand(x1[i], x2[i])
    y.append(y_true)

df_nand = pd.DataFrame({'x1': x1, 'x2': x2, 'y':y})

df_nand['bias'] = np.ones((obs,), dtype=int)

df_nand

x1  x2  y  bias
0     1   1  1     1
1     0   0  0     1
2     0   1  0     1
3     1   0  0     1
4     1   1  1     1
..   ..  .. ..   ...
995   0   1  0     1
996   1   0  0     1
997   0   0  0     1
998   1   1  1     1
999   1   1  1     1

[1000 rows x 4 columns]

In [429]:
df_nand['y'].value_counts()

0    769
1    231
Name: y, dtype: int64

In [430]:
# inputs_nand = df_nand[['x1', 'x2', 'bias']].values
inputs_nand = df_nand[['x1', 'x2', 'y']].values

inputs_nand

array([[1, 1, 1],
       [0, 0, 0],
       [0, 1, 0],
       ...,
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [431]:
correct_outputs_nand = [[value] for value in df_nand['y']]

In [432]:
weights_nand = 2 * np.random.random((3,1)) - 1

weights_nand

array([[-0.25091976],
       [ 0.90142861],
       [ 0.46398788]])

In [433]:
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum_nand = np.dot(inputs_nand, weights_nand)
    
    # Activate!
    activated_output_nand = sigmoid(weighted_sum_nand)
    
    # Calculate absolute error
    error_nand = correct_outputs_nand - activated_output_nand
    
    adjustments_nand = error_nand * sigmoid_derivative(weighted_sum_nand)
    
    # Update the Weights
    weights_nand += np.dot(inputs_nand.T, adjustments_nand)
    
print("Weights after training")
# print(weights_nand)

print("Output after training")
# print(activated_output_nand)

Weights after training
[[-18.17565914]
 [-24.71006158]
 [ 11.07848359]]
Output after training
[[1.53565067e-14]
 [5.00000000e-01]
 [1.85590870e-11]
 [1.27764890e-08]
 [1.53565067e-14]
 [1.53565067e-14]
 [1.27764890e-08]
 [5.00000000e-01]
 [1.85590870e-11]
 [1.53565067e-14]
 [1.85590870e-11]
 [1.27764890e-08]
 [1.27764890e-08]
 [5.00000000e-01]
 [5.00000000e-01]
 [1.53565067e-14]
 [1.53565067e-14]
 [1.53565067e-14]
 [1.53565067e-14]
 [5.00000000e-01]
 [1.85590870e-11]
 [1.27764890e-08]
 [5.00000000e-01]
 [1.53565067e-14]
 [1.53565067e-14]
 [1.27764890e-08]
 [5.00000000e-01]
 [1.85590870e-11]
 [1.27764890e-08]
 [1.85590870e-11]
 [1.85590870e-11]
 [1.85590870e-11]
 [1.53565067e-14]
 [1.53565067e-14]
 [5.00000000e-01]
 [1.27764890e-08]
 [1.27764890e-08]
 [1.85590870e-11]
 [1.27764890e-08]
 [1.27764890e-08]
 [1.53565067e-14]
 [1.27764890e-08]
 [5.00000000e-01]
 [5.00000000e-01]
 [5.00000000e-01]
 [1.53565067e-14]
 [1.85590870e-11]
 [5.00000000e-01]
 [1.85590870e-11]
 [1.85590870e-11]
 [1.27

### Testing result accuracy

In [434]:
def binary_classifier(result):
    if result >= 0.5:
        return 1
    else:
        return 0
    
binary_activated_output_nand = pd.DataFrame(activated_output_nand)[0].apply(binary_classifier)

binary_activated_output_nand

0      0
1      1
2      0
3      0
4      0
      ..
995    0
996    0
997    1
998    0
999    0
Name: 0, Length: 1000, dtype: int64

In [435]:
print('Accuracy Score:', accuracy_score(df_nand['y'], binary_activated_output_nand))

Accuracy Score: 0.513


In [436]:
df_comparison_nand = pd.DataFrame({'control': df_nand['y'], 'result': binary_activated_output_nand})

In [437]:
print(df_comparison_nand['result'].value_counts())
df_comparison_nand

0    744
1    256
Name: result, dtype: int64


control  result
0          1       0
1          0       1
2          0       0
3          0       0
4          1       0
..       ...     ...
995        0       0
996        0       0
997        0       1
998        1       0
999        1       0

[1000 rows x 2 columns]

### Using Perceptron class on NAND gate

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [4]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [10]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [ ]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = ...

        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?