<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
- The input layer is where the data that will be used to predict the output goes. Generally the first layer in most neural networks.
### Hidden Layer:
- These layers will take outputs and preform more functions on them. Invisible might be a bit of a misnomer, but these are generally not looked at
### Output Layer:
- This is where the predictions are reported. Once you have an output you can imporve your model based on how good your model preformed
### Neuron:
- The nodes that take an input and give an output to the next layer
### Weight:
- A parameter that modifys the input values to give us an output
### Activation Function:
- A function that decides whether or not the cell fires. A probability curve
### Node Map:
- a pictoral diagram of how the nodes connect to eachother and what each node does.
### Perceptron:
- The most basic of neural networks where two input nodes generate 1 output node


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [3]:
import numpy as np

inputs = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,0]
])
inputs

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [ ]:
correct_outputs = [[1],[1],[1],[0]]

In [ ]:
import numpy as np

# sigmoid activation function and its derivative for updating weights
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [66]:
# initalizing random weights for 3 inputs
weights = 2 * np.random.random((3,1)) - 1
weights

array([[-0.11868466],
       [ 0.84133232],
       [-0.96903124]])

In [67]:
# calculating weighted sum of inputs and weights
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[-0.96903124],
       [-1.0877159 ],
       [-0.12769893],
       [ 0.72264766]])

In [68]:
# output the activated value for the end of 1 training epoch
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.27507364],
       [0.25204863],
       [0.46811858],
       [0.67318978]])

In [69]:
# take difference of output and true values to calculate error
error = correct_outputs - activated_output
error

array([[ 0.72492636],
       [ 0.74795137],
       [ 0.53188142],
       [-0.67318978]])

In [70]:
# Gradient descent/backpop - magic!
adjusted = error * sigmoid_derivative(activated_output)
adjusted

array([[ 0.17784612],
       [ 0.18404924],
       [ 0.12594376],
       [-0.15058288]])

In [71]:
weights += np.dot(inputs.T, adjusted)
weights

array([[-0.0852183 ],
       [ 0.8166932 ],
       [-0.48119212]])

In [72]:
# update weights 10,000 times
for iteration in range(10000):
    
    # weighted sum
    weighted_sum = np.dot(inputs, weights)
    
    # activate
    activated_output = sigmoid(weighted_sum)
    
    # cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # update weights:
    weights += np.dot(inputs.T, adjustments)
    
print('Weights after training')
print(weights)

print('Output after training')
print(activated_output)

Weights after training
[[-3.80978358]
 [-3.80368347]
 [11.6963286 ]]
Output after training
[[9.99991675e-01]
 [9.99624338e-01]
 [9.99626622e-01]
 [4.93562409e-04]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [4]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [9]:
from sklearn.preprocessing import MinMaxScaler, Normalizer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

feats = list(diabetes)[:-1]

train, test = train_test_split(diabetes)

In [8]:
baseline = [0] * len(diabetes['Outcome'])

In [10]:
accuracy_score(diabetes['Outcome'], baseline)

0.6510416666666666

In [205]:
X_train = train.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7]].values
y_train = train.iloc[:, [8]].values

In [203]:
def normalization(X):
    normalize = Normalizer()
    return normalize.fit_transform(X)

X = normalization(X)

In [196]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = self.sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = 2 * np.random.random((X.shape[1],1)) - 1

        for i in range(self.niter):
            # Weighted sum of inputs / weights
            weighted_sum = np.dot(X, self.weights)

            # Activate!
            activated_outputs = sigmoid(weighted_sum)

            # Cac error
            error = y - activated_outputs

            adjustments = error * sigmoid_derivative(activated_outputs)

            # Update the Weights
            self.weights += np.dot(X.T, adjustments)

        return activated_outputs
        
    def predict(self, X, y):
        """Return class label after unit step"""
        return self.fit(X, y)

In [197]:
pertron = Perceptron(niter=100000)

In [198]:
answers = pertron.fit(X, y)

In [199]:
answers_rounded = np.around(answers)

In [200]:
accuracy_score(y, answers_rounded)

1.0

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?