# Intro to Neural Networks Assignment

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [2]:
import numpy as np

In [330]:
x = np.array(([0,0],[1,0],[0,1],[1,1]))
y = np.array([1,1,1,0])

In [326]:
x.shape, np.zeros((x.shape[0],1)).shape

((4, 2), (4, 1))

In [327]:
b = np.zeros((x.shape[0],1))

In [328]:
x = np.concatenate( (x,b  ), axis=1)

In [329]:
x

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.]])

In [379]:
##### Your Code Here #####
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1- sigmoid(x))


def generate_perceptron_weights(x,y,weights):
    lr= 0.01
    b = np.ones((x.shape[0],1))
    x = np.concatenate( (x,b  ), axis=1)
    dot = np.matmul(x, weights)
    activated_output = sigmoid(dot)
    error = (y - activated_output.ravel((-1,1)))*lr
    adjustment = error * sigmoid_derivative(activated_output).ravel((-1,1))
    weight_change = np.dot(x.T, adjustment)
    weights = weights.ravel((-1,1)) + weight_change
    return weights 
def perceptimus_prime(x,y, num_iterations=1000):
    weights = np.random.random( ([x.shape[1]+1,1]) )
    for i in range(2000):
        weights = generate_perceptron_weights(x,y,weights)
    bias = weights[-1:]
    weights = weights[:-1]
    return weights, bias

def predictor(weights,bias, x_features):
    result = np.dot(weights,x_features)+ bias[0]
    return np.where(result <0,1,0)

    

In [380]:
new_weights, bias = perceptimus_prime(x,y,1000)


C:\Users\cwcol\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
C:\Users\cwcol\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
C:\Users\cwcol\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead


In [381]:
new_weights , bias

(array([-0.86938042, -0.86784615]), array([1.67264538]))

In [382]:
x_test = np.array([1,1])
print(predictor(new_weights,bias,x_test))
x_test = np.array([0,0])
print(predictor(new_weights,bias,x_test))
x_test = np.array([1,0])
print(predictor(new_weights,bias,x_test))
x_test = np.array([0,1])
print(predictor(new_weights,bias,x_test))


1
0
0
0


In [301]:
class Perceptron(object):
    def __init__(self):
        
        
    def generate_perceptron(self,X,y):
        self.weights = np.random.random( ([x.shape[1],1]) )
        
        
    def perceptron(x,y,weights):
        dot = np.matmul(x, weights)
        activated_output = sigmoid(dot)
        error = y - activated_output.ravel((-1,1))
        adjustment = error * sigmoid_derivative(activated_output).ravel((-1,1))
        weight_change = np.dot(x.T, adjustment)
        weights = weights.ravel((-1,1)) + weight_change
        return weights
        
        

IndentationError: expected an indented block (<ipython-input-301-a4a0ee136375>, line 5)

## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [385]:
##### Your Code Here #####
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv")
df = df[~((df["Species"] == "Iris-veriscolor" ) | (df["Species"] == "Iris-setosa") )]
x = df[["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]
y = df["Species"]
y.value_counts()

Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [395]:
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [387]:
y = y.replace("Iris-versicolor",1)
y = y.replace("Iris-virginica",0)

In [393]:
##### Your Code Here #####
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1- sigmoid(x))


def generate_perceptron_weights(x,y,weights):
    lr= 0.01
    b = np.ones((x.shape[0],1))
    x = np.concatenate( (x,b  ), axis=1)
    dot = np.matmul(x, weights)
    activated_output = sigmoid(dot)
    error = (y - activated_output.ravel((-1,1)))*lr
    adjustment = error * sigmoid_derivative(activated_output).ravel((-1,1))
    weight_change = np.dot(x.T, adjustment)
    weights = weights.ravel((-1,1)) + weight_change
    return weights 
def perceptimus_prime(x,y, num_iterations=1000):
    weights = np.random.random( ([x.shape[1]+1,1]) )
    for i in range(2000):
        weights = generate_perceptron_weights(x,y,weights)
    bias = weights[-1:]
    weights = weights[:-1]
    return weights, bias

def predictor(weights,bias, x_features):
    result = np.dot(weights,x_features)+ bias[0]
    return np.where(result >0,1,0)


In [396]:
new_weights, bias = perceptimus_prime(x,y,1000)
    
print(new_weights)

x_test = np.array([6.7,3.0,5.4,2.3])
    
predictor(new_weights,bias, x_test)


C:\Users\cwcol\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
C:\Users\cwcol\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead
C:\Users\cwcol\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: DeprecationWarning: Non-string object detected for the array ordering. Please pass in 'C', 'F', 'A', or 'K' instead


[ 3.54340243  3.61226508 -5.36165617 -6.20926201]


array(0)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?