<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
A Neuron is the basic unit of a neural network. It takes N inputs, weighs them and optionally applies a bias. It then applies an activation function to the sum of all inputs, weights, and bias. Depending on the actiation function, the neuron might activate, not activate, or send a weak signal to the next layer. 
- **Input Layer:**
The input layer is the first layer of the neural network, it will have number of nodes equal to the number of features in the data and apply no activation function, but pass the inputs to the first hidden layer.
- **Hidden Layer:**
The hidden layers do not produce inputs or outputs, they are made up of neurons and behave due to the above description of neurons: they apply weights to the inputs they receive, may add bias, and then apply an activation function, possibly activating and sending a signal to the next layer.

- **Output Layer:**
The output layer will determine the shape of the output from the neural network, for a regression function, it will be a single neuron applying a linear function to the input.

For a binary classification function, it will use a binary activation function, for a multi-classificaiton function, it will use a softmax function.

The number of neurons in the output layer will correspond to the number of output features.

- **Activation:**

Neurons activate according to their activation functions. Sigmoid, Relu, and step are some possible functions, based on the inputs and weights (and bias) applied to the inputs, the function will (or will not) produce an output.

Choosing the activation function depends on the nature of the problem. Relu functions produce a linearly increasing output once the input signal is above zero, and nothing when the input signal is below zero. 

Step functions produce a signal of 1 if the input signal is above zero, and zero below it.

Sigmoid (or tanh which is a transformed sigmoid function) provide a signal of 1 at high inputs and zero at low inputs, with an inbetween output signal between 6 and -6.

- **Backpropagation:**

The process by which neural networks learn. During training, the outputs of the neural network are compared to the true y values to generate an error term, this error term is multiplied by the derivative of the activation function of the output of each layer of the neural network (except the input layer that has no activation function) to create a delta term. The weights of the inputs to each layer are then multiplied by delta term.

Intuitively, we are updating the weights of inputs to our layers by the derivative of our activation functions so as to reduce the error or loss function of our model.


## 2. Perceptron on AND Gates <a id="Q3=2"></a>

Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2|x3|	y|
|---|---|---|---|
1|	1|	1|	1|
1|	0|	1|	0|
0|	1|	1|	0|
0|	0|	1|	0|

In [3]:
import numpy as np

# first we format our inputs and outputs

inputs = np.array(([1,1,1],
                   [1,0,1],
                   [0,1,1],
                   [0,0,1]), dtype=float)

correct_outputs = np.array(([1], [0], [0], [0]), dtype=float)

In [15]:
# this is a single perceptron neural network
class Perceptron():
    
    
    def __init__(self, input_size = 3, outputNodes = 1):
  # Set up Architecture of neural network
        self.input = input_size 
        self.outputNodes = outputNodes
        # Initial Weights
        # 3x4 matrix for first layer
        self.weights1 = np.random.randn(self.input, self.outputNodes)
        
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, z):
#         return z / (1 + z)
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forawrd

        """
        #weighted sum of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        #Activations of weighted sums
        self.activated_output = self.sigmoid(self.hidden_sum)
        


        return self.activated_output
    
    def get_attributes(self):
        
        attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']

        [print(i + '\n', getattr(nn,i), '\n' + '---'*3) for i in dir(nn) if i in attributes]

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) 
        # apply derivative of sigmoid to error

        self.weights1 += X.T.dot(self.o_delta) #Adjust first set (input => hidden) weights
        print('Current Weights: ', self.weights1)
        print('Gradient Adjustment: ', X.T.dot(self.o_delta))
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
        

In [16]:
p = Perceptron()

X = inputs
y = correct_outputs

for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(p.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - p.feed_forward(X)))))
    p.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
Actual Output: 
 [[1.]
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.48507262]
 [0.67742136]
 [0.28967167]
 [0.47619166]]
Loss: 
 0.2586795167911171
Current Weights:  [[ 0.73186935]
 [-0.69854469]
 [-0.41936133]]
Gradient Adjustment:  [[-0.1053826 ]
 [ 0.10312907]
 [-0.32405589]]
+---------EPOCH 2---------+
Input: 
 [[1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
Actual Output: 
 [[1.]
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.40467175]
 [0.57749732]
 [0.2463999 ]
 [0.39666959]]
Loss: 
 0.22649463769133127
Current Weights:  [[ 0.69196459]
 [-0.57574726]
 [-0.62063526]]
Gradient Adjustment:  [[-0.03990476]
 [ 0.12279744]
 [-0.20127392]]
+---------EPOCH 3---------+
Input: 
 [[1. 1. 1.]
 [1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
Actual Output: 
 [[1.]
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.376503  ]
 [0.51782478]
 [0.23211937]
 [0.34963699]]
Loss: 
 0.20825410719617674
Current Weights:  [[ 0.68584199]
 [-0.

 [-7.88810659]]
Gradient Adjustment:  [[ 0.00407919]
 [ 0.00407919]
 [-0.00554492]]
Current Weights:  [[ 5.72672659]
 [ 5.72672655]
 [-7.89363759]]
Gradient Adjustment:  [[ 0.00406901]
 [ 0.00406901]
 [-0.005531  ]]
Current Weights:  [[ 5.73078548]
 [ 5.73078544]
 [-7.89915473]]
Gradient Adjustment:  [[ 0.00405888]
 [ 0.00405889]
 [-0.00551715]]
Current Weights:  [[ 5.73483429]
 [ 5.73483425]
 [-7.90465809]]
Gradient Adjustment:  [[ 0.00404881]
 [ 0.00404881]
 [-0.00550336]]
Current Weights:  [[ 5.73887307]
 [ 5.73887303]
 [-7.91014773]]
Gradient Adjustment:  [[ 0.00403878]
 [ 0.00403878]
 [-0.00548964]]
Current Weights:  [[ 5.74290186]
 [ 5.74290182]
 [-7.91562371]]
Gradient Adjustment:  [[ 0.0040288 ]
 [ 0.0040288 ]
 [-0.00547598]]
Current Weights:  [[ 5.74692073]
 [ 5.74692069]
 [-7.9210861 ]]
Gradient Adjustment:  [[ 0.00401887]
 [ 0.00401887]
 [-0.00546239]]
Current Weights:  [[ 5.75092971]
 [ 5.75092967]
 [-7.92653497]]
Gradient Adjustment:  [[ 0.00400898]
 [ 0.00400898]
 [-0.005

 [-9.57314014]]
Gradient Adjustment:  [[ 0.00187632]
 [ 0.00187632]
 [-0.00253793]]
Current Weights:  [[ 6.96726334]
 [ 6.96726334]
 [-9.57567504]]
Gradient Adjustment:  [[ 0.00187409]
 [ 0.00187409]
 [-0.0025349 ]]
Current Weights:  [[ 6.9691352 ]
 [ 6.9691352 ]
 [-9.57820691]]
Gradient Adjustment:  [[ 0.00187186]
 [ 0.00187186]
 [-0.00253188]]
Current Weights:  [[ 6.97100485]
 [ 6.97100485]
 [-9.58073577]]
Gradient Adjustment:  [[ 0.00186964]
 [ 0.00186964]
 [-0.00252886]]
Current Weights:  [[ 6.97287228]
 [ 6.97287228]
 [-9.58326162]]
Gradient Adjustment:  [[ 0.00186743]
 [ 0.00186743]
 [-0.00252585]]
Current Weights:  [[ 6.9747375 ]
 [ 6.9747375 ]
 [-9.58578446]]
Gradient Adjustment:  [[ 0.00186522]
 [ 0.00186522]
 [-0.00252284]]
Current Weights:  [[ 6.97660052]
 [ 6.97660052]
 [-9.5883043 ]]
Gradient Adjustment:  [[ 0.00186302]
 [ 0.00186302]
 [-0.00251984]]
Current Weights:  [[ 6.97846134]
 [ 6.97846134]
 [-9.59082115]]
Gradient Adjustment:  [[ 0.00186082]
 [ 0.00186082]
 [-0.002

Gradient Adjustment:  [[ 0.00121173]
 [ 0.00121173]
 [-0.00163504]]
Current Weights:  [[  7.65168687]
 [  7.65168687]
 [-10.50028743]]
Gradient Adjustment:  [[ 0.00121079]
 [ 0.00121079]
 [-0.00163377]]
Current Weights:  [[  7.65289672]
 [  7.65289672]
 [-10.50191992]]
Gradient Adjustment:  [[ 0.00120985]
 [ 0.00120985]
 [-0.00163249]]
Current Weights:  [[  7.65410563]
 [  7.65410563]
 [-10.50355113]]
Gradient Adjustment:  [[ 0.00120891]
 [ 0.00120891]
 [-0.00163122]]
Current Weights:  [[  7.65531361]
 [  7.65531361]
 [-10.50518108]]
Gradient Adjustment:  [[ 0.00120797]
 [ 0.00120797]
 [-0.00162995]]
Current Weights:  [[  7.65652064]
 [  7.65652064]
 [-10.50680976]]
Gradient Adjustment:  [[ 0.00120704]
 [ 0.00120704]
 [-0.00162868]]
Current Weights:  [[  7.65772675]
 [  7.65772675]
 [-10.50843717]]
Gradient Adjustment:  [[ 0.0012061 ]
 [ 0.0012061 ]
 [-0.00162741]]
Current Weights:  [[  7.65893192]
 [  7.65893192]
 [-10.51006332]]
Gradient Adjustment:  [[ 0.00120517]
 [ 0.00120517]
 [-

Current Weights:  [[  8.11235519]
 [  8.11235519]
 [-11.12142497]]
Gradient Adjustment:  [[ 0.0009    ]
 [ 0.0009    ]
 [-0.00121263]]
Current Weights:  [[  8.11325466]
 [  8.11325466]
 [-11.1226369 ]]
Gradient Adjustment:  [[ 0.00089947]
 [ 0.00089947]
 [-0.00121193]]
Current Weights:  [[  8.11415361]
 [  8.11415361]
 [-11.12384812]]
Gradient Adjustment:  [[ 0.00089895]
 [ 0.00089895]
 [-0.00121122]]
Current Weights:  [[  8.11505204]
 [  8.11505204]
 [-11.12505864]]
Gradient Adjustment:  [[ 0.00089843]
 [ 0.00089843]
 [-0.00121051]]
Current Weights:  [[  8.11594995]
 [  8.11594995]
 [-11.12626845]]
Gradient Adjustment:  [[ 0.00089791]
 [ 0.00089791]
 [-0.00120981]]
Current Weights:  [[  8.11684734]
 [  8.11684734]
 [-11.12747755]]
Gradient Adjustment:  [[ 0.00089739]
 [ 0.00089739]
 [-0.00120911]]
Current Weights:  [[  8.11774421]
 [  8.11774421]
 [-11.12868595]]
Gradient Adjustment:  [[ 0.00089687]
 [ 0.00089687]
 [-0.0012084 ]]
Current Weights:  [[  8.11864056]
 [  8.11864056]
 [-11

 [-0.00095672]]
Current Weights:  [[  8.47767552]
 [  8.47767552]
 [-11.61338633]]
Gradient Adjustment:  [[ 0.00071048]
 [ 0.00071048]
 [-0.00095628]]
Current Weights:  [[  8.47838567]
 [  8.47838567]
 [-11.61434217]]
Gradient Adjustment:  [[ 0.00071015]
 [ 0.00071015]
 [-0.00095584]]
Current Weights:  [[  8.4790955 ]
 [  8.4790955 ]
 [-11.61529756]]
Gradient Adjustment:  [[ 0.00070983]
 [ 0.00070983]
 [-0.00095539]]
Current Weights:  [[  8.479805  ]
 [  8.479805  ]
 [-11.61625251]]
Gradient Adjustment:  [[ 0.0007095 ]
 [ 0.0007095 ]
 [-0.00095495]]
Current Weights:  [[  8.48051417]
 [  8.48051417]
 [-11.61720703]]
Gradient Adjustment:  [[ 0.00070917]
 [ 0.00070917]
 [-0.00095451]]
Current Weights:  [[  8.48122302]
 [  8.48122302]
 [-11.6181611 ]]
Gradient Adjustment:  [[ 0.00070885]
 [ 0.00070885]
 [-0.00095407]]
Current Weights:  [[  8.48193154]
 [  8.48193154]
 [-11.61911473]]
Gradient Adjustment:  [[ 0.00070852]
 [ 0.00070852]
 [-0.00095363]]
Current Weights:  [[  8.48263974]
 [  8

Current Weights:  [[  8.75216927]
 [  8.75216927]
 [-11.98270713]]
Gradient Adjustment:  [[ 0.00059447]
 [ 0.00059447]
 [-0.00079955]]
Current Weights:  [[  8.75276351]
 [  8.75276351]
 [-11.98350637]]
Gradient Adjustment:  [[ 0.00059424]
 [ 0.00059424]
 [-0.00079924]]
Current Weights:  [[  8.75335753]
 [  8.75335753]
 [-11.9843053 ]]
Gradient Adjustment:  [[ 0.00059401]
 [ 0.00059401]
 [-0.00079893]]
Current Weights:  [[  8.75395131]
 [  8.75395131]
 [-11.98510392]]
Gradient Adjustment:  [[ 0.00059378]
 [ 0.00059378]
 [-0.00079862]]
Current Weights:  [[  8.75454486]
 [  8.75454486]
 [-11.98590223]]
Gradient Adjustment:  [[ 0.00059355]
 [ 0.00059355]
 [-0.00079831]]
Current Weights:  [[  8.75513818]
 [  8.75513818]
 [-11.98670023]]
Gradient Adjustment:  [[ 0.00059332]
 [ 0.00059332]
 [-0.000798  ]]
Current Weights:  [[  8.75573128]
 [  8.75573128]
 [-11.98749792]]
Gradient Adjustment:  [[ 0.00059309]
 [ 0.00059309]
 [-0.00079769]]
Current Weights:  [[  8.75632414]
 [  8.75632414]
 [-11

Current Weights:  [[  8.9977333 ]
 [  8.9977333 ]
 [-12.31288225]]
Gradient Adjustment:  [[ 0.00050664]
 [ 0.00050664]
 [-0.000681  ]]
Current Weights:  [[  8.99823977]
 [  8.99823977]
 [-12.31356302]]
Gradient Adjustment:  [[ 0.00050647]
 [ 0.00050647]
 [-0.00068077]]
Current Weights:  [[  8.99874608]
 [  8.99874608]
 [-12.31424357]]
Gradient Adjustment:  [[ 0.0005063 ]
 [ 0.0005063 ]
 [-0.00068055]]
Current Weights:  [[  8.99925221]
 [  8.99925221]
 [-12.31492389]]
Gradient Adjustment:  [[ 0.00050614]
 [ 0.00050614]
 [-0.00068032]]
Current Weights:  [[  8.99975818]
 [  8.99975818]
 [-12.31560399]]
Gradient Adjustment:  [[ 0.00050597]
 [ 0.00050597]
 [-0.0006801 ]]
Current Weights:  [[  9.00026399]
 [  9.00026399]
 [-12.31628386]]
Gradient Adjustment:  [[ 0.0005058 ]
 [ 0.0005058 ]
 [-0.00067987]]
Current Weights:  [[  9.00076962]
 [  9.00076962]
 [-12.3169635 ]]
Gradient Adjustment:  [[ 0.00050564]
 [ 0.00050564]
 [-0.00067965]]
Current Weights:  [[  9.00127509]
 [  9.00127509]
 [-12

 [-0.00059169]]
Current Weights:  [[  9.21289748]
 [  9.21289748]
 [-12.6020213 ]]
Gradient Adjustment:  [[ 0.00044029]
 [ 0.00044029]
 [-0.00059152]]
Current Weights:  [[  9.21333765]
 [  9.21333765]
 [-12.60261265]]
Gradient Adjustment:  [[ 0.00044017]
 [ 0.00044017]
 [-0.00059135]]
Current Weights:  [[  9.21377769]
 [  9.21377769]
 [-12.60320383]]
Gradient Adjustment:  [[ 0.00044004]
 [ 0.00044004]
 [-0.00059118]]
Current Weights:  [[  9.2142176 ]
 [  9.2142176 ]
 [-12.60379484]]
Gradient Adjustment:  [[ 0.00043991]
 [ 0.00043991]
 [-0.00059101]]
Current Weights:  [[  9.21465739]
 [  9.21465739]
 [-12.60438568]]
Gradient Adjustment:  [[ 0.00043979]
 [ 0.00043979]
 [-0.00059084]]
Current Weights:  [[  9.21509705]
 [  9.21509705]
 [-12.60497635]]
Gradient Adjustment:  [[ 0.00043966]
 [ 0.00043966]
 [-0.00059067]]
Current Weights:  [[  9.21553658]
 [  9.21553658]
 [-12.60556684]]
Gradient Adjustment:  [[ 0.00043953]
 [ 0.00043953]
 [-0.0005905 ]]
Current Weights:  [[  9.21597599]
 [  9

 [-0.00052284]]
Current Weights:  [[  9.40152998]
 [  9.40152998]
 [-12.85538956]]
Gradient Adjustment:  [[ 0.00038924]
 [ 0.00038924]
 [-0.00052271]]
Current Weights:  [[  9.40191912]
 [  9.40191912]
 [-12.85591213]]
Gradient Adjustment:  [[ 0.00038914]
 [ 0.00038914]
 [-0.00052258]]
Current Weights:  [[  9.40230816]
 [  9.40230816]
 [-12.85643458]]
Gradient Adjustment:  [[ 0.00038904]
 [ 0.00038904]
 [-0.00052244]]
Current Weights:  [[  9.4026971 ]
 [  9.4026971 ]
 [-12.85695689]]
Gradient Adjustment:  [[ 0.00038894]
 [ 0.00038894]
 [-0.00052231]]
Current Weights:  [[  9.40308594]
 [  9.40308594]
 [-12.85747907]]
Gradient Adjustment:  [[ 0.00038884]
 [ 0.00038884]
 [-0.00052218]]
Current Weights:  [[  9.40347469]
 [  9.40347469]
 [-12.85800111]]
Gradient Adjustment:  [[ 0.00038874]
 [ 0.00038874]
 [-0.00052204]]
Current Weights:  [[  9.40386333]
 [  9.40386333]
 [-12.85852302]]
Gradient Adjustment:  [[ 0.00038865]
 [ 0.00038865]
 [-0.00052191]]
Current Weights:  [[  9.40425188]
 [  9

 [-13.07801842]]
Gradient Adjustment:  [[ 0.00034923]
 [ 0.00034923]
 [-0.00046881]]
Current Weights:  [[  9.56769021]
 [  9.56769021]
 [-13.07848713]]
Gradient Adjustment:  [[ 0.00034915]
 [ 0.00034915]
 [-0.0004687 ]]
Current Weights:  [[  9.56803928]
 [  9.56803928]
 [-13.07895573]]
Gradient Adjustment:  [[ 0.00034907]
 [ 0.00034907]
 [-0.0004686 ]]
Current Weights:  [[  9.56838826]
 [  9.56838826]
 [-13.07942422]]
Gradient Adjustment:  [[ 0.00034899]
 [ 0.00034899]
 [-0.00046849]]
Current Weights:  [[  9.56873717]
 [  9.56873717]
 [-13.0798926 ]]
Gradient Adjustment:  [[ 0.00034891]
 [ 0.00034891]
 [-0.00046838]]
Current Weights:  [[  9.569086  ]
 [  9.569086  ]
 [-13.08036087]]
Gradient Adjustment:  [[ 0.00034883]
 [ 0.00034883]
 [-0.00046828]]
Current Weights:  [[  9.56943475]
 [  9.56943475]
 [-13.08082904]]
Gradient Adjustment:  [[ 0.00034875]
 [ 0.00034875]
 [-0.00046817]]
Current Weights:  [[  9.56978341]
 [  9.56978341]
 [-13.0812971 ]]
Gradient Adjustment:  [[ 0.00034867]
 

 [-0.00042485]]
Current Weights:  [[  9.71753996]
 [  9.71753996]
 [-13.27961899]]
Gradient Adjustment:  [[ 0.00031651]
 [ 0.00031651]
 [-0.00042476]]
Current Weights:  [[  9.7178564 ]
 [  9.7178564 ]
 [-13.28004366]]
Gradient Adjustment:  [[ 0.00031644]
 [ 0.00031644]
 [-0.00042467]]
Current Weights:  [[  9.71817278]
 [  9.71817278]
 [-13.28046825]]
Gradient Adjustment:  [[ 0.00031638]
 [ 0.00031638]
 [-0.00042459]]
Current Weights:  [[  9.71848909]
 [  9.71848909]
 [-13.28089274]]
Gradient Adjustment:  [[ 0.00031631]
 [ 0.00031631]
 [-0.0004245 ]]
Current Weights:  [[  9.71880534]
 [  9.71880534]
 [-13.28131715]]
Gradient Adjustment:  [[ 0.00031625]
 [ 0.00031625]
 [-0.00042441]]
Current Weights:  [[  9.71912152]
 [  9.71912152]
 [-13.28174148]]
Gradient Adjustment:  [[ 0.00031618]
 [ 0.00031618]
 [-0.00042432]]
Current Weights:  [[  9.71943764]
 [  9.71943764]
 [-13.28216571]]
Gradient Adjustment:  [[ 0.00031612]
 [ 0.00031612]
 [-0.00042423]]
Current Weights:  [[  9.71975369]
 [  9

 [-0.00038795]]
Current Weights:  [[  9.85572023]
 [  9.85572023]
 [-13.46503445]]
Gradient Adjustment:  [[ 0.0002891 ]
 [ 0.0002891 ]
 [-0.00038787]]
Current Weights:  [[  9.85600927]
 [  9.85600927]
 [-13.46542225]]
Gradient Adjustment:  [[ 0.00028905]
 [ 0.00028905]
 [-0.0003878 ]]
Current Weights:  [[  9.85629826]
 [  9.85629826]
 [-13.46580998]]
Gradient Adjustment:  [[ 0.00028899]
 [ 0.00028899]
 [-0.00038773]]
Current Weights:  [[  9.8565872 ]
 [  9.8565872 ]
 [-13.46619763]]
Gradient Adjustment:  [[ 0.00028894]
 [ 0.00028894]
 [-0.00038765]]
Current Weights:  [[  9.85687608]
 [  9.85687608]
 [-13.46658521]]
Gradient Adjustment:  [[ 0.00028888]
 [ 0.00028888]
 [-0.00038758]]
Current Weights:  [[  9.85716491]
 [  9.85716491]
 [-13.46697272]]
Gradient Adjustment:  [[ 0.00028883]
 [ 0.00028883]
 [-0.00038751]]
Current Weights:  [[  9.85745368]
 [  9.85745368]
 [-13.46736015]]
Gradient Adjustment:  [[ 0.00028877]
 [ 0.00028877]
 [-0.00038743]]
Current Weights:  [[  9.8577424 ]
 [  9

Current Weights:  [[  9.98188192]
 [  9.98188192]
 [-13.63427993]]
Gradient Adjustment:  [[ 0.00026614]
 [ 0.00026614]
 [-0.00035698]]
Current Weights:  [[  9.98214801]
 [  9.98214801]
 [-13.63463685]]
Gradient Adjustment:  [[ 0.00026609]
 [ 0.00026609]
 [-0.00035692]]
Current Weights:  [[  9.98241405]
 [  9.98241405]
 [-13.6349937 ]]
Gradient Adjustment:  [[ 0.00026604]
 [ 0.00026604]
 [-0.00035685]]
Current Weights:  [[  9.98268005]
 [  9.98268005]
 [-13.63535049]]
Gradient Adjustment:  [[ 0.000266  ]
 [ 0.000266  ]
 [-0.00035679]]
Current Weights:  [[  9.982946  ]
 [  9.982946  ]
 [-13.63570722]]
Gradient Adjustment:  [[ 0.00026595]
 [ 0.00026595]
 [-0.00035673]]
Current Weights:  [[  9.9832119 ]
 [  9.9832119 ]
 [-13.63606389]]
Gradient Adjustment:  [[ 0.0002659 ]
 [ 0.0002659 ]
 [-0.00035667]]
Current Weights:  [[  9.98347776]
 [  9.98347776]
 [-13.6364205 ]]
Gradient Adjustment:  [[ 0.00026586]
 [ 0.00026586]
 [-0.0003566 ]]
Current Weights:  [[  9.98374357]
 [  9.98374357]
 [-13

 [-0.000331  ]]
Current Weights:  [[ 10.09691298]
 [ 10.09691298]
 [-13.7885592 ]]
Gradient Adjustment:  [[ 0.00024678]
 [ 0.00024678]
 [-0.00033094]]
Current Weights:  [[ 10.09715972]
 [ 10.09715972]
 [-13.78889009]]
Gradient Adjustment:  [[ 0.00024674]
 [ 0.00024674]
 [-0.00033089]]
Current Weights:  [[ 10.09740642]
 [ 10.09740642]
 [-13.78922093]]
Gradient Adjustment:  [[ 0.0002467 ]
 [ 0.0002467 ]
 [-0.00033084]]
Current Weights:  [[ 10.09765308]
 [ 10.09765308]
 [-13.78955171]]
Gradient Adjustment:  [[ 0.00024666]
 [ 0.00024666]
 [-0.00033078]]
Current Weights:  [[ 10.0978997 ]
 [ 10.0978997 ]
 [-13.78988244]]
Gradient Adjustment:  [[ 0.00024662]
 [ 0.00024662]
 [-0.00033073]]
Current Weights:  [[ 10.09814628]
 [ 10.09814628]
 [-13.79021312]]
Gradient Adjustment:  [[ 0.00024658]
 [ 0.00024658]
 [-0.00033068]]
Current Weights:  [[ 10.09839282]
 [ 10.09839282]
 [-13.79054374]]
Gradient Adjustment:  [[ 0.00024654]
 [ 0.00024654]
 [-0.00033062]]
Current Weights:  [[ 10.09863932]
 [ 10

 [-13.92888413]]
Gradient Adjustment:  [[ 0.00023039]
 [ 0.00023039]
 [-0.0003089 ]]
Current Weights:  [[ 10.20179064]
 [ 10.20179064]
 [-13.92919299]]
Gradient Adjustment:  [[ 0.00023035]
 [ 0.00023035]
 [-0.00030886]]
Current Weights:  [[ 10.20202095]
 [ 10.20202095]
 [-13.9295018 ]]
Gradient Adjustment:  [[ 0.00023032]
 [ 0.00023032]
 [-0.00030881]]
Current Weights:  [[ 10.20225123]
 [ 10.20225123]
 [-13.92981056]]
Gradient Adjustment:  [[ 0.00023028]
 [ 0.00023028]
 [-0.00030876]]
Current Weights:  [[ 10.20248148]
 [ 10.20248148]
 [-13.93011927]]
Gradient Adjustment:  [[ 0.00023025]
 [ 0.00023025]
 [-0.00030872]]
Current Weights:  [[ 10.20271169]
 [ 10.20271169]
 [-13.93042794]]
Gradient Adjustment:  [[ 0.00023021]
 [ 0.00023021]
 [-0.00030867]]
Current Weights:  [[ 10.20294187]
 [ 10.20294187]
 [-13.93073656]]
Gradient Adjustment:  [[ 0.00023018]
 [ 0.00023018]
 [-0.00030862]]
Current Weights:  [[ 10.20317201]
 [ 10.20317201]
 [-13.93104514]]
Gradient Adjustment:  [[ 0.00023014]
 

 [-0.0002896 ]]
Current Weights:  [[ 10.29968915]
 [ 10.29968915]
 [-14.06044505]]
Gradient Adjustment:  [[ 0.000216  ]
 [ 0.000216  ]
 [-0.00028956]]
Current Weights:  [[ 10.29990512]
 [ 10.29990512]
 [-14.06073457]]
Gradient Adjustment:  [[ 0.00021597]
 [ 0.00021597]
 [-0.00028952]]
Current Weights:  [[ 10.30012105]
 [ 10.30012105]
 [-14.06102404]]
Gradient Adjustment:  [[ 0.00021593]
 [ 0.00021593]
 [-0.00028948]]
Current Weights:  [[ 10.30033696]
 [ 10.30033696]
 [-14.06131348]]
Gradient Adjustment:  [[ 0.0002159 ]
 [ 0.0002159 ]
 [-0.00028944]]
Current Weights:  [[ 10.30055283]
 [ 10.30055283]
 [-14.06160288]]
Gradient Adjustment:  [[ 0.00021587]
 [ 0.00021587]
 [-0.0002894 ]]
Current Weights:  [[ 10.30076867]
 [ 10.30076867]
 [-14.06189223]]
Gradient Adjustment:  [[ 0.00021584]
 [ 0.00021584]
 [-0.00028935]]
Current Weights:  [[ 10.30098449]
 [ 10.30098449]
 [-14.06218154]]
Gradient Adjustment:  [[ 0.00021581]
 [ 0.00021581]
 [-0.00028931]]
Current Weights:  [[ 10.30120027]
 [ 10

Current Weights:  [[ 10.39471321]
 [ 10.39471321]
 [-14.18782252]]
Gradient Adjustment:  [[ 0.00020291]
 [ 0.00020291]
 [-0.00027198]]
Current Weights:  [[ 10.39491609]
 [ 10.39491609]
 [-14.18809446]]
Gradient Adjustment:  [[ 0.00020289]
 [ 0.00020289]
 [-0.00027194]]
Current Weights:  [[ 10.39511895]
 [ 10.39511895]
 [-14.18836637]]
Gradient Adjustment:  [[ 0.00020286]
 [ 0.00020286]
 [-0.00027191]]
Current Weights:  [[ 10.39532178]
 [ 10.39532178]
 [-14.18863824]]
Gradient Adjustment:  [[ 0.00020283]
 [ 0.00020283]
 [-0.00027187]]
Current Weights:  [[ 10.39552459]
 [ 10.39552459]
 [-14.18891007]]
Gradient Adjustment:  [[ 0.0002028 ]
 [ 0.0002028 ]
 [-0.00027183]]
Current Weights:  [[ 10.39572736]
 [ 10.39572736]
 [-14.18918187]]
Gradient Adjustment:  [[ 0.00020278]
 [ 0.00020278]
 [-0.0002718 ]]
Current Weights:  [[ 10.39593011]
 [ 10.39593011]
 [-14.18945363]]
Gradient Adjustment:  [[ 0.00020275]
 [ 0.00020275]
 [-0.00027176]]
Current Weights:  [[ 10.39613284]
 [ 10.39613284]
 [-14

 [-14.30640518]]
Gradient Adjustment:  [[ 0.00019144]
 [ 0.00019144]
 [-0.00025656]]
Current Weights:  [[ 10.48338109]
 [ 10.48338109]
 [-14.30666171]]
Gradient Adjustment:  [[ 0.00019142]
 [ 0.00019142]
 [-0.00025653]]
Current Weights:  [[ 10.48357248]
 [ 10.48357248]
 [-14.30691821]]
Gradient Adjustment:  [[ 0.00019139]
 [ 0.00019139]
 [-0.0002565 ]]
Current Weights:  [[ 10.48376384]
 [ 10.48376384]
 [-14.30717468]]
Gradient Adjustment:  [[ 0.00019137]
 [ 0.00019137]
 [-0.00025647]]
Current Weights:  [[ 10.48395519]
 [ 10.48395519]
 [-14.30743111]]
Gradient Adjustment:  [[ 0.00019134]
 [ 0.00019134]
 [-0.00025643]]
Current Weights:  [[ 10.4841465 ]
 [ 10.4841465 ]
 [-14.30768751]]
Gradient Adjustment:  [[ 0.00019132]
 [ 0.00019132]
 [-0.0002564 ]]
Current Weights:  [[ 10.4843378 ]
 [ 10.4843378 ]
 [-14.30794388]]
Gradient Adjustment:  [[ 0.00019129]
 [ 0.00019129]
 [-0.00025637]]
Current Weights:  [[ 10.48452907]
 [ 10.48452907]
 [-14.30820022]]
Gradient Adjustment:  [[ 0.00019127]
 

Gradient Adjustment:  [[ 0.00018095]
 [ 0.00018095]
 [-0.00024248]]
Current Weights:  [[ 10.56897036]
 [ 10.56897036]
 [-14.42135869]]
Gradient Adjustment:  [[ 0.00018093]
 [ 0.00018093]
 [-0.00024245]]
Current Weights:  [[ 10.56915126]
 [ 10.56915126]
 [-14.42160111]]
Gradient Adjustment:  [[ 0.00018091]
 [ 0.00018091]
 [-0.00024242]]
Current Weights:  [[ 10.56933215]
 [ 10.56933215]
 [-14.4218435 ]]
Gradient Adjustment:  [[ 0.00018089]
 [ 0.00018089]
 [-0.00024239]]
Current Weights:  [[ 10.56951302]
 [ 10.56951302]
 [-14.42208586]]
Gradient Adjustment:  [[ 0.00018087]
 [ 0.00018087]
 [-0.00024236]]
Current Weights:  [[ 10.56969386]
 [ 10.56969386]
 [-14.42232819]]
Gradient Adjustment:  [[ 0.00018084]
 [ 0.00018084]
 [-0.00024233]]
Current Weights:  [[ 10.56987469]
 [ 10.56987469]
 [-14.42257049]]
Gradient Adjustment:  [[ 0.00018082]
 [ 0.00018082]
 [-0.0002423 ]]
Current Weights:  [[ 10.57005549]
 [ 10.57005549]
 [-14.42281276]]
Gradient Adjustment:  [[ 0.0001808 ]
 [ 0.0001808 ]
 [-

 [-0.00022988]]
Current Weights:  [[ 10.6498224 ]
 [ 10.6498224 ]
 [-14.52969326]]
Gradient Adjustment:  [[ 0.00017155]
 [ 0.00017155]
 [-0.00022985]]
Current Weights:  [[ 10.64999393]
 [ 10.64999393]
 [-14.52992308]]
Gradient Adjustment:  [[ 0.00017153]
 [ 0.00017153]
 [-0.00022982]]
Current Weights:  [[ 10.65016545]
 [ 10.65016545]
 [-14.53015288]]
Gradient Adjustment:  [[ 0.00017151]
 [ 0.00017151]
 [-0.0002298 ]]
Current Weights:  [[ 10.65033694]
 [ 10.65033694]
 [-14.53038265]]
Gradient Adjustment:  [[ 0.00017149]
 [ 0.00017149]
 [-0.00022977]]
Current Weights:  [[ 10.65050841]
 [ 10.65050841]
 [-14.5306124 ]]
Gradient Adjustment:  [[ 0.00017147]
 [ 0.00017147]
 [-0.00022975]]
Current Weights:  [[ 10.65067987]
 [ 10.65067987]
 [-14.53084212]]
Gradient Adjustment:  [[ 0.00017145]
 [ 0.00017145]
 [-0.00022972]]
Current Weights:  [[ 10.6508513 ]
 [ 10.6508513 ]
 [-14.53107181]]
Gradient Adjustment:  [[ 0.00017144]
 [ 0.00017144]
 [-0.00022969]]
Current Weights:  [[ 10.65102272]
 [ 10

 [-14.63122701]]
Gradient Adjustment:  [[ 0.0001632 ]
 [ 0.0001632 ]
 [-0.00021863]]
Current Weights:  [[ 10.72577113]
 [ 10.72577113]
 [-14.63144562]]
Gradient Adjustment:  [[ 0.00016318]
 [ 0.00016318]
 [-0.00021861]]
Current Weights:  [[ 10.7259343 ]
 [ 10.7259343 ]
 [-14.63166421]]
Gradient Adjustment:  [[ 0.00016316]
 [ 0.00016316]
 [-0.00021859]]
Current Weights:  [[ 10.72609744]
 [ 10.72609744]
 [-14.63188277]]
Gradient Adjustment:  [[ 0.00016315]
 [ 0.00016315]
 [-0.00021856]]
Current Weights:  [[ 10.72626057]
 [ 10.72626057]
 [-14.63210131]]
Gradient Adjustment:  [[ 0.00016313]
 [ 0.00016313]
 [-0.00021854]]
Current Weights:  [[ 10.72642368]
 [ 10.72642368]
 [-14.63231983]]
Gradient Adjustment:  [[ 0.00016311]
 [ 0.00016311]
 [-0.00021852]]
Current Weights:  [[ 10.72658678]
 [ 10.72658678]
 [-14.63253832]]
Gradient Adjustment:  [[ 0.00016309]
 [ 0.00016309]
 [-0.00021849]]
Current Weights:  [[ 10.72674985]
 [ 10.72674985]
 [-14.63275679]]
Gradient Adjustment:  [[ 0.00016308]
 

Current Weights:  [[ 10.7957653 ]
 [ 10.7957653 ]
 [-14.72521012]]
Gradient Adjustment:  [[ 0.00015583]
 [ 0.00015583]
 [-0.00020874]]
Current Weights:  [[ 10.79592111]
 [ 10.79592111]
 [-14.72541884]]
Gradient Adjustment:  [[ 0.00015581]
 [ 0.00015581]
 [-0.00020872]]
Current Weights:  [[ 10.79607691]
 [ 10.79607691]
 [-14.72562753]]
Gradient Adjustment:  [[ 0.0001558 ]
 [ 0.0001558 ]
 [-0.00020869]]
Current Weights:  [[ 10.79623269]
 [ 10.79623269]
 [-14.7258362 ]]
Gradient Adjustment:  [[ 0.00015578]
 [ 0.00015578]
 [-0.00020867]]
Current Weights:  [[ 10.79638845]
 [ 10.79638845]
 [-14.72604485]]
Gradient Adjustment:  [[ 0.00015576]
 [ 0.00015576]
 [-0.00020865]]
Current Weights:  [[ 10.7965442 ]
 [ 10.7965442 ]
 [-14.72625348]]
Gradient Adjustment:  [[ 0.00015575]
 [ 0.00015575]
 [-0.00020863]]
Current Weights:  [[ 10.79669993]
 [ 10.79669993]
 [-14.72646209]]
Gradient Adjustment:  [[ 0.00015573]
 [ 0.00015573]
 [-0.00020861]]
Current Weights:  [[ 10.79685565]
 [ 10.79685565]
 [-14

In [ ]:
# my loss function is not reducing, not sure why

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [19]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# download data and seperate columns into categorical vs continuous values

colnames = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 
            'restecg', 'thalach', 'exang', 'oldspeak', 'slope', 'ca', 'thal', 'target']

onehot = ['sex', 'cp', 'fbs', 'restecg','exang', 'slope', 'ca', 'thal']

scale = ['age', 'trestbps', 'chol', 'thalach', 'oldspeak' ]

df = pd.read_csv('processed.cleveland.data', names=colnames)


In [20]:
# clean out some nans, cast object columns to numeric and encode the target as a 
# binary variable
df.replace('?', np.nan, inplace=True)
df.dropna(inplace=True)
df['ca'] = pd.to_numeric(df['ca']) 
df['thal'] = pd.to_numeric(df['thal'])
df['target'] = df['target'].map({0:0, 1:1, 2:1, 3:1, 4:1})

In [21]:
# encode data using a column transformer
cleaning_trans = ColumnTransformer(
    [
    ('scaler', StandardScaler(), scale),
    ('hot', OneHotEncoder(), onehot)],
    n_jobs=-1, remainder='passthrough', verbose=True)

In [22]:
cleaning_trans.fit_transform(df)
X = df.drop(columns='target').values
y = df['target'].values
X.shape, y.shape

((297, 13), (297,))

In [23]:
class NueralNetwork():
    def __init__(self, input_size = 13, hiddenNodes = 13, outputNodes = 1):
#     def __init__(self, input_size, hiddenNodes, outputNodes):
        # Set up Architecture of neural network
        self.input = input_size 
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes
        
        # Initial Weights
        # 3x4 matrix for first layer
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        #4x1 matrix for hidden to output layer
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, z):
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forawrd

        """
        #weighted sum of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        #Activations of weighted sums
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        

        #Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        # Final Activation of output
        self.activated_output = self.sigmoid(self.output_sum)


        return self.activated_output
    
    def get_attributes(self):
        
        attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']

        [print(i + '\n', getattr(nn,i), '\n' + '---'*3) for i in dir(nn) if i in attributes]

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [24]:
# reshape y for network compatibility
y = y.reshape(-1,1)
y.shape, X.shape

((297, 1), (297, 13))

In [25]:
new_nn = NueralNetwork()

for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
#         print('Actual Output: \n', y)
#         print('Predicted Output: \n', str(new_nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - new_nn.feed_forward(X)))))
    new_nn.train(X, y)
# print("Loss: \n", str(np.mean(np.square(y - new_nn.feed_forward(X)))))

+---------EPOCH 1---------+
Input: 
 [[63.  1.  1. ...  3.  0.  6.]
 [67.  1.  4. ...  2.  3.  3.]
 [67.  1.  4. ...  2.  2.  7.]
 ...
 [68.  1.  4. ...  2.  2.  7.]
 [57.  1.  4. ...  2.  1.  7.]
 [57.  0.  2. ...  2.  1.  3.]]
Loss: 
 0.4156613694567119
+---------EPOCH 2---------+
Input: 
 [[63.  1.  1. ...  3.  0.  6.]
 [67.  1.  4. ...  2.  3.  3.]
 [67.  1.  4. ...  2.  2.  7.]
 ...
 [68.  1.  4. ...  2.  2.  7.]
 [57.  1.  4. ...  2.  1.  7.]
 [57.  0.  2. ...  2.  1.  3.]]
Loss: 
 0.4612794612794613
+---------EPOCH 3---------+
Input: 
 [[63.  1.  1. ...  3.  0.  6.]
 [67.  1.  4. ...  2.  3.  3.]
 [67.  1.  4. ...  2.  2.  7.]
 ...
 [68.  1.  4. ...  2.  2.  7.]
 [57.  1.  4. ...  2.  1.  7.]
 [57.  0.  2. ...  2.  1.  3.]]
Loss: 
 0.5387205387205354
+---------EPOCH 4---------+
Input: 
 [[63.  1.  1. ...  3.  0.  6.]
 [67.  1.  4. ...  2.  3.  3.]
 [67.  1.  4. ...  2.  2.  7.]
 ...
 [68.  1.  4. ...  2.  2.  7.]
 [57.  1.  4. ...  2.  1.  7.]
 [57.  0.  2. ...  2.  1.  3.]]
Los

In [193]:
# loss increases, again not sure why

## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [154]:
# create a baseline model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split

# Random Seed
seed = 2001
np.random.seed(seed)

# Important Hyperparameters
inputs = X.shape[1]
epochs = 150
batch_size = 20

# Create our model
model = Sequential()

# input and hidden
model.add(Dense(16, input_dim = inputs, activation='relu'))
# model.add(Dropout(0.3))
# model.add(Dense(64, activation='sigmoid'))
model.add(Dense(1, activation='relu'))

#compile
model.compile(loss='binary_crossentropy',
               optimizer = 'adam',
               metrics=['accuracy'])


# Manual Validation Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, 
                                                    random_state=seed)

In [155]:
history = model.fit(X_train, y_train, batch_size=batch_size, epochs = epochs, validation_split=.1, verbose =0)
scores = model.evaluate(X_test, y_test)
print(f'{model.metrics_names[1]}: {scores[1]*100}')

30/30 [==============================] - 0s 18us/sample - loss: 7.6666 - acc: 0.5000
acc: 50.0


In [204]:
# now to hyper paramater tune
# I'm going to optimize batch size 

from sklearn.model_selection import GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

# Random Seed
seed = 2001
np.random.seed(seed)

# Important Hyperparameters
inputs = X.shape[1]
# epochs = 50
# batch_size = 32

# Create our model function for the kerasclassifier wrapper
def create_model():
    model = Sequential()
    # input and hidden
    model.add(Dense(32, input_dim = inputs, activation='relu'))
#     model.add(Dropout(0.3))
#     model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='relu'))

    #compile
    model.compile(loss='binary_crossentropy',
                   optimizer = 'adam',
                   metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# create hyper paramaters to optomize
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

# create a grid search
grid = GridSearchCV(estimator=model, cv=3, param_grid=param_grid, n_jobs=-1, verbose=0)
grid_results = grid.fit(X, y)


In [205]:
# Report Results
print(f"Best: {grid_results.best_score_} using {grid_results.best_params_}")
means = grid_results.cv_results_['mean_test_score']
stds = grid_results.cv_results_['std_test_score']
params = grid_results.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

Best: 0.5420875350634257 using {'batch_size': 60, 'epochs': 20}
Means: 0.49494948983192444, Stdev: 0.042854957712725565 with: {'batch_size': 10, 'epochs': 20}
Means: 0.5050505002339681, Stdev: 0.04285494366377606 with: {'batch_size': 20, 'epochs': 20}
Means: 0.5252525210380554, Stdev: 0.03298974560640662 with: {'batch_size': 40, 'epochs': 20}
Means: 0.5420875350634257, Stdev: 0.04832558313939803 with: {'batch_size': 60, 'epochs': 20}
Means: 0.5420875350634257, Stdev: 0.09523322062967969 with: {'batch_size': 80, 'epochs': 20}
Means: 0.5353535215059916, Stdev: 0.021820670271058235 with: {'batch_size': 100, 'epochs': 20}


In [210]:
# batch size looks good at 60
# now I will try different optimizer functions
optimizers = ['Adam', 'Adagrad', 'Adadelta', 'Adamax']
init_mode = ['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']

model = Sequential()
# input and hidden
model.add(Dense(32, input_dim = inputs, activation='relu'))
#     model.add(Dropout(0.3))
#     model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='relu'))

#compile
model.compile(loss='binary_crossentropy',
               optimizer = 'adagrad',
               metrics=['accuracy'])

batch_size= 60
epochs= 20

history = model.fit(X_train, y_train, batch_size=batch_size, epochs = epochs, 
                    validation_split=.1, verbose =0)
scores = model.evaluate(X_test, y_test)
print(f'{model.metrics_names[1]}: {scores[1]*100}')

W0719 10:13:08.547494 140187306571584 deprecation.py:506] From /home/nedderlander/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/adagrad.py:105: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


30/30 [==============================] - 0s 86us/sample - loss: 8.1777 - acc: 0.4667
acc: 46.666666865348816


In [212]:
model = Sequential()
# input and hidden
model.add(Dense(32, input_dim = inputs, activation='relu'))
#     model.add(Dropout(0.3))
#     model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='relu'))

#compile
model.compile(loss='binary_crossentropy',
               optimizer = 'adamax',
               metrics=['accuracy'])

batch_size= 60
epochs= 20

history = model.fit(X_train, y_train, batch_size=batch_size, epochs = epochs, 
                    validation_split=.1, verbose =0)
scores = model.evaluate(X_test, y_test)
print(f'{model.metrics_names[1]}: {scores[1]*100}')

30/30 [==============================] - 0s 54us/sample - loss: 7.1983 - acc: 0.5333
acc: 53.33333611488342


In [221]:
# adamax seems to have a slight improvement
# so I will tune epochs with the adamax optimizer

# Random Seed
seed = 2001
np.random.seed(seed)

# Important Hyperparameters
inputs = X.shape[1]
# epochs = 50
# batch_size = 32

# Create our model function for the kerasclassifier wrapper
def create_model():
    model = Sequential()
    # input and hidden
    model.add(Dense(32, input_dim = inputs, activation='relu'))
#     model.add(Dropout(0.3))
#     model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='relu'))

    #compile
    model.compile(loss='binary_crossentropy',
                   optimizer = 'adamax',
                   metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# create hyper paramaters to optomize
param_grid = {'batch_size': [60],
              'epochs': [100, 150, 250],
              'shuffle': [True, False],
             'validation_data': [(X_test,y_test)],
             'class_weight': [{0:1, 1:10}, {0:0.5, 1:100}]}

# create a grid search
grid = GridSearchCV(estimator=model, cv=3, param_grid=param_grid, n_jobs=-1, verbose=0)
grid_results = grid.fit(X_train, y_train)


In [222]:
# Report Results
print(f"Best: {grid_results.best_score_} using {grid_results.best_params_}")
means = grid_results.cv_results_['mean_test_score']
stds = grid_results.cv_results_['std_test_score']
params = grid_results.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

Best: 0.5280898809432983 using {'batch_size': 60, 'class_weight': {0: 0.5, 1: 100}, 'epochs': 100, 'shuffle': True, 'validation_data': (array([[6.50e+01, 1.00e+00, 4.00e+00, 1.20e+02, 1.77e+02, 0.00e+00,
        0.00e+00, 1.40e+02, 0.00e+00, 4.00e-01, 1.00e+00, 0.00e+00,
        7.00e+00],
       [5.80e+01, 1.00e+00, 4.00e+00, 1.46e+02, 2.18e+02, 0.00e+00,
        0.00e+00, 1.05e+02, 0.00e+00, 2.00e+00, 2.00e+00, 1.00e+00,
        7.00e+00],
       [4.70e+01, 1.00e+00, 4.00e+00, 1.10e+02, 2.75e+02, 0.00e+00,
        2.00e+00, 1.18e+02, 1.00e+00, 1.00e+00, 2.00e+00, 1.00e+00,
        3.00e+00],
       [5.70e+01, 1.00e+00, 4.00e+00, 1.10e+02, 2.01e+02, 0.00e+00,
        0.00e+00, 1.26e+02, 1.00e+00, 1.50e+00, 2.00e+00, 0.00e+00,
        6.00e+00],
       [3.40e+01, 1.00e+00, 1.00e+00, 1.18e+02, 1.82e+02, 0.00e+00,
        2.00e+00, 1.74e+02, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00,
        3.00e+00],
       [6.60e+01, 0.00e+00, 1.00e+00, 1.50e+02, 2.26e+02, 0.00e+00,
        0.00e+00, 1.1

In [229]:
model = grid_results.best_estimator_

In [233]:
# our best estimator is thus
model.get_params()

{'verbose': 0,
 'batch_size': 60,
 'class_weight': {0: 0.5, 1: 100},
 'epochs': 100,
 'shuffle': True,
 'validation_data': (array([[6.50e+01, 1.00e+00, 4.00e+00, 1.20e+02, 1.77e+02, 0.00e+00,
          0.00e+00, 1.40e+02, 0.00e+00, 4.00e-01, 1.00e+00, 0.00e+00,
          7.00e+00],
         [5.80e+01, 1.00e+00, 4.00e+00, 1.46e+02, 2.18e+02, 0.00e+00,
          0.00e+00, 1.05e+02, 0.00e+00, 2.00e+00, 2.00e+00, 1.00e+00,
          7.00e+00],
         [4.70e+01, 1.00e+00, 4.00e+00, 1.10e+02, 2.75e+02, 0.00e+00,
          2.00e+00, 1.18e+02, 1.00e+00, 1.00e+00, 2.00e+00, 1.00e+00,
          3.00e+00],
         [5.70e+01, 1.00e+00, 4.00e+00, 1.10e+02, 2.01e+02, 0.00e+00,
          0.00e+00, 1.26e+02, 1.00e+00, 1.50e+00, 2.00e+00, 0.00e+00,
          6.00e+00],
         [3.40e+01, 1.00e+00, 1.00e+00, 1.18e+02, 1.82e+02, 0.00e+00,
          2.00e+00, 1.74e+02, 0.00e+00, 0.00e+00, 1.00e+00, 0.00e+00,
          3.00e+00],
         [6.60e+01, 0.00e+00, 1.00e+00, 1.50e+02, 2.26e+02, 0.00e+00,
   