<a href="https://colab.research.google.com/github/danhorsley/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/Copy_of_LS_DS_432_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [0]:
#XOR stands for 'exclusive or' so A XOR B would mean A or B but NOT A AND B
# or in other words OR AND NAND
import pandas as pd
import numpy as np
X = np.array(([0,0,1],
            [0,1,1],
            [1,0,1],
            [0,1,0],
            [1,0,0],
            [1,1,1],
            [0,0,0]), dtype=float)

y=np.array(([0,1,1,1,1,0,0]), dtype=float).reshape(-1,1)

In [8]:
X,y

(array([[0., 0., 1.],
        [0., 1., 1.],
        [1., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 1., 1.],
        [0., 0., 0.]]), array([[0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.]]))

In [0]:
##### Your Code Here #####
class NeuralNetwork:
  
  def __init__(self):
    self.inputs = 3
    self.hiddenNodes=4
    self.outputNodes=1
    
   #Weights (parameters)
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)  #3x4
    print(self.weights1)
    self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #4x1
  
  def sigmoid(self,s):
    return 1/(1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
  
  def feed_forward(self, X):
      """
      Calculate the NN inference using feed forward.
      """

      #Weighted sume of inputs and hidden layer
      self.hidden_sum = np.dot(X, self.weights1)
      #print(self.hidden_sum)

      #Acivations of weighted sum
      self.activated_hidden = self.sigmoid(self.hidden_sum)

      # Weight sum between hidden and output
      self.output_sum = np.dot(self.activated_hidden, self.weights2)

      #Final activation of output
      self.activated_output = self.sigmoid(self.output_sum)

      return self.activated_output

  def backward(self, X, y, o):
      """
      Backward propagate through the network
      """
      self.o_error = y - o #error in output
      self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

      self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
      self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

      self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
      self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights

  def train(self, X, y):
      o = self.feed_forward(X)
      self.backward(X, y, o)

In [46]:
nn = NeuralNetwork()

for i in range(10000):
    if ((i+1) % 2000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

[[ 0.5562323   0.23518919 -0.10112782 -0.18993379]
 [ 0.91099585  0.27871053  0.22164634  0.11210913]
 [ 0.55224598 -0.40826605  0.01509356 -0.42081057]]
+---------EPOCH 2000---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.00744063]
 [0.96698559]
 [0.96695232]
 [0.96876879]
 [0.96873995]
 [0.05578303]
 [0.0128627 ]]
Loss: 
 0.0010667483093382713
+---------EPOCH 4000---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.00437857]
 [0.97942906]
 [0.97940773]
 [0.98031858]
 [0.98029943]
 [0.0342968 ]
 [0.0097131 ]]
Loss: 
 0.0004160661057212508
+---------EPOCH 6000---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]


In [14]:
XX = np.array(([2,9], 
              [1,5],
              [3,6]), dtype=float)

mult = np.random.randn(2,3)

np.dot(XX,mult)

array([[-4.12277   ,  1.46779702,  8.39430312],
       [-2.23408581,  0.90848767,  4.69563273],
       [-3.59364285, -0.41714188,  5.11423711]])

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [50]:
##### Your Code Here #####
from google.colab import files
uploaded = files.upload()

Saving t10k-images-idx3-ubyte.gz to t10k-images-idx3-ubyte.gz
Saving t10k-labels-idx1-ubyte.gz to t10k-labels-idx1-ubyte.gz
Saving train-images-idx3-ubyte.gz to train-images-idx3-ubyte (1).gz
Saving train-labels-idx1-ubyte.gz to train-labels-idx1-ubyte.gz


In [0]:
!pip install python-mnist

In [0]:
from mnist import MNIST

mndata = MNIST('')
mndata.gz = True
images, labels = mndata.load_training()

In [70]:
im = pd.DataFrame(images)
im.head()

0    1    2    3    4    5    6    ...  777  778  779  780  781  782  783
0    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[5 rows x 784 columns]

In [0]:
class NeuralNetwork:
  
  def __init__(self):
    self.inputs = 784
    self.hiddenNodes=2
    self.outputNodes=1
    
   #Weights (parameters)
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)  #3x4
    #print(self.weights1)
    self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #4x1
  
  def sigmoid(self,s):
    return 1/(1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
  
  def feed_forward(self, X):
      """
      Calculate the NN inference using feed forward.
      """

      #Weighted sume of inputs and hidden layer
      self.hidden_sum = np.dot(X, self.weights1)
      #print(self.hidden_sum)

      #Acivations of weighted sum
      self.activated_hidden = self.sigmoid(self.hidden_sum)

      # Weight sum between hidden and output
      self.output_sum = np.dot(self.activated_hidden, self.weights2)

      #Final activation of output
      self.activated_output = self.sigmoid(self.output_sum)

      return self.activated_output

  def backward(self, X, y, o):
      """
      Backward propagate through the network
      """
      self.o_error = y - o #error in output
      self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

      self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
      self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

      self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
      self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights

  def train(self, X, y):
      o = self.feed_forward(X)
      self.backward(X, y, o)

In [92]:
#checking it works
nn=NeuralNetwork()
X = images[0]
nn.feed_forward(X)

array([0.56049477])

In [104]:
nn = NeuralNetwork()
X = im.values[0:100]
y = lab.values[0:100]
X = X / 255

y = y / 100

for i in range(100):
    if ((i+1) % 100 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 100---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
 [[0.05]
 [0.  ]
 [0.04]
 [0.01]
 [0.09]
 [0.02]
 [0.01]
 [0.03]
 [0.01]
 [0.04]
 [0.03]
 [0.05]
 [0.03]
 [0.06]
 [0.01]
 [0.07]
 [0.02]
 [0.08]
 [0.06]
 [0.09]
 [0.04]
 [0.  ]
 [0.09]
 [0.01]
 [0.01]
 [0.02]
 [0.04]
 [0.03]
 [0.02]
 [0.07]
 [0.03]
 [0.08]
 [0.06]
 [0.09]
 [0.  ]
 [0.05]
 [0.06]
 [0.  ]
 [0.07]
 [0.06]
 [0.01]
 [0.08]
 [0.07]
 [0.09]
 [0.03]
 [0.09]
 [0.08]
 [0.05]
 [0.09]
 [0.03]
 [0.03]
 [0.  ]
 [0.07]
 [0.04]
 [0.09]
 [0.08]
 [0.  ]
 [0.09]
 [0.04]
 [0.01]
 [0.04]
 [0.04]
 [0.06]
 [0.  ]
 [0.04]
 [0.05]
 [0.06]
 [0.01]
 [0.  ]
 [0.  ]
 [0.01]
 [0.07]
 [0.01]
 [0.06]
 [0.03]
 [0.  ]
 [0.02]
 [0.01]
 [0.01]
 [0.07]
 [0.09]
 [0.  ]
 [0.02]
 [0.06]
 [0.07]
 [0.08]
 [0.03]
 [0.09]
 [0.  ]
 [0.04]
 [0.06]
 [0.07]
 [0.04]
 [0.06]
 [0.08]
 [0.  ]
 [0.07]
 [0.08]
 [0.

In [102]:
X = im.values[0:100]
np.amax(X)

255

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?