<a href="https://colab.research.google.com/github/derek-shing/DS-Unit-4-Sprint-3-Neural-Networks/blob/master/DS_Unit_4_Sprint_3_Neural_Nets_Spring_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural Networks Sprint Challenge

## 1) Define the following terms:

- Neuron
- Input Layer
- Hidden Layer
- Output Layer
- Activation
- Backpropagation

**Neuron**

Neuron is node in the Neural Network. It take input from previous layer , and pass it to next layer based on activiation function

**Input Layer**

It is the first layer of the Neural Network that interact with the input. It's function is taking the data as an input and pass it to the layer after.

**Hidden Layer**

hidden layer is the layers between input and output layers. Increase the number of hidden layer can increase the complexity of the Neural Network and hence the ability to fit non- linear pattern data and the risk of overfitting at the same time.

**Output Layer**

Output layer is the final layer of the Neural Network. It represent the expected format of the output of the algorithm. For example , 0/1 in a binary classification Neural Network.

**Activation**

Each Neuron in a each is connected to all the Neuron at the layer after. Activation is the function determine which connection need to be activate and pass the signal to those activated Neuron.

**Backpropagation**

Backpropagation is a technique of updating the weight in the Neural Network. It start by calcualating the error in the output layer, and go backward to the first hidden layer to examine reason of causing the error. Since the error can be caused by the weight in each hidden layer or the input of them, we can reduce the error in each iternation by allocate change in weight in different layer.

## 2) Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 1  | 1  | 1  | 1 |
| 1  | 0  | 1  | 0 |
| 0  | 1  | 1  | 0 |
| 0  | 0  | 1  | 0 |

In [0]:
##### Your Code Here #####

import numpy as np
np.random.seed(42)

inputs = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1],
    [0, 0, 1]
])

correct_outputs = [[1], [0], [0], [0]]

In [0]:
class Perceptron(object):
  
  def sigmoid(self,x):
    return 1 / (1 + np.exp(-x))

  def sigmoid_derivative(self,x):
    return sigmoid(x) * (1 - sigmoid(x))
  
  def __init__(self, rate = 0.01, niter = 1000):
    self.rate = rate
    self.niter = niter
    self.weights = 2 * np.random.random((3, 1)) - 1
    
  def fit(self, X, y):

    for iteration in range(self.niter):
      # Weighted sum of inputs/weights
      weighted_sum = np.dot(X, self.weights)
      # Activate
      self.activated_output = self.sigmoid(weighted_sum)
      # Calculate error
      error = correct_outputs - self.activated_output
      # Calculate weight adjustments 
      adjustments = error * self.sigmoid(self.activated_output)
      # Update weights
      self.weights = self.weights + np.dot(inputs.T, adjustments)
      
    print('final weight',self.weights)
    return self
  
  def output_layer(self):
    print('Output after training')
    print(self.activated_output)
    return

In [20]:
p=Perceptron()
p.fit(inputs,correct_outputs)

final weight [[  9.22394561]
 [  9.22394561]
 [-13.81795682]]


In [22]:
#print classification result

#compare the correct result of [[1], [0], [0], [0]]
p.output_layer()

Output after training
[[9.90329164e-01]
 [1.00209386e-02]
 [1.00209386e-02]
 [1.00057303e-06]]


## 3) Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. 
- Your network must have one hidden layer. 
- You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
- Train your model on the Heart Disease dataset from UCI:

[Github Dataset](https://github.com/ryanleeallred/datasets/blob/master/heart.csv)

[Raw File on Github](https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv)


In [0]:
##### Your Code Here #####
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
X = df.drop(columns='target')
y = df['target']


In [25]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [26]:
X.shape, y.shape

((303, 13), (303,))

In [48]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
X = scaler.fit_transform(X)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [49]:
y = np.array(y).reshape((-1,1))
y.shape

(303, 1)

In [0]:
class NeuralNetwork:
  def __init__(self,X,y):
    # Set up NN architecture/layout
    self.inputs = X.shape[1]
    self.hiddenNodes = 3
    self.outputNodes = 1
    
    # Initialize weights for each layer
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
    self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
    
  
  def sigmoid(self, s):
    return 1/(1+np.exp(-s))
    
  def feed_forward(self, X):
    """Calculate the NN inference using feed forward."""
    # Weighted sum of inputs and hidden layer
    self.hidden_sum = np.dot(X, self.weights1)
    # Activations of weighted sum
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    # Weighted sum between hidden and output
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    # Final activation of output
    self.activated_output = self.sigmoid(self.output_sum)
    return self.activated_output
  
  def sigmoid(self, s):
    return 1/(1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
  
  def backward(self, X, y, o):
    # backward propgate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden) # applying derivative of sigmoid to z2 error

    self.weights1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.weights2 += self.activated_hidden.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
    
  def train (self, X, y):
    o = self.feed_forward(X)
    self.backward(X, y, o)

In [50]:
print('Initial weight\n')
nn = NeuralNetwork(X,y)

print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 weights: \n", nn.weights2)

Initial weight

Layer 1 weights: 
 [[-0.45246223  0.77704979  1.04557117]
 [-0.34214171 -0.92604662 -0.51296532]
 [ 0.71010924  0.09247887  0.63007494]
 [ 1.76293747  0.23095372 -0.80893689]
 [ 1.05742351  0.05136086  0.87244716]
 [ 1.06619854 -0.9590081   1.3820046 ]
 [ 0.90512196 -0.60390437  0.30444912]
 [ 0.25720749  0.02393181  0.87191399]
 [ 1.43735633  0.00730637  1.33088133]
 [ 0.98820261  0.23229616  0.17618092]
 [-1.15256537 -1.50076839  0.1650228 ]
 [-0.85592892 -0.03963614 -0.53466274]
 [-1.7884965   0.35730454 -0.41453181]]
Layer 2 weights: 
 [[ 0.08019871]
 [-0.89312027]
 [-0.33481725]]


In [53]:
for i in range(1000): # trains the NN 1,000 times
  if i== 999:
    print('+---------- EPOCH', i+1, '-----------+')
    #print("Input: \n", X) 
    #print("Actual Output: \n", y)  
    #print("Predicted Output: \n" + str(nn.feed_forward(X))) 
    print("final weight 1:\n",nn.weights1)
    print("final weight 2:\n",nn.weights2)
    print("Loss: \n" + str(np.mean(np.square(y - nn.feed_forward(X))))) # mean sum squared loss
    print("\n")
  nn.train(X, y)

+---------- EPOCH 1000 -----------+
final weight 1:
 [[ -4.59173083  -3.76707964   0.04231524]
 [ -7.48941177   2.04649339 -10.16663307]
 [  3.33480597  -1.79194923  15.88784664]
 [  4.74636402   3.58610028  -5.98770361]
 [  3.33976222   7.69313371   4.1530919 ]
 [  3.19565716   5.89416739   4.96256623]
 [  4.5121025   -3.30031171  -2.49014567]
 [  0.37424746  -2.35289202   6.49853049]
 [ -1.12129506   3.00708631  -1.25198321]
 [ -0.17664894  10.38351448  -4.44600492]
 [ -2.9749837   -9.46512152   3.17717657]
 [ -0.72467127   1.44138735 -12.5465926 ]
 [-12.28683744   2.3008704  -12.92571533]]
final weight 2:
 [[  4.64521405]
 [-24.94257139]
 [ 21.56903186]]
Loss: 
0.08425154954293343




## 4) Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy. 

- Use the Heart Disease Dataset (binary classification)
- Use an appropriate loss function for a binary classification task
- Use an appropriate activation function on the final layer of your network. 
- Train your model using verbose output for ease of grading.
- Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
- When hyperparameter tuning, show you work by adding code cells for each new experiment. 
- Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
- You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [0]:
##### Your Code Here #####

In [46]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier
import pandas as pd

Using TensorFlow backend.


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y)

In [0]:
def create_model():
    model = Sequential()
    model.add(Dense(16, input_dim=13, activation='relu'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [60]:
model = create_model()
model.fit(X, y, validation_split=0.20, epochs=60, batch_size=60)

Train on 242 samples, validate on 61 samples
Epoch 1/60
242/242 [==============================] - 0s 1ms/step - loss: 0.6456 - acc: 0.6116 - val_loss: 1.0075 - val_acc: 0.1639
Epoch 2/60
242/242 [==============================] - 0s 58us/step - loss: 0.6251 - acc: 0.6488 - val_loss: 0.9890 - val_acc: 0.1639
Epoch 3/60
242/242 [==============================] - 0s 40us/step - loss: 0.6061 - acc: 0.6860 - val_loss: 0.9881 - val_acc: 0.2295
Epoch 4/60
242/242 [==============================] - 0s 53us/step - loss: 0.5877 - acc: 0.7149 - val_loss: 0.9929 - val_acc: 0.2295
Epoch 5/60
242/242 [==============================] - 0s 43us/step - loss: 0.5711 - acc: 0.7479 - val_loss: 0.9982 - val_acc: 0.2295
Epoch 6/60
242/242 [==============================] - 0s 47us/step - loss: 0.5563 - acc: 0.7645 - val_loss: 1.0067 - val_acc: 0.2459
Epoch 7/60
242/242 [==============================] - 0s 45us/step - loss: 0.5408 - acc: 0.7686 - val_loss: 1.0115 - val_acc: 0.2295
Epoch 8/60
242/242 [=====

### Use GridSearchCV to tune batch size and epochs

In [0]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
model = KerasClassifier(build_fn=create_model, verbose=1)
param_grid = {'batch_size': [40,60,80],
              'epochs': [20,40],
              #'activation':['relu','sigmoid']
             }

In [64]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Epoch 1/20
202/202 [==============================] - 0s 2ms/step - loss: 0.7293 - acc: 0.5149
Epoch 2/20
202/202 [==============================] - 0s 52us/step - loss: 0.6946 - acc: 0.5842
Epoch 3/20
202/202 [==============================] - 0s 53us/step - loss: 0.6613 - acc: 0.6485
Epoch 4/20
202/202 [==============================] - 0s 50us/step - loss: 0.6351 - acc: 0.6980
Epoch 5/20
202/202 [==============================] - 0s 71us/step - loss: 0.6108 - acc: 0.7525
Epoch 6/20
202/202 [==============================] - 0s 68us/step - loss: 0.5897 - acc: 0.7624
Epoch 7/20
202/202 [==============================] - 0s 67us/step - loss: 0.5704 - acc: 0.7871
Epoch 8/20
202/202 [==============================] - 0s 68us/step - loss: 0.5522 - acc: 0.8218
Epoch 9/20
202/202 [==============================] - 0s 57us/step - loss: 0.5364 - acc: 0.8119
Epoch 10/20
202/202 [==============================] - 0s 64us/step - loss: 0.5216 - acc: 0.8218
Epoch 11/20
202/202 [===================

In [65]:
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

Best: 0.5808580840381459 using {'batch_size': 40, 'epochs': 20}
Means: 0.5808580840381459, Stdev: 0.13389743896896858 with: {'batch_size': 40, 'epochs': 20}
Means: 0.5148514764438762, Stdev: 0.23485737879077612 with: {'batch_size': 40, 'epochs': 40}
Means: 0.3861386085254918, Stdev: 0.2752166482191622 with: {'batch_size': 60, 'epochs': 20}
Means: 0.5379537902649479, Stdev: 0.27203208549432273 with: {'batch_size': 60, 'epochs': 40}
Means: 0.47194718867048574, Stdev: 0.3014341542125554 with: {'batch_size': 80, 'epochs': 20}
Means: 0.5049504937708574, Stdev: 0.24103710497898198 with: {'batch_size': 80, 'epochs': 40}
