<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** A neuron takes inputs, processes these inputs, decides if its active and gives an output, this output is then 
       checked how far it is from the expected output and then it modifies the wieghts of it frmula in order to minimize the distanc ebetween observed and expected.

- **Input Layer:** Input layer is the part of a neuron network that takes in the features and inputs
- **Hidden Layer:** Layer that process the inputs and activate them
- **Output Layer:** Layer that gives us an output based on the output funtion of the hidden layer
- **Activation:** when inputs in a node in a hidden layer gets processed in an activation function the neuron gets activated or not based on the outcome of that function 
- **Backpropagation:** The act of learning and adjusting the weights


## 2. Perceptron on XOR Gates <a id="Q2"></a>

The XOr, or “exclusive or”, problem is a classic problem in ANN research. It is the problem of using a neural network to predict the outputs of XOr logic gates given two binary inputs. An XOr function should return a true value if the two inputs are not equal and a false value if they are equal. Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2 | y |
|---|---|---|
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 1 | 0 |
| 1 | 0 | 1 |


In [3]:
import numpy as np

X = np.array([[0, 0],
                [0, 1],
                [1, 1],
                [1, 0]])
y = np.array([[0], [1], [0], [1]])

In [41]:
class Perceptron(object):
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter
        
    def fit(self, X, y):
        """
        Fit training data
        """
        
        self.weight = np.zeros(1 + X.shape[1])
        
        self.errors = []
        
        for i in range(self.niter):
            err = 0
            for xi, target in zip(X, y):
                delta_w = self.rate * (target - self.predict(xi))
                self.weight[1:] += delta_w * xi
                self.weight[0] += delta_w
                err += int(delta_w != 0.0)
            self.errors.append(err)
        return self
    
    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weight[1:]) + self.weight[0]
    
    def predict(self, X):
        return np.where(self.net_input(X) >= 1, 1, 0)

In [58]:
pn = Perceptron(0.01, 50)
pn.fit(X, y)

In [59]:
pn.predict(X)

array([0, 1, 1, 1])

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [148]:

class NeuralNetwork:
    def __init__(self, inputs, hiddenNodes, outputNodes):
        self.inputs = inputs
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes
        
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        
        self.hidden_sum = np.dot(X, self.weights1)
        
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        self.o_error = y - o
        
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
        self.weights1 += X.T.dot(self.z2_delta)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
        
    def accuracy(y,o):
        listy=[]
        for i in range(len(y)):
            if y[i] == o[i]:
                listy.append(1)
            else:
                listy.append(0)
        return (sum(listy)/len(listy))
            
            

In [5]:
from numpy import genfromtxt
my_data = genfromtxt('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv', delimiter=',')[1:]

In [6]:
my_data

array([[63.,  1.,  3., ...,  0.,  1.,  1.],
       [37.,  1.,  2., ...,  0.,  2.,  1.],
       [41.,  0.,  1., ...,  0.,  2.,  1.],
       ...,
       [68.,  1.,  0., ...,  2.,  3.,  0.],
       [57.,  1.,  0., ...,  1.,  3.,  0.],
       [57.,  0.,  1., ...,  1.,  2.,  0.]])

In [7]:
X = my_data[:,:-1]
y = my_data[:,-1]

In [8]:
X.shape, y.shape

((303, 13), (303,))

In [9]:
y = y.reshape(303,1)

In [10]:
y.shape

(303, 1)

0.5445544554455446

In [156]:
nn = NeuralNetwork(13, 10, 1)

for i in range(5):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 200 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y[10])
        print('Predicted Output: \n', str(nn.feed_forward(X)[10]))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
        
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
Actual Output: 
 [1.]
Predicted Output: 
 [0.81330988]
Loss: 
 0.3220954531334406
+---------EPOCH 2---------+
Input: 
 [[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
Actual Output: 
 [1.]
Predicted Output: 
 [6.90882972e-16]
Loss: 
 0.5445544554455277
+---------EPOCH 3---------+
Input: 
 [[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
Actual Output: 
 [1.]
Predicted Output: 
 [6.90882972e-16]
Loss: 
 0.5445544554455277
+---------EPOCH 4---------+
Input: 
 [[63.  1.  3. ...  0. 

In [164]:
nn = NeuralNetwork(13, 5000, 1)
nn.train(X,y)
print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))

Loss: 
 0.5445544554455446


## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [11]:
##### Your Code Here #####
import keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
import numpy as np
# fix random seed for reproducibility
np.random.seed(42)
seed = 42

In [12]:
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')

In [13]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [24]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [38]:
y = y.reshape(303,)
#y = y.reshape(303,1)

# 1st trial

In [15]:
# Important Hyperparameters
inputs = X.shape[1]
epochs = 50
batch_size = 16

# Create Model
model = Sequential()
model.add(Dense(16, input_dim=inputs, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 
# Fit Model
model.fit(X, y, validation_split=0.1, epochs=10, batch_size=batch_size)

W0816 20:13:14.826681  2364 deprecation_wrapper.py:119] From C:\Users\mhdal\Anaconda3\envs\lambda-neural\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0816 20:13:14.865544  2364 deprecation_wrapper.py:119] From C:\Users\mhdal\Anaconda3\envs\lambda-neural\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0816 20:13:14.878509  2364 deprecation_wrapper.py:119] From C:\Users\mhdal\Anaconda3\envs\lambda-neural\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0816 20:13:14.927939  2364 deprecation_wrapper.py:119] From C:\Users\mhdal\Anaconda3\envs\lambda-neural\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W081

Train on 272 samples, validate on 31 samples
Epoch 1/10
272/272 [==============================] - 1s 3ms/step - loss: 6.2715 - acc: 0.6066 - val_loss: 15.9424 - val_acc: 0.0000e+00
Epoch 2/10
272/272 [==============================] - 0s 73us/step - loss: 6.2715 - acc: 0.6066 - val_loss: 15.9424 - val_acc: 0.0000e+00
Epoch 3/10
272/272 [==============================] - 0s 77us/step - loss: 6.2715 - acc: 0.6066 - val_loss: 15.9424 - val_acc: 0.0000e+00
Epoch 4/10
272/272 [==============================] - 0s 103us/step - loss: 6.2715 - acc: 0.6066 - val_loss: 15.9424 - val_acc: 0.0000e+00
Epoch 5/10
272/272 [==============================] - 0s 95us/step - loss: 6.2715 - acc: 0.6066 - val_loss: 15.9424 - val_acc: 0.0000e+00
Epoch 6/10
272/272 [==============================] - 0s 70us/step - loss: 6.2715 - acc: 0.6066 - val_loss: 15.9424 - val_acc: 0.0000e+00
Epoch 7/10
272/272 [==============================] - 0s 66us/step - loss: 6.2715 - acc: 0.6066 - val_loss: 15.9424 - val_acc: 

# 2nd trial

In [42]:
# Important Hyperparameters
inputs = X.shape[1]
epochs = 50
batch_size = 32

# Create Model
model = Sequential()
model.add(Dense(39, input_dim=inputs, activation='relu'))
model.add(Dense(26, activation='relu'))
model.add(Dense(13, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 
# Fit Model
model.fit(X, y, validation_split=0.1, epochs=30, batch_size=16)

Train on 272 samples, validate on 31 samples
Epoch 1/30
272/272 [==============================] - 11s 39ms/step - loss: 1.2192 - acc: 0.4449 - val_loss: 1.8965 - val_acc: 0.0000e+00
Epoch 2/30
272/272 [==============================] - 0s 198us/step - loss: 0.8306 - acc: 0.5772 - val_loss: 0.8317 - val_acc: 0.2903
Epoch 3/30
272/272 [==============================] - 0s 227us/step - loss: 0.7083 - acc: 0.5956 - val_loss: 1.1190 - val_acc: 0.1935
Epoch 4/30
272/272 [==============================] - 0s 198us/step - loss: 0.6725 - acc: 0.5772 - val_loss: 1.2797 - val_acc: 0.1290
Epoch 5/30
272/272 [==============================] - 0s 178us/step - loss: 0.6361 - acc: 0.6213 - val_loss: 0.9883 - val_acc: 0.2258
Epoch 6/30
272/272 [==============================] - 0s 202us/step - loss: 0.5736 - acc: 0.7132 - val_loss: 0.4423 - val_acc: 0.8387
Epoch 7/30
272/272 [==============================] - 0s 182us/step - loss: 0.6023 - acc: 0.6471 - val_loss: 1.2440 - val_acc: 0.1613
Epoch 8/30
27

In [17]:
# MLP for Pima Indians Dataset with 10-fold cross validation
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import StratifiedKFold
import numpy

# fix random seed for reproducibility
seed = 42
numpy.random.seed(seed)

# define 5-fold cross validation test harness
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=seed)
cvscores = []
for train, test in kfold.split(X, y):
  # create model
  model = Sequential()
  model.add(Dense(26, input_dim=13, activation='relu'))
  model.add(Dense(13, activation='relu'))
  model.add(Dense(1, activation='sigmoid'))
  # Compile model
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) # Fit the model
  model.fit(X[train], y[train], epochs=10, batch_size=10, verbose=0)
  # evaluate the model
  scores = model.evaluate(X[test], y[test], verbose=0)
  print(f'{model.metrics_names[1]}: {(scores[1]*100):.2f}%') 
  cvscores.append(scores[1]*100)
print(f'{numpy.mean(cvscores):.2f}% +/- {numpy.std(cvscores):.2f}%')

acc: 45.90%
acc: 68.85%
acc: 72.13%
acc: 45.00%
acc: 68.33%
60.04% +/- 11.99%


In [43]:
import numpy
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier

# fix random seed for reproducibility
seed = 42
numpy.random.seed(seed)

# Function to create model, required for KerasClassifier
def create_model():
  # create model
        model = Sequential()
        model.add(Dense(39, input_dim=inputs, activation='relu'))
        model.add(Dense(26, activation='relu'))
        model.add(Dense(13, activation='relu'))
        model.add(Dense(1, activation='sigmoid'))
# Compile model
  # Compile model
        model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 16, 20, 40, 60, 80, 100],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

C:\Users\mhdal\Anaconda3\envs\lambda-neural\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Best: 0.574257430316198 using {'batch_size': 40, 'epochs': 20}
Means: 0.29042904501897665, Stdev: 0.24604618822183663 with: {'batch_size': 10, 'epochs': 20}
Means: 0.3201320132504989, Stdev: 0.06534320093650178 with: {'batch_size': 16, 'epochs': 20}
Means: 0.5313531343299563, Stdev: 0.07511423565426005 with: {'batch_size': 20, 'epochs': 20}
Means: 0.574257430316198, Stdev: 0.14095152596546182 with: {'batch_size': 40, 'epochs': 20}
Means: 0.39603960602590355, Stdev: 0.17110866261818813 with: {'batch_size': 60, 'epochs': 20}
Means: 0.3861386224184886, Stdev: 0.21065311621672145 with: {'batch_size': 80, 'epochs': 20}
Means: 0.36963696841752963, Stdev: 0.27879488478193154 with: {'batch_size': 100, 'epochs': 20}


In [44]:
# define the grid search parameters
param_grid = {'batch_size': [16,40],
              'epochs': [10, 20, 40, 60]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Best: 0.9009900991082584 using {'batch_size': 16, 'epochs': 40}
Means: 0.2541254129346841, Stdev: 0.24750274985316215 with: {'batch_size': 16, 'epochs': 10}
Means: 0.6006600660557794, Stdev: 0.28379000428434986 with: {'batch_size': 16, 'epochs': 20}
Means: 0.9009900991082584, Stdev: 0.14002114465031684 with: {'batch_size': 16, 'epochs': 40}
Means: 0.25082508260660835, Stdev: 0.3547202336056174 with: {'batch_size': 16, 'epochs': 60}
Means: 0.39273928125502644, Stdev: 0.27844304265960607 with: {'batch_size': 40, 'epochs': 10}
Means: 0.1848184833481367, Stdev: 0.12841634686036554 with: {'batch_size': 40, 'epochs': 20}
Means: 0.5445544585929846, Stdev: 0.41308215433215534 with: {'batch_size': 40, 'epochs': 40}
Means: 0.2739273943129939, Stdev: 0.2948582157693152 with: {'batch_size': 40, 'epochs': 60}


In [ ]:
print("done")

In [ ]:
# define the grid search parameters
param_grid = {'batch_size': [16],
              'epochs': [40]}

# Function to create model, required for KerasClassifier
for opt in ['Adadelta','Adagrad','Adam','Adamax','NAdam','RMSprop','SGD']:

    score=[]
    cvscores=[]
    for train, test in kfold.split(X, y):
      # create model
        model = Sequential()
        model.add(Dense(39, input_dim=13, activation='relu'))
        model.add(Dense(26, activation='relu'))
        model.add(Dense(13, activation='relu'))
        model.add(Dense(1, activation='sigmoid'))
    # Compile model
        model.compile(loss='binary_crossentropy', optimizer=opt, metrics=['accuracy'])
        # Fit Model
        model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=0)
        # evaluate the model
        scores = model.evaluate(X[test], y[test], verbose=0)
        print(opt, model.evaluate(X, y, verbose=0))
        print(f'{model.metrics_names[1]}: {(scores[1]*100):.2f}%')
        score.append(scores)
        cvscores.append(scores[1]*100)
    print(f'{numpy.mean(cvscores):.2f}% +/- {numpy.std(cvscores):.2f}%')
    print(f'{numpy.mean(score):.2f}% +/- {numpy.std(score):.2f}%')


Adadelta [8.777180698883246, 0.45544554455445546]
acc: 45.90%
Adadelta [7.260887781778994, 0.5445544554455446]
acc: 54.10%
Adadelta [8.777180698883246, 0.45544554455445546]
acc: 45.90%
Adadelta [7.260887781778994, 0.5445544554455446]
acc: 55.00%
Adadelta [0.7469227936598334, 0.5511551155115512]
acc: 56.67%
51.51% +/- 4.66%
3.52% +/- 3.67%
Adagrad [0.5045763531533798, 0.7590759083776191]
acc: 78.69%
Adagrad [8.777180698883246, 0.45544554455445546]
acc: 45.90%
Adagrad [0.43642596295564484, 0.8151815189386752]
acc: 80.33%
Adagrad [8.777180698883246, 0.45544554455445546]
acc: 45.00%
Adagrad [0.5197574151034402, 0.7293729374904444]
acc: 70.00%
63.98% +/- 15.54%
2.22% +/- 3.29%


In [ ]:
from sklearn.preprocessing import StandardScaler

#Scale input data
scaler = StandardScaler()
X = scaler.fit_transform(X)