<a href="https://colab.research.google.com/github/JayTheOpenSourcerer/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/LS_DS_Unit_4_Sprint_Challenge_2_JM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
 - Neurons are the biological explanation of nodes in a neural network.  The nodes/neurons are mathematical functions that are designed to work in a successive model of individual nodes that collectivley/individually, ingest data, tranform data, activate data, and output data. 
- **Input Layer:**
 - The input layer of a neural network is composed of artificial input neurons, and ingest the initial data into the network for further processing by subsequent layers of artificial neurons.  The dimensionality of the data is what determines how many nodes make up the input layer.
- **Hidden Layer:**
 - This is the layer (or layers) between the input and output layers. The hidden layer takes in the data from the input layer, performs a function on it, then transforms it into outputs.
- **Output Layer:**
 - This layer distributes the vectorized results of the hidden layer and display the results of the transformation of the system. 
- **Activation:**
 - Activation determines whether or not a specific node will be activated or not based on a pre-defined threshold. The purpose of this is to create non-linearity which helps to solve complex problems. 
- **Backpropagation:**
 - Short for "Backwards Propagation of errors", it refers to a specific algorithm for how weights in a neural network are updated in reverse order at the end of each training epoch in order to minimize the loss function and increase the accuracy of the model.  


## 2. Perceptron on XOR Gates <a id="Q3=2"></a>

Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2|x3|	y|
|---|---|---|---|
1|	1|	1|	1|
1|	0|	1|	0|
0|	1|	1|	0|
0|	0|	1|	0|

In [0]:
# training data- Created a NP Array that matches the model and used as the training data
# Created a philsoraptor 

import numpy as np

X = np.array([[1,1,1],[1,0,1],[0,1,1],[0,0,1]])
y = [[1], [0], [0], [0]]

In [0]:
def Perceptron(X, y):
    
    # sigmoid activation function and derivative
    def sigmoid(x):
        return 1 / (1+np.exp(-x))

    def sigmoid_derivative(x):
        sx = sigmoid(x)
        return sx * (1-sx)
    
    # initialize random weights for inputs
    weights = 2 * np.random.random((3,1)) - 1
    
    
    for iteration in range(1000):
    
        # Weighted sum of inputs/weights
        weighted_sum = np.dot(X, weights)

        # Activate
        activated_outputs = sigmoid(weighted_sum)

        # Calculate error
        error = y - activated_outputs

        # Adjsutments
        adjustments = error * sigmoid_derivative(activated_outputs)

        weights += np.dot(X.T, adjustments)
    
    return activated_outputs

In [4]:
# Output of perceptron
Perceptron(X, y)

array([[9.64736844e-01],
       [2.01270549e-02],
       [2.01270487e-02],
       [1.54214926e-05]])

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [5]:
# And so it began in week one, we still import using Pandas 2 weeks from the end
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [6]:
y = df["target"].values
y = y.reshape(303, 1)
y

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [0]:
X = df.drop(columns="target").values
#X.shape, X_train[0:5]

### Initializing Weights

In [0]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.input = 13
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        # Initial Weights
        # 13x4 Matrix Array for the First Layer
        self.weights1 = np.random.randn(self.input,self.hiddenNodes)
        # 4x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)

In [21]:
nn = NeuralNetwork()

print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 weights: \n", nn.weights2)

Layer 1 weights: 
 [[-0.39731968  1.77242018  0.71201507 -0.62274712]
 [ 0.88858027  1.420477    1.16468856  0.1065638 ]
 [ 1.70627479  1.57123774  0.39039331  1.04966296]
 [ 1.53947933  1.21506138  0.63038032 -0.65935857]
 [ 0.00984776  0.11179473  1.83171502  0.55874711]
 [-0.87606385  1.02574026 -0.91480104 -0.50026428]
 [ 0.28144365 -1.26949724 -0.31859446  1.88250931]
 [ 0.46421638 -0.53156631 -0.40092778  1.06315786]
 [ 0.29915555 -0.4316073   1.22702763  0.29657047]
 [ 0.16998554 -2.01939024 -0.59904393 -0.81683279]
 [-1.00938634  1.01438057 -0.67169063  0.42467341]
 [ 2.3111186   0.55397979 -1.22035363  0.30535354]
 [-0.51659969  0.57420431 -0.01429635 -0.06836947]]
Layer 2 weights: 
 [[-1.22014254]
 [-0.96028197]
 [ 0.43624997]
 [-0.67914268]]


### Take in inputs, get weighted sum, activate, pass activated values to next layer

In [0]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.input = 13
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        # Initial Weights
        # 13x4 Matrix Array for the First Layer
        self.weights1 = np.random.randn(self.input,self.hiddenNodes)
        # 4x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
    
    def sigmoid(self, x):
        return 1 / (1+np.exp(-x))
    
    def feed_forward(self,X):
        """
        Calculate the NN inference using feed forward.
        """
        
        # Weighted sum of inputs & hidden
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output

In [23]:
# generate an output

nn = NeuralNetwork()

print(X[0])
output = nn.feed_forward(X[0])
print("output", output)

[ 63.    1.    3.  145.  233.    1.    0.  150.    0.    2.3   0.    0.
   1. ]
output [0.67491694]


In [24]:
# calculate error

output_all = nn.feed_forward(X)
error_all = y - output_all
print(error_all)

[[ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32510076]
 [ 0.32511879]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32546058]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32561676]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.33732442]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32576903]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.32508306]
 [ 0.49931045]
 [ 0.32508

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app


### Backpropagation

In [25]:
attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']

[print(i + '\n', getattr(nn,i), '\n'+'---'*3) for i in dir(nn) if i in attributes]

activated_hidden
 [[1.00000000e+000 2.66434348e-094 3.23811120e-127 8.21272595e-109]
 [1.00000000e+000 1.04733810e-084 5.60490677e-132 1.45393282e-098]
 [9.99999996e-001 3.86209848e-085 1.21789203e-104 6.77473012e-090]
 ...
 [1.00000000e+000 1.47040022e-095 4.84315980e-101 8.72546266e-100]
 [1.00000000e+000 1.31120559e-080 1.95471629e-070 2.46560752e-088]
 [1.00000000e+000 1.68823308e-092 2.67924410e-116 9.59139322e-094]] 
---------
hidden_sum
 [[  56.58938844 -215.46304106 -291.25331661 -248.87609024]
 [  31.21673991 -193.37089601 -302.21758985 -225.27906694]
 [  19.22636724 -194.36852222 -239.27172816 -205.31945884]
 ...
 [  53.55555561 -218.36004921 -230.98352703 -228.09226381]
 [  22.61223581 -183.93586043 -160.51071145 -201.72504995]
 [  53.50248683 -211.31414609 -266.11433608 -214.18213258]] 
---------
weights1
 [[ 1.21325678 -1.06293495  1.30054157  0.52333482]
 [ 1.15707664  0.30385293 -0.49577658 -1.91865716]
 [-0.97719958  0.6837032   0.52807908 -0.33949837]
 [-0.60044115 -0.

[None, None, None, None]

### Putting it all together

In [0]:
class NeuralNetwork: 
    def __init__(self):
        # Set upArchietecture 
        self.inputs = 13
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        #Initial weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) #13x4
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #4x1
    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """
        
        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error
        
        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [27]:
nn = NeuralNetwork()

for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
Actual Output: 
 [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


+---------EPOCH 550---------+
Input: 
 [[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
Actual Output: 
 [[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [

## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [28]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242, 1), (61, 1))

In [29]:
import keras
from keras.models import Sequential
from keras.layers import Dense


#baseline model

model = Sequential()
model.add(Dense(13, input_dim=13, activation='sigmoid'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation="sigmoid"))

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

model.fit(X_train, y_train, validation_split=.2, epochs=20, batch_size=10)

Using TensorFlow backend.
W0720 12:15:38.144343 140119948306304 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0720 12:15:38.201896 140119948306304 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0720 12:15:38.214877 140119948306304 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0720 12:15:38.271202 140119948306304 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0720 12:15:38.296000 14011994

Train on 193 samples, validate on 49 samples
Epoch 1/20
193/193 [==============================] - 1s 4ms/step - loss: 0.6995 - acc: 0.4560 - val_loss: 0.6918 - val_acc: 0.4286
Epoch 2/20
193/193 [==============================] - 0s 165us/step - loss: 0.6911 - acc: 0.4715 - val_loss: 0.6884 - val_acc: 0.6531
Epoch 3/20
193/193 [==============================] - 0s 158us/step - loss: 0.6876 - acc: 0.5959 - val_loss: 0.6843 - val_acc: 0.6531
Epoch 4/20
193/193 [==============================] - 0s 153us/step - loss: 0.6857 - acc: 0.5648 - val_loss: 0.6807 - val_acc: 0.5714
Epoch 5/20
193/193 [==============================] - 0s 164us/step - loss: 0.6854 - acc: 0.5596 - val_loss: 0.6800 - val_acc: 0.6531
Epoch 6/20
193/193 [==============================] - 0s 165us/step - loss: 0.6836 - acc: 0.5699 - val_loss: 0.6772 - val_acc: 0.5714
Epoch 7/20
193/193 [==============================] - 0s 173us/step - loss: 0.6810 - acc: 0.5389 - val_loss: 0.6753 - val_acc: 0.6327
Epoch 8/20
193/193 

In [30]:
#experimenting with batch size

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

def create_model():
    model = Sequential()
    model.add(Dense(13, input_dim=13, activation='sigmoid'))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation="sigmoid"))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    
    return model

model = KerasClassifier(build_fn=create_model, verbose=1)

param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/20
242/242 [==============================] - 0s 1ms/step - loss: 0.7476 - acc: 0.4463
Epoch 2/20
242/242 [==============================] - 0s 155us/step - loss: 0.6845 - acc: 0.5455
Epoch 3/20
242/242 [==============================] - 0s 168us/step - loss: 0.6702 - acc: 0.5496
Epoch 4/20
242/242 [==============================] - 0s 141us/step - loss: 0.6578 - acc: 0.6612
Epoch 5/20
242/242 [==============================] - 0s 159us/step - loss: 0.6498 - acc: 0.6364
Epoch 6/20
242/242 [==============================] - 0s 154us/step - loss: 0.6469 - acc: 0.6116
Epoch 7/20
242/242 [==============================] - 0s 154us/step - loss: 0.6412 - acc: 0.6529
Epoch 8/20
242/242 [==============================] - 0s 147us/step - loss: 0.6406 - acc: 0.6488
Epoch 9/20
242/242 [==============================] - 0s 141us/step - loss: 0.6322 - acc: 0.6281
Epoch 10/20
242/242 [==============================] - 0s 172us/step - loss: 0.6242 - acc: 0.6488
Epoch 11/20
242/242 [==========

In [31]:
# experimenting with activation function in input layer

def create_model(activation='relu'):
    model = Sequential()
    model.add(Dense(13, input_dim=13, activation=activation))
    model.add(Dense(16, activation='relu'))
    model.add(Dense(1, activation="sigmoid"))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    
    return model

model = KerasClassifier(build_fn=create_model, batch_size=10, verbose=1)

param_grid = {'activation': ['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear'],
              'epochs': [20]}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/20
242/242 [==============================] - 0s 2ms/step - loss: 0.6842 - acc: 0.5455
Epoch 2/20
242/242 [==============================] - 0s 138us/step - loss: 0.6592 - acc: 0.6198
Epoch 3/20
242/242 [==============================] - 0s 138us/step - loss: 0.6537 - acc: 0.6116
Epoch 4/20
242/242 [==============================] - 0s 151us/step - loss: 0.6472 - acc: 0.6281
Epoch 5/20
242/242 [==============================] - 0s 143us/step - loss: 0.6423 - acc: 0.6405
Epoch 6/20
242/242 [==============================] - 0s 149us/step - loss: 0.6391 - acc: 0.6240
Epoch 7/20
242/242 [==============================] - 0s 148us/step - loss: 0.6328 - acc: 0.6488
Epoch 8/20
242/242 [==============================] - 0s 145us/step - loss: 0.6264 - acc: 0.6612
Epoch 9/20
242/242 [==============================] - 0s 166us/step - loss: 0.6242 - acc: 0.6529
Epoch 10/20
242/242 [==============================] - 0s 156us/step - loss: 0.6293 - acc: 0.6529
Epoch 11/20
242/242 [==========

In [32]:
# experimenting with activation function in hidden layer

def create_model(activation='relu'):
    model = Sequential()
    model.add(Dense(13, input_dim=13, activation='tanh'))
    model.add(Dense(16, activation=activation))
    model.add(Dense(1, activation="sigmoid"))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    
    return model

model = KerasClassifier(build_fn=create_model, batch_size=10, verbose=1)

param_grid = {'activation': ['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear'],
              'epochs': [20]}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/20
242/242 [==============================] - 0s 2ms/step - loss: 0.7021 - acc: 0.5413
Epoch 2/20
242/242 [==============================] - 0s 151us/step - loss: 0.6893 - acc: 0.5413
Epoch 3/20
242/242 [==============================] - 0s 135us/step - loss: 0.6854 - acc: 0.5413
Epoch 4/20
242/242 [==============================] - 0s 140us/step - loss: 0.6832 - acc: 0.5537
Epoch 5/20
242/242 [==============================] - 0s 149us/step - loss: 0.6711 - acc: 0.5537
Epoch 6/20
242/242 [==============================] - 0s 151us/step - loss: 0.6640 - acc: 0.5785
Epoch 7/20
242/242 [==============================] - 0s 143us/step - loss: 0.6643 - acc: 0.6033
Epoch 8/20
242/242 [==============================] - 0s 153us/step - loss: 0.6595 - acc: 0.6405
Epoch 9/20
242/242 [==============================] - 0s 147us/step - loss: 0.6568 - acc: 0.6364
Epoch 10/20
242/242 [==============================] - 0s 147us/step - loss: 0.6510 - acc: 0.6405
Epoch 11/20
242/242 [==========

In [33]:
# experimenting with activation function in output layer

def create_model(activation='relu'):
    model = Sequential()
    model.add(Dense(13, input_dim=13, activation='tanh'))
    model.add(Dense(16, activation='hard_sigmoid'))
    model.add(Dense(1, activation=activation))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    
    return model

model = KerasClassifier(build_fn=create_model, batch_size=10, verbose=1)

param_grid = {'activation': ['softmax', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear'],
              'epochs': [20]}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/20
242/242 [==============================] - 1s 2ms/step - loss: 0.7690 - acc: 0.4504
Epoch 2/20
242/242 [==============================] - 0s 160us/step - loss: 0.7086 - acc: 0.4628
Epoch 3/20
242/242 [==============================] - 0s 156us/step - loss: 0.6873 - acc: 0.6033
Epoch 4/20
242/242 [==============================] - 0s 156us/step - loss: 0.6762 - acc: 0.5950
Epoch 5/20
242/242 [==============================] - 0s 148us/step - loss: 0.6736 - acc: 0.5744
Epoch 6/20
242/242 [==============================] - 0s 163us/step - loss: 0.6704 - acc: 0.5950
Epoch 7/20
242/242 [==============================] - 0s 162us/step - loss: 0.6631 - acc: 0.5992
Epoch 8/20
242/242 [==============================] - 0s 172us/step - loss: 0.6597 - acc: 0.6116
Epoch 9/20
242/242 [==============================] - 0s 160us/step - loss: 0.6606 - acc: 0.6488
Epoch 10/20
242/242 [==============================] - 0s 170us/step - loss: 0.6539 - acc: 0.6570
Epoch 11/20
242/242 [==========

In [34]:
# experimenting with number of epochs

def create_model():
    model = Sequential()
    model.add(Dense(13, input_dim=13, activation='tanh'))
    model.add(Dense(16, activation='hard_sigmoid'))
    model.add(Dense(1, activation="softplus"))
    model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    
    return model

model = KerasClassifier(build_fn=create_model, batch_size=10, verbose=1)

param_grid = {'epochs': [20, 50, 80, 140, 300]}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/140
242/242 [==============================] - 1s 3ms/step - loss: 0.7174 - acc: 0.5496
Epoch 2/140
242/242 [==============================] - 0s 153us/step - loss: 0.6794 - acc: 0.5372
Epoch 3/140
242/242 [==============================] - 0s 155us/step - loss: 0.6729 - acc: 0.5826
Epoch 4/140
242/242 [==============================] - 0s 166us/step - loss: 0.6714 - acc: 0.5826
Epoch 5/140
242/242 [==============================] - 0s 169us/step - loss: 0.6699 - acc: 0.6157
Epoch 6/140
242/242 [==============================] - 0s 174us/step - loss: 0.6674 - acc: 0.5826
Epoch 7/140
242/242 [==============================] - 0s 170us/step - loss: 0.6623 - acc: 0.6157
Epoch 8/140
242/242 [==============================] - 0s 158us/step - loss: 0.6616 - acc: 0.5661
Epoch 9/140
242/242 [==============================] - 0s 165us/step - loss: 0.6542 - acc: 0.6116
Epoch 10/140
242/242 [==============================] - 0s 171us/step - loss: 0.6473 - acc: 0.6405
Epoch 11/140
242/242 

In [35]:
# experimenting with optimizer

def create_model(optimizer='adam'):
    model = Sequential()
    model.add(Dense(13, input_dim=13, activation='tanh'))
    model.add(Dense(16, activation='hard_sigmoid'))
    model.add(Dense(1, activation="softplus"))
    model.compile(optimizer=optimizer, loss="binary_crossentropy", metrics=["accuracy"])
    
    return model

model = KerasClassifier(build_fn=create_model, batch_size=10, epochs=80, verbose=1)

param_grid = {'optimizer': ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']}

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)
grid_result = grid.fit(X_train, y_train)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py:706: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/80
242/242 [==============================] - 1s 3ms/step - loss: 0.8130 - acc: 0.5496
Epoch 2/80
242/242 [==============================] - 0s 166us/step - loss: 0.7030 - acc: 0.5496
Epoch 3/80
242/242 [==============================] - 0s 165us/step - loss: 0.6912 - acc: 0.5413
Epoch 4/80
242/242 [==============================] - 0s 157us/step - loss: 0.6847 - acc: 0.5207
Epoch 5/80
242/242 [==============================] - 0s 151us/step - loss: 0.6807 - acc: 0.5579
Epoch 6/80
242/242 [==============================] - 0s 174us/step - loss: 0.6768 - acc: 0.5537
Epoch 7/80
242/242 [==============================] - 0s 173us/step - loss: 0.6759 - acc: 0.5537
Epoch 8/80
242/242 [==============================] - 0s 177us/step - loss: 0.6756 - acc: 0.5413
Epoch 9/80
242/242 [==============================] - 0s 166us/step - loss: 0.6713 - acc: 0.5455
Epoch 10/80
242/242 [==============================] - 0s 172us/step - loss: 0.6673 - acc: 0.5702
Epoch 11/80
242/242 [==========