<a href="https://colab.research.google.com/github/skredenmathias/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
### Hidden Layer:
### Output Layer:
### Neuron:
### Weight:
### Activation Function:
### Node Map:
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
# Correct outputs?
correct_output = [[1], [1], [1], [0]] # ?

In [0]:
# Initialize random weights for our three inputs  (4)?
weights = 2 * np.random.random([3, 1]) - 1   # Consider using () here.
weights

array([[-0.77835634],
       [ 0.00573614],
       [ 0.89342429]])

In [0]:
# Sigmoid activation function and its derivative for updating weights
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return sigmoid(x) * (1 - sigmoid(x))

In [0]:
# Calculate weighted sum of inputs & weights
weighted_sum = np.dot(df, weights) # Or 'data'? ### inputs is np.array
weighted_sum

array([[ 0.89342429],
       [ 0.11506795],
       [ 0.89916043],
       [-0.7726202 ]])

In [0]:
# Output the activated value for the end of 12 training epoch
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.70959632],
       [0.52873529],
       [0.71077694],
       [0.31591258]])

In [0]:
# Take difference of output and true values to calculate error
error = correct_output - activated_output

In [0]:
# Gradient descent/backprop - magic!
adjustments = error * sigmoid_derivative(activated_output)

In [0]:
# Update the weights
weights += np.dot(df.T, adjustments) # df = inputs in lecture

In [0]:
# Put it all together

for iteration in range(10000):
  # Weighted sum of inputs/weights
  weighted_sum = np.matmul(df, weights)

  # Activate!
  activated_output = sigmoid(weighted_sum)

  # Calculate error
  error = correct_output - activated_output

  # Calculate weight adjustments
  adjustments = error * sigmoid(activated_output)

  # Update weights
  weights += np.dot(df.T, adjustments)

print('Weights after training')
print(weights)
print('Output after training')
print(activated_output)

ValueError: ignored

In [0]:
# Write it as an actual function


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [0]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [0]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
    self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

    # Randomly Initialize Weights
    weights = ...

    for i in range(self.niter):
        # Weighted sum of inputs / weights

        # Activate!

        # Cac error

        # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

In [0]:
# https://medium.com/@thomascountz/19-line-line-by-line-python-perceptron-b6f113b161f3

class Perceptron(object):

    def __init__(self, no_of_inputs, threshold=100, learning_rate=0.01):
      # no_of_inputs = how many weights needed we need to learn
        self.threshold = threshold # number of epochs
        self.learning_rate = learning_rate # step change
        self.weights = np.zeros(no_of_inputs + 1) # Initialize weight vector
            # with n zeros. # Why +1? We move our bias into the weight vector
            # so we dont have to deal with it indepdently of our other weights.
            # referred to as bias weight
           
    def predict(self, inputs):
        summation = np.dot(inputs, self.weights[1:]) + self.weights[0]
        # note the slicing is due to the added bias above.
        # inputs is expected to be a numpy array of dimension = no_of_inputs
        if summation > 0:
          activation = 1
        else:
          activation = 0            
        return activation
        # Explicit pseudocode

    def train(self, training_inputs, labels):
      # training_inputs expects a list of numpy vectors, used as predict input.
      # labels expects a numpy array of expected output values for each of
      # the corresponding inputs in the training_inputs list.  
        for _ in range(self.threshold):
            # create new iterable object from t_i, labels
            # store each element in the t_i list into the inputs variable
            # and each of the elements in labels, in the variable label.
            for inputs, label in zip(training_inputs, labels):
                # ^ expected output of the input vector is stored in 'inputs'
                # we do this once for every inputs / label pair.
                prediction = self.predict(inputs)
                # ^ pass inputs vector into predict method, store in prediction.
                self.weights[1:] += self.learning_rate * (label - prediction) * inputs
                # ^ find error (label - prediction) * by self.learning_rate & inputs vector
                # store back into self.weights[1:]
                self.weights[0] += self.learning_rate * (label - prediction)
                # ^ note this is the bias weight, added like this because
                # self.weights & inputs vectors are of different dimensions.

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?