<a href="https://colab.research.google.com/github/danhorsley/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/LS_DS_Unit_4_Sprint_Challenge_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Perceptron on XOR Gates](#Q2)
3. [Multilayer Perceptron](#Q3)
4. [Keras MMP](#Q4)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
Artificial Neural Networks are a computational model that was inspired by how neural networks in the brain process information. In the brain electrochemical signals flow from earlier neurons through the dendrites of the cell toward the cell body. If the received signals surpass a certain threshold with a given timing then the neuron fires sending a large spike of energy down the axon and through the axon terminals to other neurons down the line.

In Artificial Neural Networks the neurons or "nodes" are similar in that they receive inputs and pass on their signal to the next layer of nodes if a certain threshold is reached What a neuron does is it takes each of the input values, multplies each of them by a weight, sums all of these products up, and then passes the sum through what is called an "activation function" the result of which is the final value
- **Input Layer:**
The nodes of the input layer are passive, meaning they do not modify the data. They receive a single value on their input, and duplicate the value to their multiple outputs. For example, they may be pixel values from an image, samples from an audio signal, stock market prices on successive days, etc. They may also be the output of some other algorithm, such as the classifiers in our cancer detection example: diameter, brightness, edge sharpness, etc. Each value from the input layer is duplicated and sent to all of the hidden nodes
- **Hidden Layer:**
In comparison, the nodes of the hidden and output layer are active. This means they modify the data. The values entering a hidden node are multiplied by weights, a set of predetermined numbers stored in the program. The weighted inputs are then added to produce a single number.
- **Output Layer:**
The purpose of the output layer is to output a vector of values that is in a format that is suitable for the type of problem that we're trying to address. Typically the output value is modified by an "activation function" to transform it into a format that makes sense for our context. for examplebefore leaving the node, this vector can be passed through a nonlinear mathematical function called a sigmoid. This is an "s" shaped curve that limits the node's output. That is, the input to the sigmoid is a value between -∞ and +∞, while its output can only be between 0 and 1.
- **Activation:**
see above - for example sigmoid
- **Backpropagation:**
is an algorithm for supervised learning of artificial neural networks using gradient descent. Given an artificial neural network and an error function, the method calculates the gradient of the error function with respect to the neural network's weights.


## 2. Perceptron on XOR Gates <a id="Q3=2"></a>

Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

|x1	|x2|x3|	y|
|---|---|---|---|
1|	1|	1|	1|
1|	0|	1|	0|
0|	1|	1|	0|
0|	0|	1|	0|

In [0]:
#imports and put in train data
#adding vector of ones for bias term
import pandas as pd
import numpy as np
X = np.array(([1,1,1,1],
            [1,0,1,1],
            [0,1,1,1],
            [0,0,1,1]), dtype=float)

y=np.array(([1,0,0,0]), dtype=float).reshape(-1,1)

In [0]:
#define my activations functions
def sigmoid(x):
  return 1/(1+np.exp(-x))

def sigmoid_derivate(x):
  sx = sigmoid(x)
  return sx*(1-sx)

def relu(x):
  return np.where(x > 0.5, 1.0, 0.0)

def relu_prime(x):
  
  return 0

In [55]:
#make random weights for each feature
weights = np.random.random((4,1))
inputs = X
ground_truth = y
for iteration in range(1000):
  #weighted sum of inputs/weights
  weighted_sum = np.dot(inputs,weights)
  #activate
  activated_output = sigmoid(weighted_sum)
  #activated_output = relu(weighted_sum)
  #calculate the error
  error = ground_truth - activated_output
  #adjustments
  adjustments = error * sigmoid_derivate(activated_output)
  #adjustments = error * relu_prime(activated_output)
  weights+=np.dot(inputs.T,adjustments)
 
format_output = ['%.2f' % x for x in activated_output]
print("weights and training")
print(weights)
print("output after training")
print(format_output)

weights and training
[[ 7.80466694]
 [ 7.80465833]
 [-5.81273864]
 [-6.24109098]]
output after training
['0.97', '0.01', '0.01', '0.00']


In [53]:
#above we can see our output after training matches
#let's try it on [1,0,0] which should give output 0
predict_weighted_sum = np.dot([1,0,1,1],weights)
predict_activated_output = sigmoid(predict_weighted_sum)
predict_activated_output

array([0.01401939])

## 3. Multilayer Perceptron <a id="Q3"></a>

Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights.
Your network must have one hidden layer.
You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
Train your model on the Heart Disease dataset from UCI:



In [0]:
class NeuralNetwork:
  
  def __init__(self):
    self.inputs = 13
    self.hiddenNodes=4
    self.outputNodes=1
    
   #Weights (parameters)
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)  #13x4
    print(self.weights1)
    self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) #4x1
  
  def sigmoid(self,s):
    return 1/(1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
  
  def feed_forward(self, X):
      """
      Calculate the NN inference using feed forward.
      """

      #Weighted sume of inputs and hidden layer
      self.hidden_sum = np.dot(X, self.weights1)
      #print(self.hidden_sum)

      #Acivations of weighted sum
      self.activated_hidden = self.sigmoid(self.hidden_sum)

      # Weight sum between hidden and output
      self.output_sum = np.dot(self.activated_hidden, self.weights2)

      #Final activation of output
      self.activated_output = self.sigmoid(self.output_sum)

      return self.activated_output

  def backward(self, X, y, o):
      """
      Backward propagate through the network
      """
      self.o_error = y - o #error in output
      self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

      self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
      self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

      self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
      self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights

  def train(self, X, y):
      o = self.feed_forward(X)
      self.backward(X, y, o)

In [3]:
from google.colab import files
up = files.upload()

Saving heart.csv to heart (1).csv


In [4]:
#using subset of 14 features as described 
heart = pd.read_csv('heart.csv')
heart.head()

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [5]:
heart.shape

(303, 14)

In [0]:
features = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal']

target = ['target']

In [0]:
#mapping data to [0,1]
from sklearn.preprocessing import MinMaxScaler
mms = MinMaxScaler()
train = heart[features].copy()
train = mms.fit_transform(train)

In [0]:
tgt = heart[target]
tgt = np.array(tgt).reshape(-1,1)

In [9]:
train.shape, tgt.shape

((303, 13), (303, 1))

In [78]:
nn = NeuralNetwork()

for i in range(10000):
    if ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', train)
        print('Actual Output: \n', tgt)
        print('Predicted Output: \n', str(nn.feed_forward(train)))
        print("Loss: \n", str(np.mean(np.square(tgt - nn.feed_forward(train)))))
    nn.train(train,tgt)

[[ 0.69712855  2.28022945 -1.56481118  0.43929958]
 [-0.20651722 -0.34247572 -0.93291096 -3.11640796]
 [-1.61444711 -0.13996112 -1.34138175 -1.37572089]
 [ 2.47588279 -1.08895328  1.93753119 -1.0878475 ]
 [-0.77630967 -0.02096941  1.17950465  0.60040611]
 [-0.19114069  0.66850798  1.74562102  0.26017152]
 [ 0.48115786 -1.61636034 -0.82535482  0.55912827]
 [ 1.73293216 -1.84838666  0.24753896  0.6457771 ]
 [ 1.12297563 -1.48615484 -0.97576951  0.52505809]
 [-1.22098847 -0.06015324 -0.06325455  0.46665997]
 [-0.39663847  0.57015668  0.08289668  1.01915266]
 [ 0.02629206 -0.78238833  0.33845239  0.13298396]
 [-0.146368    1.54421352  0.01827762 -0.38563623]]
+---------EPOCH 1000---------+
Input: 
 [[0.70833333 1.         1.         ... 0.         0.         0.33333333]
 [0.16666667 1.         0.66666667 ... 0.         0.         0.66666667]
 [0.25       0.         0.33333333 ... 1.         0.         0.66666667]
 ...
 [0.8125     1.         0.         ... 0.5        0.5        1.        ]

## 4. Keras MMP <a id="Q4"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [0]:
import tensorflow
#tensorflow.__version__
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
np.random.seed(55)

In [12]:
# checking it works on small params
inputs = train.shape[1]
epochs = 10
batch_size = 10

# Create Model
model = Sequential()
model.add(Dense(12, activation='sigmoid', input_shape=(inputs,)))
model.add(Dense(12, activation='sigmoid'))
model.add(Dense(1))
# Compile Model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# Fit Model
model.fit(train, tgt, validation_split=0.33, epochs=epochs, batch_size=batch_size,verbose=1)

Train on 203 samples, validate on 100 samples
Epoch 1/10
203/203 [==============================] - 0s 785us/sample - loss: 1.2991 - acc: 0.1872 - val_loss: 0.4327 - val_acc: 1.0000
Epoch 2/10
203/203 [==============================] - 0s 212us/sample - loss: 0.7905 - acc: 0.2611 - val_loss: 0.7370 - val_acc: 0.0500
Epoch 3/10
203/203 [==============================] - 0s 198us/sample - loss: 0.6073 - acc: 0.8128 - val_loss: 1.0236 - val_acc: 0.0000e+00
Epoch 4/10
203/203 [==============================] - 0s 216us/sample - loss: 0.5251 - acc: 0.8128 - val_loss: 1.3145 - val_acc: 0.0000e+00
Epoch 5/10
203/203 [==============================] - 0s 205us/sample - loss: 0.4864 - acc: 0.8128 - val_loss: 1.5145 - val_acc: 0.0000e+00
Epoch 6/10
203/203 [==============================] - 0s 244us/sample - loss: 0.4748 - acc: 0.8128 - val_loss: 1.5966 - val_acc: 0.0000e+00
Epoch 7/10
203/203 [==============================] - 0s 212us/sample - loss: 0.4691 - acc: 0.8128 - val_loss: 1.6137 - va

In [26]:
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier
from keras.optimizers import SGD

def create_model(optimizer='adam',activation1='sigmoid',activation2='sigmoid'):
  # create model
  model = Sequential()
  model.add(Dense(12, input_dim=13, activation=activation1))
  model.add(Dense(1, activation=activation2))
  #optimize model
  #optimizer = SGD(lr=learn_rate, momentum=momentum)
  # Compile model
  model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)
param_grid = {'batch_size': [ 40, 60 ],
              'epochs': [30,40],
             'optimizer' : [ 'Adam', 'Adamax', 'Nadam'],
             'activation1' : [ 'relu','sigmoid'],
             'activation2' : [ 'relu','sigmoid']
             }

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(train, tgt)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Epoch 1/30
202/202 [==============================] - 0s 889us/sample - loss: 0.7588 - acc: 0.3218
Epoch 2/30
202/202 [==============================] - 0s 68us/sample - loss: 0.7379 - acc: 0.3465
Epoch 3/30
202/202 [==============================] - 0s 64us/sample - loss: 0.7189 - acc: 0.3861
Epoch 4/30
202/202 [==============================] - 0s 68us/sample - loss: 0.7034 - acc: 0.4406
Epoch 5/30
202/202 [==============================] - 0s 72us/sample - loss: 0.6894 - acc: 0.5198
Epoch 6/30
202/202 [==============================] - 0s 57us/sample - loss: 0.6778 - acc: 0.5792
Epoch 7/30
202/202 [==============================] - 0s 64us/sample - loss: 0.6648 - acc: 0.6733
Epoch 8/30
202/202 [==============================] - 0s 62us/sample - loss: 0.6541 - acc: 0.7327
Epoch 9/30
202/202 [==============================] - 0s 65us/sample - loss: 0.6437 - acc: 0.7426
Epoch 10/30
202/202 [==============================] - 0s 65us/sample - loss: 0.6344 - acc: 0.7426
Epoch 11/30
202/20

In [27]:
#when i first ran this i only had 2 parameters and was adjusting more params to use later see below
"""Best: 0.47524752219518024 using {'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}"""
# Best: 0.47524752219518024 using {'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}
# Means: 0.30033003135273856, Stdev: 0.36951907260166106 with: {'batch_size': 40, 'epochs': 30, 'optimizer': 'Adam'}
# Means: 0.3630362957095106, Stdev: 0.26644927277961866 with: {'batch_size': 40, 'epochs': 30, 'optimizer': 'Adamax'}
# Means: 0.2739274005095164, Stdev: 0.31354873539509165 with: {'batch_size': 40, 'epochs': 30, 'optimizer': 'Nadam'}
# Means: 0.3201320171356201, Stdev: 0.32299425269090787 with: {'batch_size': 40, 'epochs': 40, 'optimizer': 'Adam'}
# Means: 0.23102309927344322, Stdev: 0.28574073202605876 with: {'batch_size': 40, 'epochs': 40, 'optimizer': 'Adamax'}
# Means: 0.47524752219518024, Stdev: 0.22461649852982968 with: {'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}
# Means: 0.33663366238276166, Stdev: 0.3456376870529728 with: {'batch_size': 60, 'epochs': 30, 'optimizer': 'Adam'}
# Means: 0.22442243496576944, Stdev: 0.3173812512293851 with: {'batch_size': 60, 'epochs': 30, 'optimizer': 'Adamax'}
# Means: 0.2772277295589447, Stdev: 0.3310545321030772 with: {'batch_size': 60, 'epochs': 30, 'optimizer': 'Nadam'}
# Means: 0.42904291053613025, Stdev: 0.279614116210151 with: {'batch_size': 60, 'epochs': 40, 'optimizer': 'Adam'}
# Means: 0.32673268516858417, Stdev: 0.2891134440121785 with: {'batch_size': 60, 'epochs': 40, 'optimizer': 'Adamax'}
# Means: 0.30693069597085315, Stdev: 0.3407820514959077 with: {'batch_size': 60, 'epochs': 40, 'optimizer': 'Nadam'}

"Best: 0.47524752219518024 using {'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}"

In [28]:
#now try and fine tune more
def create_model(optimizer='adam',activation1='sigmoid',activation2='sigmoid'):
  # create model
  model = Sequential()
  model.add(Dense(12, input_dim=13, activation=activation1))
  model.add(Dense(1, activation=activation2))
  #optimize model
  #optimizer = SGD(lr=learn_rate, momentum=momentum)
  # Compile model
  model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
  return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)
param_grid = {'batch_size': [ 40, 60,80 ],
              'epochs': [40,50,60],
             'optimizer' : [ 'Nadam'],
             'activation1' : [ 'relu','sigmoid'],
             'activation2' : [ 'relu','sigmoid']
             }

grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(train, tgt)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Epoch 1/40
202/202 [==============================] - 0s 2ms/sample - loss: 1.0917 - acc: 0.5297
Epoch 2/40
202/202 [==============================] - 0s 71us/sample - loss: 1.0620 - acc: 0.5545
Epoch 3/40
202/202 [==============================] - 0s 68us/sample - loss: 1.0365 - acc: 0.5644
Epoch 4/40
202/202 [==============================] - 0s 70us/sample - loss: 0.9557 - acc: 0.5743
Epoch 5/40
202/202 [==============================] - 0s 67us/sample - loss: 0.9295 - acc: 0.5842
Epoch 6/40
202/202 [==============================] - 0s 69us/sample - loss: 0.9085 - acc: 0.5842
Epoch 7/40
202/202 [==============================] - 0s 66us/sample - loss: 0.8895 - acc: 0.5842
Epoch 8/40
202/202 [==============================] - 0s 63us/sample - loss: 0.8716 - acc: 0.5891
Epoch 9/40
202/202 [==============================] - 0s 66us/sample - loss: 0.8553 - acc: 0.5941
Epoch 10/40
202/202 [==============================] - 0s 68us/sample - loss: 0.8393 - acc: 0.6089
Epoch 11/40
202/202 

In [29]:
"""Best: 0.9273927410443624 using {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.4587458868821462, Stdev: 0.12242401183367235 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.40924092133839923, Stdev: 0.17643651555301473 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 40, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.5280528167883555, Stdev: 0.2102390518978813 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 40, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.48514851927757263, Stdev: 0.05829545751063169 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 60, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.37953796486059826, Stdev: 0.11327395123014597 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.3696369646737973, Stdev: 0.3246088920916083 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 60, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.3234323561191559, Stdev: 0.1358357566773945 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 80, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.36963696281115216, Stdev: 0.26583538597159784 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 80, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.2904290457566579, Stdev: 0.3366660237050142 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 80, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.3993399391571681, Stdev: 0.24256865450903747 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.28382838269074756, Stdev: 0.3669456475396596 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 40, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.4191419134537379, Stdev: 0.24789851628071427 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 40, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.32013201899826527, Stdev: 0.30744483790438265 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 60, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.3795379598935445, Stdev: 0.3197404994687893 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.4323432284096877, Stdev: 0.315419016524466 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 60, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.3234323499103387, Stdev: 0.3025162588733272 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 80, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.3861386179924011, Stdev: 0.3236679960283603 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 80, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.389438937107722, Stdev: 0.3415801689743473 with: {'activation1': 'relu', 'activation2': 'sigmoid', 'batch_size': 80, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.6501650164524714, Stdev: 0.3758320976088691 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.6666666666666666, Stdev: 0.2597424700889049 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 40, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.7821782231330872, Stdev: 0.1703430723310058 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 40, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.13861386477947235, Stdev: 0.16228767269383687 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 60, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.9273927410443624, Stdev: 0.095766455826271 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.27392739057540894, Stdev: 0.38739183085721524 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 60, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.594059407711029, Stdev: 0.42937281123117915 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 80, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.41914190848668414, Stdev: 0.3435832144115948 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 80, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.47194719811280567, Stdev: 0.3951585349505806 with: {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 80, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.2475247581799825, Stdev: 0.3500528700412519 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.2673267324765523, Stdev: 0.3780570906532244 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 40, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.2541254162788391, Stdev: 0.35938761024524274 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 40, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.2541254162788391, Stdev: 0.35938761024524274 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 60, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.2574257453282674, Stdev: 0.3640549803472382 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.2343234419822693, Stdev: 0.3313833896332703 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 60, 'epochs': 60, 'optimizer': 'Nadam'}
Means: 0.264026403427124, Stdev: 0.37338972055122904 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 80, 'epochs': 40, 'optimizer': 'Nadam'}
Means: 0.1551155149936676, Stdev: 0.21936646503853188 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 80, 'epochs': 50, 'optimizer': 'Nadam'}
Means: 0.19801980257034302, Stdev: 0.28004229041342177 with: {'activation1': 'sigmoid', 'activation2': 'sigmoid', 'batch_size': 80, 'epochs': 60, 'optimizer': 'Nadam'}"""

"Best: 0.9273927410443624 using {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}\nMeans: 0.4587458868821462, Stdev: 0.12242401183367235 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 40, 'epochs': 40, 'optimizer': 'Nadam'}\nMeans: 0.40924092133839923, Stdev: 0.17643651555301473 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 40, 'epochs': 50, 'optimizer': 'Nadam'}\nMeans: 0.5280528167883555, Stdev: 0.2102390518978813 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 40, 'epochs': 60, 'optimizer': 'Nadam'}\nMeans: 0.48514851927757263, Stdev: 0.05829545751063169 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 60, 'epochs': 40, 'optimizer': 'Nadam'}\nMeans: 0.37953796486059826, Stdev: 0.11327395123014597 with: {'activation1': 'relu', 'activation2': 'relu', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}\nMeans: 0.3696369646737973, Stdev: 0.324608892091608

In [0]:
#not bad 92% accuracy
"Best: 0.9273927410443624 using {'activation1': 'sigmoid', 'activation2': 'relu', 'batch_size': 60, 'epochs': 50, 'optimizer': 'Nadam'}"