<a href="https://colab.research.google.com/github/aaptecode/DS-Unit-4-Sprint-3-Neural-Networks/blob/master/LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Neural Networks Assignment

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: Aka the visible layer, the feature set converted into a series of neurons. which is fed into the neural network.
### Hidden Layer: The engine that converts feature set neurons into a predicted target set.
### Output Layer: The target variable
### Neuron: An entity that stores a value
### Weight: Nudges the activations based on sign  and magnitude.
### Activation Function: A squish function used to map previous lavers into subsequent layers, usually a sigmoid function.
### Node Map: A map of the structure of the neural network.
### Perceptron: A single neuron, a single node, of a neural network
### Bias: An adjustment to the weighted sum to get the desired result. 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Your Answer Here

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
##### Your Code Here #####

import matplotlib.pyplot as plt
import matplotlib.style as style
import numpy as np
import pandas as pd
style.use('seaborn-whitegrid')

In [0]:
np.random.seed(237)

inputs = np.array([[1,0,0],
                   [1,1,0],
                   [1,0,1],
                   [1,1,1]]) # includes bias vector = 1

correct_outputs = [[1],
                  [1],
                  [1],
                  [0]]

In [0]:
def sigmoid(x):
    return (1 + np.exp(-x))**-1

def sigmoid_derivative(x):
    return sigmoid(x)* (1 - sigmoid(x))

In [4]:
# for an mxn feature matrix the weights should have dimensions of nx1

weights = 2*np.random.random((inputs.shape[1],1))-1

weights

array([[ 0.97561731],
       [-0.52256163],
       [-0.97208453]])

In [5]:
# weighted sum has dimensions mx1

weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[ 0.97561731],
       [ 0.45305568],
       [ 0.00353278],
       [-0.51902885]])

In [6]:
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.72623773],
       [0.6113655 ],
       [0.50088319],
       [0.37307935]])

In [7]:
error = correct_outputs - activated_output
error

array([[ 0.27376227],
       [ 0.3886345 ],
       [ 0.49911681],
       [-0.37307935]])

In [8]:
adjustments = error * sigmoid_derivative(activated_output) ### Gradient Descent / Backprop 
adjustments

array([[ 0.06015413],
       [ 0.08861693],
       [ 0.11726891],
       [-0.09009815]])

In [9]:
weights += np.dot(inputs.T, adjustments)
weights

array([[ 1.15155913],
       [-0.52404285],
       [-0.94491377]])

In [10]:
for iteration in range(100000):
    
    # Weighted sum of inputs and weights
    weighted_sum = np.dot(inputs, weights)

    # Activate with sigmoid function
    activated_output = sigmoid(weighted_sum)

    # Calculate Error
    error = correct_outputs - activated_output

    # Calculate weight adjustments with sigmoid_derivative
    adjustments = error * sigmoid_derivative(activated_output)

    # Update weights
    weights += np.dot(inputs.T, adjustments)
  
print('optimized weights after training: ')
print(weights)
print()
print('Error')
print(error)
print()


print("Output After Training:")
print(activated_output)

print()


optimized weights after training: 
[[ 24.73182109]
 [-16.45575046]
 [-16.45575046]]

Error
[[ 1.81601401e-11]
 [ 2.54473174e-04]
 [ 2.54473174e-04]
 [-2.80215931e-04]]

Output After Training:
[[1.00000000e+00]
 [9.99745527e-01]
 [9.99745527e-01]
 [2.80215931e-04]]



## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [11]:
##### Your Code Here #####

url = 'https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv'
df = pd.read_csv(url)

df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [12]:
df.Outcome.value_counts(normalize=True)

0    0.651042
1    0.348958
Name: Outcome, dtype: float64

In [13]:
correct_outputs = df.Outcome.reshape(len(df.Outcome),1)
inputs = df.drop(columns='Outcome')
inputs['Bias'] = 1

inputs.shape, correct_outputs.shape

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


((768, 9), (768, 1))

In [14]:
inputs.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Bias  
0                     0.627   50     1  
1                     0.351   31     1  
2                     0.672   32     1  
3                     0.167   21     1  
4                     2.288   33     1

In [15]:
weights = weights = 2*np.random.random((inputs.shape[1],1))-1

weights

array([[ 0.63756872],
       [-0.67875967],
       [ 0.95924509],
       [ 0.16444417],
       [ 0.0542513 ],
       [-0.15121154],
       [ 0.23673119],
       [-0.63144079],
       [-0.43654658]])

In [17]:
from sklearn.metrics import accuracy_score

for iteration in range(10000):
    
    # Weighted sum of inputs and weights
    weighted_sum = np.dot(inputs, weights)

    # Activate with sigmoid function
    activated_output = sigmoid(weighted_sum)

    # Calculate Error
    error = correct_outputs - activated_output

    # Calculate weight adjustments with sigmoid_derivative
    adjustments = error * sigmoid_derivative(activated_output)

    # Update weights
    weights += np.dot(inputs.T, adjustments)
    
    
print('optimized weights after training: ')
print(weights)
print()
print('Error')
print(error.sum())
print()

print("Accuracy After Training:")
print(accuracy_score(activated_output.astype(int), correct_outputs))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


optimized weights after training: 
[[131061.24912707]
 [  6397.49085031]
 [-22532.17049569]
 [ -1856.95057752]
 [   660.83513602]
 [ -9620.31100873]
 [ 12418.73086397]
 [-12760.87010807]
 [-67475.55825081]]

Error
-371.0

Accuracy After Training:
0.45703125


## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?