<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
    - A Neuron is a perceptron that takes a weighted sum of the inputs, add bias, and passes through an activation function to determine if the passed information should go to the next stage. The 'most lit up' neuron in a layer, being the one to move forward. 
- **Input Layer:**
    - The first layer of the Neural Network. It takes an input and feeds it into the rest of the network/perceptron.
- **Hidden Layer:**
    - The layer inbetween input and output and does not see anything outside of it. 
- **Output Layer:**
     - The final layer of the neural Network, this is where the classification/regression will emerge.  The layer that returns the outputs/predictions. 
- **Activation:**
    - An Activation function transforms a matrix into a desirables shape for the output. The common activation functions are sigmoid, tanh, step, relu. If the problem is a regression problem, then the activation function is just a pass through. 
- **Backpropagation:**
    - Backpropagation makes a pass through the neural network everytime it finishes going through forwards to adjust the parameters and weights



## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [2]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [3]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. Explain why you could not achieve a higher accuracy with a *simple perceptron*. It's possible to achieve ~95% accuracy on this dataset.

In [4]:
# Start your candy perceptron here
import numpy as np

X = candy[['chocolate', 'gummy']].to_numpy()
y = candy['ate'].to_numpy().reshape(-1,1)

def sigmoid(x):
    '''  A funciton that takes 1 parameter, x, and returns the sigmoid calculation for it '''
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    ''' A function that takes 1 parameter, x, and returns the sigmoid derivative for it  '''
    sx = sigmoid(x)
    return sx * (1-sx)
 

def perceptron(inputs, outputs, num_passes):
    ''' A Funcition that runs a basic neural network, the Perceptron. 
        It takes the inputs, the outputs to search for, as well as the number of passes
        to learn off of. '''
    
    ''' Assigning Random weights for the inputs'''
    weights = 2 * np.random.random((len(inputs.T),1)) - 1
    
    for iteration in range(num_passes):
        ''' Calculating the dot product of the inputs times the weights'''
        weighted_sum = np.dot(inputs, weights) 

        ''' Output the activated value for the end of 1 Training epoch '''
        activated_output = sigmoid(weighted_sum).astype(int)

        ''' taking the difference of Output and True values and calculating the error '''
        error = outputs - activated_output

        ''' This is where the learning happens '''
        adjustments = error * sigmoid_derivative(activated_output)

        ''' Updating the Weights after each iteration '''
        weights += np.dot(inputs.T, adjustments)
        
        print(iteration)
        print('Outputs After the Training:\n',activated_output)
    
    return activated_output

In [5]:
values = perceptron(X,y,25)

0
Outputs After the Training:
 [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
1
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
2
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
3
Outputs After the Training:
 [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
4
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
5
Outputs After the Training:
 [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
6
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
7
Outputs After the Training:
 [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
8
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
9
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
10
Outputs After the Training:
 [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
11
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
12
Outputs After the Training:
 [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
13
Outputs After the Training:
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
14
Outputs After the Training:
 [[0]
 [0]
 [0]
 ...
 [0]
 

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [56]:
class NeuralNetwork2:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 10000
        self.hiddenNodes = 2
        self.outputNodes = 10000

        # Initial Weights
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        #X = X.reshape(self.inputs,self.hiddenNodes)

        self.weights1 = self.weights1.reshape(self.inputs,self.hiddenNodes)
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X.T, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        # Error in Output
        self.o_error = y.T - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = o * self.sigmoidPrime(o)
        
        self.weights2 = self.weights2.reshape(self.hiddenNodes, self.outputNodes)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.dot(self.z2_delta)

         # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)  

In [57]:
nn = NeuralNetwork2()

# Number of Epochs / Iterations
for i in range(50):
    if (i+1 in range(150)) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(y)))))
        print("Unique Outputs: \n", str(np.unique(nn.feed_forward(X))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.79759846 0.79284142 0.82765986 ... 0.62528221 0.81191088 0.80507363]
 [0.79759846 0.79284142 0.82765986 ... 0.62528221 0.81191088 0.80507363]]
Loss: 
 0.3068914702795405
Unique Outputs: 
 [0.5027435  0.50612424 0.50637946 ... 0.8768819  0.87742352 0.87874095]
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.86834377 0.86564811 0.88507153 ... 0.74989555 0.87636268 0.87254745]
 [0.86834377 0.86564811 0.88507153 ... 0.74989555 0.87636268 0.87254745]]
Loss: 
 0.3550028424793446
Unique Outputs: 
 [0.62567402 0.62961056 0.62990662 ... 0.91228832 0.91259402 0.91333867]
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [95]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
279   61    1   0       138   166    0        0      125      1      3.6   
182   61    0   0       130   330    0        0      169      0      0.0   
16    58    0   2       120   340    0        1      172      0      0.0   
119   46    0   0       138   243    0        0      152      1      0.0   
174   60    1   0       130   206    0        0      132      1      2.4   

     slope  ca  thal  target  
279      1   1     2       0  
182      2   0     2       0  
16       2   0     2       1  
119      1   0     2       1  
174      1   2     3       0

In [98]:
''' Imports '''
#!pip install tensorflow==1.14.0 keras==2.2.4
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
from keras.layers.normalization import BatchNormalization
from keras import backend

X = df.loc[:, df.columns != 'target']
y = df['target']

''' Importing the DataSet '''
x_train, x_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

x_train.shape, y_train.shape, x_test.shape, y_test.shape

((242, 13), (242,), (61, 13), (61,))

In [104]:
def create_model():
    ''' Building the Model '''
    model = Sequential()
    model.add(Dense(13, input_dim=13, activation='relu'))
    model.add(BatchNormalization()) # normalizing the data 
    model.add(Dense(13, activation='relu'))
    model.add(Dense(1, activation='relu'))

    ''' Compiling the model '''
    model.compile(loss='mean_absolute_percentage_error',
                  optimizer='adam',
                  metrics=['accuracy'])
    return model

In [106]:
''' Fitting the model '''
fitting = create_model().fit(x_train, y_train, epochs=150)
scores = create_model().evaluate(x_test, y_test)
print((scores[1]*100))

Epoch 1/150
242/242 [==============================] - 0s 1ms/step - loss: 41364459.4380 - accuracy: 0.4545
Epoch 2/150
242/242 [==============================] - 0s 134us/step - loss: 10742617.9876 - accuracy: 0.4587
Epoch 3/150
242/242 [==============================] - 0s 128us/step - loss: 4708546.8345 - accuracy: 0.4587
Epoch 4/150
242/242 [==============================] - 0s 135us/step - loss: 2361722.3020 - accuracy: 0.4628
Epoch 5/150
242/242 [==============================] - 0s 130us/step - loss: 2131711.9894 - accuracy: 0.4587
Epoch 6/150
242/242 [==============================] - 0s 128us/step - loss: 1089782.1318 - accuracy: 0.4587
Epoch 7/150
242/242 [==============================] - 0s 135us/step - loss: 1543579.2389 - accuracy: 0.4587
Epoch 8/150
242/242 [==============================] - 0s 126us/step - loss: 2328210.7291 - accuracy: 0.4628
Epoch 9/150
242/242 [==============================] - 0s 132us/step - loss: 1585272.1259 - accuracy: 0.4587
Epoch 10/150
242/24

In [108]:
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV

model = KerasClassifier(build_fn=create_model, verbose=0)
param_grid = {'batch_size': [10],
              'epochs': [5],
              #'momentum' : [.01, .1, .2, .3, ],
             # 'lr' : [.01]
             }

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X, y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Best: 0.45214521884918213 using {'batch_size': 10, 'epochs': 5}
