<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:**
Neuron takes one or more inputs that are multiplied by values called “weights” and added together. This value is then passed to a non-linear function, known as an activation function, to become the neuron's output.
Its basic building bock of any Neural Network.
- **Input Layer:**
Its the first layer of neural Net, where the inputs of data are fed. 
- **Hidden Layer:**
Hidden layers reside in-between input and output layers,where artificial neurons take in a set of weighted inputs and produce an output through an activation function.
- **Output Layer:**
The output layer in an artificial neural network is the last layer of neurons that produces given outputs for the program.
- **Activation:**
Activation functions are mathematical equations that determine the output of a neural network. The function is attached to each neuron in the network, and determines whether it should be activated (“fired”) or not, based on whether each neuron's input is relevant for the model's prediction.
- **Backpropagation:**
Backpropagation is used to update the weights by calculating a gradient. The gradient gives a direction in which to adjust the weight. The gradient and the error determine how much to move the weight. This is were the learning takes place and it happens after every epoch


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [18]:
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. You will not be able to achieve more than ~50% with the simple perceptron. Explain why you could not achieve a higher accuracy with the *simple perceptron* architecture, because it's possible to achieve ~95% accuracy on this dataset. Provide your answer in markdown (and *optional* data anlysis code) after your perceptron implementation. 

In [40]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
#y = candy['ate'].values
y = candy.as_matrix(columns = ['ate'])

/Users/karthikmahendra/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """


In [41]:
X

array([[0, 1],
       [1, 0],
       [0, 1],
       ...,
       [0, 1],
       [0, 1],
       [1, 0]])

In [50]:
type(X[0][0])

numpy.int64

In [42]:
y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

In [53]:
type(y[0][0])

numpy.int64

In [43]:
class Perceptron():
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 2
        self.outputNodes = 1
        # Initial Weights
        # 2x1 Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.outputNodes)
    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        # Weighted sum of inputs => output layer
        self.output_sum = np.dot(X, self.weights1)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X,y,o):
        # Error in Output
        self.o_error = y - o
        
        self.adjustments = self.o_error * self.sigmoidPrime(o)
        
        # Adjustment to first set of weights (input => output)
        self.weights1 += np.dot(X.T, self.adjustments)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
        
        
    

In [44]:
per = Perceptron()

In [69]:
# Number of Epochs / Iterations
for i in range(100):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 10 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(per.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - per.feed_forward(X)))))
        print("Accuracy: \n",str(1-np.mean(np.square(y - per.feed_forward(X)))))
    per.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[1.51506346e-45]
 [3.43243876e-80]
 [1.51506346e-45]
 ...
 [1.51506346e-45]
 [1.51506346e-45]
 [3.43243876e-80]]
Loss: 
 0.54885
Accuracy: 
 0.45115000000000005
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[1.51506346e-45]
 [3.43243876e-80]
 [1.51506346e-45]
 ...
 [1.51506346e-45]
 [1.51506346e-45]
 [3.43243876e-80]]
Loss: 
 0.54885
Accuracy: 
 0.45115000000000005
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[1.51506346e-45]
 [3.43243876e-80]
 [1.51506346e-45]
 ...
 [1.51506346e-45]
 [1.51506346e-45]
 [3.43243876e-80]]
Loss: 
 0.54885
Accuracy: 
 0.45115000000000005
+---------EPOCH 4---------+
Input: 
 [[0

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [77]:
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 2
        self.hiddenNodes = 25
        self.outputNodes = 1
        # Initial Weights
        # 3x4 Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        # 4x1 Matrix Array for the First Layer
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X,y,o):
        # Error in Output
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [78]:
nn = NeuralNetwork()

In [79]:
# Number of Epochs / Iterations
for i in range(100):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
        print("Accuracy: \n",str(1-np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.99945737]
 [0.99936087]
 [0.99945737]
 ...
 [0.99945737]
 [0.99945737]
 [0.99936087]]
Loss: 
 0.4986126356639787
Accuracy: 
 0.5013873643360214
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[6.78547871e-22]
 [4.39647226e-21]
 [6.78547871e-22]
 ...
 [6.78547871e-22]
 [6.78547871e-22]
 [4.39647226e-21]]
Loss: 
 0.5
Accuracy: 
 0.5
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[6.78547871e-22]
 [4.39647226e-21]
 [6.78547871e-22]
 ...
 [6.78547871e-22]
 [6.78547871e-22]
 [4.39647226e-21]]
Loss: 
 0.5
Accuracy: 
 0.5
+---------EPOCH 4---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Ou

**Accuracy of MLP is better than Simple Perceptron because we have an extra hidden layer. Hidden layer adds more complexity to model, hence its able to give more accurate predictions.

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [108]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
233   64    1   0       120   246    0        0       96      1      2.2   
105   68    0   2       120   211    0        0      115      0      1.5   
144   76    0   2       140   197    0        2      116      0      1.1   
163   38    1   2       138   175    0        1      173      0      0.0   
61    54    1   1       108   309    0        1      156      0      0.0   

     slope  ca  thal  target  
233      0   1     2       0  
105      1   0     2       1  
144      1   0     2       1  
163      2   4     2       1  
61       2   0     3       1

In [109]:
# Split traget out of df
X = df.drop('target', axis=1).values.astype('float32')
y = df['target'].values.reshape(-1,1)
X.shape, y.shape

((303, 13), (303, 1))

In [110]:
# Baseline
df['target'].value_counts(normalize=True)

1    0.544554
0    0.455446
Name: target, dtype: float64

In [111]:
#from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [112]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
seed = 42
np.random.seed(seed)

In [113]:
#X_train.shape,X_test.shape
num_inputs = X.shape[1]
num_inputs

13

In [120]:
def create_model( hidden_1_nodes=13,optimizer='adam',init_mode = 'uniform'):
    # create model
    model = Sequential()
    model.add(Dense(hidden_1_nodes, input_dim=num_inputs, activation='relu'))
    model.add(Dense(7, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

In [121]:
model.fit(X, y,  
          epochs=20, 
          batch_size=10,
          verbose=True,
         )

Train on 303 samples
Epoch 1/20
303/303 [==============================] - 0s 1ms/sample - loss: 4.9041 - accuracy: 0.5413
Epoch 2/20
303/303 [==============================] - 0s 227us/sample - loss: 1.3630 - accuracy: 0.4818
Epoch 3/20
303/303 [==============================] - 0s 161us/sample - loss: 1.0423 - accuracy: 0.5149
Epoch 4/20
303/303 [==============================] - 0s 140us/sample - loss: 0.7656 - accuracy: 0.5743
Epoch 5/20
303/303 [==============================] - 0s 138us/sample - loss: 0.7092 - accuracy: 0.6337
Epoch 6/20
303/303 [==============================] - 0s 145us/sample - loss: 0.6230 - accuracy: 0.6469
Epoch 7/20
303/303 [==============================] - 0s 137us/sample - loss: 0.5443 - accuracy: 0.7360
Epoch 8/20
303/303 [==============================] - 0s 131us/sample - loss: 0.5305 - accuracy: 0.7228
Epoch 9/20
303/303 [==============================] - 0s 140us/sample - loss: 0.5778 - accuracy: 0.7030
Epoch 10/20
303/303 [========================

In [116]:
param_grid = {'batch_size': [5, 10, 100],
             'epochs': [20, 50, 100],
             'optimizer': ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']}

In [117]:
%%time
# Create Grid Search

grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=1)
grid_result = grid.fit(X, y,verbose=False)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Mean: {mean}, Stdev: {stdev} with: {param}")
                       
        

Best: 0.8052805264790853 using {'batch_size': 5, 'epochs': 50, 'optimizer': 'Adam'}
Mean: 0.5445544719696045, Stdev: 0.029147716944745876 with: {'batch_size': 5, 'epochs': 20, 'optimizer': 'SGD'}
Mean: 0.7656765580177307, Stdev: 0.05197366159998095 with: {'batch_size': 5, 'epochs': 20, 'optimizer': 'RMSprop'}
Mean: 0.5346534649531046, Stdev: 0.12934597880363888 with: {'batch_size': 5, 'epochs': 20, 'optimizer': 'Adagrad'}
Mean: 0.5016501744588217, Stdev: 0.06121201287978154 with: {'batch_size': 5, 'epochs': 20, 'optimizer': 'Adadelta'}
Mean: 0.726072629292806, Stdev: 0.004667370101995413 with: {'batch_size': 5, 'epochs': 20, 'optimizer': 'Adam'}
Mean: 0.6567656795183817, Stdev: 0.06584137467860096 with: {'batch_size': 5, 'epochs': 20, 'optimizer': 'Adamax'}
Mean: 0.5940594176451365, Stdev: 0.10321119961528105 with: {'batch_size': 5, 'epochs': 20, 'optimizer': 'Nadam'}
Mean: 0.5742574334144592, Stdev: 0.06617139168454245 with: {'batch_size': 5, 'epochs': 50, 'optimizer': 'SGD'}
Mean: 0.

In [122]:
param_grid = {'batch_size': [5, 10, 100],
             'epochs': [20, 50, 100],
             'optimizer': ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam'],
             'init_mode': ['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']}

In [ ]:
%%time
# Create Grid Search

grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, n_jobs=1)
grid_result = grid.fit(X, y,verbose=False)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Mean: {mean}, Stdev: {stdev} with: {param}")