<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Neural Network Framework (Keras)

## *Data Science Unit 4 Sprint 2 Assignment 3*

## Use the Keras Library to build a Multi-Layer Perceptron Model on the Boston Housing dataset

- The Boston Housing dataset comes with the Keras library so use Keras to import it into your notebook. 
- Normalize the data (all features should have roughly the same scale)
- Import the type of model and layers that you will need from Keras.
- Instantiate a model object and use `model.add()` to add layers to your model
- Since this is a regression model you will have a single output node in the final layer.
- Use activation functions that are appropriate for this task
- Compile your model
- Fit your model and report its accuracy in terms of Mean Squared Error
- Use the history object that is returned from model.fit to make graphs of the model's loss or train/validation accuracies by epoch. 
- Run this same data through a linear regression model. Which achieves higher accuracy?
- Do a little bit of feature engineering and see how that affects your neural network model. (you will need to change your model to accept more inputs)
- After feature engineering, which model sees a greater accuracy boost due to the new features?

In [24]:
##### Your Code Here #####
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.datasets import boston_housing
import numpy as np

In [6]:
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

57344/57026 [==============================] - 0s 1us/step


In [9]:
print(f"The shape of the x train is:  {x_train.shape}")
print(f"The shape of the y_train is: {y_train.shape}")
print(f"The shape of the x_test is : {x_test.shape}")
print(f"The shape of the y_test is: {y_test.shape}")

The shape of the x train is:  (404, 13)
The shape of the y_train is: (404,)
The shape of the x_test is : (102, 13)
The shape of the y_test is: (102,)


In [12]:
# looking at the shape of one row of the data
# and what is in it
x_train[:1]

array([[  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
         91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
         18.72   ]])

In [18]:
type(x_train)

numpy.ndarray

In [27]:
# function that will do the normalization
def normalization(num_array):
     arr =  num_array/np.amax(num_array, axis=0)
     return arr

In [28]:
# Doing the normalization
x_train_norm = normalization(x_train)
x_test_norm = normalization(x_test)

In [26]:
trying[0]

array([0.01385168, 0.        , 0.29343908, 0.        , 0.61768083,
       0.70395415, 0.917     , 0.37131546, 0.16666667, 0.43178622,
       0.95454545, 1.        , 0.49302081])

In [29]:
# Becuase it is a set of continuous numbers we will do a regression
y_train[:5]

array([15.2, 42.3, 50. , 21.1, 17.7])

In [5]:
# Instanciating the model
model = Sequential()

In [ ]:
# Builing the model
# adding layers to the model
model.add(Dense())

## Use the Keras Library to build an image recognition network using the Fashion-MNIST dataset (also comes with keras)

- Load and preprocess the image data similar to how we preprocessed the MNIST data in class.
- Make sure to one-hot encode your category labels
- The number of nodes in your output layer should equal the number of classes you want to predict for Fashion-MNIST.
- Try different hyperparameters. What is the highest accuracy that you are able to achieve.
- Use the history object that is returned from model.fit to make graphs of the model's loss or train/validation accuracies by epoch. 
- Remember that neural networks fall prey to randomness so you may need to run your model multiple times (or use Cross Validation) in order to tell if a change to a hyperparameter is truly producing better results.

In [ ]:
##### Your Code Here #####

## Stretch Goals:

- Use Hyperparameter Tuning to make the accuracy of your models as high as possible. (error as low as possible)
- Use Cross Validation techniques to get more consistent results with your model.
- Use GridSearchCV to try different combinations of hyperparameters. 
- Start looking into other types of Keras layers for CNNs and RNNs maybe try and build a CNN model for fashion-MNIST to see how the results compare.