<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** Node in a neural network which takes input and "fires" depending on the activation function.
- **Input Layer:** Initial layer with the data we want to analyze.
- **Hidden Layer:** Layers between the input and output layers which performs transformation of data from the prior layer.
- **Output Layer:** Final layer which provides the results of the training done in the hidden layers. This is where the predictions are.
- **Activation:** Function associated with each neuron which decides if and what information gets passed to the next layer.
- **Backpropagation:** This is how neural nets improve. Neurons have a weight associated to them. By looking at errors (eg mae, mse, accuracy) between the NN predction and the expected true values adjustments to these weights (ie usefulness of a particular neuron to getting correct results) are fed backward through the NN.


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [1]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [2]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

In [3]:
candy.shape

(10000, 3)

In [4]:
candy.isnull().sum()

chocolate    0
gummy        0
ate          0
dtype: int64

In [5]:
candy.describe()

chocolate         gummy           ate
count  10000.000000  10000.000000  10000.000000
mean       0.499100      0.499300      0.500000
std        0.500024      0.500025      0.500025
min        0.000000      0.000000      0.000000
25%        0.000000      0.000000      0.000000
50%        0.000000      0.000000      0.500000
75%        1.000000      1.000000      1.000000
max        1.000000      1.000000      1.000000

In [6]:
for col in candy.columns:
    print(f"{col}: ", candy[col].unique())

chocolate:  [0 1]
gummy:  [1 0]
ate:  [1 0]


### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. Explain why you could not achieve a higher accuracy with a *simple perceptron*. It's possible to achieve ~95% accuracy on this dataset.

In [211]:
# Start your candy perceptron here
import numpy as np
X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

In [212]:
X.shape, y.shape

((10000, 2), (10000,))

In [213]:
y = np.reshape(y, (-1,1))

In [214]:
y.shape

(10000, 1)

In [132]:
np.unique(y)

array([0, 1])

In [233]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [261]:
weights = 2 * np.random.random((2,1)) - 1
weights

array([[-0.61894498],
       [-0.72972321]])

In [235]:
weighted_sum = np.dot(X, weights)
weighted_sum

array([[-0.12373798],
       [-0.54847875],
       [-0.12373798],
       ...,
       [-0.12373798],
       [-0.12373798],
       [-0.54847875]])

In [262]:
%%time
for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(X, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Calc error
    error = y - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(X.T, adjustments)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


CPU times: user 11.9 s, sys: 32.1 s, total: 44 s
Wall time: 6.11 s


In [263]:
# convert values less than 1 to 0
activated_output = np.where(activated_output >= .5, 1, 0)

In [264]:
print(f"Final weights are \n{weights}")
print(f"Final predictions are\n {activated_output}")

Final weights are 
[[454.66889998]
 [135.79076426]]
Final predictions are
 [[1]
 [0]
 [1]
 ...
 [1]
 [1]
 [0]]


In [265]:
np.unique(activated_output)

array([0, 1])

In [266]:
from sklearn.metrics import accuracy_score
print(f'Accuracy is {accuracy_score(y, activated_output.astype(int))}')

Accuracy is 0.4993


### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [198]:
# I want activations that correspond to negative weights to be lower
# and activations that correspond to positive weights to be higher

class NeuralNetwork(object):
    
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 2
        self.hiddenNodes =  64
        self.outputNodes = 1

        # Initial Weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
       
        # Weights for Hidden to Output
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        """Activation function to push to 1 or 0.
        """
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        """Derivative of above.
        """
        return s * (1-s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward pass.
        """
        
        # Weighted sum of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activation of the weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted sum of hidden layer to output layer
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Activation of Output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """Send the error back and adjust the weights.
        """
        self.o_error = y - o #error in output
        
        #Size of Adjustment from hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivate of sigmoid to error
        
        # z2 error: how much our input => hidden weights weights were off
        self.z2_error = self.o_delta.dot(self.weights2.T)
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        #Adjustment hidden => output weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        
        #Adjustment input => hidden weights
        self.weights1 += X.T.dot(self.z2_delta)
        
    def train(self, X, y):
        """Train the net forward and back.
        """
        o = self.feed_forward(X) #o is output layer
        self.backward(X, y, o)


In [201]:
nn = NeuralNetwork()

In [165]:
np.unique(y), np.unique(X)

(array([0, 1]), array([0, 1]))

In [159]:
# cost = []
# for _ in range(1000):
#     cost.append(np.mean(np.square(y - nn.feed_forward(X))))
#     nn.train(X,y)

In [202]:
print("Predicted Output: \n" + str(nn.feed_forward(X))) 
print("Loss: \n" + str(np.mean(np.square(y - nn.feed_forward(X)))))

Predicted Output: 
[[0.8752232 ]
 [0.76694834]
 [0.8752232 ]
 ...
 [0.8752232 ]
 [0.8752232 ]
 [0.76694834]]
Loss: 
0.3619278515280812


In [195]:
print(f'Accuracy is {accuracy_score(y,np.round(nn.feed_forward(X)))}')


Accuracy is 0.5


In [197]:
%%time
for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 200 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print("Loss: ", str(np.mean(np.square(y - nn.feed_forward(X)))))
        print("Accuracy: ", str(accuracy_score(y, nn.feed_forward(X))))
#         print("ff: ", nn.feed_forward(X))
    nn.train(X, y)

+---------EPOCH 1---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 2---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 3---------+
Loss:  0.5
Accuracy:  0.5


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: overflow encountered in exp


+---------EPOCH 4---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 5---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 200---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 400---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 600---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 800---------+
Loss:  0.5
Accuracy:  0.5
+---------EPOCH 1000---------+
Loss:  0.5
Accuracy:  0.5


P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [108]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
72    29    1   1       130   204    0        0      202      0      0.0   
165   67    1   0       160   286    0        0      108      1      1.5   
127   67    0   2       152   277    0        1      172      0      0.0   
129   74    0   1       120   269    0        0      121      1      0.2   
281   52    1   0       128   204    1        1      156      1      1.0   

     slope  ca  thal  target  
72       2   0     2       1  
165      1   3     2       0  
127      2   1     2       1  
129      2   1     2       1  
281      1   0     0       0

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. 

In [115]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier

In [110]:
scaler = StandardScaler()

X = scaler.fit_transform(df.iloc[:,:13])
y = df.target.values.reshape(-1,1)
     
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [111]:
print(X_train.shape, X_test.shape, y_test.shape, y_train.shape)

(242, 13) (61, 13) (61, 1) (242, 1)


In [112]:
model = Sequential()
model.add(Dense(20, input_dim=13, activation='relu'))
model.add(Dense(20, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['mae','accuracy'])

In [113]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 20)                280       
_________________________________________________________________
dense_4 (Dense)              (None, 20)                420       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 21        
Total params: 721
Trainable params: 721
Non-trainable params: 0
_________________________________________________________________


Train your model and report its baseline accuracy. 

In [114]:
%%time
fit = model.fit(X_train, y_train, epochs=150, verbose=False)

scores = model.evaluate(X_train, y_train, verbose=False)
print("Train Loss, MAE, Accuracy", scores)
scores = model.evaluate(X_test, y_test, verbose=False)
print("Test Loss, MAE, Accuracy ", scores)

Train Loss, MAE, Accuracy [0.10636305599665839, 0.08100721, 0.9710744]
Test Loss, MAE, Accuracy  [0.583517811826018, 0.21942833, 0.8196721]
CPU times: user 5.32 s, sys: 1.52 s, total: 6.84 s
Wall time: 4.25 s


Then hyperparameter tune at least two parameters and report your model's accuracy.

Use the Heart Disease Dataset (binary classification)

Use an appropriate loss function for a binary classification task

Use an appropriate activation function on the final layer of your network.

Train your model using verbose output for ease of grading.

Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)

In [119]:
%%time
# BATCH SIZE TUNING
# fix random seed for reproducibility
seed = 7
np.random.seed(seed)

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(12, input_dim=13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train, verbose=True)

# Report Results
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

Train on 161 samples
Epoch 1/20
161/161 [==============================] - 1s 4ms/sample - loss: 0.8118 - accuracy: 0.4596
Epoch 2/20
161/161 [==============================] - 0s 261us/sample - loss: 0.7698 - accuracy: 0.4845
Epoch 3/20
161/161 [==============================] - 0s 258us/sample - loss: 0.7389 - accuracy: 0.5093
Epoch 4/20
161/161 [==============================] - 0s 263us/sample - loss: 0.7129 - accuracy: 0.5466
Epoch 5/20
161/161 [==============================] - 0s 258us/sample - loss: 0.6890 - accuracy: 0.5590
Epoch 6/20
161/161 [==============================] - 0s 256us/sample - loss: 0.6667 - accuracy: 0.5901
Epoch 7/20
161/161 [==============================] - 0s 259us/sample - loss: 0.6475 - accuracy: 0.6211
Epoch 8/20
161/161 [==============================] - 0s 274us/sample - loss: 0.6302 - accuracy: 0.6335
Epoch 9/20
161/161 [==============================] - 0s 266us/sample - loss: 0.6145 - accuracy: 0.6522
Epoch 10/20
161/161 [========================

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


242/242 [==============================] - 0s 2ms/sample - loss: 0.7345 - accuracy: 0.5702
Epoch 2/20
242/242 [==============================] - 0s 146us/sample - loss: 0.6973 - accuracy: 0.6157
Epoch 3/20
242/242 [==============================] - 0s 139us/sample - loss: 0.6690 - accuracy: 0.6446
Epoch 4/20
242/242 [==============================] - 0s 144us/sample - loss: 0.6418 - accuracy: 0.6612
Epoch 5/20
242/242 [==============================] - 0s 144us/sample - loss: 0.6165 - accuracy: 0.6818
Epoch 6/20
242/242 [==============================] - 0s 141us/sample - loss: 0.5945 - accuracy: 0.6942
Epoch 7/20
242/242 [==============================] - 0s 139us/sample - loss: 0.5734 - accuracy: 0.7231
Epoch 8/20
242/242 [==============================] - 0s 140us/sample - loss: 0.5555 - accuracy: 0.7355
Epoch 9/20
242/242 [==============================] - 0s 139us/sample - loss: 0.5377 - accuracy: 0.7397
Epoch 10/20
242/242 [==============================] - 0s 143us/sample - loss

When hyperparameter tuning, show you work by adding code cells for each new experiment.

In [120]:
%%time
# TUNING THE EPOCHS
param_grid = {'batch_size': [20],
              'epochs': [20, 40, 80, 160]}
# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train, verbose=True)

# Report Results
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

Train on 161 samples
Epoch 1/20
161/161 [==============================] - 0s 2ms/sample - loss: 0.5731 - accuracy: 0.7391
Epoch 2/20
161/161 [==============================] - 0s 164us/sample - loss: 0.5591 - accuracy: 0.7516
Epoch 3/20
161/161 [==============================] - 0s 158us/sample - loss: 0.5463 - accuracy: 0.7578
Epoch 4/20
161/161 [==============================] - 0s 153us/sample - loss: 0.5361 - accuracy: 0.7826
Epoch 5/20
161/161 [==============================] - 0s 142us/sample - loss: 0.5284 - accuracy: 0.7826
Epoch 6/20
161/161 [==============================] - 0s 138us/sample - loss: 0.5223 - accuracy: 0.7888
Epoch 7/20
161/161 [==============================] - 0s 141us/sample - loss: 0.5155 - accuracy: 0.7888
Epoch 8/20
161/161 [==============================] - 0s 144us/sample - loss: 0.5096 - accuracy: 0.7826
Epoch 9/20
161/161 [==============================] - 0s 141us/sample - loss: 0.5035 - accuracy: 0.7888
Epoch 10/20
161/161 [========================

Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.

You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [126]:
def create_model(neurons, activation, optimizer):
    # create model
    model = Sequential()
    model.add(Dense(neurons, input_dim=13, activation=activation))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=0)

In [127]:
%%time
# define the grid search parameters
param_grid = {"batch_size":[20],
              "epochs": [80],
              "neurons": [15, 25, 30],
              "activation": ['relu', 'sigmoid'],
              "optimizer": ['adam', 'SGD']
             }

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1)
grid_result = grid.fit(X_train, y_train, verbose=True)

# Report Results
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")


Train on 161 samples
Epoch 1/80
161/161 [==============================] - 0s 2ms/sample - loss: 0.7105 - accuracy: 0.5404
Epoch 2/80
161/161 [==============================] - 0s 175us/sample - loss: 0.6888 - accuracy: 0.5776
Epoch 3/80
161/161 [==============================] - 0s 167us/sample - loss: 0.6695 - accuracy: 0.5776
Epoch 4/80
161/161 [==============================] - 0s 173us/sample - loss: 0.6514 - accuracy: 0.5963
Epoch 5/80
161/161 [==============================] - 0s 158us/sample - loss: 0.6356 - accuracy: 0.6149
Epoch 6/80
161/161 [==============================] - 0s 165us/sample - loss: 0.6213 - accuracy: 0.6460
Epoch 7/80
161/161 [==============================] - 0s 155us/sample - loss: 0.6085 - accuracy: 0.6894
Epoch 8/80
161/161 [==============================] - 0s 152us/sample - loss: 0.5981 - accuracy: 0.7143
Epoch 9/80
161/161 [==============================] - 0s 161us/sample - loss: 0.5878 - accuracy: 0.7329
Epoch 10/80
161/161 [========================

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


242/242 [==============================] - 0s 2ms/sample - loss: 0.7529 - accuracy: 0.4917
Epoch 2/80
242/242 [==============================] - 0s 135us/sample - loss: 0.6821 - accuracy: 0.6198
Epoch 3/80
242/242 [==============================] - 0s 140us/sample - loss: 0.6279 - accuracy: 0.6694
Epoch 4/80
242/242 [==============================] - 0s 136us/sample - loss: 0.5860 - accuracy: 0.7107
Epoch 5/80
242/242 [==============================] - 0s 141us/sample - loss: 0.5521 - accuracy: 0.7645
Epoch 6/80
242/242 [==============================] - 0s 137us/sample - loss: 0.5256 - accuracy: 0.7934
Epoch 7/80
242/242 [==============================] - 0s 144us/sample - loss: 0.5037 - accuracy: 0.8017
Epoch 8/80
242/242 [==============================] - 0s 143us/sample - loss: 0.4843 - accuracy: 0.8099
Epoch 9/80
242/242 [==============================] - 0s 141us/sample - loss: 0.4658 - accuracy: 0.8099
Epoch 10/80
242/242 [==============================] - 0s 146us/sample - loss