In [1]:
import numpy as np

In [39]:
# fake data
def fake(): 
    X = np.array([[1,9],[1,5],[3,6]], dtype=float)
    y = np.array([[92], [86], [89]], dtype=float)
    return X/np.amax(X, axis=0), y/100

def squish(x: np.number) -> np.number: 
    return np.divide(1, 1 + np.exp(-x))

def del_squish(x: np.number) -> np.number: 
    s = squish(x)
    return s * (1 - s)

X, y = fake()

In [49]:
class NeuralNetwork: 
    def __init__(self, X, y): 
        self.X = X
        self.y = y
        self.inputs = X.shape[1]
        self.hidden_1 = 3
        self.hidden_2 = 3
        self.output_nodes = 1
        # init weights: 
        self.L1_weights = np.random.randn(self.inputs, self.hidden_1)
        self.L2_weights = np.random.randn(self.hidden_1, self.hidden_2)
        self.L3_weights = np.random.randn(self.hidden_2, self.output_nodes)
        self.predictions = self.feed_forward()
        
    def feed_forward(self): 
        hidden_sum_1 = self.X @ self.L1_weights
        self.activated_hidden_1 = squish(hidden_sum_1)
        hidden_sum_2 = self.activated_hidden_1 @ self.L2_weights
        self.activated_hidden_2 = squish(hidden_sum_2)
        hidden_sum_3 = self.activated_hidden_2 @ self.L3_weights
        self.activated_hidden_3 = squish(hidden_sum_3)
        return self.activated_hidden_3

    def loss(self): 
        n = len(self.y)
        assert len(self.predictions)==n
        return np.divide(sum([Y**2 for Y in self.predictions - self.y]), n)
    
    def back(self): 
        ''' will modify values of Lk_weights '''
        output_error = self.predictions - self.y
        del_output_error = output_error * del_squish(self.predictions) # ??????? 
        
        s3_error = del_output_error @ self.L3_weights.T
        del_s3_error = s3_error * del_squish(self.activated_hidden_3)
        
        s2_error = del_s3_error @ self.L2_weights.T
        del_s2_error = s2_error * del_squish(self.activated_hidden_2)
        
        s1_error = del_s2_error @ self.L1_weights.T
        del_s1_error = s1_error * del_squish(self.activated_hidden_1)
        
        self.L1_weights = X.T @ del_s3_error
        self.L2_weights = 
        
        return del_s3_error
    
NN = NeuralNetwork(X,y)

NN.back(), NN.L1_weights

(array([[ 0.04151353, -0.02174404, -0.00131355],
        [ 0.03634194, -0.01903525, -0.00114992],
        [ 0.03861174, -0.02022413, -0.00122174]]),
 array([[ 0.06456357, -0.03381723, -0.00204289],
        [ 0.08744466, -0.04580193, -0.00276689]]),
 array([[0.40561474],
        [0.4054553 ],
        [0.4056714 ]]))