<a href="https://colab.research.google.com/github/ChanceDurr/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module2-backpropagation/Chance_Dare_LS_DS_432_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [0]:
data = {'x1': [0, 0, 1, 0, 1, 1, 0],
        'x2': [0, 1, 0, 1, 0, 1, 0],
        'x3': [1, 1, 1, 0, 0, 1, 0],
        'y':  [0, 1, 1, 1, 1, 0, 0]}

In [0]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data=data)

In [3]:
df.head(10)

x1  x2  x3  y
0   0   0   1  0
1   0   1   1  1
2   1   0   1  1
3   0   1   0  1
4   1   0   0  1
5   1   1   1  0
6   0   0   0  0

In [0]:
X = np.array(df[['x1', 'x2', 'x3']])
y = np.array(df['y']).reshape(-1, 1)

In [0]:
class NeuralNetwork:
  
  def __init__(self):
    self.inputs = 3
    self.hiddenNodes = 4
    self.outputNodes = 1
    
    #initialize weights
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
    self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
    
    
  def sigmoid(self, s):
    return 1 / ( 1 + np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
    
    
  def feed_forward(self, X):
    """Calculate the NN inferences using feed forward"""
    
    self.hidden_sum = np.dot(X, self.weights1)
    
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    
    self.activated_output = self.sigmoid(self.output_sum)
    return self.activated_output
  
  def backward(self, X, y, o):
    
    self.o_error = y - o
    self.o_delta = self.o_error * self.sigmoidPrime(o)
    
    self.z2_error = self.o_delta.dot(self.weights2.T)
    self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
    
    self.weights1 += X.T.dot(self.z2_delta)
    self.weights2 += self.activated_hidden.T.dot(self.o_delta)
    
  def train(self, X, y):
    o = self.feed_forward(X)
    self.backward(X, y, o)

In [6]:
nn = NeuralNetwork()
output = nn.feed_forward(X[0])

print('Layer 1 weights: \n', nn.weights1)
print('Layer 12 weights: \n', nn.weights2)

Layer 1 weights: 
 [[-1.55604419  1.12157407  1.72988097 -0.72776259]
 [-1.48363817 -1.60383726  0.29485875 -0.7985304 ]
 [-2.28476198 -0.77639705  0.08451211 -1.2466157 ]]
Layer 12 weights: 
 [[-0.69982163]
 [ 0.59793369]
 [ 1.79368355]
 [ 0.27699478]]


In [7]:
print(output)

[0.75404695]


In [8]:
error = y[0] - output
error

array([-0.75404695])

In [9]:
output_all = nn.feed_forward(X)
error_all = y - output_all
print(output_all)
print(error_all)

[[0.75404695]
 [0.75611989]
 [0.87118649]
 [0.74740411]
 [0.87466529]
 [0.85129164]
 [0.72797945]]
[[-0.75404695]
 [ 0.24388011]
 [ 0.12881351]
 [ 0.25259589]
 [ 0.12533471]
 [-0.85129164]
 [-0.72797945]]


In [10]:
nn = NeuralNetwork()
for i in range(1000):
  if i+1 in [1, 2, 3, 4, 5] or (i+1) % 50 == 0:
    print('+--------- EPOCH', i+1, '---------+')
    print('Input: \n', X)
    print('Actual Output: \n', y)
    print('Predicted Output: \n' + str(nn.feed_forward(X)))
    print('Loss: \n' + str(np.mean(np.square(y - nn.feed_forward(X)))))
    print('\n')
  nn.train(X, y)

+--------- EPOCH 1 ---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.33531615]
 [0.41398567]
 [0.32224752]
 [0.38526702]
 [0.27269249]
 [0.4221057 ]
 [0.28929307]]
Loss: 
0.2977049551590519


+--------- EPOCH 2 ---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.40833256]
 [0.47527818]
 [0.40761324]
 [0.43225033]
 [0.33674295]
 [0.49137265]
 [0.34093141]]
Loss: 
0.2732744930031318


+--------- EPOCH 3 ---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.45948369]
 [0.51687387]
 [0.47474799]
 [0.46624378]
 [0.39284218]
 [0.54064535]
 [0.37995707]]
Loss: 
0.2586609838755799


+--------- EPOCH 4 ---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [11]:
!curl -O http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
!curl -O http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
!curl -O http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
!curl -O http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9680k  100 9680k    0     0   468k      0  0:00:20  0:00:20 --:--:--  609k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28881  100 28881    0     0  21996      0  0:00:01  0:00:01 --:--:-- 21979
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1610k  100 1610k    0     0  35474      0  0:00:46  0:00:46 --:--:-- 25662
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4542  100  4542    0     0  11828      0 --:--:-- --:--:-- --:--:-- 11828


In [0]:
!gunzip t*-ubyte.gz

In [0]:
from mlxtend.data import loadlocal_mnist

In [0]:
X, y = loadlocal_mnist(
        images_path='/content/train-images-idx3-ubyte', 
        labels_path='/content/train-labels-idx1-ubyte')

In [16]:
print(y.reshape(-1, 1))

[[5]
 [0]
 [4]
 ...
 [5]
 [6]
 [8]]


In [0]:
class NeuralNetwork:
  
  def __init__(self):
    self.inputs = 784
    self.hiddenNodes = 4
    self.outputNodes = 1
    
    #initialize weights
    self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
    self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
    
    
  def sigmoid(self, s):
    return 1 / ( 1 + np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
    
    
  def feed_forward(self, X):
    """Calculate the NN inferences using feed forward"""
    
    self.hidden_sum = np.dot(X, self.weights1)
    
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    
    self.activated_output = self.sigmoid(self.output_sum)
    return self.activated_output
  
  def backward(self, X, y, o):
    
    self.o_error = y - o
    self.o_delta = self.o_error * self.sigmoidPrime(o)
    
    self.z2_error = self.o_delta.dot(self.weights2.T)
    self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
    
    self.weights1 += X.T.dot(self.z2_delta)
    self.weights2 += self.activated_hidden.T.dot(self.o_delta)
    
  def train(self, X, y):
    o = self.feed_forward(X)
    self.backward(X, y, o)

## Run the cell below to run out of memoryyyy

In [0]:
# nn = NeuralNetwork()
# for i in range(1000):
#   if i+1 in [1, 2, 3, 4, 5] or (i+1) % 50 == 0:
#     print('+--------- EPOCH', i+1, '---------+')
#     print('Input: \n', X)
#     print('Actual Output: \n', y)
#     print('Predicted Output: \n' + str(nn.feed_forward(X)))
#     print('Loss: \n' + str(np.mean(np.square(y - nn.feed_forward(X)))))
#     print('\n')
#   nn.train(X, y)

+--------- EPOCH 1 ---------+
Input: 
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Actual Output: 
 [5 0 4 ... 5 6 8]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


Predicted Output: 
[[0.30622033]
 [0.52577373]
 [0.28666064]
 ...
 [0.30622033]
 [0.33367926]
 [0.47081299]]


## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?