<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Backpropagation-Practice" data-toc-modified-id="Backpropagation-Practice-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Backpropagation Practice</a></span><ul class="toc-item"><li><span><a href="#Data-Science-Unit-4-Sprint-2-Assignment-2" data-toc-modified-id="Data-Science-Unit-4-Sprint-2-Assignment-2-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span><em>Data Science Unit 4 Sprint 2 Assignment 2</em></a></span></li><li><span><a href="#Try-building/training-a-more-complex-MLP-on-a-bigger-dataset." data-toc-modified-id="Try-building/training-a-more-complex-MLP-on-a-bigger-dataset.-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Try building/training a more complex MLP on a bigger dataset.</a></span></li><li><span><a href="#Stretch-Goals:" data-toc-modified-id="Stretch-Goals:-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Stretch Goals:</a></span></li></ul></li></ul></div>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
# Set data as arrays

import numpy as np

X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
    [1, 1, 1],
    [0, 0, 0]
])

y = np.array([
    [0],
    [1],
    [1],
    [1],
    [1],
    [0],
    [0]
])

In [2]:
# I want activations that correspond to negative weights to be lower
# and activations that correspond to positive weights to be higher

# create neural network class.
class NeuralNetwork:
  # __init__ function.
    def __init__(self):
        # set up architecture of neural network.
        
        # set input nodes.
        self.inputs = 3
        # set hidden nodes.
        self.hiddenNodes = 4
        # set output nodes.
        self.outputNodes = 1

        # create initial weights.
        # 2x3 matrix array for the first Layer.
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
        
        # 3x1 matrix array for hidden to output.
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    # create sigmoid function.    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    # create sigmoidprime function.
    def sigmoidPrime(self, x):
        s = self.sigmoid(x)
        return s * (1 - s)
    
    # create feedforward function.
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        # weighted sum of inputs => hidden layer.
        self.hidden_sum = np.dot(X, self.weights1)
        # activations of weighted sum.
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        # weight sum between hidden and output.
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        # final activation of output.
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output

    # create backward pass function.    
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        # error in output.
        self.o_error = y - o 
        
        # apply derivative of sigmoid to error.
        # how far off are we in relation to the Sigmoid f(x) of the output.
        # ^- aka hidden => output.
        self.o_delta = self.o_error * self.sigmoidPrime(o) # scale by sigmoidprime derivative.
        
        # z2 error.
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # how much of that "far off" can explained by the input => hidden.
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # adjustment to first set of weights (input => hidden).
        self.weights1 = self.weights1 + X.T.dot(self.z2_delta)
        
        # adjustment to second set of weights (hidden => output).
        self.weights2 = self.weights2 + self.activated_hidden.T.dot(self.o_delta)
        
  # create train function, performs 1 epoch of the training process.
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [3]:
# set the neuralnetwork class.
nn = NeuralNetwork()

# for loop for number of epochs / iterations, #10000 times.
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
        
    # train the nueralnetwork class on X,y data.
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.65108862]
 [0.66221205]
 [0.67598   ]
 [0.65219666]
 [0.66548401]
 [0.68583058]
 [0.63966239]]
Loss: 
 0.2507722442174635
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.59941691]
 [0.60326575]
 [0.61958545]
 [0.60302317]
 [0.61937764]
 [0.62334202]
 [0.5997161 ]]
Loss: 
 0.24458465460904905
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.57903837]
 [0.58053674]
 [0.59771131]
 [0.58484127]
 [0.60230094]
 [0.59944358]
 [0.58465737]]
Loss: 
 0.2435356000077249
+---------EPOCH 4---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [4]:
# imports.
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [5]:
# input the given image dimensions.
img_rows, img_cols = 28, 28

In [7]:
# split data between train and test sets.
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [9]:
# show all dataframe shapes.
print('x train:', x_train.shape)
print('y train:', y_train.shape)
print('x test:', x_test.shape)
print('y test:', y_test.shape)

x train: (60000, 28, 28)
y train: (60000,)
x test: (10000, 28, 28)
y test: (10000,)


In [11]:
# reshape the x_train data by dimensions.
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
# reshape the x_test data by dimensions.
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# normalize the data sets.
x_train = x_train / 255
x_test = x_test / 255

In [13]:
# check its in correct format.
x_train.shape

(60000, 784)

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?

# Bonus Questions Chris Shared with us:

1. Investigate the various loss functions. Which is best suited for the task at hand (predicting 1 / 0) and why?
2. What is the difference between a loss function and a metric? Why might we need both in Keras?
3. Investigate the various optimizers. Stochastic Gradient Descent (sgd) is not the learning algorithm dejour anyone. Why is that? What do newer optimizers such as adam have to offer?

### Answers

1.

2.

3.