<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [19]:
##### Your Code Here #####
import numpy as np

# XOR inputs and noise
X = np.array(([0,0,1],
              [0,1,1],
              [1,0,1],
              [0,1,0],
              [1,0,0],
              [1,1,1],
              [0,0,0]), dtype=float)

# XOR outputs
y = np.array(([0],
              [1],
              [1],
              [1],
              [1],
              [0],
              [0]), dtype=float)

print(type(X))

<class 'numpy.ndarray'>


In [20]:
class NeuralNetwork:
    """a basic neural network with a single hidden layer."""
    
    def __init__(self, inputcount, hiddencount, outputcount):
        """initialize the structure and weights of the NN."""
        # define node quantities for layers
        self.input_nodes = inputcount
        self.hidden_nodes = hiddencount
        self.output_nodes = outputcount
        
        # define the initial weights and biases
        # input-to-hidden
        self.first_weights = np.random.rand(self.input_nodes, self.hidden_nodes)
        self.first_biases = np.ones((1, self.hidden_nodes))
        # hidden-to-output
        self.second_weights = np.random.rand(self.hidden_nodes,self.output_nodes)
        self.second_biases = np.ones((1,self.output_nodes))
        
    def sigmoid(self, s):
        """sigmoid activation function."""
        return 1 / (1+np.exp(-s))
    
    def d_sigmoid(self, s):
        """derivative of the sigmoid function."""
        return s * (1 - s)
    
    def forward_pass(self, X):
        """prediction function."""
        # transform and sum the inputs
        self.first_sum = np.dot(X, self.first_weights) + self.first_biases
        
        # activate the first sum
        self.first_activation = self.sigmoid(self.first_sum)
        
        # transform and sum the intermediates
        self.second_sum = np.dot(self.first_activation, self.second_weights) + self.second_biases
        
        # activate the second sum
        self.second_activation = self.sigmoid(self.second_sum)
        
        return self.second_activation
    
    def backprop(self, X, y, y_hat, alpha):
        """backpropagate errors to correct weights."""
        # get output error
        self.y_hat_error = y - y_hat
        
        # use grad to get direction of output error
        self.y_hat_grad = self.y_hat_error * self.d_sigmoid(y_hat)
        
        # get error in hidden layers
        self.hidden_error = self.y_hat_grad.dot(self.second_weights.T)
        
        # use grad to get direction of hidden layer error
        self.hidden_grad = self.hidden_error * self.d_sigmoid(self.first_activation)
        
        # adjust the first weights and biases
        self.first_weights = self.first_weights + alpha*X.T.dot(self.hidden_grad)
        self.first_biases = self.first_biases + alpha*np.sum(self.hidden_grad, axis=0, keepdims=True)
        
        # adjust the second weights and biases
        self.second_weights = self.second_weights + alpha*self.first_activation.T.dot(self.y_hat_grad)
        self.second_biases = self.second_biases + alpha*np.sum(self.y_hat_grad, axis=0, keepdims=True)
        
    def train(self, X, y, alpha, iterations, verbose):
        """use forward and back passes to train the network."""
        for i in range(iterations):
            y_hat = self.forward_pass(X)
            self.backprop(X,y,y_hat,alpha)
            
            if verbose == True:
                if (i+1 in [1,2,3,4,5, iterations]) or ((i+1) % 1000 ==0):
                    print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
                    print('Input: \n', X)
                    print('Actual Output: \n', y)
                    print('Predicted Output: \n', str(self.forward_pass(X)))
                    print("Loss: \n", str(np.mean(np.square(y - self.forward_pass(X)))))
                
        

In [21]:
nn = NeuralNetwork(3,4,1)

nn.forward_pass(X)

array([[0.92295298],
       [0.92989399],
       [0.93299969],
       [0.92262865],
       [0.92685853],
       [0.93657734],
       [0.91126623]])

In [22]:
nn = NeuralNetwork(3,4,1)

nn.train(X,y,alpha=0.1,iterations=10000,verbose=True)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.8709199 ]
 [0.87903055]
 [0.87948769]
 [0.8712655 ]
 [0.87283898]
 [0.88433115]
 [0.85941311]]
Loss: 
 0.33443332626815525
+---------EPOCH 2---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.86087136]
 [0.86894258]
 [0.86948471]
 [0.86117502]
 [0.86284025]
 [0.874297  ]
 [0.8494326 ]]
Loss: 
 0.32847513724127253
+---------EPOCH 3---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.84984977]
 [0.85781826]
 [0.85845672]
 [0.85010084]
 [0.85186248]
 [0.86319475]
 [0.83855584]]
Loss: 
 0.32217005014810424
+---------EPO

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [23]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [24]:
# input image dimensions
img_rows, img_cols = 28, 28

In [25]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [26]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [27]:
# Now the data should be in a format you're more familiar with
print(x_train.shape)

(60000, 784)


In [28]:
x_train_subset = x_train[:20000, :]
print(x_train_subset.shape)
print(type(x_train_subset))

(20000, 784)
<class 'numpy.ndarray'>


### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [29]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [30]:
# A Nice Binary target for ya to work with
y_train
y_train.shape = [60000,1]

In [31]:
y_train_subset = y_train[:20000]
y_train_subset.shape

(20000, 1)

### Estimating Your `net

In [32]:
##### Your Code Here #####

nn_mnist = NeuralNetwork(784,784,1)
nn_mnist.train(x_train,y_train,alpha=0.1,iterations=10,verbose=True)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
Loss: 
 0.9012833333333333
+---------EPOCH 2---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
Loss: 
 0.9012833333333333
+---------EPOCH 3---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
Loss

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?