# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [3]:
import numpy as np
import random

In [4]:
X = np.array([[0,0,1],[0,1,1],[1,0,1],[0,1,0],[1,0,0],[1,1,1],[0,0,0]])
y = np.array([[0],[1],[1],[1],[1],[0],[0]])

In [5]:
X, y

(array([[0, 0, 1],
        [0, 1, 1],
        [1, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
        [1, 1, 1],
        [0, 0, 0]]), array([[0],
        [1],
        [1],
        [1],
        [1],
        [0],
        [0]]))

In [6]:
y.shape

(7, 1)

In [1]:
##### Your Code Here #####
class Neural_Network(object):
  def __init__(self):
    self.inputs = 3
    self.hiddenNodes = 16
    self.outputNodes = 1

    # Initlize Weights
    self.Layer1_weights = np.random.randn(self.inputs, self.hiddenNodes) # (4x3)
    self.Layer2_weights = np.random.randn(self.hiddenNodes, self.outputNodes) # (4x1)

  def feed_forward(self, X):
    # Weighted sum between inputs and hidden layer
    self.hidden_sum = np.dot(X, self.Layer1_weights)
    # Activations of weighted sum
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    # Weighted sum between hidden and output
    self.output_sum = np.dot(self.activated_hidden, self.Layer2_weights)
    # final activation of output
    self.activated_output = self.sigmoid(self.output_sum)
    return self.activated_output
    
  def sigmoid(self, s):
    return 1/(1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
  
  def backward(self, X, y, o):
    # backward propgate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.Layer2_weights.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden) # applying derivative of sigmoid to z2 error

    self.Layer1_weights += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.Layer2_weights += self.activated_hidden.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
    
  def train (self, X, y):
    o = self.feed_forward(X)
    self.backward(X, y, o)

LoadError: syntax: extra token "Neural_Network" after end of expression

In [10]:
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    if i+1 in [1,2,3,4,5] or (i+1) % 50 == 0:
        print('+---------- EPOCH', i+1, '-----------+')
        print("Input: \n", X) 
        print("Actual Output: \n", y)  
        print("Predicted Output: \n" + str(NN.feed_forward(X))) 
        print("Loss: \n" + str(np.mean(np.square(y - NN.feed_forward(X))))) # mean sum squared loss
        print("\n")
    NN.train(X, y)

+---------- EPOCH 1 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.0415604 ]
 [0.13498533]
 [0.09499148]
 [0.12013828]
 [0.09077914]
 [0.2618345 ]
 [0.03265784]]
Loss: 
0.4627830190174313


+---------- EPOCH 2 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.14762421]
 [0.37359822]
 [0.26644211]
 [0.271051  ]
 [0.19383701]
 [0.52563069]
 [0.08527267]]
Loss: 
0.3453005338782339


+---------- EPOCH 3 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.52255911]
 [0.77239861]
 [0.65481171]
 [0.58469419]
 [0.44785917]
 [0.8276547 ]
 [0.27384144]]
Loss: 
0.24019503215089524


+---------- EPOCH 4 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 

In [12]:
##### Your Code Here #####
class Neural_Network(object):
    def __init__(self):
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1

        # Initlize Weights
        self.Layer1_weights = np.random.randn(self.inputs, self.hiddenNodes) # (4x3)
        self.Layer2_weights = np.random.randn(self.hiddenNodes, self.outputNodes) # (4x1)


    def feed_forward(self, X):
        # Weighted sum between inputs and hidden layer
        self.hidden_sum = np.dot(X, self.Layer1_weights)
        # Activations of weighted sum
        self.activated_hidden = self.relu(self.hidden_sum)
        # Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.Layer2_weights)
        # final activation of output
        self.activated_output = self.relu(self.output_sum)
        return self.activated_output


    def relu(self,s):
        return np.maximum(0,s)
    
    def relu_prime(self,s):
        
        return np.heaviside(s,0)
    
  
    def backward(self, X, y, o):
    # backward propgate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.relu_prime(o)# applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.Layer2_weights.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.relu_prime(self.activated_hidden) # applying derivative of sigmoid to z2 error

        self.Layer1_weights += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.Layer2_weights += self.activated_hidden.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
        
    def train (self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
    
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
    if i+1 in [1,2,3,4,5] or i==1000 == 0:
        print('+---------- EPOCH', i+1, '-----------+')
        print("Input: \n", X) 
        print("Actual Output: \n", y)  
        print("Predicted Output: \n" + str(NN.feed_forward(X))) 
        print("Loss: \n" + str(np.mean(np.square(y - NN.feed_forward(X))))) # mean sum squared loss
        print("\n")
    NN.train(X, y)

+---------- EPOCH 1 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Loss: 
0.5714285714285714


+---------- EPOCH 2 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Loss: 
0.5714285714285714


+---------- EPOCH 3 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Loss: 
0.5714285714285714


+---------- EPOCH 4 -----------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Loss: 
0.5714285714285714


+---

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [1]:
import pandas as pd

In [2]:
import numpy as np
from numpy import genfromtxt
x_train = genfromtxt('mnist_train.csv', delimiter=',')

In [3]:
X = pd.DataFrame(x_train)

In [4]:
X = X.drop([0],axis=0)

In [5]:
Y=X[0]
X=X[list(range(1,785))]

In [6]:
X = X/X.max().max()

In [7]:
#!pipenv install blackcellmagic

In [8]:
#%load_ext blackcellmagic

In [9]:
def thermometer_encoder(largest_value, individual_value):
    a = np.concatenate(
       ( np.ones((individual_value + 1)),
        np.zeros(( largest_value - individual_value - 1)))
    )
    return a

In [10]:
Yt = Y.apply(lambda x : thermometer_encoder(10,int(x)))

In [30]:
##### Your Code Here #####
class Neural_Network(object):
    def __init__(self):
        self.inputs = 784
        self.hiddenNodes = 16
        self.outputNodes = 10

        # Initlize Weights
        self.Layer1_weights = np.random.randn(self.inputs, self.hiddenNodes) # (4x3)
        self.Layer2_weights = np.random.randn(self.hiddenNodes, self.outputNodes) # (4x1)


    def feed_forward(self, X):
        # Weighted sum between inputs and hidden layer
        self.hidden_sum = np.dot(X, self.Layer1_weights)
        # Activations of weighted sum
        self.activated_hidden = self.relu(self.hidden_sum)
        # Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.Layer2_weights)
        # final activation of output
        self.activated_output = self.relu(self.output_sum)
        return self.activated_output


    def relu(self,s):
        return np.maximum(0,s)
    
    def relu_prime(self,s):
        
        return np.heaviside(s,0)
    
  
    def backward(self, X, y, o):
    # backward propgate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.relu_prime(o)# applying derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.Layer2_weights.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.relu_prime(self.activated_hidden) # applying derivative of sigmoid to z2 error

        self.Layer1_weights += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.Layer2_weights += self.activated_hidden.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
        
    def train (self, X, y, batchsize=64):
        batch = np.random.random_integers(0,len(X),size=batchsize)
        o = self.feed_forward(X.iloc[batch])
        self.backward(X.iloc[batch], y, o)
    
NN = Neural_Network()


In [33]:
NN.feed_forward(X)

array([[ 1.23509021, 23.157913  , 21.54197036, ..., 20.10406089,
         0.        , 35.03519669],
       [ 9.57203849,  0.        ,  2.23575483, ...,  2.18909664,
         0.        , 39.01321738],
       [15.64128644,  9.0560671 ,  9.94607718, ...,  9.04414597,
         0.        , 10.37372365],
       ...,
       [ 0.        , 26.45609295,  6.67011029, ..., 42.96509591,
         0.        , 37.25829538],
       [ 0.        ,  0.        ,  4.13231315, ..., 25.32634399,
         0.        , 49.98906362],
       [ 0.        , 14.53648513,  2.7448639 , ...,  0.        ,
         0.        ,  5.46103755]])

## Julia

In [5]:
using Random

In [39]:
function relu(r)
    return max(0,r)
end
function relu_prime(r)
    if r>=0
        return 1
    else
        return 0
    end
end

relu_prime (generic function with 1 method)

In [118]:
function sigmoid(s)
    return 1/(1+exp(-s))
end
function sigmoid_prime(s)
   return  sigmoid(s) * (1-sigmoid(s))
end

sigmoid_prime (generic function with 1 method)

In [160]:
X = [ 0 0 1 ; 0 1 1 ; 1 0 1 ; 0 1 0 ; 1 0 0 ; 1 1 1 ; 0 0 0]
y = [ 0 ; 1 ;1;1;1;0;0]


7-element Array{Int64,1}:
 0
 1
 1
 1
 1
 0
 0

In [252]:
hidden_layer1 = randn(3,16)
z_layer = randn(16, 1)
bias = ones(7).*0.5

7-element Array{Float64,1}:
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5
 0.5

In [264]:
h1 = (sigmoid).(X * hidden_layer1)

7×16 Array{Float64,2}:
 0.551924  0.49027   0.371262  0.603     …  0.447189  0.506815  0.482867
 0.590611  0.482895  0.283821  0.675819     0.407866  0.511983  0.469899
 0.591418  0.482735  0.282389  0.677156     0.407047  0.512095  0.469619
 0.539429  0.49262   0.401605  0.578506     0.459896  0.505169  0.487005
 0.540259  0.49246   0.399912  0.579995     0.459053  0.505281  0.486724
 0.628988  0.475368  0.208924  0.742189  …  0.368897  0.517259  0.456692
 0.5       0.5       0.5       0.5          0.5       0.5       0.5     

In [265]:
h1 .+ bias

7×16 Array{Float64,2}:
 1.05192  0.99027   0.871262  1.103    …  0.947189  1.00682  0.982867
 1.09061  0.982895  0.783821  1.17582     0.907866  1.01198  0.969899
 1.09142  0.982735  0.782389  1.17716     0.907047  1.01209  0.969619
 1.03943  0.99262   0.901605  1.07851     0.959896  1.00517  0.987005
 1.04026  0.99246   0.899912  1.07999     0.959053  1.00528  0.986724
 1.12899  0.975368  0.708924  1.24219  …  0.868897  1.01726  0.956692
 1.0      1.0       1.0       1.0         1.0       1.0      1.0     

In [266]:
output = h1 * z_layer

7×1 Array{Float64,2}:
 6.343993115368271 
 6.368137049968388 
 6.368376411184281 
 6.3347829797996145
 6.33518408592693  
 6.383914040722566 
 6.303955948103284 

In [267]:
y

7-element Array{Int64,1}:
 0
 1
 1
 1
 1
 0
 0

In [268]:
o_error = y - output

7×1 Array{Float64,2}:
 -6.343993115368271 
 -5.368137049968388 
 -5.368376411184281 
 -5.3347829797996145
 -5.33518408592693  
 -6.383914040722566 
 -6.303955948103284 

In [269]:
o_delta = sigmoid_prime.(o_error)

7×1 Array{Float64,2}:
 0.001751111458647804 
 0.004619628468784705 
 0.0046185331015943   
 0.0047748069981752815
 0.004772910544514598 
 0.001682813481080173 
 0.0018223822297459527

In [270]:
z2_error = o_delta.*(transpose(z_layer))

7×16 Array{Float64,2}:
 0.001264    0.00183683  0.000952235  …  0.000990856  0.00122173  0.00157388
 0.00333457  0.00484576  0.0025121       0.00261399   0.00322306  0.00415207
 0.00333378  0.00484461  0.00251151      0.00261337   0.00322229  0.00415109
 0.00344658  0.00500853  0.00259649      0.0027018    0.00333132  0.00429155
 0.00344521  0.00500654  0.00259545      0.00270072   0.00333     0.00428984
 0.0012147   0.00176519  0.000915095  …  0.00095221   0.00117408  0.0015125 
 0.00131544  0.00191159  0.000990991     0.00103118   0.00127145  0.00163794

In [271]:
z2_delta = z2_error .*(sigmoid_prime.(z2_error) )

7×16 Array{Float64,2}:
 0.000315999  0.000459207  0.000238059  …  0.000305432  0.00039347 
 0.00083364   0.00121143   0.000628024     0.000805762  0.00103801 
 0.000833442  0.00121114   0.000627875     0.000805571  0.00103777 
 0.000861642  0.00125213   0.00064912      0.000832829  0.00107288 
 0.0008613    0.00125163   0.000648863     0.000832498  0.00107246 
 0.000303674  0.000441296  0.000228774  …  0.000293519  0.000378124
 0.000328861  0.000477896  0.000247748     0.000317863  0.000409484

In [272]:
hidden_layer1 = transpose(X)*z2_delta

3×16 Array{Float64,2}:
 0.00199842  0.00290407  0.00150551  …  0.00156657  0.00193159  0.00248835
 0.00199896  0.00290485  0.00150592     0.001567    0.00193211  0.00248902
 0.00228676  0.00332308  0.00172273     0.0017926   0.00221029  0.00284738

In [273]:
z_layer = transpose(h1)* o_delta

16×1 Array{Float64,2}:
 0.013550307159524887
 0.011732621120451868
 0.00835459076937917 
 0.014996095367950595
 0.011150876977551441
 0.012055634191203136
 0.008974491641217792
 0.014712005045244355
 0.011125636228396126
 0.012315094015519496
 0.013728500464975878
 0.011727516501695567
 0.015733060606212056
 0.010466135912482551
 0.012223170999711758
 0.011513423749087233

### Put it all together

In [287]:
hidden_layer1 = randn(3,4)
z_layer = randn(4, 1)
bias = ones(7).*0.5
function NN(X,y,hidden_layer1,z_layer)
    h1 = (sigmoid).(X * hidden_layer1) 
    output = (sigmoid).( h1 * z_layer)
    
    C = 0.5*sum((y - output)^2)
    
    delta3 = h1 * (-(y-output))
    ∂C_∂z_layer =  delta3.*(sigmoid_prime.((h1 * z_layer)))
    ∂C_∂hidden_layer1 = 
    
    o_delta = sigmoid_prime.(cost)
    z2_error = o_delta.*(transpose(z_layer))
    z2_delta = z2_error .*(sigmoid_prime.(z2_error) )
    hidden_layer1 = transpose(X)*z2_delta
    z_layer = transpose(h1)* o_delta
    return X,y,hidden_layer1,z_layer,output
end

NN (generic function with 2 methods)

In [288]:
hidden_layer1 = randn(3,4)
z_layer = randn(4, 1)
for i=1:1000
    X,y,hidden_layer1,z_layer,output = NN(X,y,hidden_layer1,z_layer,bias)
end

In [289]:
output

7×1 Array{Float64,2}:
 0.9523439122850895
 0.9597472630057191
 0.9597472630057191
 0.9498631861587788
 0.9498631861587788
 0.9655794472031362
 0.9398869329295937

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?