<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [19]:
import pandas as pd
import numpy as np

In [20]:
data = {'x1': [0,0,1,0,1,1,0],
        'x2': [0,1,0,1,0,1,0],
        'x3': [1,1,1,0,0,1,0]}

df = pd.DataFrame.from_dict(data).astype('int')

corr = [[0],[1],[1],[1],[1],[0],[0]]

In [21]:
# lecture code mostly

class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 3
        self.hiddenNodes = 7
        self.outputNodes = 1

        # Initial Weights
        # 2x3 Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
       
        # 3x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        KAKAL8 the NN inference using feed forward.
        
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # "distance" hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        # "distance" input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)

         # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [22]:
X = df.values

In [23]:
# lecture style
# train NN

nn = NeuralNetwork()
y = corr

# epochs
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 == 0):
        print('+' + '---' * 3 + f'Epoch {i+1}' + '---'*3 + '+')
        print('Input : \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print('Loss: \n', str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)
    
    

+---------Epoch 1---------+
Input : 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.92831257]
 [0.9536729 ]
 [0.960894  ]
 [0.9272508 ]
 [0.94230439]
 [0.97093323]
 [0.88274559]]
Loss: 
 0.37085886198866824
+---------Epoch 2---------+
Input : 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.89316898]
 [0.92512049]
 [0.93441408]
 [0.89238592]
 [0.91018005]
 [0.94858674]
 [0.8418699 ]]
Loss: 
 0.3479813467699678
+---------Epoch 3---------+
Input : 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.82612043]
 [0.86452315]
 [0.87547811]
 [0.82577631]
 [0.84481555]
 [0.89517018]
 [0.77219588]]
Loss: 
 0.3097695527661362
+---------Epoch 4---------+
Input : 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [24]:
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [25]:
# input image dimensions
img_rows, img_cols = 28, 28

In [26]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [27]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [28]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [29]:
import numpy as np

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [30]:
# A Nice Binary target for ya to work with
y_train = np.array([y_train]).T

y_train

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

### Estimating Your `net

In [38]:
class NeuralNetwork2:
    def __init__(self):
        self.inputs = 2
        self.hiddenNodes = 3
        self.outputNodes = 1

        # Initial Weights
        if len(hiddenNodes) == 0:
            self.weights = [np.random.rand(self.inputs, self.outputNodes)]
        else:
            self.weights = [np.random.rand(self.inputs, self.hiddenNodes[0])]
            for i in range(1, len(hiddenNodes)):
                self.weights.append(np.random.rand((hiddenNodes[i-1]), hiddenNodes[i]))
            self.weights.append(np.random.rand(hiddenNodes[-1], outputNodes))
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
       
        
        # Weighted sum of inputs => hidden layer
        weighted_sum = np.dot(X, self.weights[0])
        self.activated_outputs = [self.sigmoid(weighted_sum)]
        for i in range(1, len(self.weights)):
            weighted_sum = np.dot(self.activated_outputs[i-1], self.weights[i])
            self.activated_outputs.append(self.sigmoid(weighted_sum))
                
        return self.activated_outputs[-1]
        
    def backward(self, X, y, o):
        
        
        # Error in Output
        self.o_error = y - o
        
    
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        z2_error = self.o_delta.dot(self.weights[-1].T)

        # Adjustment to final set of weights (hidden => output)
        if len(self.weights) == 1:
            self.weights[0] += X.T.dot(self.o_delta)
            return
        
        self.weights[-1] += self.activated_outputs[-2].T.dot(self.o_delta)
        
        # Hidden layer error
        for i in reversed(range(2, len(self.weights))):
            z2_delta = z2_error * self.sigmoidPrime(self.activated_outputs[i-1])
            z2_error = z2_delta.dot(self.weights[i-1].T)
        
            # Adjustment to interior set of weights (hidden => hidden)
            self.weights[i-1] += self.activated_outputs[i-2].T.dot(z2_delta)
        
        # Input layer error (if not same layer as output)
        z2_delta = z2_error * self.sigmoidPrime(self.activated_outputs[0])
        self.weights[0] += X.T.dot(z2_delta)

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

    def fit(self, X, y, max_epochs, print_epochs):
        for i in range(max_epochs):
            if (i+ 1 in print_epochs): 
                print('+' + '---' * 3 + f'EPOCH {i + 1}' + '---' * 3 + '+')
                print('Input: \n', X)
                print('Actual Output: \n', y)
                print('Predicted Output: \n', str(self.feed_forward(X)))
                print("Loss: \n", str(np.mean(np.square(y - self.feed_forward(X)))))
            self.train(X, y)
                                                                   



In [39]:
nn2 = NeuralNetwork(2, 3, 1)

TypeError: __init__() takes 1 positional argument but 4 were given

In [ ]:
#ugh whatever

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?