In [0]:
import numpy as np

# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [0]:
X = np.array(([0,0,1],
              [0,1,1],
              [1,0,1],
              [0,1,0],
              [1,0,0],
              [1,1,1],
              [0,0,0]
             ), dtype=float)
y=np.array(([0],
            [1],
            [1],
            [1],
            [1],
            [0],
            [0],
           ), dtype=float)

In [11]:
print(X)
y

[[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]


array([[0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.]])

In [0]:
class NeuralNetwork:
  def __init__(self):
    
    self.input = 3
    self.hiddenNodes = 4
    self.outputNodes = 1
    
    self.weights1= np.random.randn(self.input,self.hiddenNodes)
    self.weights2= np.random.randn(self.hiddenNodes, self.outputNodes)
  
  def sigmoid(self, s):
    return 1/ (1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
  
  def feed_forward(self,X):
    '''
    Calculate the NN inference using feed forward.
    '''
    
    self.hidden_sum = np.dot(X, self.weights1)
    
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    
    self.activated_output = self.sigmoid(self.output_sum)
    
    return self.activated_output
  
  def back_prop(self, X, y , o):
    '''
    Backward propagate through the network
    '''
    
    self.o_error = y - o
    self.o_delta = self.o_error * self.sigmoidPrime(o)
    
    self.z2_error = self.o_delta.dot(self.weights2.T)
    self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
    
    self.weights1 += X.T.dot(self.z2_delta)
    self.weights2 += self.activated_hidden.T.dot(self.o_delta)
    
  def train(self, X, y):
    o = self.feed_forward(X)
    self.back_prop(X, y, o)

In [17]:
nn = NeuralNetwork()

for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.59934437]
 [0.67439014]
 [0.62998246]
 [0.66590727]
 [0.62316386]
 [0.70055945]
 [0.58365796]]
Loss: 
 0.24103028895771733
+---------EPOCH 2---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.57943757]
 [0.64936552]
 [0.61040758]
 [0.64053923]
 [0.60342084]
 [0.67632923]
 [0.56400529]]
Loss: 
 0.23892642296845398
+---------EPOCH 3---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.56792955]
 [0.63486649]
 [0.60075184]
 [0.62692209]
 [0.59465508]
 [0.66373547]
 [0.55356163]]
Loss: 
 0.23796177553219583
+---------EPO

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [0]:
from IPython.display import clear_output

!wget 'yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz'
!wget 'yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz'
!wget 'yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz'
!wget 'yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz'

clear_output()

In [0]:
!gunzip /content/t10k-images-idx3-ubyte.gz
!gunzip /content/t10k-labels-idx1-ubyte.gz
!gunzip /content/train-images-idx3-ubyte.gz
!gunzip /content/train-labels-idx1-ubyte.gz

In [0]:
!pip install python-mnist
clear_output()

In [0]:
from mnist import MNIST

mndata = MNIST('/content')

images, labels = mndata.load_training()

In [9]:
import random
index = random.randrange(0, len(images))  # choose an index ;-)
print(mndata.display(images[0]))


............................
............................
............................
............................
............................
.....................@@.....
.............@@@@@@.@@......
........@@@@@@@@@@..........
........@@@@@@..@@..........
...........@@@..............
............@...............
............@...............
.............@..............
.............@@.............
..............@@@...........
................@@..........
.................@@.........
.................@@@........
.................@@@........
..............@@@@@.........
............@@@@@@..........
..........@@@@@.............
........@@@@@...............
......@@@@@@................
.....@@@@...................
............................
............................
............................


In [0]:
np.set_printoptions(linewidth=200)
X= []
for m in range(0,1000):
  X.append(np.reshape(images[m],(28,28)))


In [0]:
y=labels[0:1000]


In [0]:
class NeuralNetwork:
  def __init__(self):
    
    self.input = 28
    self.hiddenNodes = 4
    self.outputNodes = 1
    #28x28 matrix array for first layer
    self.weights1= np.random.randn(self.input,self.hiddenNodes)
    #28x1 matrix from hidden to output
    self.weights2= np.random.randn(self.hiddenNodes, self.outputNodes)
  
  def sigmoid(self, s):
    return 1/ (1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1 - s)
  
  def feed_forward(self,X):
    '''
    Calculate the NN inference using feed forward.
    '''
    
    self.hidden_sum = np.dot(X, self.weights1)
    
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    
    self.activated_output = self.sigmoid(self.output_sum)
    
    return self.activated_output
  
  def back_prop(self, X, y , o):
    '''
    Backward propagate through the network
    '''
    
    self.o_error = y - o
    self.o_delta = self.o_error * self.sigmoidPrime(o)
    
    self.z2_error = self.o_delta.dot(self.weights2.T)
    self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
    
    self.weights1 += X.T.dot(self.z2_delta)
    self.weights2 += self.activated_hidden.T.dot(self.o_delta)
    
  def train(self, X, y):
    o = self.feed_forward(X)
    self.back_prop(X, y, o)

In [23]:
nn = NeuralNetwork()

for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        #print('Input: \n', X)
        #print('Actual Output: \n', y)
        #print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


Loss: 
 20.379609801903264


ValueError: ignored

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?