<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score

In [2]:
df = pd.DataFrame({'x1': [0, 0, 1, 0, 1, 1, 0],
                   'x2': [0, 1, 0, 1, 0, 1, 0],
                   'x3': [1, 1, 1, 0, 0, 1, 0],
                   'y':  [0, 1, 1, 1, 1, 0, 0]})

In [3]:
df

x1  x2  x3  y
0   0   0   1  0
1   0   1   1  1
2   1   0   1  1
3   0   1   0  1
4   1   0   0  1
5   1   1   1  0
6   0   0   0  0

In [4]:
feat = ['x1', 'x2', 'x3']
X = df[feat].values
y = np.expand_dims(df['y'], axis=1)

In [5]:
class NeuralNetwork:
    def __init__(self, inputs=2, hiddenNodes=3, outputNodes=1):
        # Set up Architecture of Neural Network
        self.inputs = inputs
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes

        # Initial Weights
        # Inputs x hidden nodes Matrix Array for the First Layer
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
       
        # Hidden nodes x outputs Matrix Array for Hidden to Output
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

    def fit(self, X, y, max_epochs, print_epochs):
        for i in range(max_epochs):
            if (i+ 1 in print_epochs): 
                print('+' + '---' * 3 + f'EPOCH {i + 1}' + '---' * 3 + '+')
                print('Input: \n', X)
                print('Actual Output: \n', y)
                print('Predicted Output: \n', str(self.feed_forward(X)))
                print("Loss: \n", str(np.mean(np.square(y - self.feed_forward(X)))))
            self.train(X, y)

In [6]:
nn = NeuralNetwork(inputs=3, hiddenNodes=4, outputNodes=1)

In [7]:
nn.fit(X, y, 6000, [1, 2, 3000, 6000])

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.76600761]
 [0.78860613]
 [0.79394564]
 [0.7407078 ]
 [0.74945748]
 [0.80994432]
 [0.70973549]]
Loss: 
 0.2805216725620296
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.68340443]
 [0.69964654]
 [0.70449704]
 [0.66206152]
 [0.66939356]
 [0.71685403]
 [0.64179154]]
Loss: 
 0.2562649899291947
+---------EPOCH 3000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[2.98041847e-04]
 [9.23067952e-01]
 [9.23067955e-01]
 [9.18446091e-01]
 [9.18446220e-01]
 [1.62548456e-01]
 [9.16142894e-02]]
Loss: 
 0.008564915172455004
+---------EPOCH 6000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]


In [8]:
predictions = np.rint(nn.feed_forward(X)).astype(int)

In [9]:
predictions

array([[0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0]])

In [10]:
accuracy_score(df['y'], predictions)

1.0

In [11]:
nn.weights1

array([[ 9.63500890e-01,  6.95302436e+00,  6.51903117e+00,
         7.89879779e+00],
       [ 9.63502091e-01,  6.95325493e+00,  6.51981291e+00,
         7.89828574e+00],
       [-4.29451655e-03, -7.59234493e-01, -4.24841299e-01,
        -1.40423730e+00]])

In [12]:
nn.weights2

array([[-33.39849508],
       [  8.377109  ],
       [  7.1474559 ],
       [ 11.50615635]])

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chock-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [13]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [14]:
# input image dimensions
img_rows, img_cols = 28, 28

In [15]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [16]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [17]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [18]:
y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [19]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [20]:
class NeuralNetwork2:
    def __init__(self, inputs=2, hiddenNodes=[3], outputNodes=1):
        # Set up Architecture of Neural Network
        self.inputs = inputs
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes

        # Initial Weights
        if len(hiddenNodes) == 0:
            self.weights = [np.random.rand(self.inputs, self.outputNodes)]
        else:
            self.weights = [np.random.rand(self.inputs, self.hiddenNodes[0])]
            for i in range(1, len(hiddenNodes)):
                self.weights.append(np.random.rand((hiddenNodes[i-1]), hiddenNodes[i]))
            self.weights.append(np.random.rand(hiddenNodes[-1], outputNodes))
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        weighted_sum = np.dot(X, self.weights[0])
        self.activated_outputs = [self.sigmoid(weighted_sum)]
        for i in range(1, len(self.weights)):
            weighted_sum = np.dot(self.activated_outputs[i-1], self.weights[i])
            self.activated_outputs.append(self.sigmoid(weighted_sum))
                
        return self.activated_outputs[-1]
        
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        z2_error = self.o_delta.dot(self.weights[-1].T)

        # Adjustment to final set of weights (hidden => output)
        if len(self.weights) == 1:
            self.weights[0] += X.T.dot(self.o_delta)
            return
        
        self.weights[-1] += self.activated_outputs[-2].T.dot(self.o_delta)
        
        # Hidden layer error
        for i in reversed(range(2, len(self.weights))):
            z2_delta = z2_error * self.sigmoidPrime(self.activated_outputs[i-1])
            z2_error = z2_delta.dot(self.weights[i-1].T)
        
            # Adjustment to interior set of weights (hidden => hidden)
            self.weights[i-1] += self.activated_outputs[i-2].T.dot(z2_delta)
        
        # Input layer error
        z2_delta = z2_error * self.sigmoidPrime(self.activated_outputs[0])
        self.weights[0] += X.T.dot(z2_delta)

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

    def fit(self, X, y, max_epochs, print_epochs):
        for i in range(max_epochs):
            if (i+ 1 in print_epochs): 
                print('+' + '---' * 3 + f'EPOCH {i + 1}' + '---' * 3 + '+')
                print('Input: \n', X)
                print('Actual Output: \n', y)
                print('Predicted Output: \n', str(self.feed_forward(X)))
                print("Loss: \n", str(np.mean(np.square(y - self.feed_forward(X)))))
            self.train(X, y)

In [21]:
nn2 = NeuralNetwork2(inputs=3, hiddenNodes=[4], outputNodes=1)

In [22]:
nn2.fit(X, y, 5000, [1, 2, 3, 5000])

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.81884995]
 [0.85515717]
 [0.86084247]
 [0.82547055]
 [0.8315232 ]
 [0.88369043]
 [0.77724508]]
Loss: 
 0.307817591791039
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.75477619]
 [0.79098627]
 [0.79490713]
 [0.76296851]
 [0.76663509]
 [0.81978185]
 [0.7182116 ]]
Loss: 
 0.2791357436765027
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.68204714]
 [0.71336668]
 [0.71385449]
 [0.69030237]
 [0.69020045]
 [0.73689787]
 [0.65354828]]
Loss: 
 0.25589406072004406
+---------EPOCH 5000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 

In [23]:
predictions2 = np.rint(nn2.feed_forward(X))

In [24]:
accuracy_score(y, predictions2)

1.0

In [25]:
nn2 = NeuralNetwork2(inputs=3, hiddenNodes=[2, 3], outputNodes=1)

In [26]:
nn2.fit(X, y, 5000, [1, 2, 3, 5000])

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.59792454]
 [0.60172331]
 [0.60157671]
 [0.59832441]
 [0.59815954]
 [0.60399552]
 [0.5933822 ]]
Loss: 
 0.24494446679891915
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.58675306]
 [0.59024584]
 [0.59011735]
 [0.58713788]
 [0.5869944 ]
 [0.59232891]
 [0.58258743]]
Loss: 
 0.24449597374741047
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.58049815]
 [0.5838263 ]
 [0.58370805]
 [0.5808785 ]
 [0.58074714]
 [0.58580631]
 [0.57653747]]
Loss: 
 0.24435398891909615
+---------EPOCH 5000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0

In [27]:
predictions2 = np.rint(nn2.feed_forward(X))

In [28]:
accuracy_score(y, predictions2)

1.0

In [29]:
nn2 = NeuralNetwork2(inputs=3, hiddenNodes=[], outputNodes=1)

In [30]:
nn2.fit(X, y, 5000, [1, 2, 3, 5000])

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.52181481]
 [0.5961948 ]
 [0.58406893]
 [0.57500961]
 [0.56271419]
 [0.65516469]
 [0.5       ]]
Loss: 
 0.23706063780145983
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.50183743]
 [0.58969961]
 [0.57936371]
 [0.58792014]
 [0.57757153]
 [0.66274162]
 [0.5       ]]
Loss: 
 0.23351488416822988
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.48389127]
 [0.58465012]
 [0.57585902]
 [0.60021225]
 [0.59152041]
 [0.6708753 ]
 [0.5       ]]
Loss: 
 0.23047447617754782
+---------EPOCH 5000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0

In [31]:
nn_mnist = NeuralNetwork2(inputs=784, hiddenNodes=[3], outputNodes=1)

In [32]:
nn_mnist.fit(x_train[:10], np.expand_dims(y_train[:10], axis=1), 1000, [1, 2, 3, 1000])

+---------EPOCH 1---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.81706208]
 [0.81706208]
 [0.81706208]
 [0.81706208]
 [0.81706208]
 [0.81706208]
 [0.81706208]
 [0.81706208]
 [0.81706208]
 [0.81706208]]
Loss: 
 0.6041780244539172
+---------EPOCH 2---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.15201998]
 [0.15201998]
 [0.15201998]
 [0.15201998]
 [0.15201998]
 [0.15201998]
 [0.15201998]
 [0.15201998]
 [0.15201998]
 [0.15201998]]
Loss: 
 0.09270607852568466
+---------EPOCH 3---------+
Input: 
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0

In [33]:
mnist_predict = nn_mnist.feed_forward(x_train[:10])

In [34]:
accuracy_score(y_train[:10], np.rint(mnist_predict))

0.9

In [35]:
np.bincount(y_train[:10].astype(int))

array([9, 1], dtype=int64)

In [36]:
np.bincount(np.rint(mnist_predict[0]).astype(int))

array([1], dtype=int64)

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?