# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
import numpy as np

In [39]:
class Neural_Network(object):
    def __init__(self, num_input_nodes, num_hidden_nodes, num_output_nodes):
        self.num_input_nodes  = num_input_nodes   # 3 input nodes
        self.num_hidden_nodes = num_hidden_nodes  # 4 hidden nodes
        self.num_output_nodes = num_output_nodes  # 1 output node
        
        self.L1_weights = np.random.randn(num_input_nodes, num_hidden_nodes)
        self.L2_weights = np.random.randn(num_hidden_nodes, num_output_nodes)
        
    def feed_forward(self, X):
        self.hidden_sum = np.dot(X, self.L1_weights)
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        self.output_sum = np.dot(self.activated_hidden, self.L2_weights)
        self.activated_output = self.sigmoid(self.output_sum)
        return self.activated_output
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoid_prime(self, s):
        return s * (1 - s)
    
    def backward(self, X, y, o):

        self.o_error = y - o
        self.o_delta = self.o_error * self.sigmoid_prime(o)
        
        self.z2_error = self.o_delta.dot(self.L2_weights.T)
        self.z2_delta = self.z2_error * self.sigmoid_prime(self.activated_hidden)
        
        # Adjust weights
        self.L1_weights += X.T.dot(self.z2_delta)
        self.L2_weights += self.activated_hidden.T.dot(self.o_delta)

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [35]:
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [0, 1, 0],
              [1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]], dtype=float)
y = np.array([0, 1, 1, 1, 1, 0, 0], dtype=float)

NN = Neural_Network(3, 4, 1)
output = NN.feed_forward(X[0])
error  = y[0] - output
print('error:', error)

error: [-0.68146014]


### Let's try without the x3 column

In [36]:
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [0, 1],
              [1, 0],
              [1, 1],
              [0, 0]], dtype=float)
y = np.array([0, 1, 1, 1, 1, 0, 0], dtype=float)

NN = Neural_Network(2, 4, 1)
output = NN.feed_forward(X[0])
error  = y[0] - output
print('error:', error)

error: [-0.77858312]


### We see that the absolute value of the error is lower when we remove the unnecessary column x3

In [41]:
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [0, 1, 0],
              [1, 0, 0],
              [1, 1, 1],
              [0, 0, 0]], dtype=float)
y = np.array([[0], [1], [1], [1], [1], [0], [0]], dtype=float)

NN = Neural_Network(3, 4, 1)
for i in range(1000): # trains the NN 1,000 times
  if i+1 in [1,2,3,4,5] or (i+1) % 50 == 0:
    print('+---------- EPOCH', i+1, '-----------+')
    print("Input: \n", X) 
    print("Actual Output: \n", y)  
    print("Predicted Output: \n" + str(NN.feed_forward(X))) 
    print("Loss: \n" + str(np.mean(np.square(y - NN.feed_forward(X))))) # mean sum squared loss
    print("\n")
  NN.train(X, y)

+---------- EPOCH 1 -----------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
[[0.59932977]
 [0.52934237]
 [0.53682673]
 [0.60046591]
 [0.60730605]
 [0.49263069]
 [0.68629415]]
Loss: 
0.2603949906001927


+---------- EPOCH 2 -----------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
[[0.59031567]
 [0.52505357]
 [0.53373028]
 [0.59518261]
 [0.6030906 ]
 [0.49158572]
 [0.67574304]]
Loss: 
0.2587362173603863


+---------- EPOCH 3 -----------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
[[0.58239812]
 [0.52157072]
 [0.53122485]
 [0.59068487]
 [0.59948312]
 [0.49105805]
 [0.66617335]]
Loss: 
0.25724426731329736




## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [0]:
##### Your Code Here #####

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?