# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
##### Your Code Here #####
import numpy as np
np.random.seed(1)

class Neural_Network(object):
    def __init__(self):
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        # Initialize Weights
        self.L1_weights = np.random.randn(self.inputs, self.hiddenNodes) # 3x4
        self.L2_weights = np.random.randn(self.hiddenNodes, self.outputNodes) # 4x1
        
    def feed_forward(self, X):
        # Weighted sum between input and hidden layer
        self.hidden_sum = np.dot(X, self.L1_weights)
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        # Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.L2_weights)
        # final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        return self.activated_output
    
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def backward(self, X, y, o):
        # backward propagate through the network
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to output error
        
        self.z2_error = self.o_delta.dot(self.L2_weights.T) # z2 errro: how much of our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden) # applying derivative of sigmoid to z2_error
        
        self.L1_weights += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.L2_weights += self.activated_hidden.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
    
        

In [3]:
X = np.array(([0,0,1],[0,1,1],[1,0,1],[0,1,0],[1,0,0],[1,1,1],[0,0,0]), dtype=float)
y = np.array(([0],[1],[1],[1],[1],[0],[0]), dtype=float)

NN = Neural_Network()

for i in range(1000): # trains the NN 1,000 times
    if i+1 in [1, 2, 3, 4, 5] or (i+1) % 50 == 0:
        print('+--------- EPOCH', i+1, '------------+')
        print("Input: \n", X)
        print("Actual Ouput: \n", y)
        print("Predicted Output: \n" + str(NN.feed_forward(X)))
        print("Loss: \n" + str(np.mean(np.square(y - NN.feed_forward(X))))) # MSE
        print("\n")
    NN.train(X, y)

+--------- EPOCH 1 ------------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Ouput: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
[[0.38959854]
 [0.39520279]
 [0.35793904]
 [0.40041658]
 [0.36021476]
 [0.35615307]
 [0.39819936]]
Loss: 
0.283434591583668


+--------- EPOCH 2 ------------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Ouput: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
[[0.45988276]
 [0.48652347]
 [0.42753019]
 [0.50208257]
 [0.43915881]
 [0.44464847]
 [0.47933011]]
Loss: 
0.2561151723348865


+--------- EPOCH 3 ------------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Ouput: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
[[0.50131008]
 [0.54168989]
 [0.46899325]
 [0.56519281]
 [0.48872811]
 [0.49941899]
 [0.52933515]]
Loss: 
0.24619991143511785


+---

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [0]:
##### Your Code Here #####



## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?