<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [2]:
class NeuralNetwork():
    def __init__(self, input_size = 3, hiddenNodes = 4, outputNodes = 1):
#     def __init__(self, input_size, hiddenNodes, outputNodes):
        # Set up Architecture of neural network
        self.input = input_size 
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes
        
        # Initial Weights
        # 2x3 matrix for first layer
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        #3x1 matrix for hidden to output layer
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forawrd

        """

        #weighted sum of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        #add bias
#         self.hidden_sum + bias

        #Activations of weighted sums
        self.activated_hidden = self.sigmoid(self.hidden_sum)

        #Weighted sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)

        # Final Activation of output
        self.activated_output = self.sigmoid(self.output_sum)


        return self.activated_output
    
    def get_attributes(self):
        
        attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']

        [print(i + '\n', getattr(nn,i), '\n' + '---'*3) for i in dir(nn) if i in attributes]

    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)

        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [7]:
o = nn.feed_forward(X)

In [13]:
o.shape

(7, 1)

In [8]:
error = y-o

In [14]:
y.shape

(7, 1)

In [12]:
error.shape

(7, 1)

In [9]:
delta = nn.sigmoidPrime(o) * error

In [10]:
delta.shape

(7, 1)

In [15]:
import numpy as np

inputs = np.array((
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1],
    [0,0,0]), dtype=int)

correct_outputs = np.array(([0],[1],[1],[1],[1],[0],[0]), dtype=int)

In [16]:
correct_outputs.shape

(7, 1)

In [5]:
X = inputs
y = correct_outputs 

nn = NeuralNetwork()

# Number of Epochs / Iterations
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.75448564]
 [0.83015253]
 [0.80877122]
 [0.86852191]
 [0.84643314]
 [0.86836086]
 [0.79926477]]
Loss: 
 0.29548702865580545
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.67027097]
 [0.75540415]
 [0.72450101]
 [0.82138617]
 [0.79032768]
 [0.79785176]
 [0.74407791]]
Loss: 
 0.26443924729965546
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.58365543]
 [0.67156406]
 [0.63243333]
 [0.76810466]
 [0.72781397]
 [0.71355641]
 [0.68575784]]
Loss: 
 0.24155947480104303
+---------EPOCH 4---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

In [103]:
from sklearn.datasets import load_digits
digits = load_digits()

In [109]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
         [ 0.,  0., 13., ..., 15.,  5.,  0.],
         [ 0.,  3., 15., ..., 11.,  8.,  0.],
         ...,
         [ 0.,  4., 11., ..., 12.,  7.,  0.],
         [ 0.,  2., 14., ..., 12.,  0.,  0.],
         [ 0.,  0.,  6., ...,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
         [ 0.,  0.,  0., ...,  9.,  0.,  0.],
         [ 0.,  0.,  3., ...,  6.,  0.,  0.],
         ...,
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  1., ...,  6.,  0.,  0.],
         [ 0.,  0.,  0., ..., 10.,  0.,  0.]],
 
        [[ 0

In [104]:
X = digits.data
X.shape

(1797, 64)

In [106]:
y = digits.target.reshape(-1,1)
y.shape

(1797, 1)

In [107]:
mnist_nn = NeuralNetwork(input_size = 64, hiddenNodes = 65, outputNodes = 1)

In [117]:
row_sums.shape

(1797,)

In [108]:
# Normalize
row_sums = X.sum(axis=1)

#reshapes row_sum from (1797,) to (1797, 1)
X = X / row_sums[:, np.newaxis]
y = y /100


for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(mnist_nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - mnist_nn.feed_forward(X)))))
    mnist_nn.train(X, y)

+---------EPOCH 1---------+
Input: 
 [[0.         0.         0.0170068  ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.03194888 0.         0.        ]
 [0.         0.         0.         ... 0.04651163 0.02616279 0.        ]
 ...
 [0.         0.         0.0026738  ... 0.01604278 0.         0.        ]
 [0.         0.         0.00581395 ... 0.03488372 0.         0.        ]
 [0.         0.         0.0255102  ... 0.03061224 0.00255102 0.        ]]
Actual Output: 
 [[0.  ]
 [0.01]
 [0.02]
 ...
 [0.08]
 [0.09]
 [0.08]]
Predicted Output: 
 [[0.9970268 ]
 [0.99608999]
 [0.99656923]
 ...
 [0.99557341]
 [0.99578569]
 [0.99564791]]
Loss: 
 0.9065510719228732
+---------EPOCH 2---------+
Input: 
 [[0.         0.         0.0170068  ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.03194888 0.         0.        ]
 [0.         0.         0.         ... 0.04651163 0.02616279 0.        ]
 ...
 [0.         0.         0.0026738  ... 0.01604278 

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

### Estimating Your `net

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?