<a href="https://colab.research.google.com/github/nickwinters1/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/LS_DS_422_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [0]:
import numpy as np

X = np.array((
    [0,0,1],
    [0,1,1],
    [1,0,1],
    [0,1,0],
    [1,0,0],
    [1,1,1],
    [0,0,0]
             ), dtype=float)

y = np.array((
    [0],
    [1],
    [1],
    [1],
    [1],
    [0],
    [0]
        ), dtype=float)


In [12]:
X.shape

(7, 3)

In [0]:
class NeuralNetwork:
    def __init__(self):
        
        self.input = 3
        self.hiddenNodes = 4
        self.outputNodes = 1
        
        
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
    
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        
        self.hidden_sum = np.dot(X, self.weights1)
        
        
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        
        self.o_error = y - o 
        self.o_delta = self.o_error * self.sigmoidPrime(o) 
        
        self.z2_error = self.o_delta.dot(self.weights2.T) 
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) 
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) 
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)        

In [14]:
nn = NeuralNetwork()

nn.train(X, y)
nn.feed_forward(X).shape

(7, 1)

In [15]:
nn = NeuralNetwork()

for epoch in range(1000):
    nn.train(X, y)
print('+' + '---' * 3 + f'EPOCH {epoch+1}' + '---'*3 + '+')
print('Input: \n', X)
print('Actual Output: \n', y)
print('Weights1: ', nn.weights1)
print('Weights2:', nn.weights2)
print('Predicted Output: \n', str(nn.feed_forward(X)))
print('Loss: \n', str(np.mean(np.square(y - nn.feed_forward(X)))))

    

+---------EPOCH 1000---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Weights1:  [[ 5.84819654 -2.83368386  5.13214093 -3.74075524]
 [-3.09278081  5.71752398  5.24904849 -3.86982328]
 [ 0.68085259  0.48772492 -0.15015152 -1.32525018]]
Weights2: [[-6.54951966]
 [-6.6280888 ]
 [10.21916966]
 [-4.11528001]]
Predicted Output: 
 [[0.01002823]
 [0.95170554]
 [0.95277989]
 [0.96049488]
 [0.95949699]
 [0.07343378]
 [0.02828147]]
Loss: 
 0.002008024113478174


## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [0]:
from keras.datasets import mnist

In [17]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 1s 0us/step


In [0]:
class NeuralNetwork:
    def __init__(self):
        
        self.input = 28
        self.hiddenNodes = 29
        self.outputNodes = 9
        
        
        self.weights1 = np.random.randn(self.input, self.hiddenNodes)
        
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
    
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        
        self.hidden_sum = np.dot(X, self.weights1)
        
        
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        
        self.o_error = y - o 
        self.o_delta = self.o_error * self.sigmoidPrime(o) 
        
        self.z2_error = self.o_delta.dot(self.weights2.T) 
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) 
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) 
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [19]:
x_train.shape

(60000, 28, 28)

In [20]:
nn = NeuralNetwork()
nn.feed_forward(x_train).shape

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: RuntimeWarning: overflow encountered in exp
  


(60000, 28, 9)

In [0]:
for epoch in range(1000):
    nn.train(x_train, y_train)
print('+' + '---' * 3 + f'EPOCH {epoch+1}' + '---'*3 + '+')
print('Input: \n', X)
print('Actual Output: \n', y)
print('Weights1: ', nn.weights1)
print('Weights2:', nn.weights2)
print('Predicted Output: \n', str(nn.feed_forward(X)))
print('Loss: \n', str(np.mean(np.square(y - nn.feed_forward(X)))))

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?

In [26]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

image_size = 28
labels_size = 10
learning_rate = .05
steps_number = 1000
batch_size = 100

training_data = tf.placeholder(tf.float32, [None, image_size*image_size])
labels = tf.placeholder(tf.float32, [None, labels_size])

W = tf.Variable(tf.truncated_normal([image_size*image_size, labels_size], stddev=0.1))
b = tf.Variable(tf.constant(0.1, shape=[labels_size]))

output = tf.matmul(training_data, W) + b

loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=labels, logits=output))

train_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

correct_prediction = tf.equal(tf.argmax(output, 1), tf.argmax(labels, 1))

accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())

for i in range(steps_number):
    input_batch, labels_batch = mnist.train.next_batch(batch_size)
    
    feed_dict = {training_data: input_batch, labels: labels_batch}
    
    train_step.run(feed_dict=feed_dict)
    
    if i%100 == 0:
        train_accuracy = accuracy.eval(feed_dict=feed_dict)
        print("Step %d, training batch accuracy %g %%"%(i, train_accuracy*100))
        
test_accuracy = accuracy.eval(feed_dict={training_data: mnist.test.images, labels: mnist.test.labels})
print("Test accuracy: %g %%"%(test_accuracy*100))

W0716 23:04:04.727574 140194899007360 deprecation.py:323] From <ipython-input-26-25b6734dbc7d>:4: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0716 23:04:04.729189 140194899007360 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
W0716 23:04:04.738780 140194899007360 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be remove

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz


W0716 23:04:05.425171 140194899007360 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
W0716 23:04:05.427873 140194899007360 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.


Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz


W0716 23:04:05.702711 140194899007360 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0716 23:04:05.890154 140194899007360 deprecation.py:323] From <ipython-input-26-25b6734dbc7d>:20: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Step 0, training batch accuracy 14 %
Step 100, training batch accuracy 88 %
Step 200, training batch accuracy 82 %
Step 300, training batch accuracy 89 %
Step 400, training batch accuracy 84 %
Step 500, training batch accuracy 86 %
Step 600, training batch accuracy 90 %
Step 700, training batch accuracy 88 %
Step 800, training batch accuracy 89 %
Step 900, training batch accuracy 91 %
Test accuracy: 89.86 %
