<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [9]:
##### Your Code Here #####
import numpy as np

np.random.seed(1000)

X = np.array(([0, 0, 1],
             [0, 1, 1],
             [1, 0, 1],
             [0, 1, 0],
             [1, 0, 0],
             [1, 1, 1],
             [0, 0, 0]))

y = np.array(([0],
             [1],
             [1],
             [1],
             [1],
             [0],
             [0]))

In [10]:
print(X)
print(y)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]


In [1]:
# Initiate class for neural network
class NeuralNetwork:
    
    def __init__(self):
        
        #Set up arch
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNode = 1
        
        # Initialize weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNode)

In [3]:
#Check number of weights
nn = NeuralNetwork()
print(f' These weights {nn.weights1} are connecting inputs and hidden nodes')
print(f' These weights {nn.weights2} are connecting hidden nodes and output node')

 These weights [[ 1.53363953  0.88640657  0.94819195 -0.12871514]
 [ 1.06710757  0.06454665  1.13331103  0.56214783]
 [ 1.58911972 -0.83866214  0.13657376  1.13749784]] are connecting inputs and hidden nodes
 These weights [[-0.51572595]
 [-0.38562331]
 [ 2.02375146]
 [-1.22892099]] are connecting hidden nodes and output node


In [19]:
# Build complete class neural network
class NeuralNetwork:
    
    def __init__(self):
        
        #Set up arch
        self.inputs = 3
        self.hiddenNodes = 4
        self.outputNode = 1
        
        # Intitalize weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNode)
    
    def sigmoid(self, s):
        return 1 / (1 + np.exp(-s))
    
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1 - sx)
    
    def feed_forward(self, X):
        
        #Calculate hidden nodes
        self.hiddensum = np.dot(X, self.weights1)
        
        #Activation
        self.activated_hidden = self.sigmoid(self.hiddensum)
        
        #Output sum
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #Final output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        
        self.o_error = y - o
        
        #Apply derivative of sigmoid to error
        self.o_delta = self.o_error * self.sigmoidPrime(self.activated_output)
        
        #z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        #z2 delta
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.hiddensum)
        
        self.weights1 += X.T.dot(self.z2_delta)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
    
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)

In [20]:
#Training the net
nn = NeuralNetwork()

#Number of Epochs/Iteration
for i in range(10000):
    if (i+1 in [1, 2, 3, 4, 5]) or ((i+1) % 1000 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.26352791]
 [0.27769247]
 [0.26201984]
 [0.29041611]
 [0.26612988]
 [0.28692488]
 [0.26617368]]
Loss: 
 0.33300554369084573
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.43719323]
 [0.45317667]
 [0.46069673]
 [0.41557509]
 [0.42633163]
 [0.47376476]
 [0.39078094]]
Loss: 
 0.26125890745361163
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.51245689]
 [0.53072481]
 [0.5486053 ]
 [0.47590581]
 [0.50244476]
 [0.55632515]
 [0.44756391]]
Loss: 
 0.24551935729482913
+---------EPOCH 4---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [67]:
##### Your Code Here #####
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical
import numpy as np

In [68]:
#input img dimensions
rows_img = 28
cols_img = 28

In [69]:
#Split train test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [70]:
X_train = X_train.reshape(X_train.shape[0], rows_img * cols_img)
X_test = X_test.reshape(X_test.shape[0], rows_img * cols_img)

#Data normalization
X_train = X_train / 255
X_test = X_test / 255

In [71]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [72]:
print(X_train.shape)
print(X_test.shape)
y_train

(60000, 784)
(10000, 784)


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [73]:
#Turn MNIST into binary problem

y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [74]:
print(y_train.shape)
y_train

(60000,)


array([0., 1., 0., ..., 0., 0., 0.])

In [75]:
#Build class neural network

class NeuralNetwork(object):
    
    def __init__(self):
        self.inputLayerSize = 784
        self.outputLayerSize = 1
        self.hiddenLayerSize = 10
        
        # Initialize random weights
        self.W1 = np.random.randn(self.inputLayerSize, self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize, self.outputLayerSize)
    
    def forward(self, X):
        #Forward propagation
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        ŷ = self.sigmoid(self.z3)
        return ŷ
    
    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))
    
    def sigmoidPrime(self, z):
        dx = self.sigmoid(z)
        return dx * (1 - dx)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.ŷ = self.forward(X)
        J = 0.5 * sum((y - self.ŷ)**2)
        return J
    
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y.
        self.ŷ = self.forward(X)
        
        delta3 = np.multiply(-(y - self.ŷ), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.multiply(np.dot(delta3, self.W2.T), self.sigmoidPrime(self.z2))
        dJdW1 = np.dot(X.T, delta2)
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector.
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single parameter vector
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize, self.hiddenLayerSize))
        W2_end = W1_end + np.multiply(self.hiddenLayerSize, self.outputLayerSize)
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X,y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))

In [76]:
from scipy import optimize

class trainer(object):
    def __init__(self, N):
        #Make local reference to network
        self.N = N
    
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))
    
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = self.N.computeGradients(X, y)
        return cost, grad
    
    def train(self, X, y):
        #Internal variables for callback function
        self.X = X
        self.y = y
        
        #Create empty list to store costs
        self.J = []
        
        params0 = self.N.getParams()
        
        options = {'maxiter' : 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(X, y), options=options, callback=self.callbackF)
        self.N.setParams(_res.x)
        self.optimizationResults = _res

In [77]:
nn = NeuralNetwork()
t = trainer(nn)

In [83]:
size = 200
X_train_1 = X_train[:size]
y_train_1 = np.expand_dims(y_train[:size], axis = 1)

In [84]:
#My laptop cannot train the set unfortunately. Or if you can help me to execute this, I'll really appreciate it
t.train(X_train_1, y_train_1)

KeyboardInterrupt: 

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?