<a href="https://colab.research.google.com/github/tortas/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/module2-backpropagation/LS_DS_422_Backprop_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [0]:
import numpy as np

In [0]:
# Dataset

X = np.array(([0,0,1],
              [0,1,1],
              [1,0,1],
              [0,1,0],
              [1,0,0],
              [1,1,1],
              [0,0,0]), dtype=float)

y = np.array(([0],
              [1],
              [1],
              [1],
              [1],
              [0],
              [0]), dtype=float)

In [0]:
class NeuralNetwork:
  def __init__(self):
    # Set up architecture
    self.input = 3
    self.hiddenNodes = 4
    self.outputNodes = 1
    
    # Initial weights
    # 3x4 matrix array for first layer
    self.weights1 = np.random.randn(self.input, self.hiddenNodes)
    # 4x1 matrix for hidden to output
    self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
    
  def sigmoid(self, s):
    return 1 / (1+np.exp(-s))
  
  def sigmoidPrime(self, s):
    return s * (1-s)
  
  def feed_forward(self,X):
    """
    Calculate the NN inference using feed forward
    """
    
    # Weighted sum of inputs & hidden
    self.hidden_sum = np.dot(X, self.weights1)
    
    # Activations of weighted sum
    self.activated_hidden = self.sigmoid(self.hidden_sum)
    
    # Weighted sum between hidden and output
    self.output_sum = np.dot(self.activated_hidden, self.weights2)
    
    # Final activation of output
    self.activated_output = self.sigmoid(self.output_sum)
    
    return self.activated_output
  
  def backward(self, X, y, o):
    """
    Backward propogate through the network
    """
    self.o_error = y - o #error in output
    self.o_delta = self.o_error * self.sigmoidPrime(o) #apply derivative of sigmoid
    
    self.z2_error = self.o_delta.dot(self.weights2.T)
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
    
    self.weights1 += X.T.dot(self.z2_delta)
    self.weights2 += self.activated_hidden.T.dot(self.o_delta)
    
  def train(self, X, y):
    o = self.feed_forward(X)
    self.backward(X, y, o)

In [8]:
nn = NeuralNetwork()

for i in range(1000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 50 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.60132595]
 [0.67183774]
 [0.71394443]
 [0.74050442]
 [0.75719678]
 [0.75994588]
 [0.67224845]]
Loss: 
 0.2438340344371428
+---------EPOCH 2---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.56567734]
 [0.64788781]
 [0.6822731 ]
 [0.71474275]
 [0.72395626]
 [0.73695134]
 [0.63191381]]
Loss: 
 0.23498691769371058
+---------EPOCH 3---------+
Input: 
 [[0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]]
Actual Output: 
 [[0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]]
Predicted Output: 
 [[0.53588412]
 [0.62911227]
 [0.6562093 ]
 [0.69384586]
 [0.69582337]
 [0.7190304 ]
 [0.59735003]]
Loss: 
 0.2290010126834722
+---------EPOCH

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [0]:
##### Your Code Here #####

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?