<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [1]:
import pandas as pd
import numpy as np

In [3]:
##### Your Code Here #####
# Multiperceptron from class to fit this
# Extra input neuron is here
# Copy paste from class
data = {'x1': [0,0,1,0,1,1,0],
        'x2': [0,1,0,1,0,1,0],
        'x3': [1,1,1,0,0,1,0]}
df = pd.DataFrame.from_dict(data).astype('int')

In [5]:
corr = [[0],[1],[1],[1],[1],[0],[0]]

In [113]:
# Teacher's function
class NeuralNetwork:
    def __init__(self):
        # Set up Architecture of Neural Network
        self.inputs = 500
        self.hiddenNodes = 10
        self.outputNodes = 10

        # Initial Weights
        # 2x3 Matrix Array for the First Layer
        # Arrows in first section
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes)
       
        # 3x1 Matrix Array for Hidden to Output
        # Arrows in second section
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes)
    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        # sigmoid derivative function
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        # Bias term is not here cause who cares lol
        return self.activated_output
    
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        # Vector of errors
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

Example of what weights look like

In [13]:
print(f'''
L1|Wgt: \n{nn.weights1}
L2|Wgt: \n{nn.weights2}
''')


L1|Wgt: 
[[0.56148589 0.29255932 0.4725921  0.72739332]
 [0.01372413 0.38592464 0.78199007 0.05240753]
 [0.37122583 0.48056739 0.17912562 0.50223014]]
L2|Wgt: 
[[0.29839476]
 [0.70795497]
 [0.769425  ]
 [0.34102622]]



In [21]:
X = df.values

In [22]:
nn = NeuralNetwork()
output = nn.feed_forward(X)
print(f'''
IN: \n{df.values}
OT: \n{output}
''')


IN: 
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
OT: 
[[0.75546157]
 [0.79174367]
 [0.80024702]
 [0.77521227]
 [0.78502444]
 [0.8277613 ]
 [0.73563186]]



In [23]:
err = corr - output
err

array([[-0.75546157],
       [ 0.20825633],
       [ 0.19975298],
       [ 0.22478773],
       [ 0.21497556],
       [-0.8277613 ],
       [-0.73563186]])

In [28]:
nn = NeuralNetwork()
y = corr
# Teacher's loop
for i in range(10000):
    if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 1---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.74529993]
 [0.77573661]
 [0.77692828]
 [0.74461994]
 [0.74540694]
 [0.80074295]
 [0.70768758]]
Loss: 
 0.2753678034646191
+---------EPOCH 2---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.6753626 ]
 [0.69778596]
 [0.69817499]
 [0.67168802]
 [0.67167454]
 [0.71712841]
 [0.64541915]]
Loss: 
 0.25499595784157053
+---------EPOCH 3---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0], [1], [1], [1], [1], [0], [0]]
Predicted Output: 
 [[0.62368109]
 [0.63825754]
 [0.63801331]
 [0.61746245]
 [0.61690232]
 [0.651139  ]
 [0.60041925]]
Loss: 
 0.24692202082333933
+---------EPOCH 4---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


### Parts
1. Gathering & Transforming the Data
2. Making MNIST a Binary Problem
3. Estimating your Neural Network (the part you focus on)

### Gathering the Data 

`keras` has a handy method to pull the mnist dataset for you. You'll notice that each observation is a 28x28 arrary which represents an image. Although most Neural Network frameworks can handle higher dimensional data, that is more overhead than necessary for us. We need to flatten the image to one long row which will be 784 values (28X28). Basically, you will be appending each row to one another to make on really long row. 

Doing 2D matrix is possible w/ NN but gross, reshape and make a vector 

In [92]:
import numpy as np
import pandas as pd
from tensorflow.keras.datasets import mnist;
from tensorflow.keras.utils import to_categorical;

In [93]:
# input image dimensions
img_rows, img_cols = 28, 28

In [94]:
# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [95]:
x_train = x_train.reshape(x_train.shape[0], img_rows * img_cols)
x_test = x_test.reshape(x_test.shape[0], img_rows * img_cols)

# Normalize Our Data
x_train = x_train / 255
x_test = x_test / 255

In [96]:
# Now the data should be in a format you're more familiar with
x_train.shape

(60000, 784)

### Making MNIST a Binary Problem 
MNIST is multiclass classification problem; however we haven't covered all the necessary techniques to handle this yet. 

FOR MULTICLASS (Don't need to do this): You would need to one-hot encode the target, use a different loss metric, and use softmax activations for the last layer. This is all stuff we'll cover later this week, but let us simply the problem for now: Zero or all else.

In [122]:
class Neural_Network(object):
    def __init__(self):        
        #Define Hyperparameters
        self.inputLayerSize = 500
        self.outputLayerSize = 10
        self.hiddenLayerSize = 1
        
        #Weights (parameters)
        self.W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
        self.W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
        
    def forward(self, X):
        #Propogate inputs though network
        self.z2 = np.dot(X, self.W1)
        self.a2 = self.sigmoid(self.z2)
        self.z3 = np.dot(self.a2, self.W2)
        yHat = self.sigmoid(self.z3) 
        return yHat
        
    def sigmoid(self, z):
        #Apply sigmoid activation function to scalar, vector, or matrix
        return 1/(1+np.exp(-z))
    
    def sigmoidPrime(self,z):
        #Gradient of sigmoid
        return np.exp(-z)/((1+np.exp(-z))**2)
    
    def costFunction(self, X, y):
        #Compute cost for given X,y, use weights already stored in class.
        self.yHat = self.forward(X)
        J = 0.5*sum((y-self.yHat)**2)
        return J
        
    def costFunctionPrime(self, X, y):
        #Compute derivative with respect to W and W2 for a given X and y:
        self.yHat = self.forward(X)
        
        delta3 = np.multiply(-(y-self.yHat), self.sigmoidPrime(self.z3))
        dJdW2 = np.dot(self.a2.T, delta3)
        
        delta2 = np.dot(delta3, self.W2.T)*self.sigmoidPrime(self.z2)
        dJdW1 = np.dot(X.T, delta2)  
        
        return dJdW1, dJdW2
    
    #Helper Functions for interacting with other classes:
    def getParams(self):
        #Get W1 and W2 unrolled into vector:
        params = np.concatenate((self.W1.ravel(), self.W2.ravel()))
        return params
    
    def setParams(self, params):
        #Set W1 and W2 using single paramater vector.
        W1_start = 0
        W1_end = self.hiddenLayerSize * self.inputLayerSize
        self.W1 = np.reshape(params[W1_start:W1_end], (self.inputLayerSize , self.hiddenLayerSize))
        W2_end = W1_end + self.hiddenLayerSize*self.outputLayerSize
        self.W2 = np.reshape(params[W1_end:W2_end], (self.hiddenLayerSize, self.outputLayerSize))
        
    def computeGradients(self, X, y):
        dJdW1, dJdW2 = self.costFunctionPrime(X, y)
        return np.concatenate((dJdW1.ravel(), dJdW2.ravel()))
    
from scipy import optimize
class trainer(object):
    def __init__(self, N):
        #Make Local reference to network:
        self.N = N
        
    def callbackF(self, params):
        self.N.setParams(params)
        self.J.append(self.N.costFunction(self.X, self.y))   
        
    def costFunctionWrapper(self, params, X, y):
        self.N.setParams(params)
        cost = self.N.costFunction(X, y)
        grad = self.N.computeGradients(X,y)
        
        return cost, grad
        
    def train(self, X, y):
        #Make an internal variable for the callback function:
        self.X = X
        self.y = y

        #Make empty list to store costs:
        self.J = []
        
        params0 = self.N.getParams()

        options = {'maxiter': 200, 'disp' : True}
        _res = optimize.minimize(self.costFunctionWrapper, params0, jac=True, method='BFGS', \
                                 args=(X, y), options=options, callback=self.callbackF)

        self.N.setParams(_res.x)
        self.optimizationResults = _res

In [97]:
y_temp = np.zeros(y_train.shape)
y_temp[np.where(y_train == 0.0)[0]] = 1
y_train = y_temp

y_temp = np.zeros(y_test.shape)
y_temp[np.where(y_test == 0.0)[0]] = 1
y_test = y_temp

In [98]:
# A Nice Binary target for ya to work with
y_train

array([0., 1., 0., ..., 0., 0., 0.])

### Estimating Your `net

In [99]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((60000, 784), (10000, 784), (60000,), (10000,))

In [100]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((60000, 784), (10000, 784), (60000,), (10000,))

In [101]:
B = y_train.reshape(60000,1)

In [102]:
A = x_train

In [103]:
A, B

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]), array([[0.],
        [1.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]))

In [104]:
A.shape,B.shape

((60000, 784), (60000, 1))

In [105]:
dfA = pd.DataFrame(A)
dfB = pd.DataFrame(B)

In [106]:
dfA = dfA.iloc[0:500]
dfB = dfB.iloc[0:500]

In [107]:
from sklearn.decomposition import PCA

In [108]:
A = dfA.values
B = dfB.values
A, B[0]

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]), array([0.]))

In [109]:
A.shape, B.shape

((500, 784), (500, 1))

In [110]:
pca = PCA(n_components=10)
A = pca.fit_transform(A)

In [111]:
A.shape, B.shape

((500, 10), (500, 1))

In [117]:
nn = NeuralNetwork()

for x in range(10):
    print(str(nn.feed_forward(A)))
    nn.train(A,B)

ValueError: shapes (500,10) and (500,10) not aligned: 10 (dim 1) != 500 (dim 0)

In [115]:
print(f'''
A: \n{A}
B: \n{B.shape}
''')


A: 
[[ 7.69367606e-01  1.27551874e+00 -5.64666995e-01 ... -2.65237926e-01
   1.29449089e+00 -6.17370046e-01]
 [ 4.24496022e+00  1.81247474e-01 -4.30222209e-04 ...  9.27393504e-01
  -1.10874106e+00 -5.32730053e-01]
 [-2.52452623e-02 -1.50210361e+00 -2.86451980e-01 ...  2.09677315e+00
  -1.09971341e+00  1.69257763e+00]
 ...
 [-8.44386958e-01 -2.85494854e-01  6.03764384e-01 ... -4.81249513e-01
   9.97259744e-01  8.83141671e-01]
 [-6.92635095e-01 -4.41452168e-01  2.03871804e+00 ...  1.66341230e-01
  -3.28573873e-01  5.91756775e-01]
 [-2.05368875e-01  1.72643246e+00  2.10361282e+00 ... -2.14532996e+00
  -1.24520317e+00  8.66359348e-01]]
B: 
(500, 1)



In [123]:
NN = Neural_Network()
T = trainer(NN)
T.train(A, B)

ValueError: shapes (500,10) and (500,1) not aligned: 10 (dim 1) != 500 (dim 0)

In [ ]:
print("Predicted Output: \n" + str(NN.forward(X))) 
print("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss

In [ ]:
import matplotlib.pyplot as plt
plt.plot(T.J)
plt.xlabel('Iterations')
plt.ylabel('Cost')
plt.show()     

## Stretch Goals: 

- Make MNIST a multiclass problem using cross entropy & soft-max
- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?