# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [237]:
import numpy as np
X = np.array([[0,0,1], [0,1,1], [1,0,1], [0,1,0], [1,0,0], [1,1,1], [0,0,0]])
y = np.array([0,1,1,1,1,0,0]).reshape(-1,1)

In [238]:
X.shape, y.shape

((7, 3), (7, 1))

In [239]:
class NeuralNetwork: 
    def __init__(self, inputs, hiddenNodes, outputNodes):
        # Set upArchietecture 
        self.inputs = inputs
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes
        
        #Initial weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) 
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) 
    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        #derivative of the sigmoid
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """
        
        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error
        
        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
            
    def get_attributes(self):
        attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']
        [print(i + '\n', getattr(nn,i), '\n'+'---'*3) for i in dir(nn) if i in attributes]

In [240]:
nn = NeuralNetwork(inputs=3, hiddenNodes=4, outputNodes=1)

for i in range(10000):
    if ((i+1) % 5000 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 5000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.00332511]
 [0.98209352]
 [0.98158553]
 [0.98415048]
 [0.98476593]
 [0.0270641 ]
 [0.0131144 ]]
Loss: 
 0.00029407539147972795
+---------EPOCH 10000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.0021159 ]
 [0.98769195]
 [0.98739548]
 [0.98901561]
 [0.9893712 ]
 [0.01849642]
 [0.00952102]]
Loss: 
 0.00014017638908818625


## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [219]:
import idx2numpy

train_file = 'data/train-images.idx3-ubyte'
train_raw = idx2numpy.convert_from_file(train_file)

train_label_file = 'data/train-labels.idx1-ubyte'
train_labels = idx2numpy.convert_from_file(train_label_file).reshape(-1,1)

train_raw.shape, train_labels.shape

((60000, 28, 28), (60000, 1))

In [220]:
train_flat = []
for i in range(len(train)):
    train_flat.append(train[i].flatten())
    
train_flat = np.array(flattened)
train_flat.shape

(60000, 784)

In [221]:
X = train_flat
y = train_labels

In [222]:
y[0]

array([5], dtype=uint8)

In [228]:
nn = NeuralNetwork(inputs=784, hiddenNodes=28, outputNodes=10)

In [229]:
#batches, test on first 100:

train_counter = 0
X_batch = X[train_counter:train_counter+100]
y_batch = y[train_counter:train_counter+100]

In [233]:
%%time
for i in range(1000):
    nn.train(X_batch,y_batch)

/home/jm/.local/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


CPU times: user 3.63 s, sys: 1.88 s, total: 5.51 s
Wall time: 1.61 s


In [234]:
nn.activated_output.shape

(100, 10)

In [235]:
import pandas as pd
pd.DataFrame(nn.activated_output)

0         1         2         3    4    5         6         7         8  \
0   1.0  1.000000  1.000000  1.000000  1.0  1.0  0.999999  1.000000  1.000000   
1   1.0  1.000000  0.999998  0.999996  1.0  1.0  0.999999  0.999999  1.000000   
2   1.0  0.999999  0.999999  0.999999  1.0  1.0  0.999999  0.999996  0.999999   
3   1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
4   1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
5   1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
6   1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
7   1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
8   1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
9   1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
10  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
11  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
12  1.0  0.999999  0.999999  0.999999  1.0  1.0  0.999999  0.999999  0.999999   
13  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
14  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
15  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
16  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
17  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
18  1.0  1.000000  0.999999  0.999999  1.0  1.0  1.000000  1.000000  1.000000   
19  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
20  1.0  0.999999  1.000000  1.000000  1.0  1.0  1.000000  0.999999  1.000000   
21  1.0  0.999996  0.999997  0.999987  1.0  1.0  0.999997  0.999998  0.999999   
22  1.0  0.999997  0.999998  0.999999  1.0  1.0  0.999998  0.999998  0.999997   
23  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
24  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
25  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
26  1.0  0.999997  0.999997  0.999999  1.0  1.0  0.999996  0.999996  0.999997   
27  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
28  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
29  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
..  ...       ...       ...       ...  ...  ...       ...       ...       ...   
70  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
71  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
72  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
73  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
74  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
75  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
76  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
77  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
78  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
79  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
80  1.0  0.999997  0.999997  0.999994  1.0  1.0  0.999997  0.999998  0.999996   
81  1.0  1.000000  0.999999  0.999999  1.0  1.0  0.999999  1.000000  1.000000   
82  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
83  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
84  1.0  1.000000  0.999999  1.000000  1.0  1.0  0.999999  0.999999  1.000000   
85  1.0  1.000000  1.000000  1.000000  1.0  1.0  1.000000  1.000000  1.000000   
86  1.0  1.000000  0.999999  0.999999  1.0  1.0  1.000000  0.999999  1.000000   
87  1.0  1.000000  1.000000  1.000000

In [ ]:
#no idea how to get the NN to output 0-9 

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?