# Backpropagation Practice

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [276]:
import numpy as np
X = np.array([[0,0,1], [0,1,1], [1,0,1], [0,1,0], [1,0,0], [1,1,1], [0,0,0]])
y = np.array([0,1,1,1,1,0,0]).reshape(-1,1)

In [277]:
X.shape, y.shape

((7, 3), (7, 1))

In [290]:
class NeuralNetwork: 
    def __init__(self, inputs, hiddenNodes, outputNodes):
        # Set upArchietecture 
        self.inputs = inputs
        self.hiddenNodes = hiddenNodes
        self.outputNodes = outputNodes
        
        #Initial weights
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes) 
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) 
    
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        #derivative of the sigmoid
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """
        
        #Weighted sume of inputs and hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        #Acivations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        #Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        return self.activated_output
    
    def backward(self, X, y, o):
        """
        Backward propagate through the network
        """
        self.o_error = y - o #error in output
        self.o_delta = self.o_error * self.sigmoidPrime(o) # apply derivative of sigmoid to error
        
        self.z2_error = self.o_delta.dot(self.weights2.T) # z2 error: how much our hidden layer weights were off
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.activated_hidden)
        
        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X, y, o)
            
    def get_attributes(self):
        attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'output']
        [print(i + '\n', getattr(nn,i), '\n'+'---'*3) for i in dir(nn) if i in attributes]

In [291]:
nn = NeuralNetwork(inputs=3, hiddenNodes=4, outputNodes=1)

for i in range(10000):
    if ((i+1) % 5000 == 0):
        print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
        print('Input: \n', X)
        print('Actual Output: \n', y)
        print('Predicted Output: \n', str(nn.feed_forward(X)))
        print("Loss: \n", str(np.mean(np.square(y - nn.feed_forward(X)))))
    nn.train(X,y)

+---------EPOCH 5000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.00420612]
 [0.98186607]
 [0.98807408]
 [0.98340245]
 [0.98957603]
 [0.02049924]
 [0.02690924]]
Loss: 
 0.00028817460986999536
+---------EPOCH 10000---------+
Input: 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]
 [0 0 0]]
Actual Output: 
 [[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]
Predicted Output: 
 [[0.00280092]
 [0.98756335]
 [0.99141769]
 [0.98868473]
 [0.99257264]
 [0.01422455]
 [0.01838031]]
Loss: 
 0.00013707802034756972


## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [250]:
import idx2numpy

train_file = 'data/train-images.idx3-ubyte'
train_raw = idx2numpy.convert_from_file(train_file)

train_label_file = 'data/train-labels.idx1-ubyte'
train_labels = idx2numpy.convert_from_file(train_label_file).reshape(-1,1)

train_raw.shape, train_labels.shape

((60000, 28, 28), (60000, 1))

In [251]:
train_flat = []
for i in range(len(train)):
    train_flat.append(train[i].flatten())
    
train_flat = np.array(train_flat)
train_flat.shape

(60000, 784)

In [253]:
import keras

X = train_flat.astype('float32')
y = train_labels.astype('float32')
y = keras.utils.to_categorical(y, 10)

Using TensorFlow backend.


In [254]:
y[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [269]:
nn = NeuralNetwork(inputs=784, hiddenNodes=28, outputNodes=10)

In [270]:
#batches, test on first 500:

train_counter = 0
X_batch = X[train_counter:train_counter+500]
y_batch = y[train_counter:train_counter+500]

In [271]:
%%time
for i in range(1000):
    nn.train(X_batch,y_batch)

/home/jm/.local/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: overflow encountered in exp
  del sys.path[0]


CPU times: user 24.4 s, sys: 11.6 s, total: 36 s
Wall time: 10.6 s


In [272]:
nn.activated_output.shape

(500, 10)

In [273]:
import pandas as pd
pd.DataFrame(nn.activated_output)

0              1             2             3              4  \
0    1.454558e-05   1.142568e-70  1.617251e-41  6.569474e-08   5.900727e-70   
1    9.075705e-07  1.241320e-102  1.936808e-48  8.168581e-10   1.312897e-92   
2    6.312361e-06   7.889795e-99  6.156182e-45  2.599255e-09   1.427702e-82   
3    2.485669e-08  1.837398e-138  3.113941e-61  1.092224e-12  1.883683e-119   
4    3.358239e-07  4.414933e-117  1.803737e-58  7.949093e-12  1.170859e-105   
5    3.155080e-08  3.162952e-127  8.106345e-59  1.654973e-12  5.669653e-112   
6    1.150189e-07  2.866167e-113  4.973746e-55  1.888403e-11   3.828937e-99   
7    1.333112e-07  1.406613e-112  1.766055e-56  1.112138e-11  2.616130e-102   
8    8.495874e-07  1.695550e-102  2.985576e-51  1.981958e-10   2.335726e-94   
9    1.234012e-07  2.980944e-119  5.998671e-54  3.721557e-12  7.685199e-105   
10   1.498040e-06   5.609146e-94  1.362000e-48  1.511925e-09   2.505206e-86   
11   9.913989e-07  8.014380e-103  7.902381e-53  1.122187e-10   2.414483e-97   
12   3.439982e-07  7.340316e-102  1.712595e-52  5.274605e-11   7.739181e-97   
13   1.803391e-07  8.476960e-114  4.118496e-54  5.718393e-11   2.237418e-99   
14   5.306983e-07  1.679975e-103  1.808871e-50  1.473984e-10   6.652732e-95   
15   5.454297e-07   9.418970e-99  9.652742e-45  3.875046e-11   1.911494e-86   
16   7.729771e-09  4.845517e-150  3.186245e-62  4.222778e-14  3.389687e-128   
17   2.649021e-06   3.345411e-93  2.875136e-48  6.546359e-09   4.232661e-84   
18   2.770053e-07  8.359189e-121  5.614197e-52  2.137096e-10   2.460692e-94   
19   6.084311e-08  3.393973e-120  6.388466e-57  1.881678e-12  1.210817e-108   
20   3.809186e-08  5.335413e-125  4.093650e-61  1.124105e-11  9.033506e-107   
21   1.195071e-06   3.903638e-91  2.668446e-44  2.290289e-10   4.130034e-80   
22   4.648071e-07  3.547838e-113  3.434073e-54  3.351136e-11  3.308649e-100   
23   2.485669e-08  1.837398e-138  3.113941e-61  1.092224e-12  1.883683e-119   
24   6.638644e-06   2.756920e-78  5.850220e-42  1.111522e-08   2.731061e-76   
25   2.306694e-07  5.418747e-108  7.642358e-52  8.417600e-12  6.274719e-102   
26   7.619840e-07   3.769833e-99  8.972591e-52  3.842748e-10   1.032404e-89   
27   5.054117e-07  2.245769e-100  2.112687e-51  4.975098e-11   1.355736e-95   
28   1.399249e-05   9.385562e-82  2.273568e-42  2.838807e-09   2.631583e-80   
29   9.044780e-07   1.075536e-98  1.399112e-47  2.394762e-09   1.244824e-85   
..            ...            ...           ...           ...            ...   
470  1.005593e-05   1.387426e-84  1.499821e-44  8.822356e-09   1.117191e-80   
471  6.712421e-07   2.670252e-96  2.660943e-51  4.250161e-10   2.885399e-89   
472  5.651273e-08  8.301307e-131  3.003873e-55  2.147809e-13  3.751434e-118   
473  1.270106e-05   1.610307e-87  2.301881e-45  4.104001e-09   3.802022e-82   
474  2.544820e-06   4.263270e-84  3.183218e-46  1.901289e-09   1.495276e-82   
475  2.485669e-08  1.837398e-138  3.113941e-61  1.092224e-12  1.883683e-119   
476  7.590067e-09  2.264369e-142  2.738243e-60  1.100568e-13  2.625892e-121   
477  3.099519e-07  4.331980e-121  1.612288e-51  5.405319e-12  1.770049e-105   
478  1.454559e-05   1.142590e-70  1.617260e-41  6.569486e-08   5.900816e-70   
479  9.204378e-08  6.575430e-123  3.755896e-58  4.957583e-12  9.724704e-110   
480  3.926944e-08  4.335753e-131  6.835933e-61  7.528388e-13  6.917434e-114   
481  9.583746e-08  1.210778e-121  8.783156e-56  5.841477e-12  3.921114e-106   
482  3.951346e-07  3.513227e-106  1.138535e-53  3.379771e-10   4.834235e-93   
483  2.188566e-05   1.405149e-74  1.004502e-38  1.946066e-08   7.668378e-75   
484  4.360615e-07  4.576032e-101  5.949947e-50  8.447680e-11   1.984231e-92   
485  6.084311e-08  3.393973e-120  6.388466e-57  1.881678e-12  1.210817e-108   
486  2.284318e-08  1.509805e-129  3.301042e-60  4.941377e-13  3.471603e-112   
487  2.401145e-07  4.252120e-117  6.902706e-54  2.898277e-11  1.776177e-103   
488  4.634544e-07  1.248251e-106  5.659067e-53  1.894596e-10   1.0

In [ ]:
#no idea how to get the NN to output 0-9 

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?