# Neural Networks Sprint Challenge

## 1) Define the following terms:

- Neuron
- Input Layer
- Hidden Layer
- Output Layer
- Activation
- Backpropagation

## <u>Neuron</u>:
### The basic unit of computation in a neural network is the neuron, often called a node or unit. It receives input from some other nodes, or from an external source and computes an output. Each input has an associated weight (w), which is assigned on the basis of its relative importance to other inputs. The node applies a function f (defined below) to the weighted sum of its inputs as shown in the Figure below:





<img src="https://ujwlkarn.files.wordpress.com/2016/08/screen-shot-2016-08-09-at-3-42-21-am.png?w=568&h=303" alt="Image of Neuron" title="An Image of a Neuron"/>



> ### **Operations at one neuron of a neural network**:

<img src="https://cdn-images-1.medium.com/max/1600/1*H2GFATdntBwfKcR4Kuc5mw.png" alt="op" title="ops"/>

___

<p style="page-break-after:always;"></p>



## <u>Layers</u>: 
### A node layer is a row of neurons that turn on or off as the input is fed through the net. Each layer’s output is simultaneously the subsequent layer’s input, starting from an initial input layer receiving your data.


> ### <u>Input Layer</u>: First layer - this is where information from the outside world enters the neural network. Nodes in this layer pass information to the hidden layer.
> ### <u>Hidden Layer</u>: Nodes in the hidden layer have no direct connection to the outside world - they perform computations and transfer information from the input nodes to the output nodes.
> ### <u>Output Layer</u>: This is the layer where information exits the neural network (ideally structured that it is interpretable by humans)


<img src="https://www.jeremyjordan.me/content/images/2017/07/Screen-Shot-2017-07-26-at-1.44.58-PM.png" alt="A diagram of a Neural Network" title="Neural Network Diagram" height="408.24" width="715.05"  />




___
<p style="page-break-after:always;"></p>

## <u>Activation Function</u>: 
### An activation function decides, whether a neuron should be activated or not by calculating weighted sum and further adding bias with it. The purpose of the activation function is to introduce non-linearity into the output of a neuron.

<img src="https://qph.fs.quoracdn.net/main-qimg-d131b1b1ffb1ae9d842e135f05635f1c" alt="act" title="acts" height="899.2" width="1199.2"/>

___
<p style="page-break-after:always;"></p>

## <u>Backpropagation</u>: 

### Backpropagation is a method used in artificial neural networks to calculate a gradient that is needed in the calculation of the weights to be used in the network. Backpropagation is shorthand for "the backward propagation of errors," since an error is computed at the output and distributed backwards throughout the network’s layers.
____

## 2) Create a perceptron class that can model the behavior of an AND gate. You can use the following table as your training data:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 1  | 1  | 1  | 1 |
| 1  | 0  | 1  | 0 |
| 0  | 1  | 1  | 0 |
| 0  | 0  | 1  | 0 |

## Creating an AND gate with a single perceptron



In [23]:
import numpy as np


#Random State for reproducibility

np.random.seed(43)


#The first two columns represent T/F, the third column is a constant bias
inputs = np.array([[1,1,1],
                   [1,0,1],
                   [0,1,1],
                   [0,0,1]])

#Correct Labels
correct_outputs = np.array([[1],
                  [0],
                  [0],
                  [0]])

# Initialize weights, all in the range (-1, 1)
weights = 2 * np.random.random((3,1)) - 1

In [24]:
class Perceptron(object):

    def __init__(self, no_of_inputs, epochs=10000, learning_rate=0.01):
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.weights = np.zeros(no_of_inputs + 1)
           
    def predict(self, inputs):
        summation = np.dot(inputs, self.weights[1:]) + self.weights[0]
        if summation > 0:
          activation = 1
        else:
          activation = 0            
        return activation

    def train(self, training_inputs, labels):
        for _ in range(self.epochs):
            for inputs, label in zip(training_inputs, labels):
                prediction = self.predict(inputs)
                self.weights[1:] += self.learning_rate * (label - prediction) * inputs
                self.weights[0] += self.learning_rate * (label - prediction)

In [25]:
classifier = Perceptron(3)

In [26]:
classifier.train(inputs,correct_outputs)

In [27]:
preds = []
for i in range(len(inputs)):
    preds.append(classifier.predict(inputs[i]))

In [28]:
preds

[1, 0, 0, 0]

In [29]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(preds, correct_outputs)
print(accuracy)

1.0


## 3) Implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. 
- Your network must have one hidden layer. 
- You do not have to update weights via gradient descent. You can use something like the derivative of the sigmoid function to update weights.
- Train your model on the Heart Disease dataset from UCI:

[Github Dataset](https://github.com/ryanleeallred/datasets/blob/master/heart.csv)

[Raw File on Github](https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv)


### Load Data

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')

In [7]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [129]:
X = df.iloc[:,0:4].values
y = df.iloc[:,13:14].values

In [130]:
X.shape

(303, 4)

In [131]:
y = y.flatten()

### Activations

In [132]:
def tanh(x):
    return (1.0 - numpy.exp(-2*x))/(1.0 + numpy.exp(-2*x))

def tanh_derivative(x):
    return (1 + tanh(x))*(1 - tanh(x))

def softmax(A):
    e = np.exp(A)
    return  e / e.sum(axis=0).reshape((-1,1))

In [133]:
class NeuralNetwork:
    #########
    # parameters
    # ----------
    # self:      the class object itself
    # net_arch:  consists of a list of integers, indicating
    #            the number of neurons in each layer, i.e. the network architecture
    #########
    def __init__(self, net_arch):
        numpy.random.seed(0)
        
        # Initialized the weights, making sure we also 
        # initialize the weights for the biases that we will add later
        self.activity = tanh
        self.softmax = softmax
        self.activity_derivative = tanh_derivative
        self.layers = len(net_arch)
        self.steps_per_epoch = 1
        self.arch = net_arch
        self.weights = []
        self.multi = False

        # Random initialization with range of weight values (-1,1)
        for layer in range(self.layers - 1):
            w = 2*numpy.random.rand(net_arch[layer] + 1, net_arch[layer+1]) - 1
            self.weights.append(w)
    
    def _forward_prop(self, x):
        y = x

        for i in range(len(self.weights)-1):
            activation = numpy.dot(y[i], self.weights[i])
            activity = self.activity(activation)

            # add the bias for the next layer
            activity = numpy.concatenate((numpy.ones(1), numpy.array(activity)))
            y.append(activity)

        # last layer
        if self.multi == True:
            activation = numpy.dot(y[-1], self.weights[-1])
            activity = self.softmax(activation)
            y.append(activity)
            
        else:
            activation = numpy.dot(y[-1], self.weights[-1])
            activity = self.activity(activation)
            y.append(activity)
        
        return y
    
    def _back_prop(self, y, target, learning_rate):
        error = target - y[-1]
        delta_vec = [error * self.activity_derivative(y[-1])]

        # we need to begin from the back, from the next to last layer
        for i in range(self.layers-2, 0, -1):
            error = delta_vec[-1].dot(self.weights[i][1:].T)
            error = error*self.activity_derivative(y[i][1:])
            delta_vec.append(error)

        # Now we need to set the values from back to front
        delta_vec.reverse()
        
        # Finally, we adjust the weights, using the backpropagation rules
        for i in range(len(self.weights)):
            layer = y[i].reshape(1, self.arch[i]+1)
            delta = delta_vec[i].reshape(1, self.arch[i+1])
            self.weights[i] += learning_rate*layer.T.dot(delta)
    
    #########
    # parameters
    # ----------
    # self:    the class object itself
    # data:    the set of all possible pairs of booleans True or False indicated by the integers 1 or 0
    # labels:  the result of the logical operation 'xor' on each of those input pairs
    #########
    def fit(self, data, labels, learning_rate=0.1, epochs=100, multi = False):
        
        self.multi = multi
        # Add bias units to the input layer - 
        # add a "1" to the input data (the always-on bias neuron)
        ones = numpy.ones((1, data.shape[0]))
        Z = numpy.concatenate((ones.T, data), axis=1)
        
        for k in range(epochs):
            if (k+1) % 75000 == 0:
                print('epochs: {}'.format(k+1))
        
            sample = numpy.random.randint(X.shape[0])

            # We will now go ahead and set up our feed-forward propagation:
            x = [Z[sample]]
            y = self._forward_prop(x)

            # Now we do our back-propagation of the error to adjust the weights:
            target = labels[sample]
            self._back_prop(y, target, learning_rate)
    
    #########
    # the predict function is used to check the prediction result of
    # this neural network.
    # 
    # parameters
    # ----------
    # self:   the class object itself
    # x:      single input data
    #########
    def predict_single_data(self, x):
        val = numpy.concatenate((numpy.ones(1).T, numpy.array(x)))
        for i in range(0, len(self.weights)):
            val = self.activity(numpy.dot(val, self.weights[i]))
            val = numpy.concatenate((numpy.ones(1).T, numpy.array(val)))
        return val[1]
    
    #########
    # the predict function is used to check the prediction result of
    # this neural network.
    # 
    # parameters
    # ----------
    # self:   the class object itself
    # X:      the input data array
    #########
    def predict(self, X):
        Y = numpy.array([]).reshape(0, self.arch[-1])
        for x in X:
            y = numpy.array([[self.predict_single_data(x)]])
            Y = numpy.vstack((Y,y))
        return Y

In [160]:
net = NeuralNetwork([4,5,1])

In [161]:
# Call the fit function and train the network for a chosen number of epochs
net.fit(X, y, learning_rate = 0.05, epochs=50000)

preds = []
for i in range(len(X)):
    preds.append(net.predict_single_data(X[i]))

In [162]:
df['preds'] = preds

In [164]:
df2 = df.iloc[:,13:15]

In [168]:
df2.head(20)

target     preds
0        1  0.584438
1        1  0.584417
2        1  0.584438
3        1  0.556804
4        1  0.536323
5        1  0.538253
6        1  0.584439
7        1  0.584421
8        1  0.584439
9        1  0.584438
10       1  0.557595
11       1  0.584439
12       1  0.584432
13       1  0.597792
14       1  0.584440
15       1  0.584438
16       1  0.587158
17       1  0.584440
18       1  0.584437
19       1  0.584578

## 4) Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy. 

- Use the Heart Disease Dataset (binary classification)
- Use an appropriate loss function for a binary classification task
- Use an appropriate activation function on the final layer of your network. 
- Train your model using verbose output for ease of grading.
- Use GridSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
- When hyperparameter tuning, show you work by adding code cells for each new experiment. 
- Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
- You must hyperparameter tune at least 5 parameters in order to get a 3 on this section.

In [1]:
import numpy
dataset = numpy.loadtxt('heart.csv', delimiter=',')
# Split into X and Y variables
X = dataset[:,0:13]
print(X.shape)
print(X)
Y = dataset[:,-1]
print(Y.shape)
print(Y)

(303, 13)
[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
(303,)
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [2]:
from keras.models import Sequential
from keras.layers import Dense
# fix random seed for reproducibility
import numpy as np
np.random.seed(42)

Using TensorFlow backend.


In [3]:
model = Sequential()
model.add(Dense(1, input_dim=13, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, Y, epochs=150)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/150
303/303 [==============================] - 0s 427us/step - loss: 7.7864 - acc: 0.4719
Epoch 2/150
303/303 [==============================] - 0s 24us/step - loss: 7.3744 - acc: 0.4851
Epoch 3/150
303/303 [==============================] - 0s 25us/step - loss: 7.0085 - acc: 0.4917
Epoch 4/150
303/303 [==============================] - 0s 21us/step - loss: 6.5787 - acc: 0.5149
Epoch 5/150
303/303 [==============================] - 0s 23us/step - loss: 6.0699 - acc: 0.5281
Epoch 6/150
303/303 [==============================] - 0s 23us/step - loss: 5.4938 - acc: 0.5644
Epoch 7/150
303/303 [==============================] - 0s 24us/step - loss: 5.0874 - acc: 0.5677
Epoch 8/150
303/303 [==============================] - 0s 25us/step - loss: 4.7856 - acc: 0.5842
Epoch 9/150
303/303 [==============================] - 0s 19us/step - loss: 4.7173 - acc: 0.6007
Epoch 

## Param Tuning

In [7]:
from sklearn.model_selection import GridSearchCV
from keras.wrappers.scikit_learn import KerasClassifier



# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(15, input_dim=13, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, verbose=1)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10, 20, 40, 60, 80, 100],
              'epochs': [20]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=5)
grid_result = grid.fit(X, Y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

Epoch 1/20
242/242 [==============================] - 1s 4ms/step - loss: 4.4241 - acc: 0.3430
Epoch 2/20
242/242 [==============================] - 0s 89us/step - loss: 3.6857 - acc: 0.3678
Epoch 3/20
242/242 [==============================] - 0s 138us/step - loss: 3.1376 - acc: 0.3967
Epoch 4/20
242/242 [==============================] - 0s 91us/step - loss: 2.9417 - acc: 0.3967
Epoch 5/20
242/242 [==============================] - 0s 90us/step - loss: 2.4798 - acc: 0.4174
Epoch 6/20
242/242 [==============================] - 0s 104us/step - loss: 2.3737 - acc: 0.4669
Epoch 7/20
242/242 [==============================] - 0s 109us/step - loss: 2.0660 - acc: 0.4876
Epoch 8/20
242/242 [==============================] - 0s 89us/step - loss: 1.9856 - acc: 0.5537
Epoch 9/20
242/242 [==============================] - 0s 97us/step - loss: 1.8500 - acc: 0.5083
Epoch 10/20
242/242 [==============================] - 0s 88us/step - loss: 1.7575 - acc: 0.4959
Epoch 11/20
242/242 [================

/home/xailus/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/20
303/303 [==============================] - 2s 7ms/step - loss: 8.7772 - acc: 0.4554
Epoch 2/20
303/303 [==============================] - 0s 147us/step - loss: 8.7772 - acc: 0.4554
Epoch 3/20
303/303 [==============================] - 0s 137us/step - loss: 8.7772 - acc: 0.4554
Epoch 4/20
303/303 [==============================] - 0s 125us/step - loss: 8.7772 - acc: 0.4554
Epoch 5/20
303/303 [==============================] - 0s 127us/step - loss: 8.7772 - acc: 0.4554
Epoch 6/20
303/303 [==============================] - 0s 118us/step - loss: 8.7772 - acc: 0.4554
Epoch 7/20
303/303 [==============================] - 0s 136us/step - loss: 8.7772 - acc: 0.4554
Epoch 8/20
303/303 [==============================] - 0s 109us/step - loss: 8.7772 - acc: 0.4554
Epoch 9/20
303/303 [==============================] - 0s 124us/step - loss: 8.7772 - acc: 0.4554
Epoch 10/20
303/303 [==============================] - 0s 148us/step - loss: 8.7772 - acc: 0.4554
Epoch 11/20
303/303 [==========

## Epochs

In [8]:
# define the grid search parameters
param_grid = {'batch_size': [10],
              'epochs': [20, 40, 60]}

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3)
grid_result = grid.fit(X, Y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

Epoch 1/20
202/202 [==============================] - 2s 11ms/step - loss: 10.8913 - acc: 0.3168
Epoch 2/20
202/202 [==============================] - 0s 108us/step - loss: 10.8913 - acc: 0.3168
Epoch 3/20
202/202 [==============================] - 0s 165us/step - loss: 10.8913 - acc: 0.3168
Epoch 4/20
202/202 [==============================] - 0s 139us/step - loss: 10.8913 - acc: 0.3168
Epoch 5/20
202/202 [==============================] - 0s 177us/step - loss: 10.8913 - acc: 0.3168
Epoch 6/20
202/202 [==============================] - 0s 137us/step - loss: 10.8913 - acc: 0.3168
Epoch 7/20
202/202 [==============================] - 0s 138us/step - loss: 10.8913 - acc: 0.3168
Epoch 8/20
202/202 [==============================] - 0s 131us/step - loss: 10.8913 - acc: 0.3168
Epoch 9/20
202/202 [==============================] - 0s 120us/step - loss: 10.8913 - acc: 0.3168
Epoch 10/20
202/202 [==============================] - 0s 133us/step - loss: 10.8913 - acc: 0.3168
Epoch 11/20
202/202 

## Activation Functions

In [10]:
# define the grid search parameters
activation = ['relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear']
param_grid = dict(activation=activation)

# Function to create model, required for KerasClassifier
def create_model(activation='relu'):
    # create model
    model = Sequential()
    model.add(Dense(15, input_dim=13, activation=activation))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=60, batch_size=10, verbose=1)

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=5)
grid_result = grid.fit(X, Y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}") 

Epoch 1/60
242/242 [==============================] - 4s 15ms/step - loss: 6.9268 - acc: 0.5702
Epoch 2/60
242/242 [==============================] - 0s 175us/step - loss: 6.9268 - acc: 0.5702
Epoch 3/60
242/242 [==============================] - 0s 161us/step - loss: 6.9268 - acc: 0.5702
Epoch 4/60
242/242 [==============================] - 0s 176us/step - loss: 6.9268 - acc: 0.5702
Epoch 5/60
242/242 [==============================] - 0s 179us/step - loss: 6.9268 - acc: 0.5702
Epoch 6/60
242/242 [==============================] - 0s 180us/step - loss: 6.9268 - acc: 0.5702
Epoch 7/60
242/242 [==============================] - 0s 176us/step - loss: 6.9268 - acc: 0.5702
Epoch 8/60
242/242 [==============================] - 0s 170us/step - loss: 6.9268 - acc: 0.5702
Epoch 9/60
242/242 [==============================] - 0s 180us/step - loss: 6.9268 - acc: 0.5702
Epoch 10/60
242/242 [==============================] - 0s 180us/step - loss: 6.9268 - acc: 0.5702
Epoch 11/60
242/242 [=========

/home/xailus/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Epoch 1/60
303/303 [==============================] - 5s 17ms/step - loss: 0.6885 - acc: 0.5809
Epoch 2/60
303/303 [==============================] - 0s 194us/step - loss: 0.6890 - acc: 0.5677
Epoch 3/60
303/303 [==============================] - 0s 210us/step - loss: 0.6862 - acc: 0.5677
Epoch 4/60
303/303 [==============================] - 0s 207us/step - loss: 0.6779 - acc: 0.5776
Epoch 5/60
303/303 [==============================] - 0s 194us/step - loss: 0.6764 - acc: 0.5710
Epoch 6/60
303/303 [==============================] - 0s 260us/step - loss: 0.6759 - acc: 0.5776
Epoch 7/60
303/303 [==============================] - 0s 202us/step - loss: 0.6783 - acc: 0.5974
Epoch 8/60
303/303 [==============================] - 0s 221us/step - loss: 0.6734 - acc: 0.5842
Epoch 9/60
303/303 [==============================] - 0s 213us/step - loss: 0.6709 - acc: 0.6139
Epoch 10/60
303/303 [==============================] - 0s 230us/step - loss: 0.6653 - acc: 0.6106
Epoch 11/60
303/303 [=========

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [20]:
model = Sequential()
model.add(Dense(15, input_dim=13, activation='tanh'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=500, batch_size = 10)

Epoch 1/500
242/242 [==============================] - 5s 20ms/step - loss: 0.6827 - acc: 0.5455
Epoch 2/500
242/242 [==============================] - 0s 179us/step - loss: 0.6760 - acc: 0.5620
Epoch 3/500
242/242 [==============================] - 0s 171us/step - loss: 0.6732 - acc: 0.5620
Epoch 4/500
242/242 [==============================] - 0s 177us/step - loss: 0.6716 - acc: 0.5579
Epoch 5/500
242/242 [==============================] - 0s 170us/step - loss: 0.6684 - acc: 0.5579
Epoch 6/500
242/242 [==============================] - 0s 193us/step - loss: 0.6648 - acc: 0.5702
Epoch 7/500
242/242 [==============================] - 0s 195us/step - loss: 0.6607 - acc: 0.5950
Epoch 8/500
242/242 [==============================] - 0s 215us/step - loss: 0.6574 - acc: 0.6074
Epoch 9/500
242/242 [==============================] - 0s 177us/step - loss: 0.6536 - acc: 0.6116
Epoch 10/500
242/242 [==============================] - 0s 192us/step - loss: 0.6495 - acc: 0.6446
Epoch 11/500
242/242

In [21]:
preds = model.predict_classes(X_test)

## 81% Accuracy

In [22]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(preds, y_test)
print(accuracy)

0.819672131147541
