<a href="https://colab.research.google.com/github/nusc2016/DS-Unit-4-Sprint-2-Neural-Networks/blob/main/Module1/Aaron_Huizenga_2_LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
  * The input layer is the very beginning of the workflow for the artificial neural network.
### Hidden Layer:
  * A hidden layer is a layer in between input layers and output layers, where artificial neurons take in a set of weighted inputs, the bias and then produce an output through an activation function.
### Output Layer:
  * The output layer produces the result for given inputs, after being processed in the hidden layer.
### Neuron:
  * Typically, a neuron computes the weighted average of its input, and this sum is passed through a non-linear function, often called activation function, such as the sigmoid.
### Weight:
  * A weight represents the strength of the connection between units.
### Activation Function:
  * The AF is responsible for transforming the summed weighted input from the node into the activation of the node (or output).
### Node Map:
  * Node map is a visual representation of the structure of neural network layers.
### Perceptron:
  * A neural network with a single layer.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### The data is fed into the neural network through nodes in the input layer. These input nodes are then transformed in the hidden layers by computing the dot product between these inputs and the weights and then combining them with a bias value. The results are fed through the activation function, finally being presented in the output layer.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [1]:
# libraries necessary for the assignment

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [3]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [4]:
# define what the output is supposed to be
y = df['y'].to_list()
output = [[x] for x in y]
output

[[1], [1], [1], [0]]

In [5]:
# define the sigmoid activation function which put the outputs as a 0 or 1

def sigmoid(x):
    return 1/(1 + np.exp(-x))

# define the derivative of the sigmoid function

def sigmoid_der(x):
    # sigmoid of x
    sx = sigmoid(x)
    # derivative of x
    dx = sx * (1-sx)
    return dx

In [6]:
# initialize random weights for inputs
# 3 inputs means 3 random weights

# random 3 by 1 matrix. This matrix is a random number between 0 and 1
# multiply this 0 and 1 by 2. Then, subtract 1 from it. 

# documentation on random.random 
# https://docs.python.org/dev/library/random.html#random.random

weights = 2*np.random.random((3,1)) - 1

In [7]:
(np.random.random() * 2) - 1

0.5905262014308903

In [8]:
weights

array([[ 0.0602017 ],
       [-0.65843065],
       [-0.20677196]])

In [9]:
df

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [10]:
# weighted sum of inputs and the weights
weighted_sum = np.dot(df, weights)
weighted_sum

array([[-0.20677196],
       [-0.14657026],
       [-0.86520262],
       [-0.59822896]])

In [11]:
# how the calculation is done
# x(weight 1) + x2(weight2) + y(weight3) = output
0.31741796 + -0.83987352

-0.52245556

In [12]:
# activated function version of the output

activated_output = sigmoid(weighted_sum)
activated_output

array([[0.4484904 ],
       [0.46342289],
       [0.29625352],
       [0.35474899]])

In [13]:
# find the error between prediction and actual values
error = output - activated_output
error

array([[ 0.5515096 ],
       [ 0.53657711],
       [ 0.70374648],
       [-0.35474899]])

In [14]:
# gradient descent and back progagation

adjustment = error * sigmoid_der(weighted_sum)
adjustment

array([[ 0.13641411],
       [ 0.1334264 ],
       [ 0.14672225],
       [-0.0812028 ]])

In [15]:
df.T

# first line of new weight should be 

# 0.04961164 + -0.08699663 + original weight (0.31741796) = 0.28003297

0  1  2  3
x1  0  1  0  1
x2  0  0  1  1
y   1  1  1  0

In [16]:
0.04961164 + -0.08699663 + 0.31741796

0.28003297

In [17]:
# new weights

weights += np.dot(df.T, adjustment)
weights

array([[ 0.1124253],
       [-0.5929112],
       [ 0.2097908]])

#### This is what it would look like from scratch

In [18]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')


# the sigmoid function to be used as activation function. 

def sigmoid(x):
    return 1/(1 + np.exp(-x))

# define the derivative of the sigmoid function

def sigmoid_der(x):
    # sigmoid of x
    sx = sigmoid(x)
    # derivative of x
    dx = sx * (1-sx)
    return dx

# initializing random weights. 

weights = 2*np.random.random((3,1)) - 1

# define what the output is supposed to be
y = df['y'].to_list()
output = [[x] for x in y]

# repeat the above process 10,000 times. Update weight 10,000 times 
# and re-do calculations

for repeat in range(10000):
    
    # weighted sum of inputs and weights
    
    weighted_sum = np.dot(df, weights)
    
    # activate values
    activated_output = sigmoid(weighted_sum)
    
    # calculate error
    error = output - activated_output
    adjustment = error * sigmoid_der(weighted_sum)
    
    # pdate the weights
    weights += np.dot(df.T, adjustment)
    
print("Weights after training")
print(weights)
    
print("Output after training")
print(activated_output)

Weights after training
[[-2.40940563]
 [-2.41106076]
 [ 7.49023655]]
Output after training
[[0.99944176]
 [0.99382333]
 [0.99381316]
 [0.00799894]]


#### This function creates a simple Perceptron

In [19]:
def perceptron(df, output, weight):
    """Function to create a perceptron which 
    is a single neuron neural network. 
    When provided with a dataframe and 
    what the output is supposed to be
    and the initial weights"""
    
    import numpy as np
    
    # the sigmoid function to be used as activation function. 

    def sigmoid(x):
        return 1/(1 + np.exp(-x))

    # define the derivative of the sigmoid function

    def sigmoid_der(x):
        # sigmoid of x
        sx = sigmoid(x)
        # derivative of x
        dx = sx * (1-sx)
        return dx
    
    for repeat in range(10000):
    
        # weighted sum of inputs and weights

        weighted_sum = np.dot(df, weight)

        # activate values
        activated_output = sigmoid(weighted_sum)

        # calculate error
        error = output - activated_output
        adjustment = error * sigmoid_der(weighted_sum)

        # update the weights
        weight += np.dot(df.T, adjustment)
    
    print("Weights after training")
    print(weights, "\n")

    print("Output after training")
    print(activated_output)

In [20]:
# Lets test the funcion out from above

weights = 2*np.random.random((3,1)) - 1

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

output = [[x] for x in df['y']]

perceptron(df, output, weights)

Weights after training
[[-2.41384498]
 [-2.40676623]
 [ 7.49047253]] 

Output after training
[[0.99944189]
 [0.99379747]
 [0.99384096]
 [0.00799779]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [21]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [23]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = diabetes[
             ['Pregnancies',
              'Glucose',
              'BloodPressure',
              'SkinThickness',
              'Insulin',
              'BMI',
              'DiabetesPedigreeFunction',
              'Age']
            ].values
y = diabetes[['Outcome']].values

In [24]:
X.shape

(768, 8)

In [25]:
# This should return the array of X

X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [26]:
##### Update this Class #####

class Perceptron(object):
    """
    Perceptron classifier.
    
    Parameters
    -----------
    eta: float
        learning rate (between 0.0 and 1.0)
    n_iter: int
        Passes (epochs) over the training set.
    
    Attributes
    -----------
    weight: ld-array
        Weights after fitting.
    errors:list
        Number of misclassification in every epoch.
    """
    def __init__(self, eta = 0.01, n_iter = 10):
        self.eta = eta
        self.n_iter = n_iter

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weights = np.zeros(1 + X.shape[1])
        self.errors = []
        
        for _ in range(self.n_iter):
          err = 0
          for xi, target in zip(X, y):
            delta_w = self.eta * (target - self.predict(xi))
            self.weights[1:] += delta_w * xi
            self.weights[0] += delta_w
            err += int(delta_w != 0.0)
          self.errors.append(err)
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weights[1:]) + self.weights[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.5, 1, 0)

In [27]:
model = Perceptron(n_iter = 1000)
model.fit(X,y)

In [28]:
model.predict(X)

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,

In [29]:
model.predict(X[1])

array(0)

In [31]:
from sklearn.metrics import accuracy_score

accuracy_score(model.predict(X), y)

0.69921875

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?

#### There are several functions that deserve some credit, i.e. Step Functions, Linear Functions, great and mighty powerful Sigmoid function, the Hyperbolic Tangent Function, the ReLU (Rectified Linear Unit Function), the Leaky-ReLU function, the Softmax function, and lastly the Swish (A Self-Gated) Function.


#### All of this is new to me, but in doing some research on the functions I have come to the following conclusion:
  1. The "Sigmoid" function can be used if you were to say that the hyperbolic tangent, or in this case "model", can be learned at a slower pace because of the wide range of "activating" functions. However; if the network you are working in is a tad bit too deep and the comp load is an issue, then ReLU can be used. 
  2. I could decide to use Leaky ReLU as a solution the problems that I'm experiencing (degrading gradients in ReLU).